// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: activity_report.sql

package sqlcgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countCommentsInRange = `-- name: CountCommentsInRange :one
SELECT COUNT(*) FROM comments
WHERE user_id = $1 AND created_at >= $2 AND created_at < $3
`

type CountCommentsInRangeParams struct {
	UserID      int64
	CreatedAt   pgtype.Timestamptz
	CreatedAt_2 pgtype.Timestamptz
}

// 期間の合計にも日別集計にも同じクエリを使う。
func (q *Queries) CountCommentsInRange(ctx context.Context, arg CountCommentsInRangeParams) (int64, error) {
	row := q.db.QueryRow(ctx, countCommentsInRange, arg.UserID, arg.CreatedAt, arg.CreatedAt_2)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countCompletedGoalsInRange = `-- name: CountCompletedGoalsInRange :one
SELECT COUNT(*) FROM learning_goals
WHERE user_id = $1 AND status = 'completed' AND completed_at >= $2 AND completed_at < $3
`

type CountCompletedGoalsInRangeParams struct {
	UserID        int64
	CompletedAt   pgtype.Timestamptz
	CompletedAt_2 pgtype.Timestamptz
}

func (q *Queries) CountCompletedGoalsInRange(ctx context.Context, arg CountCompletedGoalsInRangeParams) (int64, error) {
	row := q.db.QueryRow(ctx, countCompletedGoalsInRange, arg.UserID, arg.CompletedAt, arg.CompletedAt_2)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countLikesReceivedInRange = `-- name: CountLikesReceivedInRange :one
SELECT COUNT(*) FROM likes
JOIN posts ON likes.post_id = posts.id
WHERE posts.user_id = $1 AND likes.created_at >= $2 AND likes.created_at < $3
`

type CountLikesReceivedInRangeParams struct {
	UserID      int64
	CreatedAt   pgtype.Timestamptz
	CreatedAt_2 pgtype.Timestamptz
}

func (q *Queries) CountLikesReceivedInRange(ctx context.Context, arg CountLikesReceivedInRangeParams) (int64, error) {
	row := q.db.QueryRow(ctx, countLikesReceivedInRange, arg.UserID, arg.CreatedAt, arg.CreatedAt_2)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countMessagesReceivedInRange = `-- name: CountMessagesReceivedInRange :one
SELECT COUNT(*) FROM messages
WHERE receiver_id = $1 AND created_at >= $2 AND created_at < $3
`

type CountMessagesReceivedInRangeParams struct {
	ReceiverID  int64
	CreatedAt   pgtype.Timestamptz
	CreatedAt_2 pgtype.Timestamptz
}

func (q *Queries) CountMessagesReceivedInRange(ctx context.Context, arg CountMessagesReceivedInRangeParams) (int64, error) {
	row := q.db.QueryRow(ctx, countMessagesReceivedInRange, arg.ReceiverID, arg.CreatedAt, arg.CreatedAt_2)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countMessagesSentInRange = `-- name: CountMessagesSentInRange :one
SELECT COUNT(*) FROM messages
WHERE sender_id = $1 AND created_at >= $2 AND created_at < $3
`

type CountMessagesSentInRangeParams struct {
	SenderID    int64
	CreatedAt   pgtype.Timestamptz
	CreatedAt_2 pgtype.Timestamptz
}

func (q *Queries) CountMessagesSentInRange(ctx context.Context, arg CountMessagesSentInRangeParams) (int64, error) {
	row := q.db.QueryRow(ctx, countMessagesSentInRange, arg.SenderID, arg.CreatedAt, arg.CreatedAt_2)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countNewFollowersInRange = `-- name: CountNewFollowersInRange :one
SELECT COUNT(*) FROM follows
WHERE followee_id = $1 AND created_at >= $2 AND created_at < $3
`

type CountNewFollowersInRangeParams struct {
	FolloweeID  int64
	CreatedAt   pgtype.Timestamptz
	CreatedAt_2 pgtype.Timestamptz
}

func (q *Queries) CountNewFollowersInRange(ctx context.Context, arg CountNewFollowersInRangeParams) (int64, error) {
	row := q.db.QueryRow(ctx, countNewFollowersInRange, arg.FolloweeID, arg.CreatedAt, arg.CreatedAt_2)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countPostsInRange = `-- name: CountPostsInRange :one
SELECT COUNT(*) FROM posts
WHERE user_id = $1 AND created_at >= $2 AND created_at < $3
`

type CountPostsInRangeParams struct {
	UserID      int64
	CreatedAt   pgtype.Timestamptz
	CreatedAt_2 pgtype.Timestamptz
}

// 期間の合計にも日別集計にも同じクエリを使う。
func (q *Queries) CountPostsInRange(ctx context.Context, arg CountPostsInRangeParams) (int64, error) {
	row := q.db.QueryRow(ctx, countPostsInRange, arg.UserID, arg.CreatedAt, arg.CreatedAt_2)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const sumContributionsInRange = `-- name: SumContributionsInRange :one
SELECT COALESCE(SUM(count), 0)::bigint FROM git_hub_contributions
WHERE user_id = $1 AND contributed_on >= $2 AND contributed_on < $3
`

type SumContributionsInRangeParams struct {
	UserID          int64
	ContributedOn   pgtype.Date
	ContributedOn_2 pgtype.Date
}

// 期間の合計にも日別集計（開始日=当日0時、終了日=翌日0時）にも同じクエリを使う。
func (q *Queries) SumContributionsInRange(ctx context.Context, arg SumContributionsInRangeParams) (int64, error) {
	row := q.db.QueryRow(ctx, sumContributionsInRange, arg.UserID, arg.ContributedOn, arg.ContributedOn_2)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}
