// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: answer.sql

package sqlcgen

import (
	"context"
)

const adjustAnswerVoteCount = `-- name: AdjustAnswerVoteCount :exec
UPDATE answers SET vote_count = vote_count + $1::bigint WHERE id = $2
`

type AdjustAnswerVoteCountParams struct {
	Diff int64
	ID   int64
}

func (q *Queries) AdjustAnswerVoteCount(ctx context.Context, arg AdjustAnswerVoteCountParams) error {
	_, err := q.db.Exec(ctx, adjustAnswerVoteCount, arg.Diff, arg.ID)
	return err
}

const clearBestAnswer = `-- name: ClearBestAnswer :exec
UPDATE answers SET is_best = false
WHERE question_id = $1 AND is_best = true
`

func (q *Queries) ClearBestAnswer(ctx context.Context, questionID int64) error {
	_, err := q.db.Exec(ctx, clearBestAnswer, questionID)
	return err
}

const createAnswer = `-- name: CreateAnswer :one
INSERT INTO answers (user_id, question_id, body, vote_count, is_best, created_at, updated_at)
VALUES ($1, $2, $3, $4, $5, now(), now())
RETURNING id, user_id, question_id, body, vote_count, is_best, created_at, updated_at
`

type CreateAnswerParams struct {
	UserID     int64
	QuestionID int64
	Body       string
	VoteCount  *int64
	IsBest     bool
}

func (q *Queries) CreateAnswer(ctx context.Context, arg CreateAnswerParams) (Answer, error) {
	row := q.db.QueryRow(ctx, createAnswer,
		arg.UserID,
		arg.QuestionID,
		arg.Body,
		arg.VoteCount,
		arg.IsBest,
	)
	var i Answer
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.QuestionID,
		&i.Body,
		&i.VoteCount,
		&i.IsBest,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createAnswerVote = `-- name: CreateAnswerVote :one
INSERT INTO answer_votes (user_id, answer_id, value, created_at)
VALUES ($1, $2, $3, now())
RETURNING id, user_id, answer_id, value, created_at
`

type CreateAnswerVoteParams struct {
	UserID   int64
	AnswerID int64
	Value    int64
}

func (q *Queries) CreateAnswerVote(ctx context.Context, arg CreateAnswerVoteParams) (AnswerVote, error) {
	row := q.db.QueryRow(ctx, createAnswerVote, arg.UserID, arg.AnswerID, arg.Value)
	var i AnswerVote
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.AnswerID,
		&i.Value,
		&i.CreatedAt,
	)
	return i, err
}

const decrementQuestionAnswerCountFloored = `-- name: DecrementQuestionAnswerCountFloored :exec
UPDATE questions SET answer_count = GREATEST(answer_count - 1, 0) WHERE id = $1
`

// 0未満にはしない（GORMのGREATEST(answer_count - 1, 0)に相当）。
func (q *Queries) DecrementQuestionAnswerCountFloored(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, decrementQuestionAnswerCountFloored, id)
	return err
}

const deleteAnswer = `-- name: DeleteAnswer :exec
DELETE FROM answers WHERE id = $1
`

// 依存する投票等はFKのON DELETE CASCADEでDBが自動的に削除する。
func (q *Queries) DeleteAnswer(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, deleteAnswer, id)
	return err
}

const deleteAnswerVote = `-- name: DeleteAnswerVote :exec
DELETE FROM answer_votes WHERE user_id = $1 AND answer_id = $2
`

type DeleteAnswerVoteParams struct {
	UserID   int64
	AnswerID int64
}

func (q *Queries) DeleteAnswerVote(ctx context.Context, arg DeleteAnswerVoteParams) error {
	_, err := q.db.Exec(ctx, deleteAnswerVote, arg.UserID, arg.AnswerID)
	return err
}

const getAnswerVoteByUserAndAnswer = `-- name: GetAnswerVoteByUserAndAnswer :one
SELECT id, user_id, answer_id, value, created_at FROM answer_votes WHERE user_id = $1 AND answer_id = $2
`

type GetAnswerVoteByUserAndAnswerParams struct {
	UserID   int64
	AnswerID int64
}

func (q *Queries) GetAnswerVoteByUserAndAnswer(ctx context.Context, arg GetAnswerVoteByUserAndAnswerParams) (AnswerVote, error) {
	row := q.db.QueryRow(ctx, getAnswerVoteByUserAndAnswer, arg.UserID, arg.AnswerID)
	var i AnswerVote
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.AnswerID,
		&i.Value,
		&i.CreatedAt,
	)
	return i, err
}

const getAnswerWithUserByID = `-- name: GetAnswerWithUserByID :one
SELECT answers.id, answers.user_id, answers.question_id, answers.body, answers.vote_count, answers.is_best, answers.created_at, answers.updated_at, users.id, users.username, users.name, users.email, users.avatar_url, users.bio, users.git_hub_id, users.git_hub_username, users.git_hub_token, users.git_hub_connected, users.spotify_connected, users.spotify_token, users.spotify_refresh_token, users.spotify_token_expiry, users.zenn_username, users.qiita_username, users.at_coder_username, users.paiza_rank, users.skills_languages, users.skills_frameworks, users.onboarding_completed, users.email_weekly_report, users.email_language, users.created_at, users.updated_at
FROM answers
JOIN users ON users.id = answers.user_id
WHERE answers.id = $1
`

type GetAnswerWithUserByIDRow struct {
	Answer Answer
	User   User
}

// GORMのPreload("User")に相当。user_idはNOT NULLのためINNER JOINでよい。
func (q *Queries) GetAnswerWithUserByID(ctx context.Context, id int64) (GetAnswerWithUserByIDRow, error) {
	row := q.db.QueryRow(ctx, getAnswerWithUserByID, id)
	var i GetAnswerWithUserByIDRow
	err := row.Scan(
		&i.Answer.ID,
		&i.Answer.UserID,
		&i.Answer.QuestionID,
		&i.Answer.Body,
		&i.Answer.VoteCount,
		&i.Answer.IsBest,
		&i.Answer.CreatedAt,
		&i.Answer.UpdatedAt,
		&i.User.ID,
		&i.User.Username,
		&i.User.Name,
		&i.User.Email,
		&i.User.AvatarUrl,
		&i.User.Bio,
		&i.User.GitHubID,
		&i.User.GitHubUsername,
		&i.User.GitHubToken,
		&i.User.GitHubConnected,
		&i.User.SpotifyConnected,
		&i.User.SpotifyToken,
		&i.User.SpotifyRefreshToken,
		&i.User.SpotifyTokenExpiry,
		&i.User.ZennUsername,
		&i.User.QiitaUsername,
		&i.User.AtCoderUsername,
		&i.User.PaizaRank,
		&i.User.SkillsLanguages,
		&i.User.SkillsFrameworks,
		&i.User.OnboardingCompleted,
		&i.User.EmailWeeklyReport,
		&i.User.EmailLanguage,
		&i.User.CreatedAt,
		&i.User.UpdatedAt,
	)
	return i, err
}

const incrementQuestionAnswerCount = `-- name: IncrementQuestionAnswerCount :exec
UPDATE questions SET answer_count = answer_count + 1 WHERE id = $1
`

func (q *Queries) IncrementQuestionAnswerCount(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, incrementQuestionAnswerCount, id)
	return err
}

const listAnswersByQuestionID = `-- name: ListAnswersByQuestionID :many
SELECT answers.id, answers.user_id, answers.question_id, answers.body, answers.vote_count, answers.is_best, answers.created_at, answers.updated_at, users.id, users.username, users.name, users.email, users.avatar_url, users.bio, users.git_hub_id, users.git_hub_username, users.git_hub_token, users.git_hub_connected, users.spotify_connected, users.spotify_token, users.spotify_refresh_token, users.spotify_token_expiry, users.zenn_username, users.qiita_username, users.at_coder_username, users.paiza_rank, users.skills_languages, users.skills_frameworks, users.onboarding_completed, users.email_weekly_report, users.email_language, users.created_at, users.updated_at
FROM answers
JOIN users ON users.id = answers.user_id
WHERE answers.question_id = $1
ORDER BY answers.is_best DESC, answers.vote_count DESC, answers.created_at ASC
`

type ListAnswersByQuestionIDRow struct {
	Answer Answer
	User   User
}

// GORMのPreload("User")に相当。user_idはNOT NULLのためINNER JOINでよい。
func (q *Queries) ListAnswersByQuestionID(ctx context.Context, questionID int64) ([]ListAnswersByQuestionIDRow, error) {
	rows, err := q.db.Query(ctx, listAnswersByQuestionID, questionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListAnswersByQuestionIDRow
	for rows.Next() {
		var i ListAnswersByQuestionIDRow
		if err := rows.Scan(
			&i.Answer.ID,
			&i.Answer.UserID,
			&i.Answer.QuestionID,
			&i.Answer.Body,
			&i.Answer.VoteCount,
			&i.Answer.IsBest,
			&i.Answer.CreatedAt,
			&i.Answer.UpdatedAt,
			&i.User.ID,
			&i.User.Username,
			&i.User.Name,
			&i.User.Email,
			&i.User.AvatarUrl,
			&i.User.Bio,
			&i.User.GitHubID,
			&i.User.GitHubUsername,
			&i.User.GitHubToken,
			&i.User.GitHubConnected,
			&i.User.SpotifyConnected,
			&i.User.SpotifyToken,
			&i.User.SpotifyRefreshToken,
			&i.User.SpotifyTokenExpiry,
			&i.User.ZennUsername,
			&i.User.QiitaUsername,
			&i.User.AtCoderUsername,
			&i.User.PaizaRank,
			&i.User.SkillsLanguages,
			&i.User.SkillsFrameworks,
			&i.User.OnboardingCompleted,
			&i.User.EmailWeeklyReport,
			&i.User.EmailLanguage,
			&i.User.CreatedAt,
			&i.User.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAnswersByVoteRange = `-- name: ListAnswersByVoteRange :many
SELECT answers.id, answers.user_id, answers.question_id, answers.body, answers.vote_count, answers.is_best, answers.created_at, answers.updated_at, users.id, users.username, users.name, users.email, users.avatar_url, users.bio, users.git_hub_id, users.git_hub_username, users.git_hub_token, users.git_hub_connected, users.spotify_connected, users.spotify_token, users.spotify_refresh_token, users.spotify_token_expiry, users.zenn_username, users.qiita_username, users.at_coder_username, users.paiza_rank, users.skills_languages, users.skills_frameworks, users.onboarding_completed, users.email_weekly_report, users.email_language, users.created_at, users.updated_at
FROM answers
JOIN users ON users.id = answers.user_id
WHERE answers.question_id = $1 AND answers.vote_count >= $2 AND answers.vote_count <= $3
ORDER BY answers.vote_count DESC, answers.created_at ASC
`

type ListAnswersByVoteRangeParams struct {
	QuestionID  int64
	VoteCount   *int64
	VoteCount_2 *int64
}

type ListAnswersByVoteRangeRow struct {
	Answer Answer
	User   User
}

// GORMのPreload("User")に相当。user_idはNOT NULLのためINNER JOINでよい。
func (q *Queries) ListAnswersByVoteRange(ctx context.Context, arg ListAnswersByVoteRangeParams) ([]ListAnswersByVoteRangeRow, error) {
	rows, err := q.db.Query(ctx, listAnswersByVoteRange, arg.QuestionID, arg.VoteCount, arg.VoteCount_2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListAnswersByVoteRangeRow
	for rows.Next() {
		var i ListAnswersByVoteRangeRow
		if err := rows.Scan(
			&i.Answer.ID,
			&i.Answer.UserID,
			&i.Answer.QuestionID,
			&i.Answer.Body,
			&i.Answer.VoteCount,
			&i.Answer.IsBest,
			&i.Answer.CreatedAt,
			&i.Answer.UpdatedAt,
			&i.User.ID,
			&i.User.Username,
			&i.User.Name,
			&i.User.Email,
			&i.User.AvatarUrl,
			&i.User.Bio,
			&i.User.GitHubID,
			&i.User.GitHubUsername,
			&i.User.GitHubToken,
			&i.User.GitHubConnected,
			&i.User.SpotifyConnected,
			&i.User.SpotifyToken,
			&i.User.SpotifyRefreshToken,
			&i.User.SpotifyTokenExpiry,
			&i.User.ZennUsername,
			&i.User.QiitaUsername,
			&i.User.AtCoderUsername,
			&i.User.PaizaRank,
			&i.User.SkillsLanguages,
			&i.User.SkillsFrameworks,
			&i.User.OnboardingCompleted,
			&i.User.EmailWeeklyReport,
			&i.User.EmailLanguage,
			&i.User.CreatedAt,
			&i.User.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockAnswerForVoteChange = `-- name: LockAnswerForVoteChange :one
SELECT id FROM answers WHERE id = $1 FOR UPDATE
`

// Vote/RemoveVoteでの差分計算が並行実行で古い値を読まないようにするための行ロック
// （GORMの clause.Locking{Strength: "UPDATE"} に相当）。回答が存在しなければ
// pgx.ErrNoRows を返し、呼び出し側のトランザクションを失敗させる。
func (q *Queries) LockAnswerForVoteChange(ctx context.Context, id int64) (int64, error) {
	row := q.db.QueryRow(ctx, lockAnswerForVoteChange, id)
	var id_2 int64
	err := row.Scan(&id_2)
	return id_2, err
}

const lockQuestionForAnswerChange = `-- name: LockQuestionForAnswerChange :one
SELECT id FROM questions WHERE id = $1 FOR UPDATE
`

// Delete/SetBestAnswerでのロック順序（質問→回答）をGORM実装と揃えるための行ロック
// （GORMの clause.Locking{Strength: "UPDATE"} に相当）。質問が存在しなければ
// pgx.ErrNoRows を返し、呼び出し側のトランザクションを失敗させる。
func (q *Queries) LockQuestionForAnswerChange(ctx context.Context, id int64) (int64, error) {
	row := q.db.QueryRow(ctx, lockQuestionForAnswerChange, id)
	var id_2 int64
	err := row.Scan(&id_2)
	return id_2, err
}

const setAnswerBest = `-- name: SetAnswerBest :exec
UPDATE answers SET is_best = true WHERE id = $1
`

func (q *Queries) SetAnswerBest(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, setAnswerBest, id)
	return err
}

const setQuestionSolved = `-- name: SetQuestionSolved :exec
UPDATE questions SET is_solved = true WHERE id = $1
`

func (q *Queries) SetQuestionSolved(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, setQuestionSolved, id)
	return err
}

const updateAnswer = `-- name: UpdateAnswer :one
UPDATE answers SET body = $2, vote_count = $3, is_best = $4, updated_at = now()
WHERE id = $1
RETURNING id, user_id, question_id, body, vote_count, is_best, created_at, updated_at
`

type UpdateAnswerParams struct {
	ID        int64
	Body      string
	VoteCount *int64
	IsBest    bool
}

// GORMのSave（全カラム上書き）に相当。
func (q *Queries) UpdateAnswer(ctx context.Context, arg UpdateAnswerParams) (Answer, error) {
	row := q.db.QueryRow(ctx, updateAnswer,
		arg.ID,
		arg.Body,
		arg.VoteCount,
		arg.IsBest,
	)
	var i Answer
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.QuestionID,
		&i.Body,
		&i.VoteCount,
		&i.IsBest,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateAnswerVoteValue = `-- name: UpdateAnswerVoteValue :exec
UPDATE answer_votes SET value = $3 WHERE user_id = $1 AND answer_id = $2
`

type UpdateAnswerVoteValueParams struct {
	UserID   int64
	AnswerID int64
	Value    int64
}

func (q *Queries) UpdateAnswerVoteValue(ctx context.Context, arg UpdateAnswerVoteValueParams) error {
	_, err := q.db.Exec(ctx, updateAnswerVoteValue, arg.UserID, arg.AnswerID, arg.Value)
	return err
}
