// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: badge.sql

package sqlcgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countAnswersByUserIncludingDeleted = `-- name: CountAnswersByUserIncludingDeleted :one
SELECT COUNT(*) FROM answers WHERE user_id = $1
`

// qa_stats.sql の CountAnswersByUser は deleted_at IS NULL で絞るが、
// こちらは既存の GORM Raw SQL 実装（db.Raw、GORMのsoft-deleteスコープ非適用）と
// 挙動を変えないため、論理削除された回答も含めてカウントする。
func (q *Queries) CountAnswersByUserIncludingDeleted(ctx context.Context, userID int64) (int64, error) {
	row := q.db.QueryRow(ctx, countAnswersByUserIncludingDeleted, userID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const listGitHubContributionsByUser = `-- name: ListGitHubContributionsByUser :many
SELECT date, count FROM git_hub_contributions
WHERE user_id = $1 AND count > 0
ORDER BY date DESC
`

type ListGitHubContributionsByUserRow struct {
	Date  pgtype.Timestamptz
	Count int64
}

// GitHub連続コントリビューション日数の算出に使う（countが正の日のみ、新しい順）。
func (q *Queries) ListGitHubContributionsByUser(ctx context.Context, userID int64) ([]ListGitHubContributionsByUserRow, error) {
	rows, err := q.db.Query(ctx, listGitHubContributionsByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListGitHubContributionsByUserRow
	for rows.Next() {
		var i ListGitHubContributionsByUserRow
		if err := rows.Scan(&i.Date, &i.Count); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const sumGitHubContributionsByUser = `-- name: SumGitHubContributionsByUser :one
SELECT COALESCE(SUM(count), 0)::bigint FROM git_hub_contributions WHERE user_id = $1
`

func (q *Queries) SumGitHubContributionsByUser(ctx context.Context, userID int64) (int64, error) {
	row := q.db.QueryRow(ctx, sumGitHubContributionsByUser, userID)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}
