// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: book_review_stats.sql

package sqlcgen

import (
	"context"
)

const getBookReviewStats = `-- name: GetBookReviewStats :one
SELECT
  count(*) AS total_reviews,
  COALESCE(AVG(rating), 0)::float8 AS average_rating,
  COALESCE(MAX(rating), 0)::bigint AS max_rating,
  COALESCE(MIN(rating), 0)::bigint AS min_rating,
  count(*) FILTER (WHERE rating = 5) AS five_star_count
FROM book_reviews
WHERE user_id = $1 AND deleted_at IS NULL
`

type GetBookReviewStatsRow struct {
	TotalReviews  int64
	AverageRating float64
	MaxRating     int64
	MinRating     int64
	FiveStarCount int64
}

// book_reviews は GORM の論理削除（deleted_at）付きモデルのため、GORMの既定スコープに合わせて
// deleted_at IS NULL を明示する。レビュー0件でもCOALESCEにより全項目0を返す
// （GORM実装のtotal_reviews==0での早期returnと同じ結果になる）。
func (q *Queries) GetBookReviewStats(ctx context.Context, userID int64) (GetBookReviewStatsRow, error) {
	row := q.db.QueryRow(ctx, getBookReviewStats, userID)
	var i GetBookReviewStatsRow
	err := row.Scan(
		&i.TotalReviews,
		&i.AverageRating,
		&i.MaxRating,
		&i.MinRating,
		&i.FiveStarCount,
	)
	return i, err
}
