// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: chat_room_message.sql

package sqlcgen

import (
	"context"
)

const createGroupMessage = `-- name: CreateGroupMessage :one
INSERT INTO group_messages (chat_room_id, sender_id, content, created_at)
VALUES ($1, $2, $3, now())
RETURNING id, chat_room_id, sender_id, content, created_at
`

type CreateGroupMessageParams struct {
	ChatRoomID int64
	SenderID   int64
	Content    string
}

func (q *Queries) CreateGroupMessage(ctx context.Context, arg CreateGroupMessageParams) (GroupMessage, error) {
	row := q.db.QueryRow(ctx, createGroupMessage, arg.ChatRoomID, arg.SenderID, arg.Content)
	var i GroupMessage
	err := row.Scan(
		&i.ID,
		&i.ChatRoomID,
		&i.SenderID,
		&i.Content,
		&i.CreatedAt,
	)
	return i, err
}

const getUserByIDForChatSender = `-- name: GetUserByIDForChatSender :one
SELECT id, username, name, email, avatar_url, bio, git_hub_id, git_hub_username, git_hub_token, git_hub_connected, spotify_connected, spotify_token, spotify_refresh_token, spotify_token_expiry, zenn_username, qiita_username, at_coder_username, paiza_rank, skills_languages, skills_frameworks, onboarding_completed, email_weekly_report, email_language, created_at, updated_at FROM users WHERE id = $1
`

func (q *Queries) GetUserByIDForChatSender(ctx context.Context, id int64) (User, error) {
	row := q.db.QueryRow(ctx, getUserByIDForChatSender, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Name,
		&i.Email,
		&i.AvatarUrl,
		&i.Bio,
		&i.GitHubID,
		&i.GitHubUsername,
		&i.GitHubToken,
		&i.GitHubConnected,
		&i.SpotifyConnected,
		&i.SpotifyToken,
		&i.SpotifyRefreshToken,
		&i.SpotifyTokenExpiry,
		&i.ZennUsername,
		&i.QiitaUsername,
		&i.AtCoderUsername,
		&i.PaizaRank,
		&i.SkillsLanguages,
		&i.SkillsFrameworks,
		&i.OnboardingCompleted,
		&i.EmailWeeklyReport,
		&i.EmailLanguage,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listGroupMessagesByRoom = `-- name: ListGroupMessagesByRoom :many
SELECT group_messages.id, group_messages.chat_room_id, group_messages.sender_id, group_messages.content, group_messages.created_at, users.id, users.username, users.name, users.email, users.avatar_url, users.bio, users.git_hub_id, users.git_hub_username, users.git_hub_token, users.git_hub_connected, users.spotify_connected, users.spotify_token, users.spotify_refresh_token, users.spotify_token_expiry, users.zenn_username, users.qiita_username, users.at_coder_username, users.paiza_rank, users.skills_languages, users.skills_frameworks, users.onboarding_completed, users.email_weekly_report, users.email_language, users.created_at, users.updated_at
FROM group_messages
JOIN users ON users.id = group_messages.sender_id
WHERE group_messages.chat_room_id = $1
ORDER BY group_messages.created_at ASC
LIMIT $2 OFFSET $3
`

type ListGroupMessagesByRoomParams struct {
	ChatRoomID int64
	Limit      int32
	Offset     int32
}

type ListGroupMessagesByRoomRow struct {
	GroupMessage GroupMessage
	User         User
}

// GORMのPreload("Sender")に相当。sender_idはNOT NULLのためINNER JOINでよい。
func (q *Queries) ListGroupMessagesByRoom(ctx context.Context, arg ListGroupMessagesByRoomParams) ([]ListGroupMessagesByRoomRow, error) {
	rows, err := q.db.Query(ctx, listGroupMessagesByRoom, arg.ChatRoomID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListGroupMessagesByRoomRow
	for rows.Next() {
		var i ListGroupMessagesByRoomRow
		if err := rows.Scan(
			&i.GroupMessage.ID,
			&i.GroupMessage.ChatRoomID,
			&i.GroupMessage.SenderID,
			&i.GroupMessage.Content,
			&i.GroupMessage.CreatedAt,
			&i.User.ID,
			&i.User.Username,
			&i.User.Name,
			&i.User.Email,
			&i.User.AvatarUrl,
			&i.User.Bio,
			&i.User.GitHubID,
			&i.User.GitHubUsername,
			&i.User.GitHubToken,
			&i.User.GitHubConnected,
			&i.User.SpotifyConnected,
			&i.User.SpotifyToken,
			&i.User.SpotifyRefreshToken,
			&i.User.SpotifyTokenExpiry,
			&i.User.ZennUsername,
			&i.User.QiitaUsername,
			&i.User.AtCoderUsername,
			&i.User.PaizaRank,
			&i.User.SkillsLanguages,
			&i.User.SkillsFrameworks,
			&i.User.OnboardingCompleted,
			&i.User.EmailWeeklyReport,
			&i.User.EmailLanguage,
			&i.User.CreatedAt,
			&i.User.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
