// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: chat_room.sql

package sqlcgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countChatRoomMembership = `-- name: CountChatRoomMembership :one
SELECT COUNT(*) FROM chat_room_members WHERE chat_room_id = $1 AND user_id = $2
`

type CountChatRoomMembershipParams struct {
	ChatRoomID int64
	UserID     int64
}

func (q *Queries) CountChatRoomMembership(ctx context.Context, arg CountChatRoomMembershipParams) (int64, error) {
	row := q.db.QueryRow(ctx, countChatRoomMembership, arg.ChatRoomID, arg.UserID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countChatRoomsByUser = `-- name: CountChatRoomsByUser :one
SELECT COUNT(*) FROM chat_room_members WHERE user_id = $1
`

// 件数は ListChatRoomsByUser の総数取得と CountByUserID(単体メソッド) の両方から利用する。
func (q *Queries) CountChatRoomsByUser(ctx context.Context, userID int64) (int64, error) {
	row := q.db.QueryRow(ctx, countChatRoomsByUser, userID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createChatRoom = `-- name: CreateChatRoom :one
INSERT INTO chat_rooms (name, description, owner_id, created_at, updated_at)
VALUES ($1, $2, $3, now(), now())
RETURNING id, name, description, owner_id, created_at, updated_at
`

type CreateChatRoomParams struct {
	Name        string
	Description *string
	OwnerID     int64
}

func (q *Queries) CreateChatRoom(ctx context.Context, arg CreateChatRoomParams) (ChatRoom, error) {
	row := q.db.QueryRow(ctx, createChatRoom, arg.Name, arg.Description, arg.OwnerID)
	var i ChatRoom
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.OwnerID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createChatRoomMember = `-- name: CreateChatRoomMember :exec
INSERT INTO chat_room_members (chat_room_id, user_id, joined_at)
VALUES ($1, $2, $3)
`

type CreateChatRoomMemberParams struct {
	ChatRoomID int64
	UserID     int64
	JoinedAt   pgtype.Timestamptz
}

func (q *Queries) CreateChatRoomMember(ctx context.Context, arg CreateChatRoomMemberParams) error {
	_, err := q.db.Exec(ctx, createChatRoomMember, arg.ChatRoomID, arg.UserID, arg.JoinedAt)
	return err
}

const deleteChatRoom = `-- name: DeleteChatRoom :exec
DELETE FROM chat_rooms WHERE id = $1
`

func (q *Queries) DeleteChatRoom(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, deleteChatRoom, id)
	return err
}

const deleteChatRoomMember = `-- name: DeleteChatRoomMember :exec
DELETE FROM chat_room_members WHERE chat_room_id = $1 AND user_id = $2
`

type DeleteChatRoomMemberParams struct {
	ChatRoomID int64
	UserID     int64
}

func (q *Queries) DeleteChatRoomMember(ctx context.Context, arg DeleteChatRoomMemberParams) error {
	_, err := q.db.Exec(ctx, deleteChatRoomMember, arg.ChatRoomID, arg.UserID)
	return err
}

const deleteChatRoomMembersByRoom = `-- name: DeleteChatRoomMembersByRoom :exec
DELETE FROM chat_room_members WHERE chat_room_id = $1
`

func (q *Queries) DeleteChatRoomMembersByRoom(ctx context.Context, chatRoomID int64) error {
	_, err := q.db.Exec(ctx, deleteChatRoomMembersByRoom, chatRoomID)
	return err
}

const deleteGroupMessagesByRoom = `-- name: DeleteGroupMessagesByRoom :exec
DELETE FROM group_messages WHERE chat_room_id = $1
`

func (q *Queries) DeleteGroupMessagesByRoom(ctx context.Context, chatRoomID int64) error {
	_, err := q.db.Exec(ctx, deleteGroupMessagesByRoom, chatRoomID)
	return err
}

const getChatRoomWithOwnerByID = `-- name: GetChatRoomWithOwnerByID :one
SELECT chat_rooms.id, chat_rooms.name, chat_rooms.description, chat_rooms.owner_id, chat_rooms.created_at, chat_rooms.updated_at, users.id, users.username, users.name, users.email, users.password, users.avatar_url, users.bio, users.git_hub_id, users.git_hub_username, users.git_hub_token, users.git_hub_connected, users.spotify_connected, users.spotify_token, users.spotify_refresh_token, users.spotify_token_expiry, users.zenn_username, users.qiita_username, users.at_coder_username, users.paiza_rank, users.skills_languages, users.skills_frameworks, users.onboarding_completed, users.email_weekly_report, users.email_language, users.created_at, users.updated_at
FROM chat_rooms
JOIN users ON users.id = chat_rooms.owner_id
WHERE chat_rooms.id = $1
`

type GetChatRoomWithOwnerByIDRow struct {
	ChatRoom ChatRoom
	User     User
}

// GORMのPreload("Owner")に相当。owner_idはNOT NULLのためINNER JOINでよい。
func (q *Queries) GetChatRoomWithOwnerByID(ctx context.Context, id int64) (GetChatRoomWithOwnerByIDRow, error) {
	row := q.db.QueryRow(ctx, getChatRoomWithOwnerByID, id)
	var i GetChatRoomWithOwnerByIDRow
	err := row.Scan(
		&i.ChatRoom.ID,
		&i.ChatRoom.Name,
		&i.ChatRoom.Description,
		&i.ChatRoom.OwnerID,
		&i.ChatRoom.CreatedAt,
		&i.ChatRoom.UpdatedAt,
		&i.User.ID,
		&i.User.Username,
		&i.User.Name,
		&i.User.Email,
		&i.User.Password,
		&i.User.AvatarUrl,
		&i.User.Bio,
		&i.User.GitHubID,
		&i.User.GitHubUsername,
		&i.User.GitHubToken,
		&i.User.GitHubConnected,
		&i.User.SpotifyConnected,
		&i.User.SpotifyToken,
		&i.User.SpotifyRefreshToken,
		&i.User.SpotifyTokenExpiry,
		&i.User.ZennUsername,
		&i.User.QiitaUsername,
		&i.User.AtCoderUsername,
		&i.User.PaizaRank,
		&i.User.SkillsLanguages,
		&i.User.SkillsFrameworks,
		&i.User.OnboardingCompleted,
		&i.User.EmailWeeklyReport,
		&i.User.EmailLanguage,
		&i.User.CreatedAt,
		&i.User.UpdatedAt,
	)
	return i, err
}

const listChatRoomMembersWithUser = `-- name: ListChatRoomMembersWithUser :many
SELECT chat_room_members.id, chat_room_members.chat_room_id, chat_room_members.user_id, chat_room_members.joined_at, users.id, users.username, users.name, users.email, users.password, users.avatar_url, users.bio, users.git_hub_id, users.git_hub_username, users.git_hub_token, users.git_hub_connected, users.spotify_connected, users.spotify_token, users.spotify_refresh_token, users.spotify_token_expiry, users.zenn_username, users.qiita_username, users.at_coder_username, users.paiza_rank, users.skills_languages, users.skills_frameworks, users.onboarding_completed, users.email_weekly_report, users.email_language, users.created_at, users.updated_at
FROM chat_room_members
JOIN users ON users.id = chat_room_members.user_id
WHERE chat_room_members.chat_room_id = $1
`

type ListChatRoomMembersWithUserRow struct {
	ChatRoomMember ChatRoomMember
	User           User
}

// GORMのPreload("User")に相当。user_idはNOT NULLのためINNER JOINでよい。
func (q *Queries) ListChatRoomMembersWithUser(ctx context.Context, chatRoomID int64) ([]ListChatRoomMembersWithUserRow, error) {
	rows, err := q.db.Query(ctx, listChatRoomMembersWithUser, chatRoomID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListChatRoomMembersWithUserRow
	for rows.Next() {
		var i ListChatRoomMembersWithUserRow
		if err := rows.Scan(
			&i.ChatRoomMember.ID,
			&i.ChatRoomMember.ChatRoomID,
			&i.ChatRoomMember.UserID,
			&i.ChatRoomMember.JoinedAt,
			&i.User.ID,
			&i.User.Username,
			&i.User.Name,
			&i.User.Email,
			&i.User.Password,
			&i.User.AvatarUrl,
			&i.User.Bio,
			&i.User.GitHubID,
			&i.User.GitHubUsername,
			&i.User.GitHubToken,
			&i.User.GitHubConnected,
			&i.User.SpotifyConnected,
			&i.User.SpotifyToken,
			&i.User.SpotifyRefreshToken,
			&i.User.SpotifyTokenExpiry,
			&i.User.ZennUsername,
			&i.User.QiitaUsername,
			&i.User.AtCoderUsername,
			&i.User.PaizaRank,
			&i.User.SkillsLanguages,
			&i.User.SkillsFrameworks,
			&i.User.OnboardingCompleted,
			&i.User.EmailWeeklyReport,
			&i.User.EmailLanguage,
			&i.User.CreatedAt,
			&i.User.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listChatRoomsByUser = `-- name: ListChatRoomsByUser :many
SELECT chat_rooms.id, chat_rooms.name, chat_rooms.description, chat_rooms.owner_id, chat_rooms.created_at, chat_rooms.updated_at, users.id, users.username, users.name, users.email, users.password, users.avatar_url, users.bio, users.git_hub_id, users.git_hub_username, users.git_hub_token, users.git_hub_connected, users.spotify_connected, users.spotify_token, users.spotify_refresh_token, users.spotify_token_expiry, users.zenn_username, users.qiita_username, users.at_coder_username, users.paiza_rank, users.skills_languages, users.skills_frameworks, users.onboarding_completed, users.email_weekly_report, users.email_language, users.created_at, users.updated_at
FROM chat_rooms
JOIN chat_room_members ON chat_room_members.chat_room_id = chat_rooms.id
JOIN users ON users.id = chat_rooms.owner_id
WHERE chat_room_members.user_id = $1
ORDER BY chat_rooms.updated_at DESC
LIMIT $2 OFFSET $3
`

type ListChatRoomsByUserParams struct {
	UserID int64
	Limit  int32
	Offset int32
}

type ListChatRoomsByUserRow struct {
	ChatRoom ChatRoom
	User     User
}

// GORMのPreload("Owner")に相当。owner_idはNOT NULLのためINNER JOINでよい。
func (q *Queries) ListChatRoomsByUser(ctx context.Context, arg ListChatRoomsByUserParams) ([]ListChatRoomsByUserRow, error) {
	rows, err := q.db.Query(ctx, listChatRoomsByUser, arg.UserID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListChatRoomsByUserRow
	for rows.Next() {
		var i ListChatRoomsByUserRow
		if err := rows.Scan(
			&i.ChatRoom.ID,
			&i.ChatRoom.Name,
			&i.ChatRoom.Description,
			&i.ChatRoom.OwnerID,
			&i.ChatRoom.CreatedAt,
			&i.ChatRoom.UpdatedAt,
			&i.User.ID,
			&i.User.Username,
			&i.User.Name,
			&i.User.Email,
			&i.User.Password,
			&i.User.AvatarUrl,
			&i.User.Bio,
			&i.User.GitHubID,
			&i.User.GitHubUsername,
			&i.User.GitHubToken,
			&i.User.GitHubConnected,
			&i.User.SpotifyConnected,
			&i.User.SpotifyToken,
			&i.User.SpotifyRefreshToken,
			&i.User.SpotifyTokenExpiry,
			&i.User.ZennUsername,
			&i.User.QiitaUsername,
			&i.User.AtCoderUsername,
			&i.User.PaizaRank,
			&i.User.SkillsLanguages,
			&i.User.SkillsFrameworks,
			&i.User.OnboardingCompleted,
			&i.User.EmailWeeklyReport,
			&i.User.EmailLanguage,
			&i.User.CreatedAt,
			&i.User.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateChatRoom = `-- name: UpdateChatRoom :one
UPDATE chat_rooms SET name = $2, description = $3, updated_at = now()
WHERE id = $1
RETURNING id, name, description, owner_id, created_at, updated_at
`

type UpdateChatRoomParams struct {
	ID          int64
	Name        string
	Description *string
}

// GORMのSave（全カラム上書き）に相当。
func (q *Queries) UpdateChatRoom(ctx context.Context, arg UpdateChatRoomParams) (ChatRoom, error) {
	row := q.db.QueryRow(ctx, updateChatRoom, arg.ID, arg.Name, arg.Description)
	var i ChatRoom
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.OwnerID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
