// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: code_snippet.sql

package sqlcgen

import (
	"context"
)

const countFavoritedCodeSnippets = `-- name: CountFavoritedCodeSnippets :one
SELECT COUNT(*) FROM code_snippets
WHERE code_snippets.id IN (
    SELECT f.snippet_id FROM code_snippet_favorites f WHERE f.user_id = $1
)
`

func (q *Queries) CountFavoritedCodeSnippets(ctx context.Context, userID int64) (int64, error) {
	row := q.db.QueryRow(ctx, countFavoritedCodeSnippets, userID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countSearchCodeSnippets = `-- name: CountSearchCodeSnippets :one
SELECT COUNT(*) FROM code_snippets
WHERE code_snippets.language ILIKE $1 OR code_snippets.file_name ILIKE $1 OR code_snippets.code ILIKE $1
`

func (q *Queries) CountSearchCodeSnippets(ctx context.Context, language string) (int64, error) {
	row := q.db.QueryRow(ctx, countSearchCodeSnippets, language)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countSnippetFavorite = `-- name: CountSnippetFavorite :one
SELECT COUNT(*) FROM code_snippet_favorites
WHERE code_snippet_favorites.user_id = $1 AND code_snippet_favorites.snippet_id = $2
`

type CountSnippetFavoriteParams struct {
	UserID    int64
	SnippetID int64
}

func (q *Queries) CountSnippetFavorite(ctx context.Context, arg CountSnippetFavoriteParams) (int64, error) {
	row := q.db.QueryRow(ctx, countSnippetFavorite, arg.UserID, arg.SnippetID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createCodeSnippet = `-- name: CreateCodeSnippet :one
INSERT INTO code_snippets (
    post_id, user_id, language, file_name, code, comment_count, forked_from_id, fork_count,
    created_at, updated_at
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, now(), now()
) RETURNING id, post_id, user_id, language, file_name, code, comment_count, forked_from_id, fork_count, created_at, updated_at
`

type CreateCodeSnippetParams struct {
	PostID       int64
	UserID       int64
	Language     string
	FileName     *string
	Code         string
	CommentCount *int64
	ForkedFromID *int64
	ForkCount    *int64
}

func (q *Queries) CreateCodeSnippet(ctx context.Context, arg CreateCodeSnippetParams) (CodeSnippet, error) {
	row := q.db.QueryRow(ctx, createCodeSnippet,
		arg.PostID,
		arg.UserID,
		arg.Language,
		arg.FileName,
		arg.Code,
		arg.CommentCount,
		arg.ForkedFromID,
		arg.ForkCount,
	)
	var i CodeSnippet
	err := row.Scan(
		&i.ID,
		&i.PostID,
		&i.UserID,
		&i.Language,
		&i.FileName,
		&i.Code,
		&i.CommentCount,
		&i.ForkedFromID,
		&i.ForkCount,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createSnippetComment = `-- name: CreateSnippetComment :one
INSERT INTO snippet_comments (snippet_id, user_id, line_number, content, created_at, updated_at)
VALUES ($1, $2, $3, $4, now(), now())
RETURNING id, snippet_id, user_id, line_number, content, created_at, updated_at
`

type CreateSnippetCommentParams struct {
	SnippetID  int64
	UserID     int64
	LineNumber int64
	Content    string
}

func (q *Queries) CreateSnippetComment(ctx context.Context, arg CreateSnippetCommentParams) (SnippetComment, error) {
	row := q.db.QueryRow(ctx, createSnippetComment,
		arg.SnippetID,
		arg.UserID,
		arg.LineNumber,
		arg.Content,
	)
	var i SnippetComment
	err := row.Scan(
		&i.ID,
		&i.SnippetID,
		&i.UserID,
		&i.LineNumber,
		&i.Content,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createSnippetFavorite = `-- name: CreateSnippetFavorite :exec
INSERT INTO code_snippet_favorites (user_id, snippet_id, created_at) VALUES ($1, $2, now())
`

type CreateSnippetFavoriteParams struct {
	UserID    int64
	SnippetID int64
}

func (q *Queries) CreateSnippetFavorite(ctx context.Context, arg CreateSnippetFavoriteParams) error {
	_, err := q.db.Exec(ctx, createSnippetFavorite, arg.UserID, arg.SnippetID)
	return err
}

const decrementSnippetCommentCountFloored = `-- name: DecrementSnippetCommentCountFloored :exec
UPDATE code_snippets SET comment_count = GREATEST(comment_count - 1, 0) WHERE code_snippets.id = $1
`

// 0未満にはしない（GORMのGREATEST(comment_count - 1, 0)に相当）。
func (q *Queries) DecrementSnippetCommentCountFloored(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, decrementSnippetCommentCountFloored, id)
	return err
}

const deleteCodeSnippetByID = `-- name: DeleteCodeSnippetByID :exec
DELETE FROM code_snippets WHERE code_snippets.id = $1
`

func (q *Queries) DeleteCodeSnippetByID(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, deleteCodeSnippetByID, id)
	return err
}

const deleteSnippetCommentByID = `-- name: DeleteSnippetCommentByID :exec
DELETE FROM snippet_comments WHERE snippet_comments.id = $1
`

func (q *Queries) DeleteSnippetCommentByID(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, deleteSnippetCommentByID, id)
	return err
}

const deleteSnippetFavorite = `-- name: DeleteSnippetFavorite :exec
DELETE FROM code_snippet_favorites
WHERE code_snippet_favorites.user_id = $1 AND code_snippet_favorites.snippet_id = $2
`

type DeleteSnippetFavoriteParams struct {
	UserID    int64
	SnippetID int64
}

func (q *Queries) DeleteSnippetFavorite(ctx context.Context, arg DeleteSnippetFavoriteParams) error {
	_, err := q.db.Exec(ctx, deleteSnippetFavorite, arg.UserID, arg.SnippetID)
	return err
}

const findCodeSnippetsByUserAndLanguage = `-- name: FindCodeSnippetsByUserAndLanguage :many
SELECT id, post_id, user_id, language, file_name, code, comment_count, forked_from_id, fork_count, created_at, updated_at FROM code_snippets
WHERE code_snippets.user_id = $1 AND code_snippets.language = $2
ORDER BY code_snippets.created_at DESC
`

type FindCodeSnippetsByUserAndLanguageParams struct {
	UserID   int64
	Language string
}

func (q *Queries) FindCodeSnippetsByUserAndLanguage(ctx context.Context, arg FindCodeSnippetsByUserAndLanguageParams) ([]CodeSnippet, error) {
	rows, err := q.db.Query(ctx, findCodeSnippetsByUserAndLanguage, arg.UserID, arg.Language)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CodeSnippet
	for rows.Next() {
		var i CodeSnippet
		if err := rows.Scan(
			&i.ID,
			&i.PostID,
			&i.UserID,
			&i.Language,
			&i.FileName,
			&i.Code,
			&i.CommentCount,
			&i.ForkedFromID,
			&i.ForkCount,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getCodeSnippetByID = `-- name: GetCodeSnippetByID :one
SELECT id, post_id, user_id, language, file_name, code, comment_count, forked_from_id, fork_count, created_at, updated_at FROM code_snippets WHERE code_snippets.id = $1
`

func (q *Queries) GetCodeSnippetByID(ctx context.Context, id int64) (CodeSnippet, error) {
	row := q.db.QueryRow(ctx, getCodeSnippetByID, id)
	var i CodeSnippet
	err := row.Scan(
		&i.ID,
		&i.PostID,
		&i.UserID,
		&i.Language,
		&i.FileName,
		&i.Code,
		&i.CommentCount,
		&i.ForkedFromID,
		&i.ForkCount,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getSnippetCommentByID = `-- name: GetSnippetCommentByID :one
SELECT id, snippet_id, user_id, line_number, content, created_at, updated_at FROM snippet_comments WHERE snippet_comments.id = $1
`

func (q *Queries) GetSnippetCommentByID(ctx context.Context, id int64) (SnippetComment, error) {
	row := q.db.QueryRow(ctx, getSnippetCommentByID, id)
	var i SnippetComment
	err := row.Scan(
		&i.ID,
		&i.SnippetID,
		&i.UserID,
		&i.LineNumber,
		&i.Content,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getSnippetCommentsWithUser = `-- name: GetSnippetCommentsWithUser :many
SELECT snippet_comments.id, snippet_comments.snippet_id, snippet_comments.user_id, snippet_comments.line_number, snippet_comments.content, snippet_comments.created_at, snippet_comments.updated_at, users.id, users.username, users.name, users.email, users.avatar_url, users.bio, users.git_hub_id, users.git_hub_username, users.git_hub_token, users.git_hub_connected, users.spotify_connected, users.spotify_token, users.spotify_refresh_token, users.spotify_token_expiry, users.zenn_username, users.qiita_username, users.at_coder_username, users.paiza_rank, users.skills_languages, users.skills_frameworks, users.onboarding_completed, users.email_weekly_report, users.email_language, users.created_at, users.updated_at
FROM snippet_comments
JOIN users ON users.id = snippet_comments.user_id
WHERE snippet_comments.snippet_id = $1
ORDER BY snippet_comments.line_number ASC, snippet_comments.created_at ASC
`

type GetSnippetCommentsWithUserRow struct {
	SnippetComment SnippetComment
	User           User
}

// GORMのPreload("User")に相当。user_idはNOT NULLのためINNER JOINでよい。
func (q *Queries) GetSnippetCommentsWithUser(ctx context.Context, snippetID int64) ([]GetSnippetCommentsWithUserRow, error) {
	rows, err := q.db.Query(ctx, getSnippetCommentsWithUser, snippetID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetSnippetCommentsWithUserRow
	for rows.Next() {
		var i GetSnippetCommentsWithUserRow
		if err := rows.Scan(
			&i.SnippetComment.ID,
			&i.SnippetComment.SnippetID,
			&i.SnippetComment.UserID,
			&i.SnippetComment.LineNumber,
			&i.SnippetComment.Content,
			&i.SnippetComment.CreatedAt,
			&i.SnippetComment.UpdatedAt,
			&i.User.ID,
			&i.User.Username,
			&i.User.Name,
			&i.User.Email,
			&i.User.AvatarUrl,
			&i.User.Bio,
			&i.User.GitHubID,
			&i.User.GitHubUsername,
			&i.User.GitHubToken,
			&i.User.GitHubConnected,
			&i.User.SpotifyConnected,
			&i.User.SpotifyToken,
			&i.User.SpotifyRefreshToken,
			&i.User.SpotifyTokenExpiry,
			&i.User.ZennUsername,
			&i.User.QiitaUsername,
			&i.User.AtCoderUsername,
			&i.User.PaizaRank,
			&i.User.SkillsLanguages,
			&i.User.SkillsFrameworks,
			&i.User.OnboardingCompleted,
			&i.User.EmailWeeklyReport,
			&i.User.EmailLanguage,
			&i.User.CreatedAt,
			&i.User.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const incrementSnippetCommentCount = `-- name: IncrementSnippetCommentCount :exec
UPDATE code_snippets SET comment_count = comment_count + 1 WHERE code_snippets.id = $1
`

func (q *Queries) IncrementSnippetCommentCount(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, incrementSnippetCommentCount, id)
	return err
}

const incrementSnippetForkCount = `-- name: IncrementSnippetForkCount :exec
UPDATE code_snippets SET fork_count = fork_count + 1 WHERE code_snippets.id = $1
`

func (q *Queries) IncrementSnippetForkCount(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, incrementSnippetForkCount, id)
	return err
}

const listFavoritedCodeSnippets = `-- name: ListFavoritedCodeSnippets :many
SELECT id, post_id, user_id, language, file_name, code, comment_count, forked_from_id, fork_count, created_at, updated_at FROM code_snippets
WHERE code_snippets.id IN (
    SELECT f.snippet_id FROM code_snippet_favorites f WHERE f.user_id = $1
)
ORDER BY code_snippets.created_at DESC
LIMIT $2 OFFSET $3
`

type ListFavoritedCodeSnippetsParams struct {
	UserID int64
	Limit  int32
	Offset int32
}

func (q *Queries) ListFavoritedCodeSnippets(ctx context.Context, arg ListFavoritedCodeSnippetsParams) ([]CodeSnippet, error) {
	rows, err := q.db.Query(ctx, listFavoritedCodeSnippets, arg.UserID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CodeSnippet
	for rows.Next() {
		var i CodeSnippet
		if err := rows.Scan(
			&i.ID,
			&i.PostID,
			&i.UserID,
			&i.Language,
			&i.FileName,
			&i.Code,
			&i.CommentCount,
			&i.ForkedFromID,
			&i.ForkCount,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchCodeSnippets = `-- name: SearchCodeSnippets :many
SELECT id, post_id, user_id, language, file_name, code, comment_count, forked_from_id, fork_count, created_at, updated_at FROM code_snippets
WHERE code_snippets.language ILIKE $1 OR code_snippets.file_name ILIKE $1 OR code_snippets.code ILIKE $1
ORDER BY code_snippets.created_at DESC
LIMIT $2 OFFSET $3
`

type SearchCodeSnippetsParams struct {
	Language string
	Limit    int32
	Offset   int32
}

// CodeSnippet は投稿者の ID しか持たず User の関連を張っていないため、Preload しない
// （移行前のGORM実装のコメントの通り、Preloadするとunsupported relationsで失敗する）。
func (q *Queries) SearchCodeSnippets(ctx context.Context, arg SearchCodeSnippetsParams) ([]CodeSnippet, error) {
	rows, err := q.db.Query(ctx, searchCodeSnippets, arg.Language, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CodeSnippet
	for rows.Next() {
		var i CodeSnippet
		if err := rows.Scan(
			&i.ID,
			&i.PostID,
			&i.UserID,
			&i.Language,
			&i.FileName,
			&i.Code,
			&i.CommentCount,
			&i.ForkedFromID,
			&i.ForkCount,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateCodeSnippet = `-- name: UpdateCodeSnippet :one
UPDATE code_snippets SET
    language = $2, file_name = $3, code = $4, comment_count = $5, forked_from_id = $6,
    fork_count = $7, updated_at = now()
WHERE code_snippets.id = $1
RETURNING id, post_id, user_id, language, file_name, code, comment_count, forked_from_id, fork_count, created_at, updated_at
`

type UpdateCodeSnippetParams struct {
	ID           int64
	Language     string
	FileName     *string
	Code         string
	CommentCount *int64
	ForkedFromID *int64
	ForkCount    *int64
}

// GORMのSave（全カラム上書き）に相当。
func (q *Queries) UpdateCodeSnippet(ctx context.Context, arg UpdateCodeSnippetParams) (CodeSnippet, error) {
	row := q.db.QueryRow(ctx, updateCodeSnippet,
		arg.ID,
		arg.Language,
		arg.FileName,
		arg.Code,
		arg.CommentCount,
		arg.ForkedFromID,
		arg.ForkCount,
	)
	var i CodeSnippet
	err := row.Scan(
		&i.ID,
		&i.PostID,
		&i.UserID,
		&i.Language,
		&i.FileName,
		&i.Code,
		&i.CommentCount,
		&i.ForkedFromID,
		&i.ForkCount,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
