// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: comment_stats.sql

package sqlcgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countCommentsByUserSince = `-- name: CountCommentsByUserSince :one
SELECT count(*) FROM comments
WHERE user_id = $1 AND created_at >= $2
`

type CountCommentsByUserSinceParams struct {
	UserID    int64
	CreatedAt pgtype.Timestamptz
}

func (q *Queries) CountCommentsByUserSince(ctx context.Context, arg CountCommentsByUserSinceParams) (int64, error) {
	row := q.db.QueryRow(ctx, countCommentsByUserSince, arg.UserID, arg.CreatedAt)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countCommentsReceivedByUser = `-- name: CountCommentsReceivedByUser :one
SELECT count(*) FROM comments
JOIN posts ON posts.id = comments.post_id
WHERE posts.user_id = $1 AND comments.user_id != $1
`

func (q *Queries) CountCommentsReceivedByUser(ctx context.Context, userID int64) (int64, error) {
	row := q.db.QueryRow(ctx, countCommentsReceivedByUser, userID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countRepliesByUser = `-- name: CountRepliesByUser :one
SELECT count(*) FROM comments
WHERE user_id = $1 AND parent_id IS NOT NULL
`

func (q *Queries) CountRepliesByUser(ctx context.Context, userID int64) (int64, error) {
	row := q.db.QueryRow(ctx, countRepliesByUser, userID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countTopLevelCommentsByUser = `-- name: CountTopLevelCommentsByUser :one
SELECT count(*) FROM comments
WHERE user_id = $1 AND parent_id IS NULL
`

func (q *Queries) CountTopLevelCommentsByUser(ctx context.Context, userID int64) (int64, error) {
	row := q.db.QueryRow(ctx, countTopLevelCommentsByUser, userID)
	var count int64
	err := row.Scan(&count)
	return count, err
}
