// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: github.sql

package sqlcgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const deleteGitHubContributionsByUser = `-- name: DeleteGitHubContributionsByUser :exec
DELETE FROM git_hub_contributions WHERE user_id = $1
`

// GitHub連携の「解除」（アカウント削除ではない）で使う。ユーザー本体は残るため
// FKのON DELETE CASCADEでは代替できない。GitHubRepository.DeleteUserDataから呼ばれる。
func (q *Queries) DeleteGitHubContributionsByUser(ctx context.Context, userID int64) error {
	_, err := q.db.Exec(ctx, deleteGitHubContributionsByUser, userID)
	return err
}

const deleteGitHubLanguageStatsByUser = `-- name: DeleteGitHubLanguageStatsByUser :exec
DELETE FROM git_hub_language_stats WHERE user_id = $1
`

func (q *Queries) DeleteGitHubLanguageStatsByUser(ctx context.Context, userID int64) error {
	_, err := q.db.Exec(ctx, deleteGitHubLanguageStatsByUser, userID)
	return err
}

const deleteGitHubReposByUser = `-- name: DeleteGitHubReposByUser :exec
DELETE FROM git_hub_repositories WHERE user_id = $1
`

func (q *Queries) DeleteGitHubReposByUser(ctx context.Context, userID int64) error {
	_, err := q.db.Exec(ctx, deleteGitHubReposByUser, userID)
	return err
}

const listAllGitHubContributionsByUser = `-- name: ListAllGitHubContributionsByUser :many
SELECT id, user_id, date, count, created_at, updated_at FROM git_hub_contributions WHERE user_id = $1 ORDER BY date ASC
`

func (q *Queries) ListAllGitHubContributionsByUser(ctx context.Context, userID int64) ([]GitHubContribution, error) {
	rows, err := q.db.Query(ctx, listAllGitHubContributionsByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GitHubContribution
	for rows.Next() {
		var i GitHubContribution
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Date,
			&i.Count,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listGitHubLanguageStatsByUser = `-- name: ListGitHubLanguageStatsByUser :many
SELECT id, user_id, language, bytes, repo_count, updated_at FROM git_hub_language_stats WHERE user_id = $1 ORDER BY bytes DESC
`

func (q *Queries) ListGitHubLanguageStatsByUser(ctx context.Context, userID int64) ([]GitHubLanguageStat, error) {
	rows, err := q.db.Query(ctx, listGitHubLanguageStatsByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GitHubLanguageStat
	for rows.Next() {
		var i GitHubLanguageStat
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Language,
			&i.Bytes,
			&i.RepoCount,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listGitHubReposByUser = `-- name: ListGitHubReposByUser :many
SELECT id, user_id, git_hub_repo_id, name, full_name, description, language, stars, forks, is_private, updated_at FROM git_hub_repositories WHERE user_id = $1 ORDER BY stars DESC
`

func (q *Queries) ListGitHubReposByUser(ctx context.Context, userID int64) ([]GitHubRepository, error) {
	rows, err := q.db.Query(ctx, listGitHubReposByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GitHubRepository
	for rows.Next() {
		var i GitHubRepository
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.GitHubRepoID,
			&i.Name,
			&i.FullName,
			&i.Description,
			&i.Language,
			&i.Stars,
			&i.Forks,
			&i.IsPrivate,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertGitHubContribution = `-- name: UpsertGitHubContribution :one
INSERT INTO git_hub_contributions (user_id, date, count, created_at, updated_at)
VALUES ($1, $2, $3, now(), now())
ON CONFLICT (user_id, date) DO UPDATE SET
    count = EXCLUDED.count,
    updated_at = EXCLUDED.updated_at
RETURNING id, user_id, date, count, created_at, updated_at
`

type UpsertGitHubContributionParams struct {
	UserID int64
	Date   pgtype.Timestamptz
	Count  int64
}

func (q *Queries) UpsertGitHubContribution(ctx context.Context, arg UpsertGitHubContributionParams) (GitHubContribution, error) {
	row := q.db.QueryRow(ctx, upsertGitHubContribution, arg.UserID, arg.Date, arg.Count)
	var i GitHubContribution
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Date,
		&i.Count,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertGitHubLanguageStat = `-- name: UpsertGitHubLanguageStat :one
INSERT INTO git_hub_language_stats (user_id, language, bytes, repo_count, updated_at)
VALUES ($1, $2, $3, $4, now())
ON CONFLICT (user_id, language) DO UPDATE SET
    bytes = EXCLUDED.bytes,
    repo_count = EXCLUDED.repo_count,
    updated_at = EXCLUDED.updated_at
RETURNING id, user_id, language, bytes, repo_count, updated_at
`

type UpsertGitHubLanguageStatParams struct {
	UserID    int64
	Language  string
	Bytes     int64
	RepoCount int64
}

func (q *Queries) UpsertGitHubLanguageStat(ctx context.Context, arg UpsertGitHubLanguageStatParams) (GitHubLanguageStat, error) {
	row := q.db.QueryRow(ctx, upsertGitHubLanguageStat,
		arg.UserID,
		arg.Language,
		arg.Bytes,
		arg.RepoCount,
	)
	var i GitHubLanguageStat
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Language,
		&i.Bytes,
		&i.RepoCount,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertGitHubRepo = `-- name: UpsertGitHubRepo :one
INSERT INTO git_hub_repositories (user_id, git_hub_repo_id, name, full_name, description, language, stars, forks, is_private, updated_at)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, now())
ON CONFLICT (user_id, git_hub_repo_id) DO UPDATE SET
    name = EXCLUDED.name,
    full_name = EXCLUDED.full_name,
    description = EXCLUDED.description,
    language = EXCLUDED.language,
    stars = EXCLUDED.stars,
    forks = EXCLUDED.forks,
    is_private = EXCLUDED.is_private,
    updated_at = EXCLUDED.updated_at
RETURNING id, user_id, git_hub_repo_id, name, full_name, description, language, stars, forks, is_private, updated_at
`

type UpsertGitHubRepoParams struct {
	UserID       int64
	GitHubRepoID int64
	Name         string
	FullName     *string
	Description  *string
	Language     *string
	Stars        *int64
	Forks        *int64
	IsPrivate    *bool
}

func (q *Queries) UpsertGitHubRepo(ctx context.Context, arg UpsertGitHubRepoParams) (GitHubRepository, error) {
	row := q.db.QueryRow(ctx, upsertGitHubRepo,
		arg.UserID,
		arg.GitHubRepoID,
		arg.Name,
		arg.FullName,
		arg.Description,
		arg.Language,
		arg.Stars,
		arg.Forks,
		arg.IsPrivate,
	)
	var i GitHubRepository
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.GitHubRepoID,
		&i.Name,
		&i.FullName,
		&i.Description,
		&i.Language,
		&i.Stars,
		&i.Forks,
		&i.IsPrivate,
		&i.UpdatedAt,
	)
	return i, err
}
