// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: learning_analytics.sql

package sqlcgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countLearningLogDaysSince = `-- name: CountLearningLogDaysSince :one
SELECT COUNT(DISTINCT DATE(created_at)) FROM learning_logs WHERE user_id = $1 AND created_at >= $2
`

type CountLearningLogDaysSinceParams struct {
	UserID    int64
	CreatedAt pgtype.Timestamptz
}

func (q *Queries) CountLearningLogDaysSince(ctx context.Context, arg CountLearningLogDaysSinceParams) (int64, error) {
	row := q.db.QueryRow(ctx, countLearningLogDaysSince, arg.UserID, arg.CreatedAt)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countLearningLogsBySourceSince = `-- name: CountLearningLogsBySourceSince :one
SELECT COUNT(*) FROM learning_logs WHERE user_id = $1 AND source = $2 AND created_at >= $3
`

type CountLearningLogsBySourceSinceParams struct {
	UserID    int64
	Source    *string
	CreatedAt pgtype.Timestamptz
}

func (q *Queries) CountLearningLogsBySourceSince(ctx context.Context, arg CountLearningLogsBySourceSinceParams) (int64, error) {
	row := q.db.QueryRow(ctx, countLearningLogsBySourceSince, arg.UserID, arg.Source, arg.CreatedAt)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getLearningCategoryBreakdown = `-- name: GetLearningCategoryBreakdown :many
SELECT
    category,
    COALESCE(SUM(duration), 0)::bigint AS total_minutes,
    COUNT(*) AS log_count
FROM learning_logs
WHERE user_id = $1
GROUP BY category
ORDER BY total_minutes DESC
`

type GetLearningCategoryBreakdownRow struct {
	Category     *string
	TotalMinutes int64
	LogCount     int64
}

// 割合はusecase側で計算するため、ここでは合計時間とログ件数のみを返す。
func (q *Queries) GetLearningCategoryBreakdown(ctx context.Context, userID int64) ([]GetLearningCategoryBreakdownRow, error) {
	rows, err := q.db.Query(ctx, getLearningCategoryBreakdown, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetLearningCategoryBreakdownRow
	for rows.Next() {
		var i GetLearningCategoryBreakdownRow
		if err := rows.Scan(&i.Category, &i.TotalMinutes, &i.LogCount); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getLearningHeatmapData = `-- name: GetLearningHeatmapData :many
SELECT
    EXTRACT(DOW FROM created_at)::int AS day_of_week,
    EXTRACT(HOUR FROM created_at)::int AS hour,
    COALESCE(SUM(duration), 0)::bigint AS total_minutes
FROM learning_logs
WHERE user_id = $1
GROUP BY day_of_week, hour
ORDER BY day_of_week, hour
`

type GetLearningHeatmapDataRow struct {
	DayOfWeek    int32
	Hour         int32
	TotalMinutes int64
}

func (q *Queries) GetLearningHeatmapData(ctx context.Context, userID int64) ([]GetLearningHeatmapDataRow, error) {
	rows, err := q.db.Query(ctx, getLearningHeatmapData, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetLearningHeatmapDataRow
	for rows.Next() {
		var i GetLearningHeatmapDataRow
		if err := rows.Scan(&i.DayOfWeek, &i.Hour, &i.TotalMinutes); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getLearningWeeklyTrends = `-- name: GetLearningWeeklyTrends :many
SELECT
    TO_CHAR(DATE_TRUNC('week', created_at), 'YYYY-MM-DD') AS week_start,
    COALESCE(SUM(duration), 0)::bigint AS total_minutes,
    COUNT(*) AS log_count
FROM learning_logs
WHERE user_id = $1 AND created_at >= $2
GROUP BY week_start
ORDER BY week_start
`

type GetLearningWeeklyTrendsParams struct {
	UserID    int64
	CreatedAt pgtype.Timestamptz
}

type GetLearningWeeklyTrendsRow struct {
	WeekStart    string
	TotalMinutes int64
	LogCount     int64
}

func (q *Queries) GetLearningWeeklyTrends(ctx context.Context, arg GetLearningWeeklyTrendsParams) ([]GetLearningWeeklyTrendsRow, error) {
	rows, err := q.db.Query(ctx, getLearningWeeklyTrends, arg.UserID, arg.CreatedAt)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetLearningWeeklyTrendsRow
	for rows.Next() {
		var i GetLearningWeeklyTrendsRow
		if err := rows.Scan(&i.WeekStart, &i.TotalMinutes, &i.LogCount); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDistinctLearningLogDates = `-- name: ListDistinctLearningLogDates :many
SELECT DISTINCT DATE(created_at) AS log_date
FROM learning_logs
WHERE user_id = $1
ORDER BY log_date DESC
`

// ストリーク（現在・最長連続日数）の算出に使う、学習記録がある日付の一覧（新しい順）。
func (q *Queries) ListDistinctLearningLogDates(ctx context.Context, userID int64) ([]pgtype.Date, error) {
	rows, err := q.db.Query(ctx, listDistinctLearningLogDates, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []pgtype.Date
	for rows.Next() {
		var log_date pgtype.Date
		if err := rows.Scan(&log_date); err != nil {
			return nil, err
		}
		items = append(items, log_date)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
