// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: learning_resource_stats.sql

package sqlcgen

import (
	"context"
)

const countLearningResourceCategoriesByUser = `-- name: CountLearningResourceCategoriesByUser :one
SELECT count(DISTINCT category) FROM learning_resources
WHERE user_id = $1 AND deleted_at IS NULL
`

func (q *Queries) CountLearningResourceCategoriesByUser(ctx context.Context, userID int64) (int64, error) {
	row := q.db.QueryRow(ctx, countLearningResourceCategoriesByUser, userID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countLearningResourcesByUser = `-- name: CountLearningResourcesByUser :one
SELECT count(*) FROM learning_resources
WHERE user_id = $1 AND deleted_at IS NULL
`

// learning_resources は GORM の論理削除（deleted_at）付きモデルのため、GORMの既定スコープに
// 合わせて deleted_at IS NULL を明示する（Unscoped() されていない全クエリと同じ挙動）。
func (q *Queries) CountLearningResourcesByUser(ctx context.Context, userID int64) (int64, error) {
	row := q.db.QueryRow(ctx, countLearningResourcesByUser, userID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const sumLearningResourceLikeCountByUser = `-- name: SumLearningResourceLikeCountByUser :one
SELECT COALESCE(SUM(like_count), 0)::bigint FROM learning_resources
WHERE user_id = $1 AND deleted_at IS NULL
`

func (q *Queries) SumLearningResourceLikeCountByUser(ctx context.Context, userID int64) (int64, error) {
	row := q.db.QueryRow(ctx, sumLearningResourceLikeCountByUser, userID)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const sumLearningResourceSaveCountByUser = `-- name: SumLearningResourceSaveCountByUser :one
SELECT COALESCE(SUM(save_count), 0)::bigint FROM learning_resources
WHERE user_id = $1 AND deleted_at IS NULL
`

func (q *Queries) SumLearningResourceSaveCountByUser(ctx context.Context, userID int64) (int64, error) {
	row := q.db.QueryRow(ctx, sumLearningResourceSaveCountByUser, userID)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}
