// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: learning_goal.sql

package sqlcgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countActiveLearningGoalsByUser = `-- name: CountActiveLearningGoalsByUser :one
SELECT COUNT(*) FROM learning_goals WHERE user_id = $1 AND status = 'active'
`

func (q *Queries) CountActiveLearningGoalsByUser(ctx context.Context, userID int64) (int64, error) {
	row := q.db.QueryRow(ctx, countActiveLearningGoalsByUser, userID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countLearningGoalsByUser = `-- name: CountLearningGoalsByUser :one
SELECT COUNT(*) FROM learning_goals WHERE user_id = $1
`

// 件数は GetByUserID の総数取得と CountByUserID(単体メソッド) の両方から利用する。
func (q *Queries) CountLearningGoalsByUser(ctx context.Context, userID int64) (int64, error) {
	row := q.db.QueryRow(ctx, countLearningGoalsByUser, userID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countPublicLearningGoals = `-- name: CountPublicLearningGoals :one
SELECT COUNT(*) FROM learning_goals WHERE is_public = true
`

func (q *Queries) CountPublicLearningGoals(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countPublicLearningGoals)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countPublicLearningGoalsByUser = `-- name: CountPublicLearningGoalsByUser :one
SELECT COUNT(*) FROM learning_goals WHERE user_id = $1 AND is_public = true
`

func (q *Queries) CountPublicLearningGoalsByUser(ctx context.Context, userID int64) (int64, error) {
	row := q.db.QueryRow(ctx, countPublicLearningGoalsByUser, userID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createLearningGoal = `-- name: CreateLearningGoal :one
INSERT INTO learning_goals (
    user_id, title, description, category, target_date, progress, target_hours, status, is_public,
    created_at, updated_at
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, now(), now()
) RETURNING id, user_id, title, description, category, target_date, progress, target_hours, status, is_public, created_at, updated_at, completed_at
`

type CreateLearningGoalParams struct {
	UserID      int64
	Title       string
	Description *string
	Category    *string
	TargetDate  pgtype.Timestamptz
	Progress    *int64
	TargetHours *int64
	Status      *string
	IsPublic    bool
}

func (q *Queries) CreateLearningGoal(ctx context.Context, arg CreateLearningGoalParams) (LearningGoal, error) {
	row := q.db.QueryRow(ctx, createLearningGoal,
		arg.UserID,
		arg.Title,
		arg.Description,
		arg.Category,
		arg.TargetDate,
		arg.Progress,
		arg.TargetHours,
		arg.Status,
		arg.IsPublic,
	)
	var i LearningGoal
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Title,
		&i.Description,
		&i.Category,
		&i.TargetDate,
		&i.Progress,
		&i.TargetHours,
		&i.Status,
		&i.IsPublic,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CompletedAt,
	)
	return i, err
}

const deleteLearningGoal = `-- name: DeleteLearningGoal :exec
DELETE FROM learning_goals WHERE id = $1
`

func (q *Queries) DeleteLearningGoal(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, deleteLearningGoal, id)
	return err
}

const getAverageActiveProgressByUser = `-- name: GetAverageActiveProgressByUser :one
SELECT COALESCE(AVG(progress), 0)::float8 FROM learning_goals
WHERE user_id = $1 AND status = 'active'
`

func (q *Queries) GetAverageActiveProgressByUser(ctx context.Context, userID int64) (float64, error) {
	row := q.db.QueryRow(ctx, getAverageActiveProgressByUser, userID)
	var column_1 float64
	err := row.Scan(&column_1)
	return column_1, err
}

const getLearningGoalByID = `-- name: GetLearningGoalByID :one
SELECT id, user_id, title, description, category, target_date, progress, target_hours, status, is_public, created_at, updated_at, completed_at FROM learning_goals WHERE id = $1
`

func (q *Queries) GetLearningGoalByID(ctx context.Context, id int64) (LearningGoal, error) {
	row := q.db.QueryRow(ctx, getLearningGoalByID, id)
	var i LearningGoal
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Title,
		&i.Description,
		&i.Category,
		&i.TargetDate,
		&i.Progress,
		&i.TargetHours,
		&i.Status,
		&i.IsPublic,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CompletedAt,
	)
	return i, err
}

const listActiveLearningGoalsByUser = `-- name: ListActiveLearningGoalsByUser :many
SELECT id, user_id, title, description, category, target_date, progress, target_hours, status, is_public, created_at, updated_at, completed_at FROM learning_goals
WHERE user_id = $1 AND status = 'active'
ORDER BY created_at DESC
`

func (q *Queries) ListActiveLearningGoalsByUser(ctx context.Context, userID int64) ([]LearningGoal, error) {
	rows, err := q.db.Query(ctx, listActiveLearningGoalsByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []LearningGoal
	for rows.Next() {
		var i LearningGoal
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Title,
			&i.Description,
			&i.Category,
			&i.TargetDate,
			&i.Progress,
			&i.TargetHours,
			&i.Status,
			&i.IsPublic,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.CompletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listLearningGoalsByCategory = `-- name: ListLearningGoalsByCategory :many
SELECT id, user_id, title, description, category, target_date, progress, target_hours, status, is_public, created_at, updated_at, completed_at FROM learning_goals
WHERE user_id = $1 AND category = $2
ORDER BY created_at DESC
`

type ListLearningGoalsByCategoryParams struct {
	UserID   int64
	Category *string
}

func (q *Queries) ListLearningGoalsByCategory(ctx context.Context, arg ListLearningGoalsByCategoryParams) ([]LearningGoal, error) {
	rows, err := q.db.Query(ctx, listLearningGoalsByCategory, arg.UserID, arg.Category)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []LearningGoal
	for rows.Next() {
		var i LearningGoal
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Title,
			&i.Description,
			&i.Category,
			&i.TargetDate,
			&i.Progress,
			&i.TargetHours,
			&i.Status,
			&i.IsPublic,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.CompletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listLearningGoalsByStatus = `-- name: ListLearningGoalsByStatus :many
SELECT id, user_id, title, description, category, target_date, progress, target_hours, status, is_public, created_at, updated_at, completed_at FROM learning_goals
WHERE user_id = $1 AND status = $2
ORDER BY created_at DESC
`

type ListLearningGoalsByStatusParams struct {
	UserID int64
	Status *string
}

func (q *Queries) ListLearningGoalsByStatus(ctx context.Context, arg ListLearningGoalsByStatusParams) ([]LearningGoal, error) {
	rows, err := q.db.Query(ctx, listLearningGoalsByStatus, arg.UserID, arg.Status)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []LearningGoal
	for rows.Next() {
		var i LearningGoal
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Title,
			&i.Description,
			&i.Category,
			&i.TargetDate,
			&i.Progress,
			&i.TargetHours,
			&i.Status,
			&i.IsPublic,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.CompletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listLearningGoalsByUser = `-- name: ListLearningGoalsByUser :many
SELECT id, user_id, title, description, category, target_date, progress, target_hours, status, is_public, created_at, updated_at, completed_at FROM learning_goals
WHERE user_id = $1
ORDER BY created_at DESC
LIMIT $2 OFFSET $3
`

type ListLearningGoalsByUserParams struct {
	UserID int64
	Limit  int32
	Offset int32
}

func (q *Queries) ListLearningGoalsByUser(ctx context.Context, arg ListLearningGoalsByUserParams) ([]LearningGoal, error) {
	rows, err := q.db.Query(ctx, listLearningGoalsByUser, arg.UserID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []LearningGoal
	for rows.Next() {
		var i LearningGoal
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Title,
			&i.Description,
			&i.Category,
			&i.TargetDate,
			&i.Progress,
			&i.TargetHours,
			&i.Status,
			&i.IsPublic,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.CompletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPublicLearningGoals = `-- name: ListPublicLearningGoals :many
SELECT id, user_id, title, description, category, target_date, progress, target_hours, status, is_public, created_at, updated_at, completed_at FROM learning_goals
WHERE is_public = true
ORDER BY created_at DESC
LIMIT $1 OFFSET $2
`

type ListPublicLearningGoalsParams struct {
	Limit  int32
	Offset int32
}

func (q *Queries) ListPublicLearningGoals(ctx context.Context, arg ListPublicLearningGoalsParams) ([]LearningGoal, error) {
	rows, err := q.db.Query(ctx, listPublicLearningGoals, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []LearningGoal
	for rows.Next() {
		var i LearningGoal
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Title,
			&i.Description,
			&i.Category,
			&i.TargetDate,
			&i.Progress,
			&i.TargetHours,
			&i.Status,
			&i.IsPublic,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.CompletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPublicLearningGoalsByUser = `-- name: ListPublicLearningGoalsByUser :many
SELECT id, user_id, title, description, category, target_date, progress, target_hours, status, is_public, created_at, updated_at, completed_at FROM learning_goals
WHERE user_id = $1 AND is_public = true
ORDER BY created_at DESC
LIMIT $2 OFFSET $3
`

type ListPublicLearningGoalsByUserParams struct {
	UserID int64
	Limit  int32
	Offset int32
}

func (q *Queries) ListPublicLearningGoalsByUser(ctx context.Context, arg ListPublicLearningGoalsByUserParams) ([]LearningGoal, error) {
	rows, err := q.db.Query(ctx, listPublicLearningGoalsByUser, arg.UserID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []LearningGoal
	for rows.Next() {
		var i LearningGoal
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Title,
			&i.Description,
			&i.Category,
			&i.TargetDate,
			&i.Progress,
			&i.TargetHours,
			&i.Status,
			&i.IsPublic,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.CompletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateLearningGoal = `-- name: UpdateLearningGoal :one
UPDATE learning_goals SET
    title = $2, description = $3, category = $4, target_date = $5, progress = $6,
    target_hours = $7, status = $8, is_public = $9, completed_at = $10, updated_at = now()
WHERE id = $1
RETURNING id, user_id, title, description, category, target_date, progress, target_hours, status, is_public, created_at, updated_at, completed_at
`

type UpdateLearningGoalParams struct {
	ID          int64
	Title       string
	Description *string
	Category    *string
	TargetDate  pgtype.Timestamptz
	Progress    *int64
	TargetHours *int64
	Status      *string
	IsPublic    bool
	CompletedAt pgtype.Timestamptz
}

// GORMのSave（全カラム上書き）に相当。
func (q *Queries) UpdateLearningGoal(ctx context.Context, arg UpdateLearningGoalParams) (LearningGoal, error) {
	row := q.db.QueryRow(ctx, updateLearningGoal,
		arg.ID,
		arg.Title,
		arg.Description,
		arg.Category,
		arg.TargetDate,
		arg.Progress,
		arg.TargetHours,
		arg.Status,
		arg.IsPublic,
		arg.CompletedAt,
	)
	var i LearningGoal
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Title,
		&i.Description,
		&i.Category,
		&i.TargetDate,
		&i.Progress,
		&i.TargetHours,
		&i.Status,
		&i.IsPublic,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CompletedAt,
	)
	return i, err
}
