// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: learning_log_template.sql

package sqlcgen

import (
	"context"
)

const clearOtherLearningLogTemplateDefaults = `-- name: ClearOtherLearningLogTemplateDefaults :exec
UPDATE learning_log_templates SET is_default = false, updated_at = now()
WHERE learning_log_templates.user_id = $1 AND learning_log_templates.is_default IS TRUE AND learning_log_templates.id != $2
`

type ClearOtherLearningLogTemplateDefaultsParams struct {
	UserID int64
	ID     int64
}

// 同一ユーザーの既存デフォルト（自分自身のid=$2は除く）を外す。Createからは
// 存在しないid（0）を渡すことで全件が対象になる。呼び出し元（repository）が
// 1つのトランザクション内でこのクエリの直後にCreate/Updateを実行することで、
// 「解除」と「新しいデフォルトの確定」を1つの原子的な単位にする。
// 【重要】1つのSQL文の中のCTEとしてUPDATE→INSERT/UPDATEを両方書く方式は使わない。
// PostgreSQLのデータ変更CTEは主文と同一スナップショットで動作し、UPDATEによる解除の
// 効果が同一文内の一意制約チェックに間に合わず、デフォルトが1件も無い状態からの
// 切り替えでも毎回一意制約違反になることを確認済み（2文に分けて初めて正しく動く）。
// uq_learning_log_templates_default（(user_id) WHERE is_default の部分UNIQUE索引）は
// 本当に並行する別トランザクション同士の衝突に対する最終防衛。
func (q *Queries) ClearOtherLearningLogTemplateDefaults(ctx context.Context, arg ClearOtherLearningLogTemplateDefaultsParams) error {
	_, err := q.db.Exec(ctx, clearOtherLearningLogTemplateDefaults, arg.UserID, arg.ID)
	return err
}

const countLearningLogTemplatesByUser = `-- name: CountLearningLogTemplatesByUser :one
SELECT COUNT(*) FROM learning_log_templates WHERE user_id = $1
`

func (q *Queries) CountLearningLogTemplatesByUser(ctx context.Context, userID int64) (int64, error) {
	row := q.db.QueryRow(ctx, countLearningLogTemplatesByUser, userID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createLearningLogTemplate = `-- name: CreateLearningLogTemplate :one
INSERT INTO learning_log_templates (user_id, name, default_title, default_content, default_category, default_duration, is_default, created_at, updated_at)
VALUES ($1, $2, $3, $4, $5, $6, $7, now(), now())
RETURNING id, user_id, name, default_title, default_content, default_category, default_duration, is_default, created_at, updated_at
`

type CreateLearningLogTemplateParams struct {
	UserID          int64
	Name            string
	DefaultTitle    *string
	DefaultContent  *string
	DefaultCategory *string
	DefaultDuration *int64
	IsDefault       *bool
}

func (q *Queries) CreateLearningLogTemplate(ctx context.Context, arg CreateLearningLogTemplateParams) (LearningLogTemplate, error) {
	row := q.db.QueryRow(ctx, createLearningLogTemplate,
		arg.UserID,
		arg.Name,
		arg.DefaultTitle,
		arg.DefaultContent,
		arg.DefaultCategory,
		arg.DefaultDuration,
		arg.IsDefault,
	)
	var i LearningLogTemplate
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.DefaultTitle,
		&i.DefaultContent,
		&i.DefaultCategory,
		&i.DefaultDuration,
		&i.IsDefault,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteLearningLogTemplate = `-- name: DeleteLearningLogTemplate :exec
DELETE FROM learning_log_templates WHERE id = $1
`

func (q *Queries) DeleteLearningLogTemplate(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, deleteLearningLogTemplate, id)
	return err
}

const getDefaultLearningLogTemplateByUser = `-- name: GetDefaultLearningLogTemplateByUser :one
SELECT id, user_id, name, default_title, default_content, default_category, default_duration, is_default, created_at, updated_at FROM learning_log_templates WHERE user_id = $1 AND is_default = true
`

func (q *Queries) GetDefaultLearningLogTemplateByUser(ctx context.Context, userID int64) (LearningLogTemplate, error) {
	row := q.db.QueryRow(ctx, getDefaultLearningLogTemplateByUser, userID)
	var i LearningLogTemplate
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.DefaultTitle,
		&i.DefaultContent,
		&i.DefaultCategory,
		&i.DefaultDuration,
		&i.IsDefault,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getLearningLogTemplateByID = `-- name: GetLearningLogTemplateByID :one
SELECT id, user_id, name, default_title, default_content, default_category, default_duration, is_default, created_at, updated_at FROM learning_log_templates WHERE id = $1
`

func (q *Queries) GetLearningLogTemplateByID(ctx context.Context, id int64) (LearningLogTemplate, error) {
	row := q.db.QueryRow(ctx, getLearningLogTemplateByID, id)
	var i LearningLogTemplate
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.DefaultTitle,
		&i.DefaultContent,
		&i.DefaultCategory,
		&i.DefaultDuration,
		&i.IsDefault,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listLearningLogTemplatesByUser = `-- name: ListLearningLogTemplatesByUser :many
SELECT id, user_id, name, default_title, default_content, default_category, default_duration, is_default, created_at, updated_at FROM learning_log_templates WHERE user_id = $1 ORDER BY created_at DESC
`

func (q *Queries) ListLearningLogTemplatesByUser(ctx context.Context, userID int64) ([]LearningLogTemplate, error) {
	rows, err := q.db.Query(ctx, listLearningLogTemplatesByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []LearningLogTemplate
	for rows.Next() {
		var i LearningLogTemplate
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Name,
			&i.DefaultTitle,
			&i.DefaultContent,
			&i.DefaultCategory,
			&i.DefaultDuration,
			&i.IsDefault,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateLearningLogTemplate = `-- name: UpdateLearningLogTemplate :one
UPDATE learning_log_templates SET
    name = $2,
    default_title = $3,
    default_content = $4,
    default_category = $5,
    default_duration = $6,
    is_default = $7,
    updated_at = now()
WHERE learning_log_templates.id = $1
RETURNING id, user_id, name, default_title, default_content, default_category, default_duration, is_default, created_at, updated_at
`

type UpdateLearningLogTemplateParams struct {
	ID              int64
	Name            string
	DefaultTitle    *string
	DefaultContent  *string
	DefaultCategory *string
	DefaultDuration *int64
	IsDefault       *bool
}

// GORMのSave（全カラム上書き）に相当。
func (q *Queries) UpdateLearningLogTemplate(ctx context.Context, arg UpdateLearningLogTemplateParams) (LearningLogTemplate, error) {
	row := q.db.QueryRow(ctx, updateLearningLogTemplate,
		arg.ID,
		arg.Name,
		arg.DefaultTitle,
		arg.DefaultContent,
		arg.DefaultCategory,
		arg.DefaultDuration,
		arg.IsDefault,
	)
	var i LearningLogTemplate
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.DefaultTitle,
		&i.DefaultContent,
		&i.DefaultCategory,
		&i.DefaultDuration,
		&i.IsDefault,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
