// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: learning_log_stats.sql

package sqlcgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countLearningLogCategoriesByUser = `-- name: CountLearningLogCategoriesByUser :one
SELECT count(DISTINCT category) FROM learning_logs
WHERE user_id = $1
`

func (q *Queries) CountLearningLogCategoriesByUser(ctx context.Context, userID int64) (int64, error) {
	row := q.db.QueryRow(ctx, countLearningLogCategoriesByUser, userID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countLearningLogsByUser = `-- name: CountLearningLogsByUser :one
SELECT count(*) FROM learning_logs
WHERE user_id = $1
`

func (q *Queries) CountLearningLogsByUser(ctx context.Context, userID int64) (int64, error) {
	row := q.db.QueryRow(ctx, countLearningLogsByUser, userID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countLearningLogsByUserSince = `-- name: CountLearningLogsByUserSince :one
SELECT count(*) FROM learning_logs
WHERE user_id = $1 AND created_at >= $2
`

type CountLearningLogsByUserSinceParams struct {
	UserID    int64
	CreatedAt pgtype.Timestamptz
}

func (q *Queries) CountLearningLogsByUserSince(ctx context.Context, arg CountLearningLogsByUserSinceParams) (int64, error) {
	row := q.db.QueryRow(ctx, countLearningLogsByUserSince, arg.UserID, arg.CreatedAt)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const sumLearningLogDurationByUser = `-- name: SumLearningLogDurationByUser :one
SELECT COALESCE(SUM(duration), 0)::bigint FROM learning_logs
WHERE user_id = $1
`

func (q *Queries) SumLearningLogDurationByUser(ctx context.Context, userID int64) (int64, error) {
	row := q.db.QueryRow(ctx, sumLearningLogDurationByUser, userID)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}
