// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: learning_log_template.sql

package sqlcgen

import (
	"context"
)

const countLearningLogTemplatesByUser = `-- name: CountLearningLogTemplatesByUser :one
SELECT COUNT(*) FROM learning_log_templates WHERE user_id = $1
`

func (q *Queries) CountLearningLogTemplatesByUser(ctx context.Context, userID int64) (int64, error) {
	row := q.db.QueryRow(ctx, countLearningLogTemplatesByUser, userID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createLearningLogTemplate = `-- name: CreateLearningLogTemplate :one
WITH cleared AS (
    UPDATE learning_log_templates SET is_default = false, updated_at = now()
    WHERE learning_log_templates.user_id = $1 AND learning_log_templates.is_default IS TRUE AND $7 = true
)
INSERT INTO learning_log_templates (user_id, name, default_title, default_content, default_category, default_duration, is_default, created_at, updated_at)
VALUES ($1, $2, $3, $4, $5, $6, $7, now(), now())
RETURNING id, user_id, name, default_title, default_content, default_category, default_duration, is_default, created_at, updated_at
`

type CreateLearningLogTemplateParams struct {
	UserID          int64
	Name            string
	DefaultTitle    *string
	DefaultContent  *string
	DefaultCategory *string
	DefaultDuration *int64
	IsDefault       *bool
}

// 新しい行がis_default=trueの場合のみ、同一ユーザーの既存デフォルトを同一文で外す
// （$7=trueでなければ WHERE が一致せずclearedは0行、is_default IS TRUEでNULLを安全に除外）。
// uq_learning_log_templates_default（(user_id) WHERE is_default の部分UNIQUE索引）が
// 最終的な「ユーザーごとデフォルトは高々1件」を保証する安全網になる。
func (q *Queries) CreateLearningLogTemplate(ctx context.Context, arg CreateLearningLogTemplateParams) (LearningLogTemplate, error) {
	row := q.db.QueryRow(ctx, createLearningLogTemplate,
		arg.UserID,
		arg.Name,
		arg.DefaultTitle,
		arg.DefaultContent,
		arg.DefaultCategory,
		arg.DefaultDuration,
		arg.IsDefault,
	)
	var i LearningLogTemplate
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.DefaultTitle,
		&i.DefaultContent,
		&i.DefaultCategory,
		&i.DefaultDuration,
		&i.IsDefault,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteLearningLogTemplate = `-- name: DeleteLearningLogTemplate :exec
DELETE FROM learning_log_templates WHERE id = $1
`

func (q *Queries) DeleteLearningLogTemplate(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, deleteLearningLogTemplate, id)
	return err
}

const getDefaultLearningLogTemplateByUser = `-- name: GetDefaultLearningLogTemplateByUser :one
SELECT id, user_id, name, default_title, default_content, default_category, default_duration, is_default, created_at, updated_at FROM learning_log_templates WHERE user_id = $1 AND is_default = true
`

func (q *Queries) GetDefaultLearningLogTemplateByUser(ctx context.Context, userID int64) (LearningLogTemplate, error) {
	row := q.db.QueryRow(ctx, getDefaultLearningLogTemplateByUser, userID)
	var i LearningLogTemplate
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.DefaultTitle,
		&i.DefaultContent,
		&i.DefaultCategory,
		&i.DefaultDuration,
		&i.IsDefault,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getLearningLogTemplateByID = `-- name: GetLearningLogTemplateByID :one
SELECT id, user_id, name, default_title, default_content, default_category, default_duration, is_default, created_at, updated_at FROM learning_log_templates WHERE id = $1
`

func (q *Queries) GetLearningLogTemplateByID(ctx context.Context, id int64) (LearningLogTemplate, error) {
	row := q.db.QueryRow(ctx, getLearningLogTemplateByID, id)
	var i LearningLogTemplate
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.DefaultTitle,
		&i.DefaultContent,
		&i.DefaultCategory,
		&i.DefaultDuration,
		&i.IsDefault,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listLearningLogTemplatesByUser = `-- name: ListLearningLogTemplatesByUser :many
SELECT id, user_id, name, default_title, default_content, default_category, default_duration, is_default, created_at, updated_at FROM learning_log_templates WHERE user_id = $1 ORDER BY created_at DESC
`

func (q *Queries) ListLearningLogTemplatesByUser(ctx context.Context, userID int64) ([]LearningLogTemplate, error) {
	rows, err := q.db.Query(ctx, listLearningLogTemplatesByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []LearningLogTemplate
	for rows.Next() {
		var i LearningLogTemplate
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Name,
			&i.DefaultTitle,
			&i.DefaultContent,
			&i.DefaultCategory,
			&i.DefaultDuration,
			&i.IsDefault,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateLearningLogTemplate = `-- name: UpdateLearningLogTemplate :one
WITH cleared AS (
    UPDATE learning_log_templates SET is_default = false, updated_at = now()
    WHERE learning_log_templates.user_id = $8 AND learning_log_templates.is_default IS TRUE AND learning_log_templates.id != $1 AND $7 = true
)
UPDATE learning_log_templates SET
    name = $2,
    default_title = $3,
    default_content = $4,
    default_category = $5,
    default_duration = $6,
    is_default = $7,
    updated_at = now()
WHERE learning_log_templates.id = $1
RETURNING id, user_id, name, default_title, default_content, default_category, default_duration, is_default, created_at, updated_at
`

type UpdateLearningLogTemplateParams struct {
	ID              int64
	Name            string
	DefaultTitle    *string
	DefaultContent  *string
	DefaultCategory *string
	DefaultDuration *int64
	IsDefault       *bool
	UserID          int64
}

// GORMのSave（全カラム上書き）に相当。
func (q *Queries) UpdateLearningLogTemplate(ctx context.Context, arg UpdateLearningLogTemplateParams) (LearningLogTemplate, error) {
	row := q.db.QueryRow(ctx, updateLearningLogTemplate,
		arg.ID,
		arg.Name,
		arg.DefaultTitle,
		arg.DefaultContent,
		arg.DefaultCategory,
		arg.DefaultDuration,
		arg.IsDefault,
		arg.UserID,
	)
	var i LearningLogTemplate
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.DefaultTitle,
		&i.DefaultContent,
		&i.DefaultCategory,
		&i.DefaultDuration,
		&i.IsDefault,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
