// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: learning_resource.sql

package sqlcgen

import (
	"context"
)

const countLearningResourcesByDifficulty = `-- name: CountLearningResourcesByDifficulty :one
SELECT COUNT(*) FROM learning_resources
WHERE learning_resources.is_public = true AND learning_resources.difficulty = $1
`

func (q *Queries) CountLearningResourcesByDifficulty(ctx context.Context, difficulty *string) (int64, error) {
	row := q.db.QueryRow(ctx, countLearningResourcesByDifficulty, difficulty)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countPublicLearningResources = `-- name: CountPublicLearningResources :one
SELECT COUNT(*) FROM learning_resources
WHERE learning_resources.is_public = true
    AND ($1::text IS NULL OR learning_resources.category = $1)
    AND ($2::text IS NULL OR learning_resources.difficulty = $2)
`

type CountPublicLearningResourcesParams struct {
	Category   *string
	Difficulty *string
}

func (q *Queries) CountPublicLearningResources(ctx context.Context, arg CountPublicLearningResourcesParams) (int64, error) {
	row := q.db.QueryRow(ctx, countPublicLearningResources, arg.Category, arg.Difficulty)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countResourceLike = `-- name: CountResourceLike :one
SELECT COUNT(*) FROM resource_likes
WHERE resource_likes.user_id = $1 AND resource_likes.resource_id = $2
`

type CountResourceLikeParams struct {
	UserID     int64
	ResourceID int64
}

func (q *Queries) CountResourceLike(ctx context.Context, arg CountResourceLikeParams) (int64, error) {
	row := q.db.QueryRow(ctx, countResourceLike, arg.UserID, arg.ResourceID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countResourceSave = `-- name: CountResourceSave :one
SELECT COUNT(*) FROM resource_saves
WHERE resource_saves.user_id = $1 AND resource_saves.resource_id = $2
`

type CountResourceSaveParams struct {
	UserID     int64
	ResourceID int64
}

func (q *Queries) CountResourceSave(ctx context.Context, arg CountResourceSaveParams) (int64, error) {
	row := q.db.QueryRow(ctx, countResourceSave, arg.UserID, arg.ResourceID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countSavedLearningResources = `-- name: CountSavedLearningResources :one
SELECT COUNT(*) FROM learning_resources
WHERE learning_resources.id IN (
    SELECT rs.resource_id FROM resource_saves rs WHERE rs.user_id = $1
)
`

func (q *Queries) CountSavedLearningResources(ctx context.Context, userID int64) (int64, error) {
	row := q.db.QueryRow(ctx, countSavedLearningResources, userID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countSearchLearningResources = `-- name: CountSearchLearningResources :one
SELECT COUNT(*) FROM learning_resources
WHERE learning_resources.is_public = true
    AND (learning_resources.title ILIKE $1 OR learning_resources.description ILIKE $1 OR learning_resources.tags ILIKE $1)
`

func (q *Queries) CountSearchLearningResources(ctx context.Context, title string) (int64, error) {
	row := q.db.QueryRow(ctx, countSearchLearningResources, title)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countUserVisibleLearningResources = `-- name: CountUserVisibleLearningResources :one
SELECT COUNT(*) FROM learning_resources
WHERE learning_resources.user_id = $1
    AND ($2::bool OR learning_resources.is_public = true)
`

type CountUserVisibleLearningResourcesParams struct {
	UserID         int64
	IncludePrivate bool
}

// FindByUserID の総数取得専用。include_private=falseなら公開分のみで数える
// （全件カウントはlearning_resource_stats.sqlの既存クエリCountLearningResourcesByUserを使う）。
func (q *Queries) CountUserVisibleLearningResources(ctx context.Context, arg CountUserVisibleLearningResourcesParams) (int64, error) {
	row := q.db.QueryRow(ctx, countUserVisibleLearningResources, arg.UserID, arg.IncludePrivate)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createLearningResource = `-- name: CreateLearningResource :one
INSERT INTO learning_resources (
    user_id, title, description, url, category, difficulty, tags, image_url, is_public,
    created_at, updated_at
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, now(), now()
) RETURNING id, user_id, title, description, url, category, difficulty, tags, image_url, is_public, created_at, updated_at
`

type CreateLearningResourceParams struct {
	UserID      int64
	Title       string
	Description *string
	Url         *string
	Category    string
	Difficulty  *string
	Tags        *string
	ImageUrl    *string
	IsPublic    bool
}

func (q *Queries) CreateLearningResource(ctx context.Context, arg CreateLearningResourceParams) (LearningResource, error) {
	row := q.db.QueryRow(ctx, createLearningResource,
		arg.UserID,
		arg.Title,
		arg.Description,
		arg.Url,
		arg.Category,
		arg.Difficulty,
		arg.Tags,
		arg.ImageUrl,
		arg.IsPublic,
	)
	var i LearningResource
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Title,
		&i.Description,
		&i.Url,
		&i.Category,
		&i.Difficulty,
		&i.Tags,
		&i.ImageUrl,
		&i.IsPublic,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createResourceLike = `-- name: CreateResourceLike :exec
WITH inserted AS (
    INSERT INTO resource_likes (user_id, resource_id, created_at) VALUES ($1, $2, now())
    RETURNING resource_likes.resource_id AS liked_resource_id
)
INSERT INTO learning_resource_metrics (resource_id, like_count)
SELECT liked_resource_id, 1 FROM inserted
ON CONFLICT (resource_id) DO UPDATE SET like_count = learning_resource_metrics.like_count + 1
`

type CreateResourceLikeParams struct {
	UserID     int64
	ResourceID int64
}

// resource_likesへのINSERTとlearning_resource_metrics.like_countの加算を
// 同一SQL文で行う（DEVSYNC-159）。CTEの出力列を別名にし、sqlcの列名衝突による
// 誤検出を避ける。
func (q *Queries) CreateResourceLike(ctx context.Context, arg CreateResourceLikeParams) error {
	_, err := q.db.Exec(ctx, createResourceLike, arg.UserID, arg.ResourceID)
	return err
}

const createResourceSave = `-- name: CreateResourceSave :exec
WITH inserted AS (
    INSERT INTO resource_saves (user_id, resource_id, created_at) VALUES ($1, $2, now())
    RETURNING resource_saves.resource_id AS saved_resource_id
)
INSERT INTO learning_resource_metrics (resource_id, save_count)
SELECT saved_resource_id, 1 FROM inserted
ON CONFLICT (resource_id) DO UPDATE SET save_count = learning_resource_metrics.save_count + 1
`

type CreateResourceSaveParams struct {
	UserID     int64
	ResourceID int64
}

// resource_savesへのINSERTとlearning_resource_metrics.save_countの加算を同一SQL文で行う。
func (q *Queries) CreateResourceSave(ctx context.Context, arg CreateResourceSaveParams) error {
	_, err := q.db.Exec(ctx, createResourceSave, arg.UserID, arg.ResourceID)
	return err
}

const deleteLearningResource = `-- name: DeleteLearningResource :exec
DELETE FROM learning_resources WHERE learning_resources.id = $1
`

// 依存するいいね・保存等はFKのON DELETE CASCADEでDBが自動的に削除する。
func (q *Queries) DeleteLearningResource(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, deleteLearningResource, id)
	return err
}

const deleteResourceLike = `-- name: DeleteResourceLike :execrows
WITH deleted AS (
    DELETE FROM resource_likes WHERE resource_likes.user_id = $1 AND resource_likes.resource_id = $2
    RETURNING resource_likes.resource_id AS liked_resource_id
)
INSERT INTO learning_resource_metrics (resource_id, like_count)
SELECT liked_resource_id, 0 FROM deleted
ON CONFLICT (resource_id) DO UPDATE SET like_count = GREATEST(learning_resource_metrics.like_count - 1, 0)
`

type DeleteResourceLikeParams struct {
	UserID     int64
	ResourceID int64
}

// resource_likesの削除とlearning_resource_metrics.like_countの減算を同一SQL文で行う。
// 実際に削除できた（＝deletedに1行ある）ときだけmetricsを更新するため、
// rowsAffectedは従来どおり「実際にいいねを取り消せたか」を表す。
func (q *Queries) DeleteResourceLike(ctx context.Context, arg DeleteResourceLikeParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteResourceLike, arg.UserID, arg.ResourceID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteResourceSave = `-- name: DeleteResourceSave :execrows
WITH deleted AS (
    DELETE FROM resource_saves WHERE resource_saves.user_id = $1 AND resource_saves.resource_id = $2
    RETURNING resource_saves.resource_id AS saved_resource_id
)
INSERT INTO learning_resource_metrics (resource_id, save_count)
SELECT saved_resource_id, 0 FROM deleted
ON CONFLICT (resource_id) DO UPDATE SET save_count = GREATEST(learning_resource_metrics.save_count - 1, 0)
`

type DeleteResourceSaveParams struct {
	UserID     int64
	ResourceID int64
}

// resource_savesの削除とlearning_resource_metrics.save_countの減算を同一SQL文で行う。
func (q *Queries) DeleteResourceSave(ctx context.Context, arg DeleteResourceSaveParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteResourceSave, arg.UserID, arg.ResourceID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getLearningResourceWithUserByID = `-- name: GetLearningResourceWithUserByID :one
SELECT learning_resources.id, learning_resources.user_id, learning_resources.title, learning_resources.description, learning_resources.url, learning_resources.category, learning_resources.difficulty, learning_resources.tags, learning_resources.image_url, learning_resources.is_public, learning_resources.created_at, learning_resources.updated_at, users.id, users.username, users.name, users.email, users.avatar_url, users.bio, users.git_hub_id, users.git_hub_username, users.git_hub_token, users.git_hub_connected, users.spotify_connected, users.spotify_token, users.spotify_refresh_token, users.spotify_token_expiry, users.zenn_username, users.qiita_username, users.at_coder_username, users.paiza_rank, users.skills_languages, users.skills_frameworks, users.onboarding_completed, users.email_weekly_report, users.email_language, users.created_at, users.updated_at
FROM learning_resources
JOIN users ON users.id = learning_resources.user_id
WHERE learning_resources.id = $1
`

type GetLearningResourceWithUserByIDRow struct {
	LearningResource LearningResource
	User             User
}

// GORMのPreload("User")に相当。user_idはNOT NULLのためINNER JOINでよい。
func (q *Queries) GetLearningResourceWithUserByID(ctx context.Context, id int64) (GetLearningResourceWithUserByIDRow, error) {
	row := q.db.QueryRow(ctx, getLearningResourceWithUserByID, id)
	var i GetLearningResourceWithUserByIDRow
	err := row.Scan(
		&i.LearningResource.ID,
		&i.LearningResource.UserID,
		&i.LearningResource.Title,
		&i.LearningResource.Description,
		&i.LearningResource.Url,
		&i.LearningResource.Category,
		&i.LearningResource.Difficulty,
		&i.LearningResource.Tags,
		&i.LearningResource.ImageUrl,
		&i.LearningResource.IsPublic,
		&i.LearningResource.CreatedAt,
		&i.LearningResource.UpdatedAt,
		&i.User.ID,
		&i.User.Username,
		&i.User.Name,
		&i.User.Email,
		&i.User.AvatarUrl,
		&i.User.Bio,
		&i.User.GitHubID,
		&i.User.GitHubUsername,
		&i.User.GitHubToken,
		&i.User.GitHubConnected,
		&i.User.SpotifyConnected,
		&i.User.SpotifyToken,
		&i.User.SpotifyRefreshToken,
		&i.User.SpotifyTokenExpiry,
		&i.User.ZennUsername,
		&i.User.QiitaUsername,
		&i.User.AtCoderUsername,
		&i.User.PaizaRank,
		&i.User.SkillsLanguages,
		&i.User.SkillsFrameworks,
		&i.User.OnboardingCompleted,
		&i.User.EmailWeeklyReport,
		&i.User.EmailLanguage,
		&i.User.CreatedAt,
		&i.User.UpdatedAt,
	)
	return i, err
}

const listLearningResourcesByDifficultyWithUser = `-- name: ListLearningResourcesByDifficultyWithUser :many
SELECT learning_resources.id, learning_resources.user_id, learning_resources.title, learning_resources.description, learning_resources.url, learning_resources.category, learning_resources.difficulty, learning_resources.tags, learning_resources.image_url, learning_resources.is_public, learning_resources.created_at, learning_resources.updated_at, users.id, users.username, users.name, users.email, users.avatar_url, users.bio, users.git_hub_id, users.git_hub_username, users.git_hub_token, users.git_hub_connected, users.spotify_connected, users.spotify_token, users.spotify_refresh_token, users.spotify_token_expiry, users.zenn_username, users.qiita_username, users.at_coder_username, users.paiza_rank, users.skills_languages, users.skills_frameworks, users.onboarding_completed, users.email_weekly_report, users.email_language, users.created_at, users.updated_at
FROM learning_resources
JOIN users ON users.id = learning_resources.user_id
WHERE learning_resources.is_public = true AND learning_resources.difficulty = $1
ORDER BY learning_resources.created_at DESC
LIMIT $2 OFFSET $3
`

type ListLearningResourcesByDifficultyWithUserParams struct {
	Difficulty *string
	Limit      int32
	Offset     int32
}

type ListLearningResourcesByDifficultyWithUserRow struct {
	LearningResource LearningResource
	User             User
}

func (q *Queries) ListLearningResourcesByDifficultyWithUser(ctx context.Context, arg ListLearningResourcesByDifficultyWithUserParams) ([]ListLearningResourcesByDifficultyWithUserRow, error) {
	rows, err := q.db.Query(ctx, listLearningResourcesByDifficultyWithUser, arg.Difficulty, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListLearningResourcesByDifficultyWithUserRow
	for rows.Next() {
		var i ListLearningResourcesByDifficultyWithUserRow
		if err := rows.Scan(
			&i.LearningResource.ID,
			&i.LearningResource.UserID,
			&i.LearningResource.Title,
			&i.LearningResource.Description,
			&i.LearningResource.Url,
			&i.LearningResource.Category,
			&i.LearningResource.Difficulty,
			&i.LearningResource.Tags,
			&i.LearningResource.ImageUrl,
			&i.LearningResource.IsPublic,
			&i.LearningResource.CreatedAt,
			&i.LearningResource.UpdatedAt,
			&i.User.ID,
			&i.User.Username,
			&i.User.Name,
			&i.User.Email,
			&i.User.AvatarUrl,
			&i.User.Bio,
			&i.User.GitHubID,
			&i.User.GitHubUsername,
			&i.User.GitHubToken,
			&i.User.GitHubConnected,
			&i.User.SpotifyConnected,
			&i.User.SpotifyToken,
			&i.User.SpotifyRefreshToken,
			&i.User.SpotifyTokenExpiry,
			&i.User.ZennUsername,
			&i.User.QiitaUsername,
			&i.User.AtCoderUsername,
			&i.User.PaizaRank,
			&i.User.SkillsLanguages,
			&i.User.SkillsFrameworks,
			&i.User.OnboardingCompleted,
			&i.User.EmailWeeklyReport,
			&i.User.EmailLanguage,
			&i.User.CreatedAt,
			&i.User.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listLearningResourcesByUser = `-- name: ListLearningResourcesByUser :many
SELECT id, user_id, title, description, url, category, difficulty, tags, image_url, is_public, created_at, updated_at FROM learning_resources
WHERE learning_resources.user_id = $1
    AND ($4::bool OR learning_resources.is_public = true)
ORDER BY learning_resources.created_at DESC
LIMIT $2 OFFSET $3
`

type ListLearningResourcesByUserParams struct {
	UserID         int64
	Limit          int32
	Offset         int32
	IncludePrivate bool
}

// Userは含めない（移行前からの挙動。一覧系の中でこれだけPreloadしない）。
// include_privateがfalseのときだけis_public=trueで絞り込む。
func (q *Queries) ListLearningResourcesByUser(ctx context.Context, arg ListLearningResourcesByUserParams) ([]LearningResource, error) {
	rows, err := q.db.Query(ctx, listLearningResourcesByUser,
		arg.UserID,
		arg.Limit,
		arg.Offset,
		arg.IncludePrivate,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []LearningResource
	for rows.Next() {
		var i LearningResource
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Title,
			&i.Description,
			&i.Url,
			&i.Category,
			&i.Difficulty,
			&i.Tags,
			&i.ImageUrl,
			&i.IsPublic,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPublicLearningResourcesWithUser = `-- name: ListPublicLearningResourcesWithUser :many
SELECT learning_resources.id, learning_resources.user_id, learning_resources.title, learning_resources.description, learning_resources.url, learning_resources.category, learning_resources.difficulty, learning_resources.tags, learning_resources.image_url, learning_resources.is_public, learning_resources.created_at, learning_resources.updated_at, users.id, users.username, users.name, users.email, users.avatar_url, users.bio, users.git_hub_id, users.git_hub_username, users.git_hub_token, users.git_hub_connected, users.spotify_connected, users.spotify_token, users.spotify_refresh_token, users.spotify_token_expiry, users.zenn_username, users.qiita_username, users.at_coder_username, users.paiza_rank, users.skills_languages, users.skills_frameworks, users.onboarding_completed, users.email_weekly_report, users.email_language, users.created_at, users.updated_at
FROM learning_resources
JOIN users ON users.id = learning_resources.user_id
LEFT JOIN learning_resource_metrics lrm ON lrm.resource_id = learning_resources.id
WHERE learning_resources.is_public = true
    AND ($3::text IS NULL OR learning_resources.category = $3)
    AND ($4::text IS NULL OR learning_resources.difficulty = $4)
ORDER BY COALESCE(lrm.like_count, 0) DESC, learning_resources.created_at DESC
LIMIT $1 OFFSET $2
`

type ListPublicLearningResourcesWithUserParams struct {
	Limit      int32
	Offset     int32
	Category   *string
	Difficulty *string
}

type ListPublicLearningResourcesWithUserRow struct {
	LearningResource LearningResource
	User             User
}

// GORMのPreload("User")に相当。categoryとdifficultyは空文字なら絞り込まない。
// like_countはlearning_resource_metrics側（DEVSYNC-159）。LEFT JOIN + COALESCEで0扱いにする。
func (q *Queries) ListPublicLearningResourcesWithUser(ctx context.Context, arg ListPublicLearningResourcesWithUserParams) ([]ListPublicLearningResourcesWithUserRow, error) {
	rows, err := q.db.Query(ctx, listPublicLearningResourcesWithUser,
		arg.Limit,
		arg.Offset,
		arg.Category,
		arg.Difficulty,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListPublicLearningResourcesWithUserRow
	for rows.Next() {
		var i ListPublicLearningResourcesWithUserRow
		if err := rows.Scan(
			&i.LearningResource.ID,
			&i.LearningResource.UserID,
			&i.LearningResource.Title,
			&i.LearningResource.Description,
			&i.LearningResource.Url,
			&i.LearningResource.Category,
			&i.LearningResource.Difficulty,
			&i.LearningResource.Tags,
			&i.LearningResource.ImageUrl,
			&i.LearningResource.IsPublic,
			&i.LearningResource.CreatedAt,
			&i.LearningResource.UpdatedAt,
			&i.User.ID,
			&i.User.Username,
			&i.User.Name,
			&i.User.Email,
			&i.User.AvatarUrl,
			&i.User.Bio,
			&i.User.GitHubID,
			&i.User.GitHubUsername,
			&i.User.GitHubToken,
			&i.User.GitHubConnected,
			&i.User.SpotifyConnected,
			&i.User.SpotifyToken,
			&i.User.SpotifyRefreshToken,
			&i.User.SpotifyTokenExpiry,
			&i.User.ZennUsername,
			&i.User.QiitaUsername,
			&i.User.AtCoderUsername,
			&i.User.PaizaRank,
			&i.User.SkillsLanguages,
			&i.User.SkillsFrameworks,
			&i.User.OnboardingCompleted,
			&i.User.EmailWeeklyReport,
			&i.User.EmailLanguage,
			&i.User.CreatedAt,
			&i.User.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSavedLearningResourcesWithUser = `-- name: ListSavedLearningResourcesWithUser :many
SELECT learning_resources.id, learning_resources.user_id, learning_resources.title, learning_resources.description, learning_resources.url, learning_resources.category, learning_resources.difficulty, learning_resources.tags, learning_resources.image_url, learning_resources.is_public, learning_resources.created_at, learning_resources.updated_at, users.id, users.username, users.name, users.email, users.avatar_url, users.bio, users.git_hub_id, users.git_hub_username, users.git_hub_token, users.git_hub_connected, users.spotify_connected, users.spotify_token, users.spotify_refresh_token, users.spotify_token_expiry, users.zenn_username, users.qiita_username, users.at_coder_username, users.paiza_rank, users.skills_languages, users.skills_frameworks, users.onboarding_completed, users.email_weekly_report, users.email_language, users.created_at, users.updated_at
FROM learning_resources
JOIN users ON users.id = learning_resources.user_id
WHERE learning_resources.id IN (
    SELECT rs.resource_id FROM resource_saves rs WHERE rs.user_id = $1
)
ORDER BY learning_resources.created_at DESC
LIMIT $2 OFFSET $3
`

type ListSavedLearningResourcesWithUserParams struct {
	UserID int64
	Limit  int32
	Offset int32
}

type ListSavedLearningResourcesWithUserRow struct {
	LearningResource LearningResource
	User             User
}

func (q *Queries) ListSavedLearningResourcesWithUser(ctx context.Context, arg ListSavedLearningResourcesWithUserParams) ([]ListSavedLearningResourcesWithUserRow, error) {
	rows, err := q.db.Query(ctx, listSavedLearningResourcesWithUser, arg.UserID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListSavedLearningResourcesWithUserRow
	for rows.Next() {
		var i ListSavedLearningResourcesWithUserRow
		if err := rows.Scan(
			&i.LearningResource.ID,
			&i.LearningResource.UserID,
			&i.LearningResource.Title,
			&i.LearningResource.Description,
			&i.LearningResource.Url,
			&i.LearningResource.Category,
			&i.LearningResource.Difficulty,
			&i.LearningResource.Tags,
			&i.LearningResource.ImageUrl,
			&i.LearningResource.IsPublic,
			&i.LearningResource.CreatedAt,
			&i.LearningResource.UpdatedAt,
			&i.User.ID,
			&i.User.Username,
			&i.User.Name,
			&i.User.Email,
			&i.User.AvatarUrl,
			&i.User.Bio,
			&i.User.GitHubID,
			&i.User.GitHubUsername,
			&i.User.GitHubToken,
			&i.User.GitHubConnected,
			&i.User.SpotifyConnected,
			&i.User.SpotifyToken,
			&i.User.SpotifyRefreshToken,
			&i.User.SpotifyTokenExpiry,
			&i.User.ZennUsername,
			&i.User.QiitaUsername,
			&i.User.AtCoderUsername,
			&i.User.PaizaRank,
			&i.User.SkillsLanguages,
			&i.User.SkillsFrameworks,
			&i.User.OnboardingCompleted,
			&i.User.EmailWeeklyReport,
			&i.User.EmailLanguage,
			&i.User.CreatedAt,
			&i.User.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchLearningResourcesWithUser = `-- name: SearchLearningResourcesWithUser :many
SELECT learning_resources.id, learning_resources.user_id, learning_resources.title, learning_resources.description, learning_resources.url, learning_resources.category, learning_resources.difficulty, learning_resources.tags, learning_resources.image_url, learning_resources.is_public, learning_resources.created_at, learning_resources.updated_at, users.id, users.username, users.name, users.email, users.avatar_url, users.bio, users.git_hub_id, users.git_hub_username, users.git_hub_token, users.git_hub_connected, users.spotify_connected, users.spotify_token, users.spotify_refresh_token, users.spotify_token_expiry, users.zenn_username, users.qiita_username, users.at_coder_username, users.paiza_rank, users.skills_languages, users.skills_frameworks, users.onboarding_completed, users.email_weekly_report, users.email_language, users.created_at, users.updated_at
FROM learning_resources
JOIN users ON users.id = learning_resources.user_id
LEFT JOIN learning_resource_metrics lrm ON lrm.resource_id = learning_resources.id
WHERE learning_resources.is_public = true
    AND (learning_resources.title ILIKE $1 OR learning_resources.description ILIKE $1 OR learning_resources.tags ILIKE $1)
ORDER BY COALESCE(lrm.like_count, 0) DESC, learning_resources.created_at DESC
LIMIT $2 OFFSET $3
`

type SearchLearningResourcesWithUserParams struct {
	Title  string
	Limit  int32
	Offset int32
}

type SearchLearningResourcesWithUserRow struct {
	LearningResource LearningResource
	User             User
}

// like_countはlearning_resource_metrics側（DEVSYNC-159）。LEFT JOIN + COALESCEで0扱いにする。
func (q *Queries) SearchLearningResourcesWithUser(ctx context.Context, arg SearchLearningResourcesWithUserParams) ([]SearchLearningResourcesWithUserRow, error) {
	rows, err := q.db.Query(ctx, searchLearningResourcesWithUser, arg.Title, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SearchLearningResourcesWithUserRow
	for rows.Next() {
		var i SearchLearningResourcesWithUserRow
		if err := rows.Scan(
			&i.LearningResource.ID,
			&i.LearningResource.UserID,
			&i.LearningResource.Title,
			&i.LearningResource.Description,
			&i.LearningResource.Url,
			&i.LearningResource.Category,
			&i.LearningResource.Difficulty,
			&i.LearningResource.Tags,
			&i.LearningResource.ImageUrl,
			&i.LearningResource.IsPublic,
			&i.LearningResource.CreatedAt,
			&i.LearningResource.UpdatedAt,
			&i.User.ID,
			&i.User.Username,
			&i.User.Name,
			&i.User.Email,
			&i.User.AvatarUrl,
			&i.User.Bio,
			&i.User.GitHubID,
			&i.User.GitHubUsername,
			&i.User.GitHubToken,
			&i.User.GitHubConnected,
			&i.User.SpotifyConnected,
			&i.User.SpotifyToken,
			&i.User.SpotifyRefreshToken,
			&i.User.SpotifyTokenExpiry,
			&i.User.ZennUsername,
			&i.User.QiitaUsername,
			&i.User.AtCoderUsername,
			&i.User.PaizaRank,
			&i.User.SkillsLanguages,
			&i.User.SkillsFrameworks,
			&i.User.OnboardingCompleted,
			&i.User.EmailWeeklyReport,
			&i.User.EmailLanguage,
			&i.User.CreatedAt,
			&i.User.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateLearningResource = `-- name: UpdateLearningResource :one
UPDATE learning_resources SET
    title = $2, description = $3, url = $4, category = $5, difficulty = $6, tags = $7,
    image_url = $8, is_public = $9, updated_at = now()
WHERE learning_resources.id = $1
RETURNING id, user_id, title, description, url, category, difficulty, tags, image_url, is_public, created_at, updated_at
`

type UpdateLearningResourceParams struct {
	ID          int64
	Title       string
	Description *string
	Url         *string
	Category    string
	Difficulty  *string
	Tags        *string
	ImageUrl    *string
	IsPublic    bool
}

// GORMのSave（全カラム上書き）に相当。like_count/save_countはlearning_resources自体の
// 列ではなくlearning_resource_metrics側（DEVSYNC-159）にあるため、ここには含まれない。
func (q *Queries) UpdateLearningResource(ctx context.Context, arg UpdateLearningResourceParams) (LearningResource, error) {
	row := q.db.QueryRow(ctx, updateLearningResource,
		arg.ID,
		arg.Title,
		arg.Description,
		arg.Url,
		arg.Category,
		arg.Difficulty,
		arg.Tags,
		arg.ImageUrl,
		arg.IsPublic,
	)
	var i LearningResource
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Title,
		&i.Description,
		&i.Url,
		&i.Category,
		&i.Difficulty,
		&i.Tags,
		&i.ImageUrl,
		&i.IsPublic,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
