// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: learning_log.sql

package sqlcgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countFavoriteLearningLogs = `-- name: CountFavoriteLearningLogs :one
SELECT COUNT(*) FROM learning_logs WHERE user_id = $1 AND is_favorite = true
`

func (q *Queries) CountFavoriteLearningLogs(ctx context.Context, userID int64) (int64, error) {
	row := q.db.QueryRow(ctx, countFavoriteLearningLogs, userID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countLearningLogsByGoal = `-- name: CountLearningLogsByGoal :one
SELECT COUNT(*) FROM learning_logs WHERE goal_id = $1
`

func (q *Queries) CountLearningLogsByGoal(ctx context.Context, goalID *int64) (int64, error) {
	row := q.db.QueryRow(ctx, countLearningLogsByGoal, goalID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createLearningLog = `-- name: CreateLearningLog :one
INSERT INTO learning_logs (
    user_id, title, content, category, duration, goal_id, source, is_favorite,
    created_at, updated_at
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, now(), now()
) RETURNING id, user_id, title, content, category, duration, goal_id, source, is_favorite, created_at, updated_at
`

type CreateLearningLogParams struct {
	UserID     int64
	Title      string
	Content    string
	Category   *string
	Duration   *int64
	GoalID     *int64
	Source     *string
	IsFavorite *bool
}

func (q *Queries) CreateLearningLog(ctx context.Context, arg CreateLearningLogParams) (LearningLog, error) {
	row := q.db.QueryRow(ctx, createLearningLog,
		arg.UserID,
		arg.Title,
		arg.Content,
		arg.Category,
		arg.Duration,
		arg.GoalID,
		arg.Source,
		arg.IsFavorite,
	)
	var i LearningLog
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Title,
		&i.Content,
		&i.Category,
		&i.Duration,
		&i.GoalID,
		&i.Source,
		&i.IsFavorite,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteLearningLog = `-- name: DeleteLearningLog :exec
DELETE FROM learning_logs WHERE id = $1 AND user_id = $2
`

type DeleteLearningLogParams struct {
	ID     int64
	UserID int64
}

// 所有者本人のログだけを削除する。
func (q *Queries) DeleteLearningLog(ctx context.Context, arg DeleteLearningLogParams) error {
	_, err := q.db.Exec(ctx, deleteLearningLog, arg.ID, arg.UserID)
	return err
}

const getLearningLogByID = `-- name: GetLearningLogByID :one
SELECT id, user_id, title, content, category, duration, goal_id, source, is_favorite, created_at, updated_at FROM learning_logs WHERE id = $1
`

func (q *Queries) GetLearningLogByID(ctx context.Context, id int64) (LearningLog, error) {
	row := q.db.QueryRow(ctx, getLearningLogByID, id)
	var i LearningLog
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Title,
		&i.Content,
		&i.Category,
		&i.Duration,
		&i.GoalID,
		&i.Source,
		&i.IsFavorite,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listFavoriteLearningLogs = `-- name: ListFavoriteLearningLogs :many
SELECT id, user_id, title, content, category, duration, goal_id, source, is_favorite, created_at, updated_at FROM learning_logs
WHERE user_id = $1 AND is_favorite = true
ORDER BY created_at DESC
LIMIT $2 OFFSET $3
`

type ListFavoriteLearningLogsParams struct {
	UserID int64
	Limit  int32
	Offset int32
}

func (q *Queries) ListFavoriteLearningLogs(ctx context.Context, arg ListFavoriteLearningLogsParams) ([]LearningLog, error) {
	rows, err := q.db.Query(ctx, listFavoriteLearningLogs, arg.UserID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []LearningLog
	for rows.Next() {
		var i LearningLog
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Title,
			&i.Content,
			&i.Category,
			&i.Duration,
			&i.GoalID,
			&i.Source,
			&i.IsFavorite,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listLearningLogCalendarData = `-- name: ListLearningLogCalendarData :many
SELECT DATE(created_at) AS date, COUNT(*) AS count
FROM learning_logs
WHERE user_id = $1
GROUP BY DATE(created_at)
ORDER BY date ASC
`

type ListLearningLogCalendarDataRow struct {
	Date  pgtype.Date
	Count int64
}

func (q *Queries) ListLearningLogCalendarData(ctx context.Context, userID int64) ([]ListLearningLogCalendarDataRow, error) {
	rows, err := q.db.Query(ctx, listLearningLogCalendarData, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListLearningLogCalendarDataRow
	for rows.Next() {
		var i ListLearningLogCalendarDataRow
		if err := rows.Scan(&i.Date, &i.Count); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listLearningLogMonthlySummary = `-- name: ListLearningLogMonthlySummary :many
SELECT
    TO_CHAR(DATE_TRUNC('month', created_at), 'YYYY-MM-DD') AS month,
    COALESCE(SUM(duration), 0)::bigint AS total_minutes,
    COUNT(*) AS log_count
FROM learning_logs
WHERE user_id = $1 AND created_at >= $2
GROUP BY month
ORDER BY month
`

type ListLearningLogMonthlySummaryParams struct {
	UserID    int64
	CreatedAt pgtype.Timestamptz
}

type ListLearningLogMonthlySummaryRow struct {
	Month        string
	TotalMinutes int64
	LogCount     int64
}

func (q *Queries) ListLearningLogMonthlySummary(ctx context.Context, arg ListLearningLogMonthlySummaryParams) ([]ListLearningLogMonthlySummaryRow, error) {
	rows, err := q.db.Query(ctx, listLearningLogMonthlySummary, arg.UserID, arg.CreatedAt)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListLearningLogMonthlySummaryRow
	for rows.Next() {
		var i ListLearningLogMonthlySummaryRow
		if err := rows.Scan(&i.Month, &i.TotalMinutes, &i.LogCount); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listLearningLogsByCategory = `-- name: ListLearningLogsByCategory :many
SELECT id, user_id, title, content, category, duration, goal_id, source, is_favorite, created_at, updated_at FROM learning_logs
WHERE user_id = $1 AND category = $2
ORDER BY created_at DESC
`

type ListLearningLogsByCategoryParams struct {
	UserID   int64
	Category *string
}

func (q *Queries) ListLearningLogsByCategory(ctx context.Context, arg ListLearningLogsByCategoryParams) ([]LearningLog, error) {
	rows, err := q.db.Query(ctx, listLearningLogsByCategory, arg.UserID, arg.Category)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []LearningLog
	for rows.Next() {
		var i LearningLog
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Title,
			&i.Content,
			&i.Category,
			&i.Duration,
			&i.GoalID,
			&i.Source,
			&i.IsFavorite,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listLearningLogsByGoal = `-- name: ListLearningLogsByGoal :many
SELECT id, user_id, title, content, category, duration, goal_id, source, is_favorite, created_at, updated_at FROM learning_logs
WHERE goal_id = $1
ORDER BY created_at DESC
LIMIT $2 OFFSET $3
`

type ListLearningLogsByGoalParams struct {
	GoalID *int64
	Limit  int32
	Offset int32
}

func (q *Queries) ListLearningLogsByGoal(ctx context.Context, arg ListLearningLogsByGoalParams) ([]LearningLog, error) {
	rows, err := q.db.Query(ctx, listLearningLogsByGoal, arg.GoalID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []LearningLog
	for rows.Next() {
		var i LearningLog
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Title,
			&i.Content,
			&i.Category,
			&i.Duration,
			&i.GoalID,
			&i.Source,
			&i.IsFavorite,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listLearningLogsByPeriod = `-- name: ListLearningLogsByPeriod :many
SELECT id, user_id, title, content, category, duration, goal_id, source, is_favorite, created_at, updated_at FROM learning_logs
WHERE user_id = $1 AND ($2::timestamptz IS NULL OR created_at >= $2)
ORDER BY created_at DESC
`

type ListLearningLogsByPeriodParams struct {
	UserID int64
	Since  pgtype.Timestamptz
}

// daysが0以下のときは呼び出し側がsinceにnilを渡し、全期間を対象にする。
func (q *Queries) ListLearningLogsByPeriod(ctx context.Context, arg ListLearningLogsByPeriodParams) ([]LearningLog, error) {
	rows, err := q.db.Query(ctx, listLearningLogsByPeriod, arg.UserID, arg.Since)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []LearningLog
	for rows.Next() {
		var i LearningLog
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Title,
			&i.Content,
			&i.Category,
			&i.Duration,
			&i.GoalID,
			&i.Source,
			&i.IsFavorite,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listLearningLogsBySource = `-- name: ListLearningLogsBySource :many
SELECT id, user_id, title, content, category, duration, goal_id, source, is_favorite, created_at, updated_at FROM learning_logs
WHERE user_id = $1 AND source = $2
ORDER BY created_at DESC
`

type ListLearningLogsBySourceParams struct {
	UserID int64
	Source *string
}

func (q *Queries) ListLearningLogsBySource(ctx context.Context, arg ListLearningLogsBySourceParams) ([]LearningLog, error) {
	rows, err := q.db.Query(ctx, listLearningLogsBySource, arg.UserID, arg.Source)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []LearningLog
	for rows.Next() {
		var i LearningLog
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Title,
			&i.Content,
			&i.Category,
			&i.Duration,
			&i.GoalID,
			&i.Source,
			&i.IsFavorite,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listLearningLogsByUser = `-- name: ListLearningLogsByUser :many
SELECT id, user_id, title, content, category, duration, goal_id, source, is_favorite, created_at, updated_at FROM learning_logs
WHERE user_id = $1
ORDER BY created_at DESC
LIMIT $2 OFFSET $3
`

type ListLearningLogsByUserParams struct {
	UserID int64
	Limit  int32
	Offset int32
}

func (q *Queries) ListLearningLogsByUser(ctx context.Context, arg ListLearningLogsByUserParams) ([]LearningLog, error) {
	rows, err := q.db.Query(ctx, listLearningLogsByUser, arg.UserID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []LearningLog
	for rows.Next() {
		var i LearningLog
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Title,
			&i.Content,
			&i.Category,
			&i.Duration,
			&i.GoalID,
			&i.Source,
			&i.IsFavorite,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRecentLearningLogCategories = `-- name: ListRecentLearningLogCategories :many
SELECT category FROM learning_logs
WHERE user_id = $1
GROUP BY category
ORDER BY COUNT(*) DESC
LIMIT $2
`

type ListRecentLearningLogCategoriesParams struct {
	UserID int64
	Limit  int32
}

func (q *Queries) ListRecentLearningLogCategories(ctx context.Context, arg ListRecentLearningLogCategoriesParams) ([]*string, error) {
	rows, err := q.db.Query(ctx, listRecentLearningLogCategories, arg.UserID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []*string
	for rows.Next() {
		var category *string
		if err := rows.Scan(&category); err != nil {
			return nil, err
		}
		items = append(items, category)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const sumLearningLogDurationByGoal = `-- name: SumLearningLogDurationByGoal :one
SELECT COALESCE(SUM(duration), 0)::bigint FROM learning_logs WHERE goal_id = $1
`

func (q *Queries) SumLearningLogDurationByGoal(ctx context.Context, goalID *int64) (int64, error) {
	row := q.db.QueryRow(ctx, sumLearningLogDurationByGoal, goalID)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const sumLearningLogDurationSince = `-- name: SumLearningLogDurationSince :one
SELECT COALESCE(SUM(duration), 0)::bigint FROM learning_logs
WHERE user_id = $1 AND created_at >= $2
`

type SumLearningLogDurationSinceParams struct {
	UserID    int64
	CreatedAt pgtype.Timestamptz
}

func (q *Queries) SumLearningLogDurationSince(ctx context.Context, arg SumLearningLogDurationSinceParams) (int64, error) {
	row := q.db.QueryRow(ctx, sumLearningLogDurationSince, arg.UserID, arg.CreatedAt)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const updateLearningLog = `-- name: UpdateLearningLog :one
UPDATE learning_logs SET
    title = $2, content = $3, category = $4, duration = $5, goal_id = $6, source = $7,
    is_favorite = $8, updated_at = now()
WHERE id = $1
RETURNING id, user_id, title, content, category, duration, goal_id, source, is_favorite, created_at, updated_at
`

type UpdateLearningLogParams struct {
	ID         int64
	Title      string
	Content    string
	Category   *string
	Duration   *int64
	GoalID     *int64
	Source     *string
	IsFavorite *bool
}

// GORMのSave（全カラム上書き）に相当。
func (q *Queries) UpdateLearningLog(ctx context.Context, arg UpdateLearningLogParams) (LearningLog, error) {
	row := q.db.QueryRow(ctx, updateLearningLog,
		arg.ID,
		arg.Title,
		arg.Content,
		arg.Category,
		arg.Duration,
		arg.GoalID,
		arg.Source,
		arg.IsFavorite,
	)
	var i LearningLog
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Title,
		&i.Content,
		&i.Category,
		&i.Duration,
		&i.GoalID,
		&i.Source,
		&i.IsFavorite,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
