// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: learning_resource_stats.sql

package sqlcgen

import (
	"context"
)

const countLearningResourceCategoriesByUser = `-- name: CountLearningResourceCategoriesByUser :one
SELECT count(DISTINCT category) FROM learning_resources
WHERE user_id = $1
`

func (q *Queries) CountLearningResourceCategoriesByUser(ctx context.Context, userID int64) (int64, error) {
	row := q.db.QueryRow(ctx, countLearningResourceCategoriesByUser, userID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countLearningResourcesByUser = `-- name: CountLearningResourcesByUser :one
SELECT count(*) FROM learning_resources
WHERE user_id = $1
`

func (q *Queries) CountLearningResourcesByUser(ctx context.Context, userID int64) (int64, error) {
	row := q.db.QueryRow(ctx, countLearningResourcesByUser, userID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const sumLearningResourceLikeCountByUser = `-- name: SumLearningResourceLikeCountByUser :one
SELECT COALESCE(SUM(lrm.like_count), 0)::bigint
FROM learning_resources lr
LEFT JOIN learning_resource_metrics lrm ON lrm.resource_id = lr.id
WHERE lr.user_id = $1
`

// like_countはlearning_resource_metrics側（DEVSYNC-159）。LEFT JOIN + COALESCEで0扱いにする。
func (q *Queries) SumLearningResourceLikeCountByUser(ctx context.Context, userID int64) (int64, error) {
	row := q.db.QueryRow(ctx, sumLearningResourceLikeCountByUser, userID)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const sumLearningResourceSaveCountByUser = `-- name: SumLearningResourceSaveCountByUser :one
SELECT COALESCE(SUM(lrm.save_count), 0)::bigint
FROM learning_resources lr
LEFT JOIN learning_resource_metrics lrm ON lrm.resource_id = lr.id
WHERE lr.user_id = $1
`

func (q *Queries) SumLearningResourceSaveCountByUser(ctx context.Context, userID int64) (int64, error) {
	row := q.db.QueryRow(ctx, sumLearningResourceSaveCountByUser, userID)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}
