// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: level.sql

package sqlcgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countCommentsByUser = `-- name: CountCommentsByUser :one
SELECT COUNT(*) FROM comments WHERE user_id = $1
`

func (q *Queries) CountCommentsByUser(ctx context.Context, userID int64) (int64, error) {
	row := q.db.QueryRow(ctx, countCommentsByUser, userID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countCompletedLearningGoalsByUser = `-- name: CountCompletedLearningGoalsByUser :one
SELECT COUNT(*) FROM learning_goals WHERE user_id = $1 AND status = $2
`

type CountCompletedLearningGoalsByUserParams struct {
	UserID int64
	Status *string
}

func (q *Queries) CountCompletedLearningGoalsByUser(ctx context.Context, arg CountCompletedLearningGoalsByUserParams) (int64, error) {
	row := q.db.QueryRow(ctx, countCompletedLearningGoalsByUser, arg.UserID, arg.Status)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countGitHubContributionDaysByUser = `-- name: CountGitHubContributionDaysByUser :one
SELECT COUNT(DISTINCT contributed_on) FROM git_hub_contributions WHERE user_id = $1 AND count > 0
`

func (q *Queries) CountGitHubContributionDaysByUser(ctx context.Context, userID int64) (int64, error) {
	row := q.db.QueryRow(ctx, countGitHubContributionDaysByUser, userID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countPostsByUser = `-- name: CountPostsByUser :one
SELECT COUNT(*) FROM posts WHERE user_id = $1
`

func (q *Queries) CountPostsByUser(ctx context.Context, userID int64) (int64, error) {
	row := q.db.QueryRow(ctx, countPostsByUser, userID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const listLearningLogDatesByUser = `-- name: ListLearningLogDatesByUser :many
SELECT DISTINCT DATE(created_at) AS log_date FROM learning_logs
WHERE user_id = $1
ORDER BY log_date DESC
`

// 学習ログの連続記録日数（ストリーク）算出に使う、記録のある日付一覧（新しい順）。
func (q *Queries) ListLearningLogDatesByUser(ctx context.Context, userID int64) ([]pgtype.Date, error) {
	rows, err := q.db.Query(ctx, listLearningLogDatesByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []pgtype.Date
	for rows.Next() {
		var log_date pgtype.Date
		if err := rows.Scan(&log_date); err != nil {
			return nil, err
		}
		items = append(items, log_date)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const sumPostLikesReceivedByUser = `-- name: SumPostLikesReceivedByUser :one
SELECT COALESCE(SUM(like_count), 0)::bigint FROM posts WHERE user_id = $1
`

func (q *Queries) SumPostLikesReceivedByUser(ctx context.Context, userID int64) (int64, error) {
	row := q.db.QueryRow(ctx, sumPostLikesReceivedByUser, userID)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}
