// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: mention_stats.sql

package sqlcgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countMentionsMadeByUser = `-- name: CountMentionsMadeByUser :one
SELECT count(*) FROM mentions
WHERE actor_id = $1
`

func (q *Queries) CountMentionsMadeByUser(ctx context.Context, actorID int64) (int64, error) {
	row := q.db.QueryRow(ctx, countMentionsMadeByUser, actorID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countMentionsReceivedByUser = `-- name: CountMentionsReceivedByUser :one
SELECT count(*) FROM mentions
WHERE user_id = $1
`

func (q *Queries) CountMentionsReceivedByUser(ctx context.Context, userID int64) (int64, error) {
	row := q.db.QueryRow(ctx, countMentionsReceivedByUser, userID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countMentionsReceivedByUserSince = `-- name: CountMentionsReceivedByUserSince :one
SELECT count(*) FROM mentions
WHERE user_id = $1 AND created_at >= $2
`

type CountMentionsReceivedByUserSinceParams struct {
	UserID    int64
	CreatedAt pgtype.Timestamptz
}

func (q *Queries) CountMentionsReceivedByUserSince(ctx context.Context, arg CountMentionsReceivedByUserSinceParams) (int64, error) {
	row := q.db.QueryRow(ctx, countMentionsReceivedByUserSince, arg.UserID, arg.CreatedAt)
	var count int64
	err := row.Scan(&count)
	return count, err
}
