// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: mention.sql

package sqlcgen

import (
	"context"
)

const createMention = `-- name: CreateMention :one
INSERT INTO mentions (user_id, actor_id, post_id, comment_id, created_at)
VALUES ($1, $2, $3, $4, now())
ON CONFLICT DO NOTHING
RETURNING id, user_id, actor_id, post_id, comment_id, created_at
`

type CreateMentionParams struct {
	UserID    int64
	ActorID   int64
	PostID    *int64
	CommentID *int64
}

// GORMの clause.OnConflict{DoNothing: true} に相当。衝突時は RETURNING 行が無くなるため
// pgx.ErrNoRows を「作成されなかった」判定に使う。
func (q *Queries) CreateMention(ctx context.Context, arg CreateMentionParams) (Mention, error) {
	row := q.db.QueryRow(ctx, createMention,
		arg.UserID,
		arg.ActorID,
		arg.PostID,
		arg.CommentID,
	)
	var i Mention
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ActorID,
		&i.PostID,
		&i.CommentID,
		&i.CreatedAt,
	)
	return i, err
}

const deleteMentionsByCommentID = `-- name: DeleteMentionsByCommentID :exec
DELETE FROM mentions WHERE comment_id = $1
`

func (q *Queries) DeleteMentionsByCommentID(ctx context.Context, commentID *int64) error {
	_, err := q.db.Exec(ctx, deleteMentionsByCommentID, commentID)
	return err
}

const deleteMentionsByPostID = `-- name: DeleteMentionsByPostID :exec
DELETE FROM mentions WHERE post_id = $1
`

func (q *Queries) DeleteMentionsByPostID(ctx context.Context, postID *int64) error {
	_, err := q.db.Exec(ctx, deleteMentionsByPostID, postID)
	return err
}

const listMentionsByCommentID = `-- name: ListMentionsByCommentID :many
SELECT mentions.id, mentions.user_id, mentions.actor_id, mentions.post_id, mentions.comment_id, mentions.created_at, mention_user.id, mention_user.username, mention_user.name, mention_user.email, mention_user.avatar_url, mention_user.bio, mention_user.git_hub_id, mention_user.git_hub_username, mention_user.git_hub_token, mention_user.git_hub_connected, mention_user.spotify_connected, mention_user.spotify_token, mention_user.spotify_refresh_token, mention_user.spotify_token_expiry, mention_user.zenn_username, mention_user.qiita_username, mention_user.at_coder_username, mention_user.paiza_rank, mention_user.skills_languages, mention_user.skills_frameworks, mention_user.onboarding_completed, mention_user.email_weekly_report, mention_user.email_language, mention_user.created_at, mention_user.updated_at, actor.id, actor.username, actor.name, actor.email, actor.avatar_url, actor.bio, actor.git_hub_id, actor.git_hub_username, actor.git_hub_token, actor.git_hub_connected, actor.spotify_connected, actor.spotify_token, actor.spotify_refresh_token, actor.spotify_token_expiry, actor.zenn_username, actor.qiita_username, actor.at_coder_username, actor.paiza_rank, actor.skills_languages, actor.skills_frameworks, actor.onboarding_completed, actor.email_weekly_report, actor.email_language, actor.created_at, actor.updated_at
FROM mentions
JOIN users mention_user ON mention_user.id = mentions.user_id
JOIN users actor ON actor.id = mentions.actor_id
WHERE mentions.comment_id = $1
`

type ListMentionsByCommentIDRow struct {
	Mention Mention
	User    User
	User_2  User
}

func (q *Queries) ListMentionsByCommentID(ctx context.Context, commentID *int64) ([]ListMentionsByCommentIDRow, error) {
	rows, err := q.db.Query(ctx, listMentionsByCommentID, commentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListMentionsByCommentIDRow
	for rows.Next() {
		var i ListMentionsByCommentIDRow
		if err := rows.Scan(
			&i.Mention.ID,
			&i.Mention.UserID,
			&i.Mention.ActorID,
			&i.Mention.PostID,
			&i.Mention.CommentID,
			&i.Mention.CreatedAt,
			&i.User.ID,
			&i.User.Username,
			&i.User.Name,
			&i.User.Email,
			&i.User.AvatarUrl,
			&i.User.Bio,
			&i.User.GitHubID,
			&i.User.GitHubUsername,
			&i.User.GitHubToken,
			&i.User.GitHubConnected,
			&i.User.SpotifyConnected,
			&i.User.SpotifyToken,
			&i.User.SpotifyRefreshToken,
			&i.User.SpotifyTokenExpiry,
			&i.User.ZennUsername,
			&i.User.QiitaUsername,
			&i.User.AtCoderUsername,
			&i.User.PaizaRank,
			&i.User.SkillsLanguages,
			&i.User.SkillsFrameworks,
			&i.User.OnboardingCompleted,
			&i.User.EmailWeeklyReport,
			&i.User.EmailLanguage,
			&i.User.CreatedAt,
			&i.User.UpdatedAt,
			&i.User_2.ID,
			&i.User_2.Username,
			&i.User_2.Name,
			&i.User_2.Email,
			&i.User_2.AvatarUrl,
			&i.User_2.Bio,
			&i.User_2.GitHubID,
			&i.User_2.GitHubUsername,
			&i.User_2.GitHubToken,
			&i.User_2.GitHubConnected,
			&i.User_2.SpotifyConnected,
			&i.User_2.SpotifyToken,
			&i.User_2.SpotifyRefreshToken,
			&i.User_2.SpotifyTokenExpiry,
			&i.User_2.ZennUsername,
			&i.User_2.QiitaUsername,
			&i.User_2.AtCoderUsername,
			&i.User_2.PaizaRank,
			&i.User_2.SkillsLanguages,
			&i.User_2.SkillsFrameworks,
			&i.User_2.OnboardingCompleted,
			&i.User_2.EmailWeeklyReport,
			&i.User_2.EmailLanguage,
			&i.User_2.CreatedAt,
			&i.User_2.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMentionsByPostID = `-- name: ListMentionsByPostID :many
SELECT mentions.id, mentions.user_id, mentions.actor_id, mentions.post_id, mentions.comment_id, mentions.created_at, mention_user.id, mention_user.username, mention_user.name, mention_user.email, mention_user.avatar_url, mention_user.bio, mention_user.git_hub_id, mention_user.git_hub_username, mention_user.git_hub_token, mention_user.git_hub_connected, mention_user.spotify_connected, mention_user.spotify_token, mention_user.spotify_refresh_token, mention_user.spotify_token_expiry, mention_user.zenn_username, mention_user.qiita_username, mention_user.at_coder_username, mention_user.paiza_rank, mention_user.skills_languages, mention_user.skills_frameworks, mention_user.onboarding_completed, mention_user.email_weekly_report, mention_user.email_language, mention_user.created_at, mention_user.updated_at, actor.id, actor.username, actor.name, actor.email, actor.avatar_url, actor.bio, actor.git_hub_id, actor.git_hub_username, actor.git_hub_token, actor.git_hub_connected, actor.spotify_connected, actor.spotify_token, actor.spotify_refresh_token, actor.spotify_token_expiry, actor.zenn_username, actor.qiita_username, actor.at_coder_username, actor.paiza_rank, actor.skills_languages, actor.skills_frameworks, actor.onboarding_completed, actor.email_weekly_report, actor.email_language, actor.created_at, actor.updated_at
FROM mentions
JOIN users mention_user ON mention_user.id = mentions.user_id
JOIN users actor ON actor.id = mentions.actor_id
WHERE mentions.post_id = $1
`

type ListMentionsByPostIDRow struct {
	Mention Mention
	User    User
	User_2  User
}

// GORMのPreload("User").Preload("Actor")に相当。user_id/actor_idともにNOT NULLのためINNER JOINでよい。
func (q *Queries) ListMentionsByPostID(ctx context.Context, postID *int64) ([]ListMentionsByPostIDRow, error) {
	rows, err := q.db.Query(ctx, listMentionsByPostID, postID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListMentionsByPostIDRow
	for rows.Next() {
		var i ListMentionsByPostIDRow
		if err := rows.Scan(
			&i.Mention.ID,
			&i.Mention.UserID,
			&i.Mention.ActorID,
			&i.Mention.PostID,
			&i.Mention.CommentID,
			&i.Mention.CreatedAt,
			&i.User.ID,
			&i.User.Username,
			&i.User.Name,
			&i.User.Email,
			&i.User.AvatarUrl,
			&i.User.Bio,
			&i.User.GitHubID,
			&i.User.GitHubUsername,
			&i.User.GitHubToken,
			&i.User.GitHubConnected,
			&i.User.SpotifyConnected,
			&i.User.SpotifyToken,
			&i.User.SpotifyRefreshToken,
			&i.User.SpotifyTokenExpiry,
			&i.User.ZennUsername,
			&i.User.QiitaUsername,
			&i.User.AtCoderUsername,
			&i.User.PaizaRank,
			&i.User.SkillsLanguages,
			&i.User.SkillsFrameworks,
			&i.User.OnboardingCompleted,
			&i.User.EmailWeeklyReport,
			&i.User.EmailLanguage,
			&i.User.CreatedAt,
			&i.User.UpdatedAt,
			&i.User_2.ID,
			&i.User_2.Username,
			&i.User_2.Name,
			&i.User_2.Email,
			&i.User_2.AvatarUrl,
			&i.User_2.Bio,
			&i.User_2.GitHubID,
			&i.User_2.GitHubUsername,
			&i.User_2.GitHubToken,
			&i.User_2.GitHubConnected,
			&i.User_2.SpotifyConnected,
			&i.User_2.SpotifyToken,
			&i.User_2.SpotifyRefreshToken,
			&i.User_2.SpotifyTokenExpiry,
			&i.User_2.ZennUsername,
			&i.User_2.QiitaUsername,
			&i.User_2.AtCoderUsername,
			&i.User_2.PaizaRank,
			&i.User_2.SkillsLanguages,
			&i.User_2.SkillsFrameworks,
			&i.User_2.OnboardingCompleted,
			&i.User_2.EmailWeeklyReport,
			&i.User_2.EmailLanguage,
			&i.User_2.CreatedAt,
			&i.User_2.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMentionsByUser = `-- name: ListMentionsByUser :many
SELECT mentions.id, mentions.user_id, mentions.actor_id, mentions.post_id, mentions.comment_id, mentions.created_at, actor.id, actor.username, actor.name, actor.email, actor.avatar_url, actor.bio, actor.git_hub_id, actor.git_hub_username, actor.git_hub_token, actor.git_hub_connected, actor.spotify_connected, actor.spotify_token, actor.spotify_refresh_token, actor.spotify_token_expiry, actor.zenn_username, actor.qiita_username, actor.at_coder_username, actor.paiza_rank, actor.skills_languages, actor.skills_frameworks, actor.onboarding_completed, actor.email_weekly_report, actor.email_language, actor.created_at, actor.updated_at
FROM mentions
JOIN users actor ON actor.id = mentions.actor_id
WHERE mentions.user_id = $1
ORDER BY mentions.created_at DESC
LIMIT $2 OFFSET $3
`

type ListMentionsByUserParams struct {
	UserID int64
	Limit  int32
	Offset int32
}

type ListMentionsByUserRow struct {
	Mention Mention
	User    User
}

// GORMのPreload("Actor")に相当。actor_idはNOT NULLのためINNER JOINでよい。
func (q *Queries) ListMentionsByUser(ctx context.Context, arg ListMentionsByUserParams) ([]ListMentionsByUserRow, error) {
	rows, err := q.db.Query(ctx, listMentionsByUser, arg.UserID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListMentionsByUserRow
	for rows.Next() {
		var i ListMentionsByUserRow
		if err := rows.Scan(
			&i.Mention.ID,
			&i.Mention.UserID,
			&i.Mention.ActorID,
			&i.Mention.PostID,
			&i.Mention.CommentID,
			&i.Mention.CreatedAt,
			&i.User.ID,
			&i.User.Username,
			&i.User.Name,
			&i.User.Email,
			&i.User.AvatarUrl,
			&i.User.Bio,
			&i.User.GitHubID,
			&i.User.GitHubUsername,
			&i.User.GitHubToken,
			&i.User.GitHubConnected,
			&i.User.SpotifyConnected,
			&i.User.SpotifyToken,
			&i.User.SpotifyRefreshToken,
			&i.User.SpotifyTokenExpiry,
			&i.User.ZennUsername,
			&i.User.QiitaUsername,
			&i.User.AtCoderUsername,
			&i.User.PaizaRank,
			&i.User.SkillsLanguages,
			&i.User.SkillsFrameworks,
			&i.User.OnboardingCompleted,
			&i.User.EmailWeeklyReport,
			&i.User.EmailLanguage,
			&i.User.CreatedAt,
			&i.User.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
