// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: message.sql

package sqlcgen

import (
	"context"
)

const createMessage = `-- name: CreateMessage :one
INSERT INTO messages (sender_id, receiver_id, content, read, created_at)
VALUES ($1, $2, $3, false, now())
RETURNING id, sender_id, receiver_id, content, read, created_at
`

type CreateMessageParams struct {
	SenderID   int64
	ReceiverID int64
	Content    string
}

func (q *Queries) CreateMessage(ctx context.Context, arg CreateMessageParams) (Message, error) {
	row := q.db.QueryRow(ctx, createMessage, arg.SenderID, arg.ReceiverID, arg.Content)
	var i Message
	err := row.Scan(
		&i.ID,
		&i.SenderID,
		&i.ReceiverID,
		&i.Content,
		&i.Read,
		&i.CreatedAt,
	)
	return i, err
}

const listConversationMessages = `-- name: ListConversationMessages :many
SELECT messages.id, messages.sender_id, messages.receiver_id, messages.content, messages.read, messages.created_at, sender.id, sender.username, sender.name, sender.email, sender.avatar_url, sender.bio, sender.git_hub_id, sender.git_hub_username, sender.git_hub_token, sender.git_hub_connected, sender.spotify_connected, sender.spotify_token, sender.spotify_refresh_token, sender.spotify_token_expiry, sender.zenn_username, sender.qiita_username, sender.at_coder_username, sender.paiza_rank, sender.skills_languages, sender.skills_frameworks, sender.onboarding_completed, sender.email_weekly_report, sender.email_language, sender.created_at, sender.updated_at, receiver.id, receiver.username, receiver.name, receiver.email, receiver.avatar_url, receiver.bio, receiver.git_hub_id, receiver.git_hub_username, receiver.git_hub_token, receiver.git_hub_connected, receiver.spotify_connected, receiver.spotify_token, receiver.spotify_refresh_token, receiver.spotify_token_expiry, receiver.zenn_username, receiver.qiita_username, receiver.at_coder_username, receiver.paiza_rank, receiver.skills_languages, receiver.skills_frameworks, receiver.onboarding_completed, receiver.email_weekly_report, receiver.email_language, receiver.created_at, receiver.updated_at
FROM messages
JOIN users sender ON sender.id = messages.sender_id
JOIN users receiver ON receiver.id = messages.receiver_id
WHERE (messages.sender_id = $1 AND messages.receiver_id = $2)
    OR (messages.sender_id = $2 AND messages.receiver_id = $1)
ORDER BY messages.created_at ASC
LIMIT $3 OFFSET $4
`

type ListConversationMessagesParams struct {
	SenderID   int64
	ReceiverID int64
	Limit      int32
	Offset     int32
}

type ListConversationMessagesRow struct {
	Message Message
	User    User
	User_2  User
}

// GORMのPreload("Sender").Preload("Receiver")に相当。
// sender_id/receiver_idともにNOT NULLのためINNER JOINでよい。
func (q *Queries) ListConversationMessages(ctx context.Context, arg ListConversationMessagesParams) ([]ListConversationMessagesRow, error) {
	rows, err := q.db.Query(ctx, listConversationMessages,
		arg.SenderID,
		arg.ReceiverID,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListConversationMessagesRow
	for rows.Next() {
		var i ListConversationMessagesRow
		if err := rows.Scan(
			&i.Message.ID,
			&i.Message.SenderID,
			&i.Message.ReceiverID,
			&i.Message.Content,
			&i.Message.Read,
			&i.Message.CreatedAt,
			&i.User.ID,
			&i.User.Username,
			&i.User.Name,
			&i.User.Email,
			&i.User.AvatarUrl,
			&i.User.Bio,
			&i.User.GitHubID,
			&i.User.GitHubUsername,
			&i.User.GitHubToken,
			&i.User.GitHubConnected,
			&i.User.SpotifyConnected,
			&i.User.SpotifyToken,
			&i.User.SpotifyRefreshToken,
			&i.User.SpotifyTokenExpiry,
			&i.User.ZennUsername,
			&i.User.QiitaUsername,
			&i.User.AtCoderUsername,
			&i.User.PaizaRank,
			&i.User.SkillsLanguages,
			&i.User.SkillsFrameworks,
			&i.User.OnboardingCompleted,
			&i.User.EmailWeeklyReport,
			&i.User.EmailLanguage,
			&i.User.CreatedAt,
			&i.User.UpdatedAt,
			&i.User_2.ID,
			&i.User_2.Username,
			&i.User_2.Name,
			&i.User_2.Email,
			&i.User_2.AvatarUrl,
			&i.User_2.Bio,
			&i.User_2.GitHubID,
			&i.User_2.GitHubUsername,
			&i.User_2.GitHubToken,
			&i.User_2.GitHubConnected,
			&i.User_2.SpotifyConnected,
			&i.User_2.SpotifyToken,
			&i.User_2.SpotifyRefreshToken,
			&i.User_2.SpotifyTokenExpiry,
			&i.User_2.ZennUsername,
			&i.User_2.QiitaUsername,
			&i.User_2.AtCoderUsername,
			&i.User_2.PaizaRank,
			&i.User_2.SkillsLanguages,
			&i.User_2.SkillsFrameworks,
			&i.User_2.OnboardingCompleted,
			&i.User_2.EmailWeeklyReport,
			&i.User_2.EmailLanguage,
			&i.User_2.CreatedAt,
			&i.User_2.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listConversationSummaries = `-- name: ListConversationSummaries :many
SELECT DISTINCT ON (other_id) other_id AS user_id, u.name, u.avatar_url,
    m.content AS last_message, m.created_at::text AS last_time,
    (SELECT COUNT(*) FROM messages unread WHERE unread.sender_id = other_id AND unread.receiver_id = $1 AND unread.read = false) AS unread_count
FROM (
    SELECT CASE WHEN sender_id = $1 THEN receiver_id ELSE sender_id END AS other_id, id
    FROM messages
    WHERE sender_id = $1 OR receiver_id = $1
) sub
JOIN messages m ON m.id = sub.id
JOIN users u ON u.id = sub.other_id
ORDER BY other_id, m.created_at DESC
`

type ListConversationSummariesRow struct {
	UserID      interface{}
	Name        string
	AvatarUrl   *string
	LastMessage string
	LastTime    string
	UnreadCount int64
}

// 会話相手ごとの最新メッセージと未読件数を取得する（移行前のGORM Raw SQLをそのまま踏襲）。
func (q *Queries) ListConversationSummaries(ctx context.Context, receiverID int64) ([]ListConversationSummariesRow, error) {
	rows, err := q.db.Query(ctx, listConversationSummaries, receiverID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListConversationSummariesRow
	for rows.Next() {
		var i ListConversationSummariesRow
		if err := rows.Scan(
			&i.UserID,
			&i.Name,
			&i.AvatarUrl,
			&i.LastMessage,
			&i.LastTime,
			&i.UnreadCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markMessagesAsRead = `-- name: MarkMessagesAsRead :exec
UPDATE messages SET read = true
WHERE sender_id = $1 AND receiver_id = $2 AND read = false
`

type MarkMessagesAsReadParams struct {
	SenderID   int64
	ReceiverID int64
}

func (q *Queries) MarkMessagesAsRead(ctx context.Context, arg MarkMessagesAsReadParams) error {
	_, err := q.db.Exec(ctx, markMessagesAsRead, arg.SenderID, arg.ReceiverID)
	return err
}
