// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: message_stats.sql

package sqlcgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countConversationsByUser = `-- name: CountConversationsByUser :one
SELECT count(DISTINCT CASE WHEN sender_id = $1 THEN receiver_id ELSE sender_id END)
FROM messages
WHERE sender_id = $1 OR receiver_id = $1
`

func (q *Queries) CountConversationsByUser(ctx context.Context, senderID int64) (int64, error) {
	row := q.db.QueryRow(ctx, countConversationsByUser, senderID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countMessagesReceivedByUser = `-- name: CountMessagesReceivedByUser :one
SELECT count(*) FROM messages
WHERE receiver_id = $1
`

func (q *Queries) CountMessagesReceivedByUser(ctx context.Context, receiverID int64) (int64, error) {
	row := q.db.QueryRow(ctx, countMessagesReceivedByUser, receiverID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countMessagesSentByUser = `-- name: CountMessagesSentByUser :one
SELECT count(*) FROM messages
WHERE sender_id = $1
`

func (q *Queries) CountMessagesSentByUser(ctx context.Context, senderID int64) (int64, error) {
	row := q.db.QueryRow(ctx, countMessagesSentByUser, senderID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countMessagesSentByUserSince = `-- name: CountMessagesSentByUserSince :one
SELECT count(*) FROM messages
WHERE sender_id = $1 AND created_at >= $2
`

type CountMessagesSentByUserSinceParams struct {
	SenderID  int64
	CreatedAt pgtype.Timestamptz
}

func (q *Queries) CountMessagesSentByUserSince(ctx context.Context, arg CountMessagesSentByUserSinceParams) (int64, error) {
	row := q.db.QueryRow(ctx, countMessagesSentByUserSince, arg.SenderID, arg.CreatedAt)
	var count int64
	err := row.Scan(&count)
	return count, err
}
