// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: note_stats.sql

package sqlcgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countArchivedNotesByUser = `-- name: CountArchivedNotesByUser :one
SELECT count(*) FROM notes
WHERE user_id = $1 AND is_archived = true
`

func (q *Queries) CountArchivedNotesByUser(ctx context.Context, userID int64) (int64, error) {
	row := q.db.QueryRow(ctx, countArchivedNotesByUser, userID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countFavoriteNotesByUser = `-- name: CountFavoriteNotesByUser :one
SELECT count(*) FROM notes
WHERE user_id = $1 AND is_favorite = true
`

func (q *Queries) CountFavoriteNotesByUser(ctx context.Context, userID int64) (int64, error) {
	row := q.db.QueryRow(ctx, countFavoriteNotesByUser, userID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countNoteFoldersByUser = `-- name: CountNoteFoldersByUser :one
SELECT count(*) FROM note_folders
WHERE user_id = $1
`

func (q *Queries) CountNoteFoldersByUser(ctx context.Context, userID int64) (int64, error) {
	row := q.db.QueryRow(ctx, countNoteFoldersByUser, userID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countNotesByUser = `-- name: CountNotesByUser :one
SELECT count(*) FROM notes
WHERE user_id = $1
`

func (q *Queries) CountNotesByUser(ctx context.Context, userID int64) (int64, error) {
	row := q.db.QueryRow(ctx, countNotesByUser, userID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countNotesByUserSince = `-- name: CountNotesByUserSince :one
SELECT count(*) FROM notes
WHERE user_id = $1 AND created_at >= $2
`

type CountNotesByUserSinceParams struct {
	UserID    int64
	CreatedAt pgtype.Timestamptz
}

func (q *Queries) CountNotesByUserSince(ctx context.Context, arg CountNotesByUserSinceParams) (int64, error) {
	row := q.db.QueryRow(ctx, countNotesByUserSince, arg.UserID, arg.CreatedAt)
	var count int64
	err := row.Scan(&count)
	return count, err
}
