// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: note_version.sql

package sqlcgen

import (
	"context"
)

const countNoteVersionsByNote = `-- name: CountNoteVersionsByNote :one
SELECT count(*) FROM note_versions
WHERE note_id = $1
`

func (q *Queries) CountNoteVersionsByNote(ctx context.Context, noteID int64) (int64, error) {
	row := q.db.QueryRow(ctx, countNoteVersionsByNote, noteID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createNoteVersion = `-- name: CreateNoteVersion :one
INSERT INTO note_versions (note_id, version_number, title, content, tags, created_at)
VALUES ($1, $2, $3, $4, $5, now())
RETURNING id, note_id, version_number, title, content, tags, created_at
`

type CreateNoteVersionParams struct {
	NoteID        int64
	VersionNumber int64
	Title         string
	Content       *string
	Tags          *string
}

func (q *Queries) CreateNoteVersion(ctx context.Context, arg CreateNoteVersionParams) (NoteVersion, error) {
	row := q.db.QueryRow(ctx, createNoteVersion,
		arg.NoteID,
		arg.VersionNumber,
		arg.Title,
		arg.Content,
		arg.Tags,
	)
	var i NoteVersion
	err := row.Scan(
		&i.ID,
		&i.NoteID,
		&i.VersionNumber,
		&i.Title,
		&i.Content,
		&i.Tags,
		&i.CreatedAt,
	)
	return i, err
}

const getLatestNoteVersionNumber = `-- name: GetLatestNoteVersionNumber :one
SELECT COALESCE(MAX(version_number), 0)::bigint FROM note_versions
WHERE note_id = $1
`

func (q *Queries) GetLatestNoteVersionNumber(ctx context.Context, noteID int64) (int64, error) {
	row := q.db.QueryRow(ctx, getLatestNoteVersionNumber, noteID)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const getNoteVersionByID = `-- name: GetNoteVersionByID :one
SELECT id, note_id, version_number, title, content, tags, created_at FROM note_versions
WHERE id = $1
`

func (q *Queries) GetNoteVersionByID(ctx context.Context, id int64) (NoteVersion, error) {
	row := q.db.QueryRow(ctx, getNoteVersionByID, id)
	var i NoteVersion
	err := row.Scan(
		&i.ID,
		&i.NoteID,
		&i.VersionNumber,
		&i.Title,
		&i.Content,
		&i.Tags,
		&i.CreatedAt,
	)
	return i, err
}

const listNoteVersionsByNote = `-- name: ListNoteVersionsByNote :many
SELECT id, note_id, version_number, title, content, tags, created_at FROM note_versions
WHERE note_id = $1
ORDER BY version_number DESC
LIMIT $2 OFFSET $3
`

type ListNoteVersionsByNoteParams struct {
	NoteID int64
	Limit  int32
	Offset int32
}

func (q *Queries) ListNoteVersionsByNote(ctx context.Context, arg ListNoteVersionsByNoteParams) ([]NoteVersion, error) {
	rows, err := q.db.Query(ctx, listNoteVersionsByNote, arg.NoteID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []NoteVersion
	for rows.Next() {
		var i NoteVersion
		if err := rows.Scan(
			&i.ID,
			&i.NoteID,
			&i.VersionNumber,
			&i.Title,
			&i.Content,
			&i.Tags,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
