// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: note_link.sql

package sqlcgen

import (
	"context"
)

const countNoteLinksBetween = `-- name: CountNoteLinksBetween :one
SELECT count(*) FROM note_links
WHERE source_note_id = $1 AND target_note_id = $2
`

type CountNoteLinksBetweenParams struct {
	SourceNoteID int64
	TargetNoteID int64
}

func (q *Queries) CountNoteLinksBetween(ctx context.Context, arg CountNoteLinksBetweenParams) (int64, error) {
	row := q.db.QueryRow(ctx, countNoteLinksBetween, arg.SourceNoteID, arg.TargetNoteID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countNoteLinksBySource = `-- name: CountNoteLinksBySource :one
SELECT count(*) FROM note_links
WHERE source_note_id = $1
`

func (q *Queries) CountNoteLinksBySource(ctx context.Context, sourceNoteID int64) (int64, error) {
	row := q.db.QueryRow(ctx, countNoteLinksBySource, sourceNoteID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countNoteLinksByTarget = `-- name: CountNoteLinksByTarget :one
SELECT count(*) FROM note_links
WHERE target_note_id = $1
`

func (q *Queries) CountNoteLinksByTarget(ctx context.Context, targetNoteID int64) (int64, error) {
	row := q.db.QueryRow(ctx, countNoteLinksByTarget, targetNoteID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createNoteLink = `-- name: CreateNoteLink :exec
INSERT INTO note_links (source_note_id, target_note_id, created_at)
VALUES ($1, $2, now())
`

type CreateNoteLinkParams struct {
	SourceNoteID int64
	TargetNoteID int64
}

func (q *Queries) CreateNoteLink(ctx context.Context, arg CreateNoteLinkParams) error {
	_, err := q.db.Exec(ctx, createNoteLink, arg.SourceNoteID, arg.TargetNoteID)
	return err
}

const deleteNoteLink = `-- name: DeleteNoteLink :exec
DELETE FROM note_links
WHERE source_note_id = $1 AND target_note_id = $2
`

type DeleteNoteLinkParams struct {
	SourceNoteID int64
	TargetNoteID int64
}

func (q *Queries) DeleteNoteLink(ctx context.Context, arg DeleteNoteLinkParams) error {
	_, err := q.db.Exec(ctx, deleteNoteLink, arg.SourceNoteID, arg.TargetNoteID)
	return err
}

const listNoteLinksBySource = `-- name: ListNoteLinksBySource :many
SELECT note_links.id, note_links.source_note_id, note_links.target_note_id, note_links.created_at, notes.id, notes.user_id, notes.folder_id, notes.title, notes.content, notes.tags, notes.is_favorite, notes.is_archived, notes.created_at, notes.updated_at
FROM note_links
JOIN notes ON notes.id = note_links.target_note_id
WHERE note_links.source_note_id = $1
ORDER BY note_links.created_at DESC
`

type ListNoteLinksBySourceRow struct {
	NoteLink NoteLink
	Note     Note
}

// GORMのPreload("TargetNote")に相当。リンク先ノートをsqlc.embedで一緒に取得する。
func (q *Queries) ListNoteLinksBySource(ctx context.Context, sourceNoteID int64) ([]ListNoteLinksBySourceRow, error) {
	rows, err := q.db.Query(ctx, listNoteLinksBySource, sourceNoteID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListNoteLinksBySourceRow
	for rows.Next() {
		var i ListNoteLinksBySourceRow
		if err := rows.Scan(
			&i.NoteLink.ID,
			&i.NoteLink.SourceNoteID,
			&i.NoteLink.TargetNoteID,
			&i.NoteLink.CreatedAt,
			&i.Note.ID,
			&i.Note.UserID,
			&i.Note.FolderID,
			&i.Note.Title,
			&i.Note.Content,
			&i.Note.Tags,
			&i.Note.IsFavorite,
			&i.Note.IsArchived,
			&i.Note.CreatedAt,
			&i.Note.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listNoteLinksByTarget = `-- name: ListNoteLinksByTarget :many
SELECT note_links.id, note_links.source_note_id, note_links.target_note_id, note_links.created_at, notes.id, notes.user_id, notes.folder_id, notes.title, notes.content, notes.tags, notes.is_favorite, notes.is_archived, notes.created_at, notes.updated_at
FROM note_links
JOIN notes ON notes.id = note_links.source_note_id
WHERE note_links.target_note_id = $1
ORDER BY note_links.created_at DESC
`

type ListNoteLinksByTargetRow struct {
	NoteLink NoteLink
	Note     Note
}

// GORMのPreload("SourceNote")に相当。リンク元ノートをsqlc.embedで一緒に取得する。
func (q *Queries) ListNoteLinksByTarget(ctx context.Context, targetNoteID int64) ([]ListNoteLinksByTargetRow, error) {
	rows, err := q.db.Query(ctx, listNoteLinksByTarget, targetNoteID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListNoteLinksByTargetRow
	for rows.Next() {
		var i ListNoteLinksByTargetRow
		if err := rows.Scan(
			&i.NoteLink.ID,
			&i.NoteLink.SourceNoteID,
			&i.NoteLink.TargetNoteID,
			&i.NoteLink.CreatedAt,
			&i.Note.ID,
			&i.Note.UserID,
			&i.Note.FolderID,
			&i.Note.Title,
			&i.Note.Content,
			&i.Note.Tags,
			&i.Note.IsFavorite,
			&i.Note.IsArchived,
			&i.Note.CreatedAt,
			&i.Note.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
