// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: note_template.sql

package sqlcgen

import (
	"context"
)

const clearOtherNoteTemplateDefaults = `-- name: ClearOtherNoteTemplateDefaults :exec
UPDATE note_templates SET is_default = false, updated_at = now()
WHERE note_templates.user_id = $1 AND note_templates.is_default IS TRUE AND note_templates.id != $2
`

type ClearOtherNoteTemplateDefaultsParams struct {
	UserID int64
	ID     int64
}

// 同一ユーザーの既存デフォルト（自分自身のid=$2は除く）を外す。Createからは
// 存在しないid（0）を渡すことで全件が対象になる。呼び出し元（repository）が
// 1つのトランザクション内でこのクエリの直後にCreate/Updateを実行することで、
// 「解除」と「新しいデフォルトの確定」を1つの原子的な単位にする。
// 【重要】1つのSQL文の中のCTEとしてUPDATE→INSERT/UPDATEを両方書く方式は使わない。
// PostgreSQLのデータ変更CTEは主文と同一スナップショットで動作し、UPDATEによる解除の
// 効果が同一文内の一意制約チェックに間に合わず、デフォルトが1件も無い状態からの
// 切り替えでも毎回一意制約違反になることを確認済み（2文に分けて初めて正しく動く）。
// uq_note_templates_default（(user_id) WHERE is_default の部分UNIQUE索引）は
// 本当に並行する別トランザクション同士の衝突に対する最終防衛。
func (q *Queries) ClearOtherNoteTemplateDefaults(ctx context.Context, arg ClearOtherNoteTemplateDefaultsParams) error {
	_, err := q.db.Exec(ctx, clearOtherNoteTemplateDefaults, arg.UserID, arg.ID)
	return err
}

const countNoteTemplatesByUser = `-- name: CountNoteTemplatesByUser :one
SELECT count(*) FROM note_templates
WHERE user_id = $1
`

func (q *Queries) CountNoteTemplatesByUser(ctx context.Context, userID int64) (int64, error) {
	row := q.db.QueryRow(ctx, countNoteTemplatesByUser, userID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createNoteTemplate = `-- name: CreateNoteTemplate :one
INSERT INTO note_templates (user_id, name, description, default_title, content_template, default_tags, is_default, created_at, updated_at)
VALUES ($1, $2, $3, $4, $5, $6, $7, now(), now())
RETURNING id, user_id, name, description, default_title, content_template, default_tags, is_default, created_at, updated_at
`

type CreateNoteTemplateParams struct {
	UserID          int64
	Name            string
	Description     *string
	DefaultTitle    *string
	ContentTemplate string
	DefaultTags     *string
	IsDefault       *bool
}

func (q *Queries) CreateNoteTemplate(ctx context.Context, arg CreateNoteTemplateParams) (NoteTemplate, error) {
	row := q.db.QueryRow(ctx, createNoteTemplate,
		arg.UserID,
		arg.Name,
		arg.Description,
		arg.DefaultTitle,
		arg.ContentTemplate,
		arg.DefaultTags,
		arg.IsDefault,
	)
	var i NoteTemplate
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.Description,
		&i.DefaultTitle,
		&i.ContentTemplate,
		&i.DefaultTags,
		&i.IsDefault,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteNoteTemplate = `-- name: DeleteNoteTemplate :exec
DELETE FROM note_templates
WHERE id = $1
`

func (q *Queries) DeleteNoteTemplate(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, deleteNoteTemplate, id)
	return err
}

const getDefaultNoteTemplateByUser = `-- name: GetDefaultNoteTemplateByUser :one
SELECT id, user_id, name, description, default_title, content_template, default_tags, is_default, created_at, updated_at FROM note_templates
WHERE user_id = $1 AND is_default = true
ORDER BY id ASC
LIMIT 1
`

func (q *Queries) GetDefaultNoteTemplateByUser(ctx context.Context, userID int64) (NoteTemplate, error) {
	row := q.db.QueryRow(ctx, getDefaultNoteTemplateByUser, userID)
	var i NoteTemplate
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.Description,
		&i.DefaultTitle,
		&i.ContentTemplate,
		&i.DefaultTags,
		&i.IsDefault,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getNoteTemplateByID = `-- name: GetNoteTemplateByID :one
SELECT id, user_id, name, description, default_title, content_template, default_tags, is_default, created_at, updated_at FROM note_templates
WHERE id = $1
`

func (q *Queries) GetNoteTemplateByID(ctx context.Context, id int64) (NoteTemplate, error) {
	row := q.db.QueryRow(ctx, getNoteTemplateByID, id)
	var i NoteTemplate
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.Description,
		&i.DefaultTitle,
		&i.ContentTemplate,
		&i.DefaultTags,
		&i.IsDefault,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listNoteTemplatesByUser = `-- name: ListNoteTemplatesByUser :many
SELECT id, user_id, name, description, default_title, content_template, default_tags, is_default, created_at, updated_at FROM note_templates
WHERE user_id = $1
ORDER BY created_at DESC
`

func (q *Queries) ListNoteTemplatesByUser(ctx context.Context, userID int64) ([]NoteTemplate, error) {
	rows, err := q.db.Query(ctx, listNoteTemplatesByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []NoteTemplate
	for rows.Next() {
		var i NoteTemplate
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Name,
			&i.Description,
			&i.DefaultTitle,
			&i.ContentTemplate,
			&i.DefaultTags,
			&i.IsDefault,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateNoteTemplate = `-- name: UpdateNoteTemplate :one
UPDATE note_templates
SET name = $2,
    description = $3,
    default_title = $4,
    content_template = $5,
    default_tags = $6,
    is_default = $7,
    updated_at = now()
WHERE note_templates.id = $1
RETURNING id, user_id, name, description, default_title, content_template, default_tags, is_default, created_at, updated_at
`

type UpdateNoteTemplateParams struct {
	ID              int64
	Name            string
	Description     *string
	DefaultTitle    *string
	ContentTemplate string
	DefaultTags     *string
	IsDefault       *bool
}

func (q *Queries) UpdateNoteTemplate(ctx context.Context, arg UpdateNoteTemplateParams) (NoteTemplate, error) {
	row := q.db.QueryRow(ctx, updateNoteTemplate,
		arg.ID,
		arg.Name,
		arg.Description,
		arg.DefaultTitle,
		arg.ContentTemplate,
		arg.DefaultTags,
		arg.IsDefault,
	)
	var i NoteTemplate
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.Description,
		&i.DefaultTitle,
		&i.ContentTemplate,
		&i.DefaultTags,
		&i.IsDefault,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
