// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: notification.sql

package sqlcgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countNotificationsByUserID = `-- name: CountNotificationsByUserID :one
SELECT COUNT(*) FROM notifications
WHERE user_id = $1
    AND ($2::text IS NULL OR type = $2)
`

type CountNotificationsByUserIDParams struct {
	UserID           int64
	NotificationType *string
}

func (q *Queries) CountNotificationsByUserID(ctx context.Context, arg CountNotificationsByUserIDParams) (int64, error) {
	row := q.db.QueryRow(ctx, countNotificationsByUserID, arg.UserID, arg.NotificationType)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countUnreadNotifications = `-- name: CountUnreadNotifications :one
SELECT COUNT(*) FROM notifications WHERE user_id = $1 AND read = false
`

func (q *Queries) CountUnreadNotifications(ctx context.Context, userID int64) (int64, error) {
	row := q.db.QueryRow(ctx, countUnreadNotifications, userID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createNotification = `-- name: CreateNotification :one
INSERT INTO notifications (user_id, type, actor_id, post_id, question_id, badge_id, read, created_at)
VALUES ($1, $2, $3, $4, $5, $6, $7, now())
RETURNING id, user_id, type, actor_id, post_id, question_id, badge_id, read, created_at
`

type CreateNotificationParams struct {
	UserID     int64
	Type       string
	ActorID    int64
	PostID     *int64
	QuestionID *int64
	BadgeID    *string
	Read       bool
}

func (q *Queries) CreateNotification(ctx context.Context, arg CreateNotificationParams) (Notification, error) {
	row := q.db.QueryRow(ctx, createNotification,
		arg.UserID,
		arg.Type,
		arg.ActorID,
		arg.PostID,
		arg.QuestionID,
		arg.BadgeID,
		arg.Read,
	)
	var i Notification
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Type,
		&i.ActorID,
		&i.PostID,
		&i.QuestionID,
		&i.BadgeID,
		&i.Read,
		&i.CreatedAt,
	)
	return i, err
}

const deleteNotification = `-- name: DeleteNotification :exec
DELETE FROM notifications WHERE id = $1 AND user_id = $2
`

type DeleteNotificationParams struct {
	ID     int64
	UserID int64
}

func (q *Queries) DeleteNotification(ctx context.Context, arg DeleteNotificationParams) error {
	_, err := q.db.Exec(ctx, deleteNotification, arg.ID, arg.UserID)
	return err
}

const findFollowerIDsByFollowee = `-- name: FindFollowerIDsByFollowee :many
SELECT follower_id FROM follows WHERE followee_id = $1
`

// 指定ユーザーをフォローしているユーザーのIDを返す。
func (q *Queries) FindFollowerIDsByFollowee(ctx context.Context, followeeID int64) ([]int64, error) {
	rows, err := q.db.Query(ctx, findFollowerIDsByFollowee, followeeID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []int64
	for rows.Next() {
		var follower_id int64
		if err := rows.Scan(&follower_id); err != nil {
			return nil, err
		}
		items = append(items, follower_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const findNotificationsByUserID = `-- name: FindNotificationsByUserID :many
SELECT
    notifications.id, notifications.user_id, notifications.type, notifications.actor_id, notifications.post_id, notifications.question_id, notifications.badge_id, notifications.read, notifications.created_at,
    actor.id, actor.username, actor.name, actor.email, actor.password, actor.avatar_url, actor.bio, actor.git_hub_id, actor.git_hub_username, actor.git_hub_token, actor.git_hub_connected, actor.spotify_connected, actor.spotify_token, actor.spotify_refresh_token, actor.spotify_token_expiry, actor.zenn_username, actor.qiita_username, actor.at_coder_username, actor.paiza_rank, actor.skills_languages, actor.skills_frameworks, actor.onboarding_completed, actor.email_weekly_report, actor.email_language, actor.created_at, actor.updated_at,
    posts.id AS post_id_2,
    posts.user_id AS post_user_id,
    posts.title AS post_title,
    posts.content AS post_content,
    posts.image_urls AS post_image_urls,
    posts.is_draft AS post_is_draft,
    posts.like_count AS post_like_count,
    posts.comment_count AS post_comment_count,
    (SELECT COUNT(*) FROM bookmarks WHERE bookmarks.post_id = posts.id) AS post_bookmark_count,
    posts.view_count AS post_view_count,
    posts.estimated_read_time AS post_estimated_read_time,
    posts.scheduled_at AS post_scheduled_at,
    posts.created_at AS post_created_at,
    posts.updated_at AS post_updated_at,
    questions.id AS question_id_2,
    questions.user_id AS question_user_id,
    questions.title AS question_title,
    questions.body AS question_body,
    questions.tags AS question_tags,
    questions.vote_count AS question_vote_count,
    questions.answer_count AS question_answer_count,
    questions.is_solved AS question_is_solved,
    questions.created_at AS question_created_at,
    questions.updated_at AS question_updated_at
FROM notifications
JOIN users actor ON actor.id = notifications.actor_id
LEFT JOIN posts ON posts.id = notifications.post_id
LEFT JOIN questions ON questions.id = notifications.question_id
WHERE notifications.user_id = $1
    AND ($4::text IS NULL OR notifications.type = $4)
ORDER BY notifications.created_at DESC
LIMIT $2 OFFSET $3
`

type FindNotificationsByUserIDParams struct {
	UserID           int64
	Limit            int32
	Offset           int32
	NotificationType *string
}

type FindNotificationsByUserIDRow struct {
	Notification          Notification
	User                  User
	PostID2               *int64
	PostUserID            *int64
	PostTitle             *string
	PostContent           *string
	PostImageUrls         *string
	PostIsDraft           *bool
	PostLikeCount         *int64
	PostCommentCount      *int64
	PostBookmarkCount     int64
	PostViewCount         *int64
	PostEstimatedReadTime *int64
	PostScheduledAt       pgtype.Timestamptz
	PostCreatedAt         pgtype.Timestamptz
	PostUpdatedAt         pgtype.Timestamptz
	QuestionID2           *int64
	QuestionUserID        *int64
	QuestionTitle         *string
	QuestionBody          *string
	QuestionTags          *string
	QuestionVoteCount     *int64
	QuestionAnswerCount   *int64
	QuestionIsSolved      *bool
	QuestionCreatedAt     pgtype.Timestamptz
	QuestionUpdatedAt     pgtype.Timestamptz
}

// GORMのPreload("Actor").Preload("Post").Preload("Question")に相当。
// actor_idはNOT NULLのためINNER JOINでよいが、post_id/question_idはNULL許容のためLEFT JOIN。
// LEFT JOIN側のpost/questionはsqlc.embedを使わず個別カラム選択にすることで、
// テーブル自体のスキーマではなくJOINコンテキストからNULL許容性を正しく推論させる。
func (q *Queries) FindNotificationsByUserID(ctx context.Context, arg FindNotificationsByUserIDParams) ([]FindNotificationsByUserIDRow, error) {
	rows, err := q.db.Query(ctx, findNotificationsByUserID,
		arg.UserID,
		arg.Limit,
		arg.Offset,
		arg.NotificationType,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []FindNotificationsByUserIDRow
	for rows.Next() {
		var i FindNotificationsByUserIDRow
		if err := rows.Scan(
			&i.Notification.ID,
			&i.Notification.UserID,
			&i.Notification.Type,
			&i.Notification.ActorID,
			&i.Notification.PostID,
			&i.Notification.QuestionID,
			&i.Notification.BadgeID,
			&i.Notification.Read,
			&i.Notification.CreatedAt,
			&i.User.ID,
			&i.User.Username,
			&i.User.Name,
			&i.User.Email,
			&i.User.Password,
			&i.User.AvatarUrl,
			&i.User.Bio,
			&i.User.GitHubID,
			&i.User.GitHubUsername,
			&i.User.GitHubToken,
			&i.User.GitHubConnected,
			&i.User.SpotifyConnected,
			&i.User.SpotifyToken,
			&i.User.SpotifyRefreshToken,
			&i.User.SpotifyTokenExpiry,
			&i.User.ZennUsername,
			&i.User.QiitaUsername,
			&i.User.AtCoderUsername,
			&i.User.PaizaRank,
			&i.User.SkillsLanguages,
			&i.User.SkillsFrameworks,
			&i.User.OnboardingCompleted,
			&i.User.EmailWeeklyReport,
			&i.User.EmailLanguage,
			&i.User.CreatedAt,
			&i.User.UpdatedAt,
			&i.PostID2,
			&i.PostUserID,
			&i.PostTitle,
			&i.PostContent,
			&i.PostImageUrls,
			&i.PostIsDraft,
			&i.PostLikeCount,
			&i.PostCommentCount,
			&i.PostBookmarkCount,
			&i.PostViewCount,
			&i.PostEstimatedReadTime,
			&i.PostScheduledAt,
			&i.PostCreatedAt,
			&i.PostUpdatedAt,
			&i.QuestionID2,
			&i.QuestionUserID,
			&i.QuestionTitle,
			&i.QuestionBody,
			&i.QuestionTags,
			&i.QuestionVoteCount,
			&i.QuestionAnswerCount,
			&i.QuestionIsSolved,
			&i.QuestionCreatedAt,
			&i.QuestionUpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markAllNotificationsAsRead = `-- name: MarkAllNotificationsAsRead :exec
UPDATE notifications SET read = true WHERE user_id = $1 AND read = false
`

func (q *Queries) MarkAllNotificationsAsRead(ctx context.Context, userID int64) error {
	_, err := q.db.Exec(ctx, markAllNotificationsAsRead, userID)
	return err
}

const markNotificationAsRead = `-- name: MarkNotificationAsRead :exec
UPDATE notifications SET read = true WHERE id = $1 AND user_id = $2
`

type MarkNotificationAsReadParams struct {
	ID     int64
	UserID int64
}

func (q *Queries) MarkNotificationAsRead(ctx context.Context, arg MarkNotificationAsReadParams) error {
	_, err := q.db.Exec(ctx, markNotificationAsRead, arg.ID, arg.UserID)
	return err
}
