// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: notification_verb.sql

package sqlcgen

import (
	"context"
)

const seedNotificationVerbs = `-- name: SeedNotificationVerbs :exec
INSERT INTO notification_verbs (code)
SELECT unnest($1::text[])
ON CONFLICT (code) DO NOTHING
`

// notifications.typeのFK制約（fk_notifications_type、DEVSYNC-159）を満たすため、
// アプリ起動時に既知の通知種別コードをまとめて登録する（冪等。既存分はスキップ）。
func (q *Queries) SeedNotificationVerbs(ctx context.Context, dollar_1 []string) error {
	_, err := q.db.Exec(ctx, seedNotificationVerbs, dollar_1)
	return err
}
