// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: password_reset_token.sql

package sqlcgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createPasswordResetToken = `-- name: CreatePasswordResetToken :one
INSERT INTO password_reset_tokens (user_id, token, expires_at, used, created_at)
VALUES ($1, $2, $3, $4, now())
RETURNING id, user_id, token, expires_at, used, created_at
`

type CreatePasswordResetTokenParams struct {
	UserID    int64
	Token     string
	ExpiresAt pgtype.Timestamptz
	Used      bool
}

func (q *Queries) CreatePasswordResetToken(ctx context.Context, arg CreatePasswordResetTokenParams) (PasswordResetToken, error) {
	row := q.db.QueryRow(ctx, createPasswordResetToken,
		arg.UserID,
		arg.Token,
		arg.ExpiresAt,
		arg.Used,
	)
	var i PasswordResetToken
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Token,
		&i.ExpiresAt,
		&i.Used,
		&i.CreatedAt,
	)
	return i, err
}

const getPasswordResetTokenByToken = `-- name: GetPasswordResetTokenByToken :one
SELECT id, user_id, token, expires_at, used, created_at FROM password_reset_tokens
WHERE token = $1
`

func (q *Queries) GetPasswordResetTokenByToken(ctx context.Context, token string) (PasswordResetToken, error) {
	row := q.db.QueryRow(ctx, getPasswordResetTokenByToken, token)
	var i PasswordResetToken
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Token,
		&i.ExpiresAt,
		&i.Used,
		&i.CreatedAt,
	)
	return i, err
}

const invalidateUserPasswordResetTokens = `-- name: InvalidateUserPasswordResetTokens :exec
UPDATE password_reset_tokens
SET used = true
WHERE user_id = $1 AND used = false
`

func (q *Queries) InvalidateUserPasswordResetTokens(ctx context.Context, userID int64) error {
	_, err := q.db.Exec(ctx, invalidateUserPasswordResetTokens, userID)
	return err
}

const markPasswordResetTokenAsUsed = `-- name: MarkPasswordResetTokenAsUsed :exec
UPDATE password_reset_tokens
SET used = true
WHERE id = $1
`

func (q *Queries) MarkPasswordResetTokenAsUsed(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, markPasswordResetTokenAsUsed, id)
	return err
}
