// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: post_view.sql

package sqlcgen

import (
	"context"
)

const countPostViewsByPost = `-- name: CountPostViewsByPost :one
SELECT COUNT(*) FROM post_views WHERE post_views.post_id = $1
`

func (q *Queries) CountPostViewsByPost(ctx context.Context, postID int64) (int64, error) {
	row := q.db.QueryRow(ctx, countPostViewsByPost, postID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createPostView = `-- name: CreatePostView :execrows
WITH inserted AS (
    INSERT INTO post_views (user_id, post_id, created_at)
    VALUES ($1, $2, now())
    ON CONFLICT DO NOTHING
    RETURNING post_views.post_id
)
INSERT INTO post_metrics (post_id, view_count)
SELECT inserted.post_id, 1 FROM inserted
ON CONFLICT (post_id) DO UPDATE SET view_count = post_metrics.view_count + 1
`

type CreatePostViewParams struct {
	UserID int64
	PostID int64
}

// GORMの clause.OnConflict{DoNothing: true} に相当。post_viewsへの記録と
// post_metrics.view_countの加算を同一SQL文で行う（DEVSYNC-159）。既に閲覧済み
// （ON CONFLICT DO NOTHINGでinsertedが0行）のときはpost_metricsも更新されず、
// rowsAffectedは従来どおり「実際に新規閲覧として記録できたか」を表す。
func (q *Queries) CreatePostView(ctx context.Context, arg CreatePostViewParams) (int64, error) {
	result, err := q.db.Exec(ctx, createPostView, arg.UserID, arg.PostID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const listMostViewedPosts = `-- name: ListMostViewedPosts :many
SELECT post_views.post_id, COUNT(*)::bigint AS view_count FROM post_views
GROUP BY post_views.post_id
ORDER BY view_count DESC
LIMIT $1
`

type ListMostViewedPostsRow struct {
	PostID    int64
	ViewCount int64
}

func (q *Queries) ListMostViewedPosts(ctx context.Context, limit int32) ([]ListMostViewedPostsRow, error) {
	rows, err := q.db.Query(ctx, listMostViewedPosts, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListMostViewedPostsRow
	for rows.Next() {
		var i ListMostViewedPostsRow
		if err := rows.Scan(&i.PostID, &i.ViewCount); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
