// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: post_metrics.sql

package sqlcgen

import (
	"context"
)

const decrementPostCommentMetric = `-- name: DecrementPostCommentMetric :exec
INSERT INTO post_metrics (post_id, comment_count) VALUES ($1, 0)
ON CONFLICT (post_id) DO UPDATE SET comment_count = GREATEST(post_metrics.comment_count - 1, 0)
`

func (q *Queries) DecrementPostCommentMetric(ctx context.Context, postID int64) error {
	_, err := q.db.Exec(ctx, decrementPostCommentMetric, postID)
	return err
}

const decrementPostLikeMetric = `-- name: DecrementPostLikeMetric :exec
INSERT INTO post_metrics (post_id, like_count) VALUES ($1, 0)
ON CONFLICT (post_id) DO UPDATE SET like_count = GREATEST(post_metrics.like_count - 1, 0)
`

// 0未満にはしない。post_metrics行がまだ無い場合（理論上は起こらないが防御的に）は
// 0のまま新規作成する。
func (q *Queries) DecrementPostLikeMetric(ctx context.Context, postID int64) error {
	_, err := q.db.Exec(ctx, decrementPostLikeMetric, postID)
	return err
}

const getPostMetricsByPostIDs = `-- name: GetPostMetricsByPostIDs :many
SELECT post_id, like_count, comment_count, view_count
FROM post_metrics
WHERE post_id = ANY($1::bigint[])
`

// 投稿一覧へlike_count/comment_count/view_countを付与するためのまとめ取り。
// 1件もいいね/コメント/閲覧が無い投稿はpost_metrics行が存在しない（遅延生成）ため、
// この結果に現れない投稿はGo側で0扱いにする（attachMetricsToPosts参照）。
func (q *Queries) GetPostMetricsByPostIDs(ctx context.Context, dollar_1 []int64) ([]PostMetric, error) {
	rows, err := q.db.Query(ctx, getPostMetricsByPostIDs, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PostMetric
	for rows.Next() {
		var i PostMetric
		if err := rows.Scan(
			&i.PostID,
			&i.LikeCount,
			&i.CommentCount,
			&i.ViewCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const incrementPostCommentMetric = `-- name: IncrementPostCommentMetric :exec
INSERT INTO post_metrics (post_id, comment_count) VALUES ($1, 1)
ON CONFLICT (post_id) DO UPDATE SET comment_count = post_metrics.comment_count + 1
`

func (q *Queries) IncrementPostCommentMetric(ctx context.Context, postID int64) error {
	_, err := q.db.Exec(ctx, incrementPostCommentMetric, postID)
	return err
}

const incrementPostLikeMetric = `-- name: IncrementPostLikeMetric :exec
INSERT INTO post_metrics (post_id, like_count) VALUES ($1, 1)
ON CONFLICT (post_id) DO UPDATE SET like_count = post_metrics.like_count + 1
`

// likesへのINSERTと同じ呼び出し元から同一トランザクション相当で呼ぶ。post_metrics行が
// 無ければ1から作る（遅延生成）。
func (q *Queries) IncrementPostLikeMetric(ctx context.Context, postID int64) error {
	_, err := q.db.Exec(ctx, incrementPostLikeMetric, postID)
	return err
}

const incrementPostViewMetric = `-- name: IncrementPostViewMetric :exec
INSERT INTO post_metrics (post_id, view_count) VALUES ($1, 1)
ON CONFLICT (post_id) DO UPDATE SET view_count = post_metrics.view_count + 1
`

func (q *Queries) IncrementPostViewMetric(ctx context.Context, postID int64) error {
	_, err := q.db.Exec(ctx, incrementPostViewMetric, postID)
	return err
}

const reconcileAllPostMetrics = `-- name: ReconcileAllPostMetrics :exec
INSERT INTO post_metrics (post_id, like_count, comment_count, view_count)
SELECT
    p.id,
    COALESCE(l.cnt, 0),
    COALESCE(c.cnt, 0),
    COALESCE(v.cnt, 0)
FROM posts p
LEFT JOIN (SELECT post_id, COUNT(*) AS cnt FROM post_reactions WHERE kind = 'like' GROUP BY post_id) l ON l.post_id = p.id
LEFT JOIN (SELECT post_id, COUNT(*) AS cnt FROM comments GROUP BY post_id) c ON c.post_id = p.id
LEFT JOIN (SELECT post_id, COUNT(*) AS cnt FROM post_reactions WHERE kind = 'view' GROUP BY post_id) v ON v.post_id = p.id
ON CONFLICT (post_id) DO UPDATE SET
    like_count = EXCLUDED.like_count,
    comment_count = EXCLUDED.comment_count,
    view_count = EXCLUDED.view_count
`

// 夜次reconcileジョブ本体。post_reactions(kind='like'/'view')/commentsの実件数から
// post_metricsを全件まとめて補正する。CASCADE削除等でIncrement/Decrementを経由しない
// 変化を吸収する。1件も無いカウンタは0で確定させる（COALESCE）。
func (q *Queries) ReconcileAllPostMetrics(ctx context.Context) error {
	_, err := q.db.Exec(ctx, reconcileAllPostMetrics)
	return err
}
