// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: post_reaction.sql

package sqlcgen

import (
	"context"
)

const createReaction = `-- name: CreateReaction :exec
INSERT INTO reactions (user_id, post_id, emoji, created_at) VALUES ($1, $2, $3, now())
`

type CreateReactionParams struct {
	UserID int64
	PostID int64
	Emoji  string
}

func (q *Queries) CreateReaction(ctx context.Context, arg CreateReactionParams) error {
	_, err := q.db.Exec(ctx, createReaction, arg.UserID, arg.PostID, arg.Emoji)
	return err
}

const deleteReaction = `-- name: DeleteReaction :exec
DELETE FROM reactions WHERE user_id = $1 AND post_id = $2 AND emoji = $3
`

type DeleteReactionParams struct {
	UserID int64
	PostID int64
	Emoji  string
}

func (q *Queries) DeleteReaction(ctx context.Context, arg DeleteReactionParams) error {
	_, err := q.db.Exec(ctx, deleteReaction, arg.UserID, arg.PostID, arg.Emoji)
	return err
}

const getPostAuthorID = `-- name: GetPostAuthorID :one
SELECT user_id FROM posts WHERE id = $1
`

func (q *Queries) GetPostAuthorID(ctx context.Context, id int64) (int64, error) {
	row := q.db.QueryRow(ctx, getPostAuthorID, id)
	var user_id int64
	err := row.Scan(&user_id)
	return user_id, err
}

const listReactionCountsByPost = `-- name: ListReactionCountsByPost :many
SELECT emoji, COUNT(*)::bigint AS count FROM reactions
WHERE post_id = $1
GROUP BY emoji
ORDER BY count DESC
`

type ListReactionCountsByPostRow struct {
	Emoji string
	Count int64
}

func (q *Queries) ListReactionCountsByPost(ctx context.Context, postID int64) ([]ListReactionCountsByPostRow, error) {
	rows, err := q.db.Query(ctx, listReactionCountsByPost, postID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListReactionCountsByPostRow
	for rows.Next() {
		var i ListReactionCountsByPostRow
		if err := rows.Scan(&i.Emoji, &i.Count); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listReactionCountsByPosts = `-- name: ListReactionCountsByPosts :many
SELECT post_id, emoji, COUNT(*)::bigint AS count FROM reactions
WHERE post_id = ANY($1::bigint[])
GROUP BY post_id, emoji
ORDER BY post_id, count DESC
`

type ListReactionCountsByPostsRow struct {
	PostID int64
	Emoji  string
	Count  int64
}

func (q *Queries) ListReactionCountsByPosts(ctx context.Context, dollar_1 []int64) ([]ListReactionCountsByPostsRow, error) {
	rows, err := q.db.Query(ctx, listReactionCountsByPosts, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListReactionCountsByPostsRow
	for rows.Next() {
		var i ListReactionCountsByPostsRow
		if err := rows.Scan(&i.PostID, &i.Emoji, &i.Count); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUserReactionEmojisByPost = `-- name: ListUserReactionEmojisByPost :many
SELECT emoji FROM reactions WHERE user_id = $1 AND post_id = $2
`

type ListUserReactionEmojisByPostParams struct {
	UserID int64
	PostID int64
}

func (q *Queries) ListUserReactionEmojisByPost(ctx context.Context, arg ListUserReactionEmojisByPostParams) ([]string, error) {
	rows, err := q.db.Query(ctx, listUserReactionEmojisByPost, arg.UserID, arg.PostID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var emoji string
		if err := rows.Scan(&emoji); err != nil {
			return nil, err
		}
		items = append(items, emoji)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUserReactionsByPosts = `-- name: ListUserReactionsByPosts :many
SELECT post_id, emoji FROM reactions
WHERE user_id = $1 AND post_id = ANY($2::bigint[])
`

type ListUserReactionsByPostsParams struct {
	UserID  int64
	Column2 []int64
}

type ListUserReactionsByPostsRow struct {
	PostID int64
	Emoji  string
}

func (q *Queries) ListUserReactionsByPosts(ctx context.Context, arg ListUserReactionsByPostsParams) ([]ListUserReactionsByPostsRow, error) {
	rows, err := q.db.Query(ctx, listUserReactionsByPosts, arg.UserID, arg.Column2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListUserReactionsByPostsRow
	for rows.Next() {
		var i ListUserReactionsByPostsRow
		if err := rows.Scan(&i.PostID, &i.Emoji); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
