// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: post_template.sql

package sqlcgen

import (
	"context"
)

const countPostTemplatesByUserID = `-- name: CountPostTemplatesByUserID :one
SELECT count(*) FROM post_templates
WHERE user_id = $1
`

func (q *Queries) CountPostTemplatesByUserID(ctx context.Context, userID int64) (int64, error) {
	row := q.db.QueryRow(ctx, countPostTemplatesByUserID, userID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createPostTemplate = `-- name: CreatePostTemplate :one
INSERT INTO post_templates (user_id, name, title_template, content_template, created_at, updated_at)
VALUES ($1, $2, $3, $4, now(), now())
RETURNING id, user_id, name, title_template, content_template, created_at, updated_at
`

type CreatePostTemplateParams struct {
	UserID          int64
	Name            string
	TitleTemplate   *string
	ContentTemplate string
}

func (q *Queries) CreatePostTemplate(ctx context.Context, arg CreatePostTemplateParams) (PostTemplate, error) {
	row := q.db.QueryRow(ctx, createPostTemplate,
		arg.UserID,
		arg.Name,
		arg.TitleTemplate,
		arg.ContentTemplate,
	)
	var i PostTemplate
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.TitleTemplate,
		&i.ContentTemplate,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deletePostTemplate = `-- name: DeletePostTemplate :exec
DELETE FROM post_templates
WHERE id = $1
`

func (q *Queries) DeletePostTemplate(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, deletePostTemplate, id)
	return err
}

const getPostTemplateByID = `-- name: GetPostTemplateByID :one
SELECT id, user_id, name, title_template, content_template, created_at, updated_at FROM post_templates
WHERE id = $1
`

func (q *Queries) GetPostTemplateByID(ctx context.Context, id int64) (PostTemplate, error) {
	row := q.db.QueryRow(ctx, getPostTemplateByID, id)
	var i PostTemplate
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.TitleTemplate,
		&i.ContentTemplate,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listPostTemplatesByUserID = `-- name: ListPostTemplatesByUserID :many
SELECT id, user_id, name, title_template, content_template, created_at, updated_at FROM post_templates
WHERE user_id = $1
ORDER BY created_at DESC
LIMIT $2 OFFSET $3
`

type ListPostTemplatesByUserIDParams struct {
	UserID int64
	Limit  int32
	Offset int32
}

func (q *Queries) ListPostTemplatesByUserID(ctx context.Context, arg ListPostTemplatesByUserIDParams) ([]PostTemplate, error) {
	rows, err := q.db.Query(ctx, listPostTemplatesByUserID, arg.UserID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PostTemplate
	for rows.Next() {
		var i PostTemplate
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Name,
			&i.TitleTemplate,
			&i.ContentTemplate,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updatePostTemplate = `-- name: UpdatePostTemplate :one
UPDATE post_templates
SET name = $2,
    title_template = $3,
    content_template = $4,
    updated_at = now()
WHERE id = $1
RETURNING id, user_id, name, title_template, content_template, created_at, updated_at
`

type UpdatePostTemplateParams struct {
	ID              int64
	Name            string
	TitleTemplate   *string
	ContentTemplate string
}

func (q *Queries) UpdatePostTemplate(ctx context.Context, arg UpdatePostTemplateParams) (PostTemplate, error) {
	row := q.db.QueryRow(ctx, updatePostTemplate,
		arg.ID,
		arg.Name,
		arg.TitleTemplate,
		arg.ContentTemplate,
	)
	var i PostTemplate
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.TitleTemplate,
		&i.ContentTemplate,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
