// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: post.sql

package sqlcgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countPublicPosts = `-- name: CountPublicPosts :one
SELECT COUNT(*) FROM posts WHERE is_draft = false
`

func (q *Queries) CountPublicPosts(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countPublicPosts)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countScheduledPostsByUser = `-- name: CountScheduledPostsByUser :one
SELECT COUNT(*) FROM posts WHERE user_id = $1 AND is_draft = true AND scheduled_at IS NOT NULL
`

func (q *Queries) CountScheduledPostsByUser(ctx context.Context, userID int64) (int64, error) {
	row := q.db.QueryRow(ctx, countScheduledPostsByUser, userID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createPost = `-- name: CreatePost :one
INSERT INTO posts (
    user_id, title, content, image_urls, is_draft, like_count, comment_count,
    bookmark_count, view_count, estimated_read_time, scheduled_at, created_at, updated_at
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, now(), now()
) RETURNING id, user_id, title, content, image_urls, is_draft, like_count, comment_count, bookmark_count, view_count, estimated_read_time, scheduled_at, created_at, updated_at
`

type CreatePostParams struct {
	UserID            int64
	Title             string
	Content           string
	ImageUrls         *string
	IsDraft           *bool
	LikeCount         *int64
	CommentCount      *int64
	BookmarkCount     *int64
	ViewCount         *int64
	EstimatedReadTime *int64
	ScheduledAt       pgtype.Timestamptz
}

func (q *Queries) CreatePost(ctx context.Context, arg CreatePostParams) (Post, error) {
	row := q.db.QueryRow(ctx, createPost,
		arg.UserID,
		arg.Title,
		arg.Content,
		arg.ImageUrls,
		arg.IsDraft,
		arg.LikeCount,
		arg.CommentCount,
		arg.BookmarkCount,
		arg.ViewCount,
		arg.EstimatedReadTime,
		arg.ScheduledAt,
	)
	var i Post
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Title,
		&i.Content,
		&i.ImageUrls,
		&i.IsDraft,
		&i.LikeCount,
		&i.CommentCount,
		&i.BookmarkCount,
		&i.ViewCount,
		&i.EstimatedReadTime,
		&i.ScheduledAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deletePost = `-- name: DeletePost :exec
DELETE FROM posts WHERE id = $1
`

func (q *Queries) DeletePost(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, deletePost, id)
	return err
}

const listDraftPostsByUserWithUser = `-- name: ListDraftPostsByUserWithUser :many
SELECT posts.id, posts.user_id, posts.title, posts.content, posts.image_urls, posts.is_draft, posts.like_count, posts.comment_count, posts.bookmark_count, posts.view_count, posts.estimated_read_time, posts.scheduled_at, posts.created_at, posts.updated_at, users.id, users.username, users.name, users.email, users.password, users.avatar_url, users.bio, users.git_hub_id, users.git_hub_username, users.git_hub_token, users.git_hub_connected, users.spotify_connected, users.spotify_token, users.spotify_refresh_token, users.spotify_token_expiry, users.zenn_username, users.qiita_username, users.at_coder_username, users.paiza_rank, users.skills_languages, users.skills_frameworks, users.onboarding_completed, users.email_weekly_report, users.email_language, users.created_at, users.updated_at
FROM posts
JOIN users ON users.id = posts.user_id
WHERE posts.user_id = $1 AND posts.is_draft = true
ORDER BY posts.updated_at DESC
`

type ListDraftPostsByUserWithUserRow struct {
	Post Post
	User User
}

func (q *Queries) ListDraftPostsByUserWithUser(ctx context.Context, userID int64) ([]ListDraftPostsByUserWithUserRow, error) {
	rows, err := q.db.Query(ctx, listDraftPostsByUserWithUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListDraftPostsByUserWithUserRow
	for rows.Next() {
		var i ListDraftPostsByUserWithUserRow
		if err := rows.Scan(
			&i.Post.ID,
			&i.Post.UserID,
			&i.Post.Title,
			&i.Post.Content,
			&i.Post.ImageUrls,
			&i.Post.IsDraft,
			&i.Post.LikeCount,
			&i.Post.CommentCount,
			&i.Post.BookmarkCount,
			&i.Post.ViewCount,
			&i.Post.EstimatedReadTime,
			&i.Post.ScheduledAt,
			&i.Post.CreatedAt,
			&i.Post.UpdatedAt,
			&i.User.ID,
			&i.User.Username,
			&i.User.Name,
			&i.User.Email,
			&i.User.Password,
			&i.User.AvatarUrl,
			&i.User.Bio,
			&i.User.GitHubID,
			&i.User.GitHubUsername,
			&i.User.GitHubToken,
			&i.User.GitHubConnected,
			&i.User.SpotifyConnected,
			&i.User.SpotifyToken,
			&i.User.SpotifyRefreshToken,
			&i.User.SpotifyTokenExpiry,
			&i.User.ZennUsername,
			&i.User.QiitaUsername,
			&i.User.AtCoderUsername,
			&i.User.PaizaRank,
			&i.User.SkillsLanguages,
			&i.User.SkillsFrameworks,
			&i.User.OnboardingCompleted,
			&i.User.EmailWeeklyReport,
			&i.User.EmailLanguage,
			&i.User.CreatedAt,
			&i.User.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPublicPostsWithUser = `-- name: ListPublicPostsWithUser :many
SELECT posts.id, posts.user_id, posts.title, posts.content, posts.image_urls, posts.is_draft, posts.like_count, posts.comment_count, posts.bookmark_count, posts.view_count, posts.estimated_read_time, posts.scheduled_at, posts.created_at, posts.updated_at, users.id, users.username, users.name, users.email, users.password, users.avatar_url, users.bio, users.git_hub_id, users.git_hub_username, users.git_hub_token, users.git_hub_connected, users.spotify_connected, users.spotify_token, users.spotify_refresh_token, users.spotify_token_expiry, users.zenn_username, users.qiita_username, users.at_coder_username, users.paiza_rank, users.skills_languages, users.skills_frameworks, users.onboarding_completed, users.email_weekly_report, users.email_language, users.created_at, users.updated_at
FROM posts
JOIN users ON users.id = posts.user_id
WHERE posts.is_draft = false
ORDER BY posts.created_at DESC
LIMIT $1 OFFSET $2
`

type ListPublicPostsWithUserParams struct {
	Limit  int32
	Offset int32
}

type ListPublicPostsWithUserRow struct {
	Post Post
	User User
}

// GORMのPreload("User")に相当（CodeSnippetsは別途post_bookmark.sqlのListCodeSnippetsByPostIDsで取得する）。
// user_idはNOT NULLのためINNER JOINでよい。
func (q *Queries) ListPublicPostsWithUser(ctx context.Context, arg ListPublicPostsWithUserParams) ([]ListPublicPostsWithUserRow, error) {
	rows, err := q.db.Query(ctx, listPublicPostsWithUser, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListPublicPostsWithUserRow
	for rows.Next() {
		var i ListPublicPostsWithUserRow
		if err := rows.Scan(
			&i.Post.ID,
			&i.Post.UserID,
			&i.Post.Title,
			&i.Post.Content,
			&i.Post.ImageUrls,
			&i.Post.IsDraft,
			&i.Post.LikeCount,
			&i.Post.CommentCount,
			&i.Post.BookmarkCount,
			&i.Post.ViewCount,
			&i.Post.EstimatedReadTime,
			&i.Post.ScheduledAt,
			&i.Post.CreatedAt,
			&i.Post.UpdatedAt,
			&i.User.ID,
			&i.User.Username,
			&i.User.Name,
			&i.User.Email,
			&i.User.Password,
			&i.User.AvatarUrl,
			&i.User.Bio,
			&i.User.GitHubID,
			&i.User.GitHubUsername,
			&i.User.GitHubToken,
			&i.User.GitHubConnected,
			&i.User.SpotifyConnected,
			&i.User.SpotifyToken,
			&i.User.SpotifyRefreshToken,
			&i.User.SpotifyTokenExpiry,
			&i.User.ZennUsername,
			&i.User.QiitaUsername,
			&i.User.AtCoderUsername,
			&i.User.PaizaRank,
			&i.User.SkillsLanguages,
			&i.User.SkillsFrameworks,
			&i.User.OnboardingCompleted,
			&i.User.EmailWeeklyReport,
			&i.User.EmailLanguage,
			&i.User.CreatedAt,
			&i.User.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPublishedPostsByUserWithUser = `-- name: ListPublishedPostsByUserWithUser :many
SELECT posts.id, posts.user_id, posts.title, posts.content, posts.image_urls, posts.is_draft, posts.like_count, posts.comment_count, posts.bookmark_count, posts.view_count, posts.estimated_read_time, posts.scheduled_at, posts.created_at, posts.updated_at, users.id, users.username, users.name, users.email, users.password, users.avatar_url, users.bio, users.git_hub_id, users.git_hub_username, users.git_hub_token, users.git_hub_connected, users.spotify_connected, users.spotify_token, users.spotify_refresh_token, users.spotify_token_expiry, users.zenn_username, users.qiita_username, users.at_coder_username, users.paiza_rank, users.skills_languages, users.skills_frameworks, users.onboarding_completed, users.email_weekly_report, users.email_language, users.created_at, users.updated_at
FROM posts
JOIN users ON users.id = posts.user_id
WHERE posts.user_id = $1 AND posts.is_draft = false
ORDER BY posts.created_at DESC
LIMIT $2 OFFSET $3
`

type ListPublishedPostsByUserWithUserParams struct {
	UserID int64
	Limit  int32
	Offset int32
}

type ListPublishedPostsByUserWithUserRow struct {
	Post Post
	User User
}

// GORMのPreload("User")に相当。user_idはNOT NULLのためINNER JOINでよい。
func (q *Queries) ListPublishedPostsByUserWithUser(ctx context.Context, arg ListPublishedPostsByUserWithUserParams) ([]ListPublishedPostsByUserWithUserRow, error) {
	rows, err := q.db.Query(ctx, listPublishedPostsByUserWithUser, arg.UserID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListPublishedPostsByUserWithUserRow
	for rows.Next() {
		var i ListPublishedPostsByUserWithUserRow
		if err := rows.Scan(
			&i.Post.ID,
			&i.Post.UserID,
			&i.Post.Title,
			&i.Post.Content,
			&i.Post.ImageUrls,
			&i.Post.IsDraft,
			&i.Post.LikeCount,
			&i.Post.CommentCount,
			&i.Post.BookmarkCount,
			&i.Post.ViewCount,
			&i.Post.EstimatedReadTime,
			&i.Post.ScheduledAt,
			&i.Post.CreatedAt,
			&i.Post.UpdatedAt,
			&i.User.ID,
			&i.User.Username,
			&i.User.Name,
			&i.User.Email,
			&i.User.Password,
			&i.User.AvatarUrl,
			&i.User.Bio,
			&i.User.GitHubID,
			&i.User.GitHubUsername,
			&i.User.GitHubToken,
			&i.User.GitHubConnected,
			&i.User.SpotifyConnected,
			&i.User.SpotifyToken,
			&i.User.SpotifyRefreshToken,
			&i.User.SpotifyTokenExpiry,
			&i.User.ZennUsername,
			&i.User.QiitaUsername,
			&i.User.AtCoderUsername,
			&i.User.PaizaRank,
			&i.User.SkillsLanguages,
			&i.User.SkillsFrameworks,
			&i.User.OnboardingCompleted,
			&i.User.EmailWeeklyReport,
			&i.User.EmailLanguage,
			&i.User.CreatedAt,
			&i.User.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listScheduledPostsByUserWithUser = `-- name: ListScheduledPostsByUserWithUser :many
SELECT posts.id, posts.user_id, posts.title, posts.content, posts.image_urls, posts.is_draft, posts.like_count, posts.comment_count, posts.bookmark_count, posts.view_count, posts.estimated_read_time, posts.scheduled_at, posts.created_at, posts.updated_at, users.id, users.username, users.name, users.email, users.password, users.avatar_url, users.bio, users.git_hub_id, users.git_hub_username, users.git_hub_token, users.git_hub_connected, users.spotify_connected, users.spotify_token, users.spotify_refresh_token, users.spotify_token_expiry, users.zenn_username, users.qiita_username, users.at_coder_username, users.paiza_rank, users.skills_languages, users.skills_frameworks, users.onboarding_completed, users.email_weekly_report, users.email_language, users.created_at, users.updated_at
FROM posts
JOIN users ON users.id = posts.user_id
WHERE posts.user_id = $1 AND posts.is_draft = true AND posts.scheduled_at IS NOT NULL
ORDER BY posts.scheduled_at ASC
`

type ListScheduledPostsByUserWithUserRow struct {
	Post Post
	User User
}

func (q *Queries) ListScheduledPostsByUserWithUser(ctx context.Context, userID int64) ([]ListScheduledPostsByUserWithUserRow, error) {
	rows, err := q.db.Query(ctx, listScheduledPostsByUserWithUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListScheduledPostsByUserWithUserRow
	for rows.Next() {
		var i ListScheduledPostsByUserWithUserRow
		if err := rows.Scan(
			&i.Post.ID,
			&i.Post.UserID,
			&i.Post.Title,
			&i.Post.Content,
			&i.Post.ImageUrls,
			&i.Post.IsDraft,
			&i.Post.LikeCount,
			&i.Post.CommentCount,
			&i.Post.BookmarkCount,
			&i.Post.ViewCount,
			&i.Post.EstimatedReadTime,
			&i.Post.ScheduledAt,
			&i.Post.CreatedAt,
			&i.Post.UpdatedAt,
			&i.User.ID,
			&i.User.Username,
			&i.User.Name,
			&i.User.Email,
			&i.User.Password,
			&i.User.AvatarUrl,
			&i.User.Bio,
			&i.User.GitHubID,
			&i.User.GitHubUsername,
			&i.User.GitHubToken,
			&i.User.GitHubConnected,
			&i.User.SpotifyConnected,
			&i.User.SpotifyToken,
			&i.User.SpotifyRefreshToken,
			&i.User.SpotifyTokenExpiry,
			&i.User.ZennUsername,
			&i.User.QiitaUsername,
			&i.User.AtCoderUsername,
			&i.User.PaizaRank,
			&i.User.SkillsLanguages,
			&i.User.SkillsFrameworks,
			&i.User.OnboardingCompleted,
			&i.User.EmailWeeklyReport,
			&i.User.EmailLanguage,
			&i.User.CreatedAt,
			&i.User.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTimelinePostsWithUser = `-- name: ListTimelinePostsWithUser :many
SELECT posts.id, posts.user_id, posts.title, posts.content, posts.image_urls, posts.is_draft, posts.like_count, posts.comment_count, posts.bookmark_count, posts.view_count, posts.estimated_read_time, posts.scheduled_at, posts.created_at, posts.updated_at, users.id, users.username, users.name, users.email, users.password, users.avatar_url, users.bio, users.git_hub_id, users.git_hub_username, users.git_hub_token, users.git_hub_connected, users.spotify_connected, users.spotify_token, users.spotify_refresh_token, users.spotify_token_expiry, users.zenn_username, users.qiita_username, users.at_coder_username, users.paiza_rank, users.skills_languages, users.skills_frameworks, users.onboarding_completed, users.email_weekly_report, users.email_language, users.created_at, users.updated_at
FROM posts
JOIN users ON users.id = posts.user_id
WHERE (posts.user_id IN (SELECT followee_id FROM follows WHERE follower_id = $1) OR posts.user_id = $1)
    AND posts.is_draft = false
ORDER BY posts.created_at DESC
LIMIT $2 OFFSET $3
`

type ListTimelinePostsWithUserParams struct {
	FollowerID int64
	Limit      int32
	Offset     int32
}

type ListTimelinePostsWithUserRow struct {
	Post Post
	User User
}

// フォロー中ユーザーと自分自身の公開済み投稿（移行前のGo実装のサブクエリをそのまま踏襲）。
func (q *Queries) ListTimelinePostsWithUser(ctx context.Context, arg ListTimelinePostsWithUserParams) ([]ListTimelinePostsWithUserRow, error) {
	rows, err := q.db.Query(ctx, listTimelinePostsWithUser, arg.FollowerID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListTimelinePostsWithUserRow
	for rows.Next() {
		var i ListTimelinePostsWithUserRow
		if err := rows.Scan(
			&i.Post.ID,
			&i.Post.UserID,
			&i.Post.Title,
			&i.Post.Content,
			&i.Post.ImageUrls,
			&i.Post.IsDraft,
			&i.Post.LikeCount,
			&i.Post.CommentCount,
			&i.Post.BookmarkCount,
			&i.Post.ViewCount,
			&i.Post.EstimatedReadTime,
			&i.Post.ScheduledAt,
			&i.Post.CreatedAt,
			&i.Post.UpdatedAt,
			&i.User.ID,
			&i.User.Username,
			&i.User.Name,
			&i.User.Email,
			&i.User.Password,
			&i.User.AvatarUrl,
			&i.User.Bio,
			&i.User.GitHubID,
			&i.User.GitHubUsername,
			&i.User.GitHubToken,
			&i.User.GitHubConnected,
			&i.User.SpotifyConnected,
			&i.User.SpotifyToken,
			&i.User.SpotifyRefreshToken,
			&i.User.SpotifyTokenExpiry,
			&i.User.ZennUsername,
			&i.User.QiitaUsername,
			&i.User.AtCoderUsername,
			&i.User.PaizaRank,
			&i.User.SkillsLanguages,
			&i.User.SkillsFrameworks,
			&i.User.OnboardingCompleted,
			&i.User.EmailWeeklyReport,
			&i.User.EmailLanguage,
			&i.User.CreatedAt,
			&i.User.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updatePost = `-- name: UpdatePost :one
UPDATE posts SET
    title = $2, content = $3, image_urls = $4, is_draft = $5,
    estimated_read_time = $6, scheduled_at = $7, updated_at = now()
WHERE id = $1
RETURNING id, user_id, title, content, image_urls, is_draft, like_count, comment_count, bookmark_count, view_count, estimated_read_time, scheduled_at, created_at, updated_at
`

type UpdatePostParams struct {
	ID                int64
	Title             string
	Content           string
	ImageUrls         *string
	IsDraft           *bool
	EstimatedReadTime *int64
	ScheduledAt       pgtype.Timestamptz
}

// GORMのSave（全カラム上書き）に相当。ただしlike_count/comment_count/bookmark_count/
// view_countは対象外（Increment/Decrement系の専用クエリだけが更新する）。
// ここに含めると、他リクエストによるカウンタ更新をこのUPDATEが読み取り時点の
// 古い値で上書きする「ロストアップデート」を起こす。
func (q *Queries) UpdatePost(ctx context.Context, arg UpdatePostParams) (Post, error) {
	row := q.db.QueryRow(ctx, updatePost,
		arg.ID,
		arg.Title,
		arg.Content,
		arg.ImageUrls,
		arg.IsDraft,
		arg.EstimatedReadTime,
		arg.ScheduledAt,
	)
	var i Post
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Title,
		&i.Content,
		&i.ImageUrls,
		&i.IsDraft,
		&i.LikeCount,
		&i.CommentCount,
		&i.BookmarkCount,
		&i.ViewCount,
		&i.EstimatedReadTime,
		&i.ScheduledAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
