// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: post_comment.sql

package sqlcgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createPostComment = `-- name: CreatePostComment :one
WITH inserted_comment AS (
    INSERT INTO comments (user_id, post_id, parent_id, content, like_count, is_hidden, created_at, updated_at)
    VALUES ($1, $2, $3, $4, 0, false, now(), now())
    RETURNING id, user_id, post_id, parent_id, content, like_count, is_hidden, created_at, updated_at
), metric_upsert AS (
    INSERT INTO post_metrics (post_id, comment_count)
    SELECT inserted_comment.post_id, 1 FROM inserted_comment
    ON CONFLICT (post_id) DO UPDATE SET comment_count = post_metrics.comment_count + 1
)
SELECT id, user_id, post_id, parent_id, content, like_count, is_hidden, created_at, updated_at FROM inserted_comment
`

type CreatePostCommentParams struct {
	UserID   int64
	PostID   int64
	ParentID *int64
	Content  string
}

type CreatePostCommentRow struct {
	ID        int64
	UserID    int64
	PostID    int64
	ParentID  *int64
	Content   string
	LikeCount *int64
	IsHidden  bool
	CreatedAt pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
}

// commentsへのINSERTとpost_metrics.comment_countの加算を同一SQL文で行う（DEVSYNC-159）。
func (q *Queries) CreatePostComment(ctx context.Context, arg CreatePostCommentParams) (CreatePostCommentRow, error) {
	row := q.db.QueryRow(ctx, createPostComment,
		arg.UserID,
		arg.PostID,
		arg.ParentID,
		arg.Content,
	)
	var i CreatePostCommentRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.PostID,
		&i.ParentID,
		&i.Content,
		&i.LikeCount,
		&i.IsHidden,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deletePostComment = `-- name: DeletePostComment :exec
WITH deleted AS (
    DELETE FROM comments WHERE comments.id = $1
    RETURNING comments.post_id
)
INSERT INTO post_metrics (post_id, comment_count)
SELECT deleted.post_id, 0 FROM deleted
ON CONFLICT (post_id) DO UPDATE SET comment_count = GREATEST(post_metrics.comment_count - 1, 0)
`

// commentsの削除とpost_metrics.comment_countの減算を同一SQL文で行う。
func (q *Queries) DeletePostComment(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, deletePostComment, id)
	return err
}

const listCommentRepliesByParentIDs = `-- name: ListCommentRepliesByParentIDs :many
SELECT comments.id, comments.user_id, comments.post_id, comments.parent_id, comments.content, comments.like_count, comments.is_hidden, comments.created_at, comments.updated_at, users.id, users.username, users.name, users.email, users.password, users.avatar_url, users.bio, users.git_hub_id, users.git_hub_username, users.git_hub_token, users.git_hub_connected, users.spotify_connected, users.spotify_token, users.spotify_refresh_token, users.spotify_token_expiry, users.zenn_username, users.qiita_username, users.at_coder_username, users.paiza_rank, users.skills_languages, users.skills_frameworks, users.onboarding_completed, users.email_weekly_report, users.email_language, users.created_at, users.updated_at
FROM comments
JOIN users ON users.id = comments.user_id
WHERE comments.parent_id = ANY($1::bigint[])
ORDER BY comments.created_at ASC
`

type ListCommentRepliesByParentIDsRow struct {
	Comment Comment
	User    User
}

// GORMのPreload("User")に相当（返信の取得）。ListReplies単体呼び出しと
// ListByPostIDのバッチ取得の両方で、親IDの配列（1件でも複数件でも）として再利用する。
func (q *Queries) ListCommentRepliesByParentIDs(ctx context.Context, parentIds []int64) ([]ListCommentRepliesByParentIDsRow, error) {
	rows, err := q.db.Query(ctx, listCommentRepliesByParentIDs, parentIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListCommentRepliesByParentIDsRow
	for rows.Next() {
		var i ListCommentRepliesByParentIDsRow
		if err := rows.Scan(
			&i.Comment.ID,
			&i.Comment.UserID,
			&i.Comment.PostID,
			&i.Comment.ParentID,
			&i.Comment.Content,
			&i.Comment.LikeCount,
			&i.Comment.IsHidden,
			&i.Comment.CreatedAt,
			&i.Comment.UpdatedAt,
			&i.User.ID,
			&i.User.Username,
			&i.User.Name,
			&i.User.Email,
			&i.User.Password,
			&i.User.AvatarUrl,
			&i.User.Bio,
			&i.User.GitHubID,
			&i.User.GitHubUsername,
			&i.User.GitHubToken,
			&i.User.GitHubConnected,
			&i.User.SpotifyConnected,
			&i.User.SpotifyToken,
			&i.User.SpotifyRefreshToken,
			&i.User.SpotifyTokenExpiry,
			&i.User.ZennUsername,
			&i.User.QiitaUsername,
			&i.User.AtCoderUsername,
			&i.User.PaizaRank,
			&i.User.SkillsLanguages,
			&i.User.SkillsFrameworks,
			&i.User.OnboardingCompleted,
			&i.User.EmailWeeklyReport,
			&i.User.EmailLanguage,
			&i.User.CreatedAt,
			&i.User.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTopLevelCommentsByPost = `-- name: ListTopLevelCommentsByPost :many
SELECT comments.id, comments.user_id, comments.post_id, comments.parent_id, comments.content, comments.like_count, comments.is_hidden, comments.created_at, comments.updated_at, users.id, users.username, users.name, users.email, users.password, users.avatar_url, users.bio, users.git_hub_id, users.git_hub_username, users.git_hub_token, users.git_hub_connected, users.spotify_connected, users.spotify_token, users.spotify_refresh_token, users.spotify_token_expiry, users.zenn_username, users.qiita_username, users.at_coder_username, users.paiza_rank, users.skills_languages, users.skills_frameworks, users.onboarding_completed, users.email_weekly_report, users.email_language, users.created_at, users.updated_at
FROM comments
JOIN users ON users.id = comments.user_id
WHERE comments.post_id = $1 AND comments.parent_id IS NULL
ORDER BY comments.created_at ASC
`

type ListTopLevelCommentsByPostRow struct {
	Comment Comment
	User    User
}

// GORMのPreload("User")に相当。user_idはNOT NULLのためINNER JOINでよい。
func (q *Queries) ListTopLevelCommentsByPost(ctx context.Context, postID int64) ([]ListTopLevelCommentsByPostRow, error) {
	rows, err := q.db.Query(ctx, listTopLevelCommentsByPost, postID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListTopLevelCommentsByPostRow
	for rows.Next() {
		var i ListTopLevelCommentsByPostRow
		if err := rows.Scan(
			&i.Comment.ID,
			&i.Comment.UserID,
			&i.Comment.PostID,
			&i.Comment.ParentID,
			&i.Comment.Content,
			&i.Comment.LikeCount,
			&i.Comment.IsHidden,
			&i.Comment.CreatedAt,
			&i.Comment.UpdatedAt,
			&i.User.ID,
			&i.User.Username,
			&i.User.Name,
			&i.User.Email,
			&i.User.Password,
			&i.User.AvatarUrl,
			&i.User.Bio,
			&i.User.GitHubID,
			&i.User.GitHubUsername,
			&i.User.GitHubToken,
			&i.User.GitHubConnected,
			&i.User.SpotifyConnected,
			&i.User.SpotifyToken,
			&i.User.SpotifyRefreshToken,
			&i.User.SpotifyTokenExpiry,
			&i.User.ZennUsername,
			&i.User.QiitaUsername,
			&i.User.AtCoderUsername,
			&i.User.PaizaRank,
			&i.User.SkillsLanguages,
			&i.User.SkillsFrameworks,
			&i.User.OnboardingCompleted,
			&i.User.EmailWeeklyReport,
			&i.User.EmailLanguage,
			&i.User.CreatedAt,
			&i.User.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updatePostComment = `-- name: UpdatePostComment :one
UPDATE comments SET content = $2, is_hidden = $3, updated_at = now()
WHERE comments.id = $1
RETURNING id, user_id, post_id, parent_id, content, like_count, is_hidden, created_at, updated_at
`

type UpdatePostCommentParams struct {
	ID       int64
	Content  string
	IsHidden bool
}

// GORMのSave（全カラム上書き）に相当。呼び出し側は必ずDBから読み込んだcommentの
// content/is_hiddenだけを変更してから呼ぶため、この2カラムの書き戻しで等価になる。
func (q *Queries) UpdatePostComment(ctx context.Context, arg UpdatePostCommentParams) (Comment, error) {
	row := q.db.QueryRow(ctx, updatePostComment, arg.ID, arg.Content, arg.IsHidden)
	var i Comment
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.PostID,
		&i.ParentID,
		&i.Content,
		&i.LikeCount,
		&i.IsHidden,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
