// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: post_series.sql

package sqlcgen

import (
	"context"
)

const countPostSeriesByUser = `-- name: CountPostSeriesByUser :one
SELECT COUNT(*) FROM post_series WHERE user_id = $1
`

func (q *Queries) CountPostSeriesByUser(ctx context.Context, userID int64) (int64, error) {
	row := q.db.QueryRow(ctx, countPostSeriesByUser, userID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countPostSeriesItemsBySeriesAndPost = `-- name: CountPostSeriesItemsBySeriesAndPost :one
SELECT COUNT(*) FROM post_series_items WHERE series_id = $1 AND post_id = $2
`

type CountPostSeriesItemsBySeriesAndPostParams struct {
	SeriesID int64
	PostID   int64
}

func (q *Queries) CountPostSeriesItemsBySeriesAndPost(ctx context.Context, arg CountPostSeriesItemsBySeriesAndPostParams) (int64, error) {
	row := q.db.QueryRow(ctx, countPostSeriesItemsBySeriesAndPost, arg.SeriesID, arg.PostID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createPostSeries = `-- name: CreatePostSeries :one
INSERT INTO post_series (user_id, title, description, created_at, updated_at)
VALUES ($1, $2, $3, now(), now())
RETURNING id, user_id, title, description, created_at, updated_at
`

type CreatePostSeriesParams struct {
	UserID      int64
	Title       string
	Description *string
}

func (q *Queries) CreatePostSeries(ctx context.Context, arg CreatePostSeriesParams) (PostSeries, error) {
	row := q.db.QueryRow(ctx, createPostSeries, arg.UserID, arg.Title, arg.Description)
	var i PostSeries
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Title,
		&i.Description,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createPostSeriesItem = `-- name: CreatePostSeriesItem :one
INSERT INTO post_series_items (series_id, post_id, order_index)
VALUES ($1, $2, $3)
RETURNING id, series_id, post_id, order_index
`

type CreatePostSeriesItemParams struct {
	SeriesID   int64
	PostID     int64
	OrderIndex int64
}

func (q *Queries) CreatePostSeriesItem(ctx context.Context, arg CreatePostSeriesItemParams) (PostSeriesItem, error) {
	row := q.db.QueryRow(ctx, createPostSeriesItem, arg.SeriesID, arg.PostID, arg.OrderIndex)
	var i PostSeriesItem
	err := row.Scan(
		&i.ID,
		&i.SeriesID,
		&i.PostID,
		&i.OrderIndex,
	)
	return i, err
}

const deletePostSeries = `-- name: DeletePostSeries :exec
DELETE FROM post_series WHERE id = $1
`

func (q *Queries) DeletePostSeries(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, deletePostSeries, id)
	return err
}

const deletePostSeriesItem = `-- name: DeletePostSeriesItem :exec
DELETE FROM post_series_items WHERE series_id = $1 AND post_id = $2
`

type DeletePostSeriesItemParams struct {
	SeriesID int64
	PostID   int64
}

func (q *Queries) DeletePostSeriesItem(ctx context.Context, arg DeletePostSeriesItemParams) error {
	_, err := q.db.Exec(ctx, deletePostSeriesItem, arg.SeriesID, arg.PostID)
	return err
}

const deletePostSeriesItemsBySeriesID = `-- name: DeletePostSeriesItemsBySeriesID :exec
DELETE FROM post_series_items WHERE series_id = $1
`

func (q *Queries) DeletePostSeriesItemsBySeriesID(ctx context.Context, seriesID int64) error {
	_, err := q.db.Exec(ctx, deletePostSeriesItemsBySeriesID, seriesID)
	return err
}

const getPostSeriesWithUserByID = `-- name: GetPostSeriesWithUserByID :one
SELECT post_series.id, post_series.user_id, post_series.title, post_series.description, post_series.created_at, post_series.updated_at, users.id, users.username, users.name, users.email, users.password, users.avatar_url, users.bio, users.git_hub_id, users.git_hub_username, users.git_hub_token, users.git_hub_connected, users.spotify_connected, users.spotify_token, users.spotify_refresh_token, users.spotify_token_expiry, users.zenn_username, users.qiita_username, users.at_coder_username, users.paiza_rank, users.skills_languages, users.skills_frameworks, users.onboarding_completed, users.email_weekly_report, users.email_language, users.created_at, users.updated_at
FROM post_series
JOIN users ON users.id = post_series.user_id
WHERE post_series.id = $1
`

type GetPostSeriesWithUserByIDRow struct {
	PostSeries PostSeries
	User       User
}

// GORMのPreload("User")に相当。user_idはNOT NULLのためINNER JOINでよい。
func (q *Queries) GetPostSeriesWithUserByID(ctx context.Context, id int64) (GetPostSeriesWithUserByIDRow, error) {
	row := q.db.QueryRow(ctx, getPostSeriesWithUserByID, id)
	var i GetPostSeriesWithUserByIDRow
	err := row.Scan(
		&i.PostSeries.ID,
		&i.PostSeries.UserID,
		&i.PostSeries.Title,
		&i.PostSeries.Description,
		&i.PostSeries.CreatedAt,
		&i.PostSeries.UpdatedAt,
		&i.User.ID,
		&i.User.Username,
		&i.User.Name,
		&i.User.Email,
		&i.User.Password,
		&i.User.AvatarUrl,
		&i.User.Bio,
		&i.User.GitHubID,
		&i.User.GitHubUsername,
		&i.User.GitHubToken,
		&i.User.GitHubConnected,
		&i.User.SpotifyConnected,
		&i.User.SpotifyToken,
		&i.User.SpotifyRefreshToken,
		&i.User.SpotifyTokenExpiry,
		&i.User.ZennUsername,
		&i.User.QiitaUsername,
		&i.User.AtCoderUsername,
		&i.User.PaizaRank,
		&i.User.SkillsLanguages,
		&i.User.SkillsFrameworks,
		&i.User.OnboardingCompleted,
		&i.User.EmailWeeklyReport,
		&i.User.EmailLanguage,
		&i.User.CreatedAt,
		&i.User.UpdatedAt,
	)
	return i, err
}

const listPostSeriesByUser = `-- name: ListPostSeriesByUser :many
SELECT id, user_id, title, description, created_at, updated_at FROM post_series
WHERE user_id = $1
ORDER BY created_at DESC
LIMIT $2 OFFSET $3
`

type ListPostSeriesByUserParams struct {
	UserID int64
	Limit  int32
	Offset int32
}

func (q *Queries) ListPostSeriesByUser(ctx context.Context, arg ListPostSeriesByUserParams) ([]PostSeries, error) {
	rows, err := q.db.Query(ctx, listPostSeriesByUser, arg.UserID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PostSeries
	for rows.Next() {
		var i PostSeries
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Title,
			&i.Description,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPostSeriesItemsWithPostBySeriesID = `-- name: ListPostSeriesItemsWithPostBySeriesID :many
SELECT post_series_items.id, post_series_items.series_id, post_series_items.post_id, post_series_items.order_index, posts.id, posts.user_id, posts.title, posts.content, posts.image_urls, posts.is_draft, posts.like_count, posts.comment_count, posts.view_count, posts.estimated_read_time, posts.scheduled_at, posts.created_at, posts.updated_at, users.id, users.username, users.name, users.email, users.password, users.avatar_url, users.bio, users.git_hub_id, users.git_hub_username, users.git_hub_token, users.git_hub_connected, users.spotify_connected, users.spotify_token, users.spotify_refresh_token, users.spotify_token_expiry, users.zenn_username, users.qiita_username, users.at_coder_username, users.paiza_rank, users.skills_languages, users.skills_frameworks, users.onboarding_completed, users.email_weekly_report, users.email_language, users.created_at, users.updated_at
FROM post_series_items
JOIN posts ON posts.id = post_series_items.post_id
JOIN users ON users.id = posts.user_id
WHERE post_series_items.series_id = $1
ORDER BY post_series_items.order_index ASC
`

type ListPostSeriesItemsWithPostBySeriesIDRow struct {
	PostSeriesItem PostSeriesItem
	Post           Post
	User           User
}

// GORMのPreload("Post").Preload("Post.User")に相当。post_idはNOT NULLのためINNER JOINでよい。
func (q *Queries) ListPostSeriesItemsWithPostBySeriesID(ctx context.Context, seriesID int64) ([]ListPostSeriesItemsWithPostBySeriesIDRow, error) {
	rows, err := q.db.Query(ctx, listPostSeriesItemsWithPostBySeriesID, seriesID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListPostSeriesItemsWithPostBySeriesIDRow
	for rows.Next() {
		var i ListPostSeriesItemsWithPostBySeriesIDRow
		if err := rows.Scan(
			&i.PostSeriesItem.ID,
			&i.PostSeriesItem.SeriesID,
			&i.PostSeriesItem.PostID,
			&i.PostSeriesItem.OrderIndex,
			&i.Post.ID,
			&i.Post.UserID,
			&i.Post.Title,
			&i.Post.Content,
			&i.Post.ImageUrls,
			&i.Post.IsDraft,
			&i.Post.LikeCount,
			&i.Post.CommentCount,
			&i.Post.ViewCount,
			&i.Post.EstimatedReadTime,
			&i.Post.ScheduledAt,
			&i.Post.CreatedAt,
			&i.Post.UpdatedAt,
			&i.User.ID,
			&i.User.Username,
			&i.User.Name,
			&i.User.Email,
			&i.User.Password,
			&i.User.AvatarUrl,
			&i.User.Bio,
			&i.User.GitHubID,
			&i.User.GitHubUsername,
			&i.User.GitHubToken,
			&i.User.GitHubConnected,
			&i.User.SpotifyConnected,
			&i.User.SpotifyToken,
			&i.User.SpotifyRefreshToken,
			&i.User.SpotifyTokenExpiry,
			&i.User.ZennUsername,
			&i.User.QiitaUsername,
			&i.User.AtCoderUsername,
			&i.User.PaizaRank,
			&i.User.SkillsLanguages,
			&i.User.SkillsFrameworks,
			&i.User.OnboardingCompleted,
			&i.User.EmailWeeklyReport,
			&i.User.EmailLanguage,
			&i.User.CreatedAt,
			&i.User.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updatePostSeries = `-- name: UpdatePostSeries :one
UPDATE post_series SET title = $2, description = $3, updated_at = now()
WHERE id = $1
RETURNING id, user_id, title, description, created_at, updated_at
`

type UpdatePostSeriesParams struct {
	ID          int64
	Title       string
	Description *string
}

// GORMのSave（全カラム上書き）に相当。
func (q *Queries) UpdatePostSeries(ctx context.Context, arg UpdatePostSeriesParams) (PostSeries, error) {
	row := q.db.QueryRow(ctx, updatePostSeries, arg.ID, arg.Title, arg.Description)
	var i PostSeries
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Title,
		&i.Description,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
