// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: post_tag.sql

package sqlcgen

import (
	"context"
)

const countPostsByTag = `-- name: CountPostsByTag :one
SELECT COUNT(*) FROM post_tags
JOIN posts ON posts.id = post_tags.post_id AND posts.is_draft = false
WHERE post_tags.tag = $1
`

// 下書きは除外する。
func (q *Queries) CountPostsByTag(ctx context.Context, tag string) (int64, error) {
	row := q.db.QueryRow(ctx, countPostsByTag, tag)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createPostTag = `-- name: CreatePostTag :exec
INSERT INTO post_tags (post_id, tag) VALUES ($1, $2)
`

type CreatePostTagParams struct {
	PostID int64
	Tag    string
}

func (q *Queries) CreatePostTag(ctx context.Context, arg CreatePostTagParams) error {
	_, err := q.db.Exec(ctx, createPostTag, arg.PostID, arg.Tag)
	return err
}

const deletePostTagsByPostID = `-- name: DeletePostTagsByPostID :exec
DELETE FROM post_tags WHERE post_id = $1
`

func (q *Queries) DeletePostTagsByPostID(ctx context.Context, postID int64) error {
	_, err := q.db.Exec(ctx, deletePostTagsByPostID, postID)
	return err
}

const listPopularTags = `-- name: ListPopularTags :many
SELECT tag, COUNT(*)::bigint AS count FROM post_tags
GROUP BY tag
ORDER BY count DESC
LIMIT $1
`

type ListPopularTagsRow struct {
	Tag   string
	Count int64
}

func (q *Queries) ListPopularTags(ctx context.Context, limit int32) ([]ListPopularTagsRow, error) {
	rows, err := q.db.Query(ctx, listPopularTags, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListPopularTagsRow
	for rows.Next() {
		var i ListPopularTagsRow
		if err := rows.Scan(&i.Tag, &i.Count); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPostIDsByTag = `-- name: ListPostIDsByTag :many
SELECT post_tags.post_id FROM post_tags
JOIN posts ON posts.id = post_tags.post_id AND posts.is_draft = false
WHERE post_tags.tag = $1
ORDER BY post_tags.id DESC
LIMIT $2 OFFSET $3
`

type ListPostIDsByTagParams struct {
	Tag    string
	Limit  int32
	Offset int32
}

// ページングはpost_tags.id順で決め、実データ（Post本体）は別クエリでcreated_at順に取得する
// （移行前のGORM実装と同じ2段構え）。
func (q *Queries) ListPostIDsByTag(ctx context.Context, arg ListPostIDsByTagParams) ([]int64, error) {
	rows, err := q.db.Query(ctx, listPostIDsByTag, arg.Tag, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []int64
	for rows.Next() {
		var post_id int64
		if err := rows.Scan(&post_id); err != nil {
			return nil, err
		}
		items = append(items, post_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPostTagsByPostID = `-- name: ListPostTagsByPostID :many
SELECT tag FROM post_tags WHERE post_id = $1 ORDER BY id ASC
`

func (q *Queries) ListPostTagsByPostID(ctx context.Context, postID int64) ([]string, error) {
	rows, err := q.db.Query(ctx, listPostTagsByPostID, postID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var tag string
		if err := rows.Scan(&tag); err != nil {
			return nil, err
		}
		items = append(items, tag)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPostsByIDs = `-- name: ListPostsByIDs :many
SELECT posts.id, posts.user_id, posts.title, posts.content, posts.image_urls, posts.is_draft, posts.like_count, posts.comment_count, posts.bookmark_count, posts.view_count, posts.estimated_read_time, posts.scheduled_at, posts.created_at, posts.updated_at, users.id, users.username, users.name, users.email, users.password, users.avatar_url, users.bio, users.git_hub_id, users.git_hub_username, users.git_hub_token, users.git_hub_connected, users.spotify_connected, users.spotify_token, users.spotify_refresh_token, users.spotify_token_expiry, users.zenn_username, users.qiita_username, users.at_coder_username, users.paiza_rank, users.skills_languages, users.skills_frameworks, users.onboarding_completed, users.email_weekly_report, users.email_language, users.created_at, users.updated_at
FROM posts
JOIN users ON users.id = posts.user_id
WHERE posts.id = ANY($1::bigint[])
ORDER BY posts.created_at DESC
`

type ListPostsByIDsRow struct {
	Post Post
	User User
}

// GORMのPreload("User")に相当。user_idはNOT NULLのためINNER JOINでよい。
func (q *Queries) ListPostsByIDs(ctx context.Context, dollar_1 []int64) ([]ListPostsByIDsRow, error) {
	rows, err := q.db.Query(ctx, listPostsByIDs, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListPostsByIDsRow
	for rows.Next() {
		var i ListPostsByIDsRow
		if err := rows.Scan(
			&i.Post.ID,
			&i.Post.UserID,
			&i.Post.Title,
			&i.Post.Content,
			&i.Post.ImageUrls,
			&i.Post.IsDraft,
			&i.Post.LikeCount,
			&i.Post.CommentCount,
			&i.Post.BookmarkCount,
			&i.Post.ViewCount,
			&i.Post.EstimatedReadTime,
			&i.Post.ScheduledAt,
			&i.Post.CreatedAt,
			&i.Post.UpdatedAt,
			&i.User.ID,
			&i.User.Username,
			&i.User.Name,
			&i.User.Email,
			&i.User.Password,
			&i.User.AvatarUrl,
			&i.User.Bio,
			&i.User.GitHubID,
			&i.User.GitHubUsername,
			&i.User.GitHubToken,
			&i.User.GitHubConnected,
			&i.User.SpotifyConnected,
			&i.User.SpotifyToken,
			&i.User.SpotifyRefreshToken,
			&i.User.SpotifyTokenExpiry,
			&i.User.ZennUsername,
			&i.User.QiitaUsername,
			&i.User.AtCoderUsername,
			&i.User.PaizaRank,
			&i.User.SkillsLanguages,
			&i.User.SkillsFrameworks,
			&i.User.OnboardingCompleted,
			&i.User.EmailWeeklyReport,
			&i.User.EmailLanguage,
			&i.User.CreatedAt,
			&i.User.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
