// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: post_view.sql

package sqlcgen

import (
	"context"
)

const countPostViewsByPost = `-- name: CountPostViewsByPost :one
SELECT COUNT(*) FROM post_views WHERE post_id = $1
`

func (q *Queries) CountPostViewsByPost(ctx context.Context, postID int64) (int64, error) {
	row := q.db.QueryRow(ctx, countPostViewsByPost, postID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createPostView = `-- name: CreatePostView :execrows
INSERT INTO post_views (user_id, post_id, created_at)
VALUES ($1, $2, now())
ON CONFLICT DO NOTHING
`

type CreatePostViewParams struct {
	UserID int64
	PostID int64
}

// GORMの clause.OnConflict{DoNothing: true} に相当。実際に挿入できた行数を返し、
// 呼び出し側で「既に閲覧済みだったか」を判定する。
func (q *Queries) CreatePostView(ctx context.Context, arg CreatePostViewParams) (int64, error) {
	result, err := q.db.Exec(ctx, createPostView, arg.UserID, arg.PostID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const incrementPostViewCount = `-- name: IncrementPostViewCount :exec
UPDATE posts SET view_count = view_count + 1 WHERE id = $1
`

func (q *Queries) IncrementPostViewCount(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, incrementPostViewCount, id)
	return err
}

const listMostViewedPosts = `-- name: ListMostViewedPosts :many
SELECT post_id, COUNT(*)::bigint AS view_count FROM post_views
GROUP BY post_id
ORDER BY view_count DESC
LIMIT $1
`

type ListMostViewedPostsRow struct {
	PostID    int64
	ViewCount int64
}

func (q *Queries) ListMostViewedPosts(ctx context.Context, limit int32) ([]ListMostViewedPostsRow, error) {
	rows, err := q.db.Query(ctx, listMostViewedPosts, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListMostViewedPostsRow
	for rows.Next() {
		var i ListMostViewedPostsRow
		if err := rows.Scan(&i.PostID, &i.ViewCount); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
