// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: post_like.sql

package sqlcgen

import (
	"context"
)

const countPostLikeByUserAndPost = `-- name: CountPostLikeByUserAndPost :one
SELECT COUNT(*) FROM likes WHERE user_id = $1 AND post_id = $2
`

type CountPostLikeByUserAndPostParams struct {
	UserID int64
	PostID int64
}

func (q *Queries) CountPostLikeByUserAndPost(ctx context.Context, arg CountPostLikeByUserAndPostParams) (int64, error) {
	row := q.db.QueryRow(ctx, countPostLikeByUserAndPost, arg.UserID, arg.PostID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createPostLike = `-- name: CreatePostLike :exec
INSERT INTO likes (user_id, post_id, created_at) VALUES ($1, $2, now())
`

type CreatePostLikeParams struct {
	UserID int64
	PostID int64
}

func (q *Queries) CreatePostLike(ctx context.Context, arg CreatePostLikeParams) error {
	_, err := q.db.Exec(ctx, createPostLike, arg.UserID, arg.PostID)
	return err
}

const decrementPostLikeCount = `-- name: DecrementPostLikeCount :exec
UPDATE posts SET like_count = GREATEST(like_count - 1, 0) WHERE id = $1
`

func (q *Queries) DecrementPostLikeCount(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, decrementPostLikeCount, id)
	return err
}

const deletePostLike = `-- name: DeletePostLike :execrows
DELETE FROM likes WHERE user_id = $1 AND post_id = $2
`

type DeletePostLikeParams struct {
	UserID int64
	PostID int64
}

func (q *Queries) DeletePostLike(ctx context.Context, arg DeletePostLikeParams) (int64, error) {
	result, err := q.db.Exec(ctx, deletePostLike, arg.UserID, arg.PostID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const incrementPostLikeCount = `-- name: IncrementPostLikeCount :exec
UPDATE posts SET like_count = like_count + 1 WHERE id = $1
`

func (q *Queries) IncrementPostLikeCount(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, incrementPostLikeCount, id)
	return err
}
