// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: post_search.sql

package sqlcgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countPostsWithFilter = `-- name: CountPostsWithFilter :one
SELECT COUNT(*) FROM posts
WHERE (posts.title LIKE $1 OR posts.content LIKE $1)
    AND posts.is_draft = false
    AND ($2::timestamptz IS NULL OR posts.created_at >= $2)
    AND ($3::timestamptz IS NULL OR posts.created_at <= $3)
    AND (
        SELECT COUNT(DISTINCT pt.tag) FROM post_tags pt
        WHERE pt.post_id = posts.id AND pt.tag = ANY($4::text[])
    ) = cardinality($4::text[])
`

type CountPostsWithFilterParams struct {
	Title    string
	DateFrom pgtype.Timestamptz
	DateTo   pgtype.Timestamptz
	Tags     []string
}

// タグはAND条件（全タグが付与されている投稿のみ）。空配列なら絞り込みなし
// （cardinality(タグ配列)=0のときCOUNT(...)側も0になり両辺が一致するため自然に通る）。
func (q *Queries) CountPostsWithFilter(ctx context.Context, arg CountPostsWithFilterParams) (int64, error) {
	row := q.db.QueryRow(ctx, countPostsWithFilter,
		arg.Title,
		arg.DateFrom,
		arg.DateTo,
		arg.Tags,
	)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const searchPostsWithFilter = `-- name: SearchPostsWithFilter :many
SELECT posts.id, posts.user_id, posts.title, posts.content, posts.image_urls, posts.is_draft, posts.like_count, posts.comment_count, posts.view_count, posts.estimated_read_time, posts.scheduled_at, posts.created_at, posts.updated_at, users.id, users.username, users.name, users.email, users.password, users.avatar_url, users.bio, users.git_hub_id, users.git_hub_username, users.git_hub_token, users.git_hub_connected, users.spotify_connected, users.spotify_token, users.spotify_refresh_token, users.spotify_token_expiry, users.zenn_username, users.qiita_username, users.at_coder_username, users.paiza_rank, users.skills_languages, users.skills_frameworks, users.onboarding_completed, users.email_weekly_report, users.email_language, users.created_at, users.updated_at
FROM posts
JOIN users ON users.id = posts.user_id
WHERE (posts.title LIKE $1 OR posts.content LIKE $1)
    AND posts.is_draft = false
    AND ($2::timestamptz IS NULL OR posts.created_at >= $2)
    AND ($3::timestamptz IS NULL OR posts.created_at <= $3)
    AND (
        SELECT COUNT(DISTINCT pt.tag) FROM post_tags pt
        WHERE pt.post_id = posts.id AND pt.tag = ANY($4::text[])
    ) = cardinality($4::text[])
ORDER BY
    CASE WHEN $5 = 'popular' THEN posts.like_count END DESC,
    CASE WHEN $5 = 'views' THEN posts.view_count END DESC,
    posts.created_at DESC
LIMIT $7 OFFSET $6
`

type SearchPostsWithFilterParams struct {
	Title    string
	DateFrom pgtype.Timestamptz
	DateTo   pgtype.Timestamptz
	Tags     []string
	SortBy   interface{}
	Offset   int32
	Limit    int32
}

type SearchPostsWithFilterRow struct {
	Post Post
	User User
}

// GORMのPreload("User")に相当（CodeSnippetsは別クエリで取得しGo側で結合する）。
// ソート順はGoの動的Order()呼び出しの代わりに、sort_byごとのCASE式で切り替える
// （sort_byはクエリ全体で単一の値のため、行ごとにNULLになったり値になったりはしない）。
func (q *Queries) SearchPostsWithFilter(ctx context.Context, arg SearchPostsWithFilterParams) ([]SearchPostsWithFilterRow, error) {
	rows, err := q.db.Query(ctx, searchPostsWithFilter,
		arg.Title,
		arg.DateFrom,
		arg.DateTo,
		arg.Tags,
		arg.SortBy,
		arg.Offset,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SearchPostsWithFilterRow
	for rows.Next() {
		var i SearchPostsWithFilterRow
		if err := rows.Scan(
			&i.Post.ID,
			&i.Post.UserID,
			&i.Post.Title,
			&i.Post.Content,
			&i.Post.ImageUrls,
			&i.Post.IsDraft,
			&i.Post.LikeCount,
			&i.Post.CommentCount,
			&i.Post.ViewCount,
			&i.Post.EstimatedReadTime,
			&i.Post.ScheduledAt,
			&i.Post.CreatedAt,
			&i.Post.UpdatedAt,
			&i.User.ID,
			&i.User.Username,
			&i.User.Name,
			&i.User.Email,
			&i.User.Password,
			&i.User.AvatarUrl,
			&i.User.Bio,
			&i.User.GitHubID,
			&i.User.GitHubUsername,
			&i.User.GitHubToken,
			&i.User.GitHubConnected,
			&i.User.SpotifyConnected,
			&i.User.SpotifyToken,
			&i.User.SpotifyRefreshToken,
			&i.User.SpotifyTokenExpiry,
			&i.User.ZennUsername,
			&i.User.QiitaUsername,
			&i.User.AtCoderUsername,
			&i.User.PaizaRank,
			&i.User.SkillsLanguages,
			&i.User.SkillsFrameworks,
			&i.User.OnboardingCompleted,
			&i.User.EmailWeeklyReport,
			&i.User.EmailLanguage,
			&i.User.CreatedAt,
			&i.User.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
