// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: post.sql

package sqlcgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countPublicPosts = `-- name: CountPublicPosts :one
SELECT COUNT(*) FROM posts WHERE is_draft = false
`

func (q *Queries) CountPublicPosts(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countPublicPosts)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countScheduledPostsByUser = `-- name: CountScheduledPostsByUser :one
SELECT COUNT(*) FROM posts WHERE user_id = $1 AND is_draft = true AND scheduled_at IS NOT NULL
`

func (q *Queries) CountScheduledPostsByUser(ctx context.Context, userID int64) (int64, error) {
	row := q.db.QueryRow(ctx, countScheduledPostsByUser, userID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createPost = `-- name: CreatePost :one
INSERT INTO posts (
    user_id, title, content, image_urls, is_draft, like_count, comment_count,
    bookmark_count, view_count, estimated_read_time, scheduled_at, created_at, updated_at
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, now(), now()
) RETURNING id, user_id, title, content, image_urls, is_draft, like_count, comment_count, bookmark_count, view_count, estimated_read_time, scheduled_at, created_at, updated_at
`

type CreatePostParams struct {
	UserID            int64
	Title             string
	Content           string
	ImageUrls         *string
	IsDraft           *bool
	LikeCount         *int64
	CommentCount      *int64
	BookmarkCount     *int64
	ViewCount         *int64
	EstimatedReadTime *int64
	ScheduledAt       pgtype.Timestamptz
}

func (q *Queries) CreatePost(ctx context.Context, arg CreatePostParams) (Post, error) {
	row := q.db.QueryRow(ctx, createPost,
		arg.UserID,
		arg.Title,
		arg.Content,
		arg.ImageUrls,
		arg.IsDraft,
		arg.LikeCount,
		arg.CommentCount,
		arg.BookmarkCount,
		arg.ViewCount,
		arg.EstimatedReadTime,
		arg.ScheduledAt,
	)
	var i Post
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Title,
		&i.Content,
		&i.ImageUrls,
		&i.IsDraft,
		&i.LikeCount,
		&i.CommentCount,
		&i.BookmarkCount,
		&i.ViewCount,
		&i.EstimatedReadTime,
		&i.ScheduledAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteBookmarkCollectionItemsByPost = `-- name: DeleteBookmarkCollectionItemsByPost :exec
DELETE FROM bookmark_collection_items WHERE post_id = $1
`

func (q *Queries) DeleteBookmarkCollectionItemsByPost(ctx context.Context, postID int64) error {
	_, err := q.db.Exec(ctx, deleteBookmarkCollectionItemsByPost, postID)
	return err
}

const deleteBookmarksByPost = `-- name: DeleteBookmarksByPost :exec
DELETE FROM bookmarks WHERE post_id = $1
`

func (q *Queries) DeleteBookmarksByPost(ctx context.Context, postID int64) error {
	_, err := q.db.Exec(ctx, deleteBookmarksByPost, postID)
	return err
}

const deleteCodeSnippetsByPost = `-- name: DeleteCodeSnippetsByPost :exec
DELETE FROM code_snippets WHERE post_id = $1
`

func (q *Queries) DeleteCodeSnippetsByPost(ctx context.Context, postID int64) error {
	_, err := q.db.Exec(ctx, deleteCodeSnippetsByPost, postID)
	return err
}

const deleteCommentLikesByPostComments = `-- name: DeleteCommentLikesByPostComments :exec
DELETE FROM comment_likes WHERE comment_id IN (SELECT id FROM comments WHERE post_id = $1)
`

func (q *Queries) DeleteCommentLikesByPostComments(ctx context.Context, postID int64) error {
	_, err := q.db.Exec(ctx, deleteCommentLikesByPostComments, postID)
	return err
}

const deleteCommentsByPost = `-- name: DeleteCommentsByPost :exec
DELETE FROM comments WHERE post_id = $1
`

func (q *Queries) DeleteCommentsByPost(ctx context.Context, postID int64) error {
	_, err := q.db.Exec(ctx, deleteCommentsByPost, postID)
	return err
}

const deleteLikesByPost = `-- name: DeleteLikesByPost :exec
DELETE FROM likes WHERE post_id = $1
`

func (q *Queries) DeleteLikesByPost(ctx context.Context, postID int64) error {
	_, err := q.db.Exec(ctx, deleteLikesByPost, postID)
	return err
}

const deleteMentionsByPost = `-- name: DeleteMentionsByPost :exec
DELETE FROM mentions WHERE post_id = $1
`

func (q *Queries) DeleteMentionsByPost(ctx context.Context, postID *int64) error {
	_, err := q.db.Exec(ctx, deleteMentionsByPost, postID)
	return err
}

const deleteMentionsByPostComments = `-- name: DeleteMentionsByPostComments :exec
DELETE FROM mentions WHERE comment_id IN (SELECT c.id FROM comments c WHERE c.post_id = $1)
`

// mentions自身もpost_id列を持つため、サブクエリのcommentsを明示的にエイリアス修飾しないと
// post_idの参照先が曖昧になる（PostgreSQLの相関サブクエリの解決規則による）。
func (q *Queries) DeleteMentionsByPostComments(ctx context.Context, postID int64) error {
	_, err := q.db.Exec(ctx, deleteMentionsByPostComments, postID)
	return err
}

const deleteNotificationsByPost = `-- name: DeleteNotificationsByPost :exec
DELETE FROM notifications WHERE post_id = $1
`

func (q *Queries) DeleteNotificationsByPost(ctx context.Context, postID *int64) error {
	_, err := q.db.Exec(ctx, deleteNotificationsByPost, postID)
	return err
}

const deletePost = `-- name: DeletePost :exec
DELETE FROM posts WHERE id = $1
`

func (q *Queries) DeletePost(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, deletePost, id)
	return err
}

const deletePostCollectionItemsByPost = `-- name: DeletePostCollectionItemsByPost :exec
DELETE FROM post_collection_items WHERE post_id = $1
`

func (q *Queries) DeletePostCollectionItemsByPost(ctx context.Context, postID int64) error {
	_, err := q.db.Exec(ctx, deletePostCollectionItemsByPost, postID)
	return err
}

const deletePostPinsByPost = `-- name: DeletePostPinsByPost :exec
DELETE FROM post_pins WHERE post_id = $1
`

func (q *Queries) DeletePostPinsByPost(ctx context.Context, postID int64) error {
	_, err := q.db.Exec(ctx, deletePostPinsByPost, postID)
	return err
}

const deletePostSeriesItemsByPost = `-- name: DeletePostSeriesItemsByPost :exec
DELETE FROM post_series_items WHERE post_id = $1
`

func (q *Queries) DeletePostSeriesItemsByPost(ctx context.Context, postID int64) error {
	_, err := q.db.Exec(ctx, deletePostSeriesItemsByPost, postID)
	return err
}

const deletePostTagsByPost = `-- name: DeletePostTagsByPost :exec
DELETE FROM post_tags WHERE post_id = $1
`

func (q *Queries) DeletePostTagsByPost(ctx context.Context, postID int64) error {
	_, err := q.db.Exec(ctx, deletePostTagsByPost, postID)
	return err
}

const deletePostViewsByPost = `-- name: DeletePostViewsByPost :exec
DELETE FROM post_views WHERE post_id = $1
`

func (q *Queries) DeletePostViewsByPost(ctx context.Context, postID int64) error {
	_, err := q.db.Exec(ctx, deletePostViewsByPost, postID)
	return err
}

const deleteReactionsByPost = `-- name: DeleteReactionsByPost :exec
DELETE FROM reactions WHERE post_id = $1
`

func (q *Queries) DeleteReactionsByPost(ctx context.Context, postID int64) error {
	_, err := q.db.Exec(ctx, deleteReactionsByPost, postID)
	return err
}

const deleteSnippetCommentsByPostSnippets = `-- name: DeleteSnippetCommentsByPostSnippets :exec
DELETE FROM snippet_comments WHERE snippet_id IN (SELECT cs.id FROM code_snippets cs WHERE cs.post_id = $1)
`

func (q *Queries) DeleteSnippetCommentsByPostSnippets(ctx context.Context, postID int64) error {
	_, err := q.db.Exec(ctx, deleteSnippetCommentsByPostSnippets, postID)
	return err
}

const listDraftPostsByUserWithUser = `-- name: ListDraftPostsByUserWithUser :many
SELECT posts.id, posts.user_id, posts.title, posts.content, posts.image_urls, posts.is_draft, posts.like_count, posts.comment_count, posts.bookmark_count, posts.view_count, posts.estimated_read_time, posts.scheduled_at, posts.created_at, posts.updated_at, users.id, users.username, users.name, users.email, users.password, users.avatar_url, users.bio, users.git_hub_id, users.git_hub_username, users.git_hub_token, users.git_hub_connected, users.spotify_connected, users.spotify_token, users.spotify_refresh_token, users.spotify_token_expiry, users.zenn_username, users.qiita_username, users.at_coder_username, users.paiza_rank, users.skills_languages, users.skills_frameworks, users.onboarding_completed, users.email_weekly_report, users.email_language, users.created_at, users.updated_at
FROM posts
JOIN users ON users.id = posts.user_id
WHERE posts.user_id = $1 AND posts.is_draft = true
ORDER BY posts.updated_at DESC
`

type ListDraftPostsByUserWithUserRow struct {
	Post Post
	User User
}

func (q *Queries) ListDraftPostsByUserWithUser(ctx context.Context, userID int64) ([]ListDraftPostsByUserWithUserRow, error) {
	rows, err := q.db.Query(ctx, listDraftPostsByUserWithUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListDraftPostsByUserWithUserRow
	for rows.Next() {
		var i ListDraftPostsByUserWithUserRow
		if err := rows.Scan(
			&i.Post.ID,
			&i.Post.UserID,
			&i.Post.Title,
			&i.Post.Content,
			&i.Post.ImageUrls,
			&i.Post.IsDraft,
			&i.Post.LikeCount,
			&i.Post.CommentCount,
			&i.Post.BookmarkCount,
			&i.Post.ViewCount,
			&i.Post.EstimatedReadTime,
			&i.Post.ScheduledAt,
			&i.Post.CreatedAt,
			&i.Post.UpdatedAt,
			&i.User.ID,
			&i.User.Username,
			&i.User.Name,
			&i.User.Email,
			&i.User.Password,
			&i.User.AvatarUrl,
			&i.User.Bio,
			&i.User.GitHubID,
			&i.User.GitHubUsername,
			&i.User.GitHubToken,
			&i.User.GitHubConnected,
			&i.User.SpotifyConnected,
			&i.User.SpotifyToken,
			&i.User.SpotifyRefreshToken,
			&i.User.SpotifyTokenExpiry,
			&i.User.ZennUsername,
			&i.User.QiitaUsername,
			&i.User.AtCoderUsername,
			&i.User.PaizaRank,
			&i.User.SkillsLanguages,
			&i.User.SkillsFrameworks,
			&i.User.OnboardingCompleted,
			&i.User.EmailWeeklyReport,
			&i.User.EmailLanguage,
			&i.User.CreatedAt,
			&i.User.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPublicPostsWithUser = `-- name: ListPublicPostsWithUser :many
SELECT posts.id, posts.user_id, posts.title, posts.content, posts.image_urls, posts.is_draft, posts.like_count, posts.comment_count, posts.bookmark_count, posts.view_count, posts.estimated_read_time, posts.scheduled_at, posts.created_at, posts.updated_at, users.id, users.username, users.name, users.email, users.password, users.avatar_url, users.bio, users.git_hub_id, users.git_hub_username, users.git_hub_token, users.git_hub_connected, users.spotify_connected, users.spotify_token, users.spotify_refresh_token, users.spotify_token_expiry, users.zenn_username, users.qiita_username, users.at_coder_username, users.paiza_rank, users.skills_languages, users.skills_frameworks, users.onboarding_completed, users.email_weekly_report, users.email_language, users.created_at, users.updated_at
FROM posts
JOIN users ON users.id = posts.user_id
WHERE posts.is_draft = false
ORDER BY posts.created_at DESC
LIMIT $1 OFFSET $2
`

type ListPublicPostsWithUserParams struct {
	Limit  int32
	Offset int32
}

type ListPublicPostsWithUserRow struct {
	Post Post
	User User
}

// GORMのPreload("User")に相当（CodeSnippetsは別途post_bookmark.sqlのListCodeSnippetsByPostIDsで取得する）。
// user_idはNOT NULLのためINNER JOINでよい。
func (q *Queries) ListPublicPostsWithUser(ctx context.Context, arg ListPublicPostsWithUserParams) ([]ListPublicPostsWithUserRow, error) {
	rows, err := q.db.Query(ctx, listPublicPostsWithUser, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListPublicPostsWithUserRow
	for rows.Next() {
		var i ListPublicPostsWithUserRow
		if err := rows.Scan(
			&i.Post.ID,
			&i.Post.UserID,
			&i.Post.Title,
			&i.Post.Content,
			&i.Post.ImageUrls,
			&i.Post.IsDraft,
			&i.Post.LikeCount,
			&i.Post.CommentCount,
			&i.Post.BookmarkCount,
			&i.Post.ViewCount,
			&i.Post.EstimatedReadTime,
			&i.Post.ScheduledAt,
			&i.Post.CreatedAt,
			&i.Post.UpdatedAt,
			&i.User.ID,
			&i.User.Username,
			&i.User.Name,
			&i.User.Email,
			&i.User.Password,
			&i.User.AvatarUrl,
			&i.User.Bio,
			&i.User.GitHubID,
			&i.User.GitHubUsername,
			&i.User.GitHubToken,
			&i.User.GitHubConnected,
			&i.User.SpotifyConnected,
			&i.User.SpotifyToken,
			&i.User.SpotifyRefreshToken,
			&i.User.SpotifyTokenExpiry,
			&i.User.ZennUsername,
			&i.User.QiitaUsername,
			&i.User.AtCoderUsername,
			&i.User.PaizaRank,
			&i.User.SkillsLanguages,
			&i.User.SkillsFrameworks,
			&i.User.OnboardingCompleted,
			&i.User.EmailWeeklyReport,
			&i.User.EmailLanguage,
			&i.User.CreatedAt,
			&i.User.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPublishedPostsByUserWithUser = `-- name: ListPublishedPostsByUserWithUser :many
SELECT posts.id, posts.user_id, posts.title, posts.content, posts.image_urls, posts.is_draft, posts.like_count, posts.comment_count, posts.bookmark_count, posts.view_count, posts.estimated_read_time, posts.scheduled_at, posts.created_at, posts.updated_at, users.id, users.username, users.name, users.email, users.password, users.avatar_url, users.bio, users.git_hub_id, users.git_hub_username, users.git_hub_token, users.git_hub_connected, users.spotify_connected, users.spotify_token, users.spotify_refresh_token, users.spotify_token_expiry, users.zenn_username, users.qiita_username, users.at_coder_username, users.paiza_rank, users.skills_languages, users.skills_frameworks, users.onboarding_completed, users.email_weekly_report, users.email_language, users.created_at, users.updated_at
FROM posts
JOIN users ON users.id = posts.user_id
WHERE posts.user_id = $1 AND posts.is_draft = false
ORDER BY posts.created_at DESC
LIMIT $2 OFFSET $3
`

type ListPublishedPostsByUserWithUserParams struct {
	UserID int64
	Limit  int32
	Offset int32
}

type ListPublishedPostsByUserWithUserRow struct {
	Post Post
	User User
}

// GORMのPreload("User")に相当。user_idはNOT NULLのためINNER JOINでよい。
func (q *Queries) ListPublishedPostsByUserWithUser(ctx context.Context, arg ListPublishedPostsByUserWithUserParams) ([]ListPublishedPostsByUserWithUserRow, error) {
	rows, err := q.db.Query(ctx, listPublishedPostsByUserWithUser, arg.UserID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListPublishedPostsByUserWithUserRow
	for rows.Next() {
		var i ListPublishedPostsByUserWithUserRow
		if err := rows.Scan(
			&i.Post.ID,
			&i.Post.UserID,
			&i.Post.Title,
			&i.Post.Content,
			&i.Post.ImageUrls,
			&i.Post.IsDraft,
			&i.Post.LikeCount,
			&i.Post.CommentCount,
			&i.Post.BookmarkCount,
			&i.Post.ViewCount,
			&i.Post.EstimatedReadTime,
			&i.Post.ScheduledAt,
			&i.Post.CreatedAt,
			&i.Post.UpdatedAt,
			&i.User.ID,
			&i.User.Username,
			&i.User.Name,
			&i.User.Email,
			&i.User.Password,
			&i.User.AvatarUrl,
			&i.User.Bio,
			&i.User.GitHubID,
			&i.User.GitHubUsername,
			&i.User.GitHubToken,
			&i.User.GitHubConnected,
			&i.User.SpotifyConnected,
			&i.User.SpotifyToken,
			&i.User.SpotifyRefreshToken,
			&i.User.SpotifyTokenExpiry,
			&i.User.ZennUsername,
			&i.User.QiitaUsername,
			&i.User.AtCoderUsername,
			&i.User.PaizaRank,
			&i.User.SkillsLanguages,
			&i.User.SkillsFrameworks,
			&i.User.OnboardingCompleted,
			&i.User.EmailWeeklyReport,
			&i.User.EmailLanguage,
			&i.User.CreatedAt,
			&i.User.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listScheduledPostsByUserWithUser = `-- name: ListScheduledPostsByUserWithUser :many
SELECT posts.id, posts.user_id, posts.title, posts.content, posts.image_urls, posts.is_draft, posts.like_count, posts.comment_count, posts.bookmark_count, posts.view_count, posts.estimated_read_time, posts.scheduled_at, posts.created_at, posts.updated_at, users.id, users.username, users.name, users.email, users.password, users.avatar_url, users.bio, users.git_hub_id, users.git_hub_username, users.git_hub_token, users.git_hub_connected, users.spotify_connected, users.spotify_token, users.spotify_refresh_token, users.spotify_token_expiry, users.zenn_username, users.qiita_username, users.at_coder_username, users.paiza_rank, users.skills_languages, users.skills_frameworks, users.onboarding_completed, users.email_weekly_report, users.email_language, users.created_at, users.updated_at
FROM posts
JOIN users ON users.id = posts.user_id
WHERE posts.user_id = $1 AND posts.is_draft = true AND posts.scheduled_at IS NOT NULL
ORDER BY posts.scheduled_at ASC
`

type ListScheduledPostsByUserWithUserRow struct {
	Post Post
	User User
}

func (q *Queries) ListScheduledPostsByUserWithUser(ctx context.Context, userID int64) ([]ListScheduledPostsByUserWithUserRow, error) {
	rows, err := q.db.Query(ctx, listScheduledPostsByUserWithUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListScheduledPostsByUserWithUserRow
	for rows.Next() {
		var i ListScheduledPostsByUserWithUserRow
		if err := rows.Scan(
			&i.Post.ID,
			&i.Post.UserID,
			&i.Post.Title,
			&i.Post.Content,
			&i.Post.ImageUrls,
			&i.Post.IsDraft,
			&i.Post.LikeCount,
			&i.Post.CommentCount,
			&i.Post.BookmarkCount,
			&i.Post.ViewCount,
			&i.Post.EstimatedReadTime,
			&i.Post.ScheduledAt,
			&i.Post.CreatedAt,
			&i.Post.UpdatedAt,
			&i.User.ID,
			&i.User.Username,
			&i.User.Name,
			&i.User.Email,
			&i.User.Password,
			&i.User.AvatarUrl,
			&i.User.Bio,
			&i.User.GitHubID,
			&i.User.GitHubUsername,
			&i.User.GitHubToken,
			&i.User.GitHubConnected,
			&i.User.SpotifyConnected,
			&i.User.SpotifyToken,
			&i.User.SpotifyRefreshToken,
			&i.User.SpotifyTokenExpiry,
			&i.User.ZennUsername,
			&i.User.QiitaUsername,
			&i.User.AtCoderUsername,
			&i.User.PaizaRank,
			&i.User.SkillsLanguages,
			&i.User.SkillsFrameworks,
			&i.User.OnboardingCompleted,
			&i.User.EmailWeeklyReport,
			&i.User.EmailLanguage,
			&i.User.CreatedAt,
			&i.User.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTimelinePostsWithUser = `-- name: ListTimelinePostsWithUser :many
SELECT posts.id, posts.user_id, posts.title, posts.content, posts.image_urls, posts.is_draft, posts.like_count, posts.comment_count, posts.bookmark_count, posts.view_count, posts.estimated_read_time, posts.scheduled_at, posts.created_at, posts.updated_at, users.id, users.username, users.name, users.email, users.password, users.avatar_url, users.bio, users.git_hub_id, users.git_hub_username, users.git_hub_token, users.git_hub_connected, users.spotify_connected, users.spotify_token, users.spotify_refresh_token, users.spotify_token_expiry, users.zenn_username, users.qiita_username, users.at_coder_username, users.paiza_rank, users.skills_languages, users.skills_frameworks, users.onboarding_completed, users.email_weekly_report, users.email_language, users.created_at, users.updated_at
FROM posts
JOIN users ON users.id = posts.user_id
WHERE (posts.user_id IN (SELECT followee_id FROM follows WHERE follower_id = $1) OR posts.user_id = $1)
    AND posts.is_draft = false
ORDER BY posts.created_at DESC
LIMIT $2 OFFSET $3
`

type ListTimelinePostsWithUserParams struct {
	FollowerID int64
	Limit      int32
	Offset     int32
}

type ListTimelinePostsWithUserRow struct {
	Post Post
	User User
}

// フォロー中ユーザーと自分自身の公開済み投稿（移行前のGo実装のサブクエリをそのまま踏襲）。
func (q *Queries) ListTimelinePostsWithUser(ctx context.Context, arg ListTimelinePostsWithUserParams) ([]ListTimelinePostsWithUserRow, error) {
	rows, err := q.db.Query(ctx, listTimelinePostsWithUser, arg.FollowerID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListTimelinePostsWithUserRow
	for rows.Next() {
		var i ListTimelinePostsWithUserRow
		if err := rows.Scan(
			&i.Post.ID,
			&i.Post.UserID,
			&i.Post.Title,
			&i.Post.Content,
			&i.Post.ImageUrls,
			&i.Post.IsDraft,
			&i.Post.LikeCount,
			&i.Post.CommentCount,
			&i.Post.BookmarkCount,
			&i.Post.ViewCount,
			&i.Post.EstimatedReadTime,
			&i.Post.ScheduledAt,
			&i.Post.CreatedAt,
			&i.Post.UpdatedAt,
			&i.User.ID,
			&i.User.Username,
			&i.User.Name,
			&i.User.Email,
			&i.User.Password,
			&i.User.AvatarUrl,
			&i.User.Bio,
			&i.User.GitHubID,
			&i.User.GitHubUsername,
			&i.User.GitHubToken,
			&i.User.GitHubConnected,
			&i.User.SpotifyConnected,
			&i.User.SpotifyToken,
			&i.User.SpotifyRefreshToken,
			&i.User.SpotifyTokenExpiry,
			&i.User.ZennUsername,
			&i.User.QiitaUsername,
			&i.User.AtCoderUsername,
			&i.User.PaizaRank,
			&i.User.SkillsLanguages,
			&i.User.SkillsFrameworks,
			&i.User.OnboardingCompleted,
			&i.User.EmailWeeklyReport,
			&i.User.EmailLanguage,
			&i.User.CreatedAt,
			&i.User.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockPostForDelete = `-- name: LockPostForDelete :one
SELECT id FROM posts WHERE id = $1 FOR UPDATE
`

// 投稿削除の直列化のための行ロック（GORMの clause.Locking{Strength: "UPDATE"} に相当）。
// 存在しなければ pgx.ErrNoRows を返し、呼び出し側で「既に無ければ何もしない（冪等）」を判定する。
func (q *Queries) LockPostForDelete(ctx context.Context, id int64) (int64, error) {
	row := q.db.QueryRow(ctx, lockPostForDelete, id)
	var id_2 int64
	err := row.Scan(&id_2)
	return id_2, err
}

const updatePost = `-- name: UpdatePost :one
UPDATE posts SET
    title = $2, content = $3, image_urls = $4, is_draft = $5, like_count = $6,
    comment_count = $7, bookmark_count = $8, view_count = $9, estimated_read_time = $10,
    scheduled_at = $11, updated_at = now()
WHERE id = $1
RETURNING id, user_id, title, content, image_urls, is_draft, like_count, comment_count, bookmark_count, view_count, estimated_read_time, scheduled_at, created_at, updated_at
`

type UpdatePostParams struct {
	ID                int64
	Title             string
	Content           string
	ImageUrls         *string
	IsDraft           *bool
	LikeCount         *int64
	CommentCount      *int64
	BookmarkCount     *int64
	ViewCount         *int64
	EstimatedReadTime *int64
	ScheduledAt       pgtype.Timestamptz
}

// GORMのSave（全カラム上書き）に相当。
func (q *Queries) UpdatePost(ctx context.Context, arg UpdatePostParams) (Post, error) {
	row := q.db.QueryRow(ctx, updatePost,
		arg.ID,
		arg.Title,
		arg.Content,
		arg.ImageUrls,
		arg.IsDraft,
		arg.LikeCount,
		arg.CommentCount,
		arg.BookmarkCount,
		arg.ViewCount,
		arg.EstimatedReadTime,
		arg.ScheduledAt,
	)
	var i Post
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Title,
		&i.Content,
		&i.ImageUrls,
		&i.IsDraft,
		&i.LikeCount,
		&i.CommentCount,
		&i.BookmarkCount,
		&i.ViewCount,
		&i.EstimatedReadTime,
		&i.ScheduledAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
