// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: post_like.sql

package sqlcgen

import (
	"context"
)

const countPostLikeByUserAndPost = `-- name: CountPostLikeByUserAndPost :one
SELECT COUNT(*) FROM post_reactions
WHERE post_reactions.user_id = $1 AND post_reactions.post_id = $2 AND post_reactions.kind = 'like'
`

type CountPostLikeByUserAndPostParams struct {
	UserID int64
	PostID int64
}

func (q *Queries) CountPostLikeByUserAndPost(ctx context.Context, arg CountPostLikeByUserAndPostParams) (int64, error) {
	row := q.db.QueryRow(ctx, countPostLikeByUserAndPost, arg.UserID, arg.PostID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createPostLike = `-- name: CreatePostLike :exec
WITH inserted AS (
    INSERT INTO post_reactions (user_id, post_id, kind, created_at) VALUES ($1, $2, 'like', now())
    RETURNING post_reactions.post_id AS liked_post_id
)
INSERT INTO post_metrics (post_id, like_count)
SELECT liked_post_id, 1 FROM inserted
ON CONFLICT (post_id) DO UPDATE SET like_count = post_metrics.like_count + 1
`

type CreatePostLikeParams struct {
	UserID int64
	PostID int64
}

// post_reactions(kind='like')へのINSERTとpost_metrics.like_countの加算を同一SQL文で
// 行う（DEVSYNC-159）。CTEの出力列をpost_metrics.post_idと別名にし、sqlcの列名衝突による
// 誤検出を避ける。DEVSYNC-160でlikes単独テーブルからpost_reactionsへ統合。
func (q *Queries) CreatePostLike(ctx context.Context, arg CreatePostLikeParams) error {
	_, err := q.db.Exec(ctx, createPostLike, arg.UserID, arg.PostID)
	return err
}

const deletePostLike = `-- name: DeletePostLike :execrows
WITH deleted AS (
    DELETE FROM post_reactions
    WHERE post_reactions.user_id = $1 AND post_reactions.post_id = $2 AND post_reactions.kind = 'like'
    RETURNING post_reactions.post_id AS liked_post_id
)
INSERT INTO post_metrics (post_id, like_count)
SELECT liked_post_id, 0 FROM deleted
ON CONFLICT (post_id) DO UPDATE SET like_count = GREATEST(post_metrics.like_count - 1, 0)
`

type DeletePostLikeParams struct {
	UserID int64
	PostID int64
}

// post_reactions(kind='like')の削除とpost_metrics.like_countの減算を同一SQL文で行う。
// 実際に削除できた（＝insertedに1行ある）ときだけpost_metricsを更新するため、
// rowsAffectedは従来どおり「実際にいいねを取り消せたか」を表す。
func (q *Queries) DeletePostLike(ctx context.Context, arg DeletePostLikeParams) (int64, error) {
	result, err := q.db.Exec(ctx, deletePostLike, arg.UserID, arg.PostID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
