// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: project_stats.sql

package sqlcgen

import (
	"context"
)

const getProjectStats = `-- name: GetProjectStats :one
SELECT
  count(*) AS total_projects,
  count(*) FILTER (WHERE featured = true) AS featured_projects,
  count(*) FILTER (WHERE end_date IS NULL) AS ongoing_projects,
  count(*) FILTER (WHERE end_date IS NOT NULL) AS completed_projects
FROM projects
WHERE user_id = $1
`

type GetProjectStatsRow struct {
	TotalProjects     int64
	FeaturedProjects  int64
	OngoingProjects   int64
	CompletedProjects int64
}

func (q *Queries) GetProjectStats(ctx context.Context, userID int64) (GetProjectStatsRow, error) {
	row := q.db.QueryRow(ctx, getProjectStats, userID)
	var i GetProjectStatsRow
	err := row.Scan(
		&i.TotalProjects,
		&i.FeaturedProjects,
		&i.OngoingProjects,
		&i.CompletedProjects,
	)
	return i, err
}
