// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: qa_stats.sql

package sqlcgen

import (
	"context"
)

const countAnswersByUser = `-- name: CountAnswersByUser :one
SELECT count(*) FROM answers
WHERE user_id = $1 AND deleted_at IS NULL
`

func (q *Queries) CountAnswersByUser(ctx context.Context, userID int64) (int64, error) {
	row := q.db.QueryRow(ctx, countAnswersByUser, userID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countBestAnswersByUser = `-- name: CountBestAnswersByUser :one
SELECT count(*) FROM answers
WHERE user_id = $1 AND is_best = true AND deleted_at IS NULL
`

func (q *Queries) CountBestAnswersByUser(ctx context.Context, userID int64) (int64, error) {
	row := q.db.QueryRow(ctx, countBestAnswersByUser, userID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countQuestionsByUser = `-- name: CountQuestionsByUser :one
SELECT count(*) FROM questions
WHERE user_id = $1 AND deleted_at IS NULL
`

// questions/answers は GORM の論理削除（deleted_at）付きモデルのため、GORMの既定スコープに
// 合わせて deleted_at IS NULL を明示する（Unscoped() されていない全クエリと同じ挙動）。
func (q *Queries) CountQuestionsByUser(ctx context.Context, userID int64) (int64, error) {
	row := q.db.QueryRow(ctx, countQuestionsByUser, userID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const sumAnswerVotesByUser = `-- name: SumAnswerVotesByUser :one
SELECT COALESCE(SUM(vote_count), 0)::bigint FROM answers
WHERE user_id = $1 AND deleted_at IS NULL
`

func (q *Queries) SumAnswerVotesByUser(ctx context.Context, userID int64) (int64, error) {
	row := q.db.QueryRow(ctx, sumAnswerVotesByUser, userID)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const sumQuestionVotesByUser = `-- name: SumQuestionVotesByUser :one
SELECT COALESCE(SUM(vote_count), 0)::bigint FROM questions
WHERE user_id = $1 AND deleted_at IS NULL
`

func (q *Queries) SumQuestionVotesByUser(ctx context.Context, userID int64) (int64, error) {
	row := q.db.QueryRow(ctx, sumQuestionVotesByUser, userID)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}
