// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlcgen

import (
	"context"
)

type Querier interface {
	CountPostTemplatesByUserID(ctx context.Context, userID int64) (int64, error)
	CreatePostTemplate(ctx context.Context, arg CreatePostTemplateParams) (PostTemplate, error)
	DeletePostTemplate(ctx context.Context, id int64) error
	GetPostTemplateByID(ctx context.Context, id int64) (PostTemplate, error)
	ListPostTemplatesByUserID(ctx context.Context, arg ListPostTemplatesByUserIDParams) ([]PostTemplate, error)
	UpdatePostTemplate(ctx context.Context, arg UpdatePostTemplateParams) (PostTemplate, error)
}

var _ Querier = (*Queries)(nil)
