// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlcgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	ArchiveNote(ctx context.Context, id int64) error
	ClearNoteTemplateDefaultFlag(ctx context.Context, userID int64) error
	// note_stats.sql の CountNotesByUser はアーカイブ済みも含めた全件数のため名前を分けている。
	CountActiveNotesByUser(ctx context.Context, userID int64) (int64, error)
	CountAnswersByUser(ctx context.Context, userID int64) (int64, error)
	// qa_stats.sql の CountAnswersByUser は deleted_at IS NULL で絞るが、
	// こちらは既存の GORM Raw SQL 実装（db.Raw、GORMのsoft-deleteスコープ非適用）と
	// 挙動を変えないため、論理削除された回答も含めてカウントする。
	CountAnswersByUserIncludingDeleted(ctx context.Context, userID int64) (int64, error)
	CountArchivedNotesByUser(ctx context.Context, userID int64) (int64, error)
	CountBestAnswersByUser(ctx context.Context, userID int64) (int64, error)
	CountBookmarkByUserAndPost(ctx context.Context, arg CountBookmarkByUserAndPostParams) (int64, error)
	CountBookmarksMadeByUser(ctx context.Context, userID int64) (int64, error)
	CountBookmarksMadeByUserSince(ctx context.Context, arg CountBookmarksMadeByUserSinceParams) (int64, error)
	CountBookmarksReceivedByUser(ctx context.Context, userID int64) (int64, error)
	CountCodeSnippetLanguagesByUser(ctx context.Context, userID int64) (int64, error)
	CountCodeSnippetsByUser(ctx context.Context, userID int64) (int64, error)
	CountCommentLikesByComment(ctx context.Context, commentID int64) (int64, error)
	CountCommentLikesByUserAndComment(ctx context.Context, arg CountCommentLikesByUserAndCommentParams) (int64, error)
	CountCommentsByUser(ctx context.Context, userID int64) (int64, error)
	CountCommentsByUserSince(ctx context.Context, arg CountCommentsByUserSinceParams) (int64, error)
	CountCommentsReceivedByUser(ctx context.Context, userID int64) (int64, error)
	CountCompletedLearningGoalsByUser(ctx context.Context, arg CountCompletedLearningGoalsByUserParams) (int64, error)
	CountConversationsByUser(ctx context.Context, senderID int64) (int64, error)
	CountDraftPostsByUser(ctx context.Context, userID int64) (int64, error)
	CountFavoriteNotesByUser(ctx context.Context, userID int64) (int64, error)
	CountFollowersByUser(ctx context.Context, followeeID int64) (int64, error)
	CountFollowingByUser(ctx context.Context, followerID int64) (int64, error)
	CountGitHubContributionDaysByUser(ctx context.Context, userID int64) (int64, error)
	CountLearningLogCategoriesByUser(ctx context.Context, userID int64) (int64, error)
	CountLearningLogsByUser(ctx context.Context, userID int64) (int64, error)
	CountLearningLogsByUserSince(ctx context.Context, arg CountLearningLogsByUserSinceParams) (int64, error)
	CountLearningResourceCategoriesByUser(ctx context.Context, userID int64) (int64, error)
	// learning_resources は GORM の論理削除（deleted_at）付きモデルのため、GORMの既定スコープに
	// 合わせて deleted_at IS NULL を明示する（Unscoped() されていない全クエリと同じ挙動）。
	CountLearningResourcesByUser(ctx context.Context, userID int64) (int64, error)
	CountMentionsMadeByUser(ctx context.Context, actorID int64) (int64, error)
	CountMentionsReceivedByUser(ctx context.Context, userID int64) (int64, error)
	CountMentionsReceivedByUserSince(ctx context.Context, arg CountMentionsReceivedByUserSinceParams) (int64, error)
	CountMessagesReceivedByUser(ctx context.Context, receiverID int64) (int64, error)
	CountMessagesSentByUser(ctx context.Context, senderID int64) (int64, error)
	CountMessagesSentByUserSince(ctx context.Context, arg CountMessagesSentByUserSinceParams) (int64, error)
	CountNoteFoldersByUser(ctx context.Context, userID int64) (int64, error)
	CountNoteLinksBetween(ctx context.Context, arg CountNoteLinksBetweenParams) (int64, error)
	CountNoteLinksBySource(ctx context.Context, sourceNoteID int64) (int64, error)
	CountNoteLinksByTarget(ctx context.Context, targetNoteID int64) (int64, error)
	CountNoteTemplatesByUser(ctx context.Context, userID int64) (int64, error)
	CountNoteVersionsByNote(ctx context.Context, noteID int64) (int64, error)
	CountNotesByUser(ctx context.Context, userID int64) (int64, error)
	CountNotesByUserSince(ctx context.Context, arg CountNotesByUserSinceParams) (int64, error)
	CountNotificationsByUser(ctx context.Context, userID int64) (int64, error)
	CountNotificationsByUserSince(ctx context.Context, arg CountNotificationsByUserSinceParams) (int64, error)
	CountPostLikeByUserAndPost(ctx context.Context, arg CountPostLikeByUserAndPostParams) (int64, error)
	CountPostPinsByUser(ctx context.Context, userID int64) (int64, error)
	CountPostPinsByUserAndPost(ctx context.Context, arg CountPostPinsByUserAndPostParams) (int64, error)
	CountPostTemplatesByUserID(ctx context.Context, userID int64) (int64, error)
	CountPostViewsByPost(ctx context.Context, postID int64) (int64, error)
	// 下書きは除外する。
	CountPostsByTag(ctx context.Context, tag string) (int64, error)
	CountPostsByUser(ctx context.Context, userID int64) (int64, error)
	CountPostsByUserSince(ctx context.Context, arg CountPostsByUserSinceParams) (int64, error)
	// タグはAND条件（全タグが付与されている投稿のみ）。空配列なら絞り込みなし
	// （cardinality(タグ配列)=0のときCOUNT(...)側も0になり両辺が一致するため自然に通る）。
	CountPostsWithFilter(ctx context.Context, arg CountPostsWithFilterParams) (int64, error)
	CountPublishedPostsByUser(ctx context.Context, userID int64) (int64, error)
	// questions/answers は GORM の論理削除（deleted_at）付きモデルのため、GORMの既定スコープに
	// 合わせて deleted_at IS NULL を明示する（Unscoped() されていない全クエリと同じ挙動）。
	CountQuestionsByUser(ctx context.Context, userID int64) (int64, error)
	CountReactionsReceivedByUser(ctx context.Context, userID int64) (int64, error)
	CountReactionsReceivedByUserSince(ctx context.Context, arg CountReactionsReceivedByUserSinceParams) (int64, error)
	CountRepliesByUser(ctx context.Context, userID int64) (int64, error)
	CountResourceProgressByUser(ctx context.Context, arg CountResourceProgressByUserParams) (int64, error)
	CountRoadmapsByUser(ctx context.Context, userID int64) (int64, error)
	CountRoadmapsByUserAndStatus(ctx context.Context, arg CountRoadmapsByUserAndStatusParams) (int64, error)
	CountSearchNotes(ctx context.Context, arg CountSearchNotesParams) (int64, error)
	CountStreakFreezesInMonth(ctx context.Context, arg CountStreakFreezesInMonthParams) (int64, error)
	CountStreakFreezesOnDate(ctx context.Context, arg CountStreakFreezesOnDateParams) (int64, error)
	CountStudyCircleCheckinsByCircle(ctx context.Context, circleID int64) (int64, error)
	CountStudyCircleCompletedStepsByCircle(ctx context.Context, circleID int64) (int64, error)
	CountStudyCircleMembersByCircle(ctx context.Context, circleID int64) (int64, error)
	CountStudyCircleStepsByCircle(ctx context.Context, circleID int64) (int64, error)
	CountTopLevelCommentsByUser(ctx context.Context, userID int64) (int64, error)
	CountUniqueReactorsByUser(ctx context.Context, userID int64) (int64, error)
	CountUnreadNotificationsByUser(ctx context.Context, userID int64) (int64, error)
	CountUserActivitiesByUser(ctx context.Context, userID int64) (int64, error)
	CountUserActivitiesByUserAndType(ctx context.Context, arg CountUserActivitiesByUserAndTypeParams) (int64, error)
	CreateAIAdvice(ctx context.Context, arg CreateAIAdviceParams) (AiAdvice, error)
	CreateBookmark(ctx context.Context, arg CreateBookmarkParams) error
	CreateCommentLike(ctx context.Context, arg CreateCommentLikeParams) error
	// 同時に複数リクエストが「不在」と判定してもuser_idの一意制約とDO NOTHINGで
	// 競合を無害化する。競合で挿入されなかった場合は0行が返る（エラーにはしない）。
	CreateDefaultReminderSettings(ctx context.Context, arg CreateDefaultReminderSettingsParams) ([]ReminderSetting, error)
	CreateFollow(ctx context.Context, arg CreateFollowParams) error
	CreateGroupMessage(ctx context.Context, arg CreateGroupMessageParams) (GroupMessage, error)
	// GORMの clause.OnConflict{DoNothing: true} に相当。衝突時は RETURNING 行が無くなるため
	// pgx.ErrNoRows を「作成されなかった」判定に使う。
	CreateMention(ctx context.Context, arg CreateMentionParams) (Mention, error)
	CreateMessage(ctx context.Context, arg CreateMessageParams) (Message, error)
	CreateNote(ctx context.Context, arg CreateNoteParams) (Note, error)
	CreateNoteFolder(ctx context.Context, arg CreateNoteFolderParams) (NoteFolder, error)
	CreateNoteLink(ctx context.Context, arg CreateNoteLinkParams) error
	CreateNoteTemplate(ctx context.Context, arg CreateNoteTemplateParams) (NoteTemplate, error)
	CreateNoteVersion(ctx context.Context, arg CreateNoteVersionParams) (NoteVersion, error)
	CreateNotificationSettings(ctx context.Context, arg CreateNotificationSettingsParams) (NotificationSetting, error)
	CreatePasswordResetToken(ctx context.Context, arg CreatePasswordResetTokenParams) (PasswordResetToken, error)
	CreatePostComment(ctx context.Context, arg CreatePostCommentParams) (Comment, error)
	CreatePostLike(ctx context.Context, arg CreatePostLikeParams) error
	CreatePostPin(ctx context.Context, arg CreatePostPinParams) error
	CreatePostTag(ctx context.Context, arg CreatePostTagParams) error
	CreatePostTemplate(ctx context.Context, arg CreatePostTemplateParams) (PostTemplate, error)
	// GORMの clause.OnConflict{DoNothing: true} に相当。実際に挿入できた行数を返し、
	// 呼び出し側で「既に閲覧済みだったか」を判定する。
	CreatePostView(ctx context.Context, arg CreatePostViewParams) (int64, error)
	CreateProjectMilestone(ctx context.Context, arg CreateProjectMilestoneParams) (ProjectMilestone, error)
	CreateReaction(ctx context.Context, arg CreateReactionParams) error
	CreateStreakFreeze(ctx context.Context, arg CreateStreakFreezeParams) (StreakFreeze, error)
	CreateWeeklyChallenge(ctx context.Context, arg CreateWeeklyChallengeParams) (WeeklyChallenge, error)
	DecrementCommentLikeCount(ctx context.Context, id int64) error
	DecrementPostBookmarkCount(ctx context.Context, id int64) error
	DecrementPostCommentCount(ctx context.Context, id int64) error
	DecrementPostLikeCount(ctx context.Context, id int64) error
	DeleteAIAdvicesByUser(ctx context.Context, userID int64) error
	DeleteBookmark(ctx context.Context, arg DeleteBookmarkParams) (int64, error)
	DeleteCommentLike(ctx context.Context, arg DeleteCommentLikeParams) error
	DeleteFollow(ctx context.Context, arg DeleteFollowParams) error
	DeleteMentionsByCommentID(ctx context.Context, commentID *int64) error
	DeleteMentionsByPostID(ctx context.Context, postID *int64) error
	DeleteNote(ctx context.Context, id int64) error
	DeleteNoteFolder(ctx context.Context, id int64) error
	DeleteNoteLink(ctx context.Context, arg DeleteNoteLinkParams) error
	DeleteNoteTemplate(ctx context.Context, id int64) error
	DeletePostComment(ctx context.Context, id int64) error
	DeletePostLike(ctx context.Context, arg DeletePostLikeParams) (int64, error)
	DeletePostPin(ctx context.Context, arg DeletePostPinParams) error
	DeletePostTagsByPostID(ctx context.Context, postID int64) error
	DeletePostTemplate(ctx context.Context, id int64) error
	DeleteProjectMilestone(ctx context.Context, id int64) error
	DeleteReaction(ctx context.Context, arg DeleteReactionParams) error
	DeleteSpotifyRecentTracksByUser(ctx context.Context, userID int64) error
	// book_reviews は GORM の論理削除（deleted_at）付きモデルのため、GORMの既定スコープに合わせて
	// deleted_at IS NULL を明示する。レビュー0件でもCOALESCEにより全項目0を返す
	// （GORM実装のtotal_reviews==0での早期returnと同じ結果になる）。
	GetBookReviewStats(ctx context.Context, userID int64) (GetBookReviewStatsRow, error)
	GetCommentByID(ctx context.Context, id int64) (Comment, error)
	GetDefaultNoteTemplateByUser(ctx context.Context, userID int64) (NoteTemplate, error)
	GetEmojiBreakdownByUser(ctx context.Context, userID int64) ([]GetEmojiBreakdownByUserRow, error)
	GetLatestNoteVersionNumber(ctx context.Context, noteID int64) (int64, error)
	// learning_resources は GORM の論理削除（deleted_at）付きモデルのため deleted_at IS NULL を明示する。
	GetLearningResourceByID(ctx context.Context, id int64) (LearningResource, error)
	// GORMのPreload("User").Preload("Folder")に相当。
	// folder_idはNULL許容のためLEFT JOIN。note_foldersはsqlc.embedを使わず個別カラム選択にすることで、
	// sqlcのJOIN文脈依存のnull推論（LEFT JOIN側は全カラムがnullableになる）を効かせる。
	// sqlc.embedは対象テーブル自身のスキーマ上のnull許容性をそのまま使うため、LEFT JOINで欠落しうる
	// 行に対しては非NULL型（例: NoteFolder.ID int64）のままとなりスキャン時にエラーとなる。
	GetNoteByID(ctx context.Context, id int64) (GetNoteByIDRow, error)
	GetNoteFolderByID(ctx context.Context, id int64) (NoteFolder, error)
	GetNoteTemplateByID(ctx context.Context, id int64) (NoteTemplate, error)
	GetNoteVersionByID(ctx context.Context, id int64) (NoteVersion, error)
	GetNotificationSettingsByUserID(ctx context.Context, userID int64) (NotificationSetting, error)
	GetPasswordResetTokenByToken(ctx context.Context, token string) (PasswordResetToken, error)
	GetPostAuthorID(ctx context.Context, id int64) (int64, error)
	GetPostTemplateByID(ctx context.Context, id int64) (PostTemplate, error)
	// GORMのPreload("User")に相当（CodeSnippetsはpost_bookmark.sqlのListCodeSnippetsByPostIDsで別途取得する）。
	// user_idはNOT NULLのためINNER JOINでよい。
	GetPostWithUserByID(ctx context.Context, id int64) (GetPostWithUserByIDRow, error)
	GetProjectMilestoneByID(ctx context.Context, id int64) (ProjectMilestone, error)
	// projects は GORM の論理削除（deleted_at）付きモデルのため、GORMの既定スコープに合わせて
	// deleted_at IS NULL を明示する（Unscoped() されていない全クエリと同じ挙動）。
	GetProjectStats(ctx context.Context, userID int64) (GetProjectStatsRow, error)
	// GORMのPreload("User").Preload("GithubRepo")に相当。
	// projectsはGORMの論理削除（deleted_at）付きモデルのためdeleted_at IS NULLを明示する。
	// github_repo_idはNULL許容のためLEFT JOIN。git_hub_repositoriesはsqlc.embedを使わず
	// 個別カラム選択にすることで、sqlcのJOIN文脈依存のnull推論を効かせる
	// （sqlc.embedは対象テーブル自身のスキーマ上のnull許容性をそのまま使ってしまい、
	// LEFT JOINで欠落しうる行を表現できないため）。
	GetProjectWithUserAndRepoByID(ctx context.Context, id int64) (GetProjectWithUserAndRepoByIDRow, error)
	GetReminderSettingsByUserID(ctx context.Context, userID int64) (ReminderSetting, error)
	GetResourceProgressByUserAndResource(ctx context.Context, arg GetResourceProgressByUserAndResourceParams) (ResourceProgress, error)
	GetTopReactedPostsByUser(ctx context.Context, arg GetTopReactedPostsByUserParams) ([]GetTopReactedPostsByUserRow, error)
	GetUserByIDForChatSender(ctx context.Context, id int64) (User, error)
	GetWeeklyChallengeByUserAndWeek(ctx context.Context, arg GetWeeklyChallengeByUserAndWeekParams) (WeeklyChallenge, error)
	GetWidgetSettingsByUserID(ctx context.Context, userID int64) (WidgetSetting, error)
	HasStreakFreezeOnDate(ctx context.Context, arg HasStreakFreezeOnDateParams) (bool, error)
	IncrementCommentLikeCount(ctx context.Context, id int64) error
	IncrementPostBookmarkCount(ctx context.Context, id int64) error
	IncrementPostCommentCount(ctx context.Context, id int64) error
	IncrementPostLikeCount(ctx context.Context, id int64) error
	IncrementPostViewCount(ctx context.Context, id int64) error
	InvalidateUserPasswordResetTokens(ctx context.Context, userID int64) error
	ListAIAdvicesByUser(ctx context.Context, arg ListAIAdvicesByUserParams) ([]AiAdvice, error)
	ListArchivedNotesByUser(ctx context.Context, arg ListArchivedNotesByUserParams) ([]ListArchivedNotesByUserRow, error)
	// GORMのPreload("User")に相当（CodeSnippetsは別クエリで取得しGo側で結合する）。
	// user_id/post_idともにNOT NULLのためINNER JOINでよい。
	ListBookmarkedPostsByUser(ctx context.Context, arg ListBookmarkedPostsByUserParams) ([]ListBookmarkedPostsByUserRow, error)
	ListChatRoomMemberUserIDs(ctx context.Context, chatRoomID int64) ([]int64, error)
	// GORMのPreload("CodeSnippets")に相当。1対多のため投稿IDのまとめ取りとGo側でのグルーピングで再現する。
	ListCodeSnippetsByPostIDs(ctx context.Context, dollar_1 []int64) ([]CodeSnippet, error)
	// GORMのPreload("User")に相当（返信の取得）。ListReplies単体呼び出しと
	// ListByPostIDのバッチ取得の両方で、親IDの配列（1件でも複数件でも）として再利用する。
	ListCommentRepliesByParentIDs(ctx context.Context, parentIds []int64) ([]ListCommentRepliesByParentIDsRow, error)
	// GORMのPreload("Sender").Preload("Receiver")に相当。
	// sender_id/receiver_idともにNOT NULLのためINNER JOINでよい。
	ListConversationMessages(ctx context.Context, arg ListConversationMessagesParams) ([]ListConversationMessagesRow, error)
	// 会話相手ごとの最新メッセージと未読件数を取得する（移行前のGORM Raw SQLをそのまま踏襲）。
	ListConversationSummaries(ctx context.Context, receiverID int64) ([]ListConversationSummariesRow, error)
	ListFavoriteNotesByUser(ctx context.Context, arg ListFavoriteNotesByUserParams) ([]ListFavoriteNotesByUserRow, error)
	// 件数は follow_stats.sql の CountFollowersByUser を再利用する。
	ListFollowers(ctx context.Context, arg ListFollowersParams) ([]User, error)
	// 件数は follow_stats.sql の CountFollowingByUser を再利用する。
	ListFollowing(ctx context.Context, arg ListFollowingParams) ([]User, error)
	// GitHub連続コントリビューション日数の算出に使う（countが正の日のみ、新しい順）。
	ListGitHubContributionsByUser(ctx context.Context, userID int64) ([]ListGitHubContributionsByUserRow, error)
	// GORMのPreload("Sender")に相当。sender_idはNOT NULLのためINNER JOINでよい。
	ListGroupMessagesByRoom(ctx context.Context, arg ListGroupMessagesByRoomParams) ([]ListGroupMessagesByRoomRow, error)
	// 学習ログの連続記録日数（ストリーク）算出に使う、記録のある日付一覧（新しい順）。
	ListLearningLogDatesByUser(ctx context.Context, userID int64) ([]pgtype.Date, error)
	ListMentionsByCommentID(ctx context.Context, commentID *int64) ([]ListMentionsByCommentIDRow, error)
	// GORMのPreload("User").Preload("Actor")に相当。user_id/actor_idともにNOT NULLのためINNER JOINでよい。
	ListMentionsByPostID(ctx context.Context, postID *int64) ([]ListMentionsByPostIDRow, error)
	// GORMのPreload("Actor")に相当。actor_idはNOT NULLのためINNER JOINでよい。
	ListMentionsByUser(ctx context.Context, arg ListMentionsByUserParams) ([]ListMentionsByUserRow, error)
	ListMostViewedPosts(ctx context.Context, limit int32) ([]ListMostViewedPostsRow, error)
	ListNoteFoldersByParent(ctx context.Context, parentID *int64) ([]NoteFolder, error)
	ListNoteFoldersByUser(ctx context.Context, arg ListNoteFoldersByUserParams) ([]NoteFolder, error)
	// GORMのPreload("TargetNote")に相当。リンク先ノートをsqlc.embedで一緒に取得する。
	ListNoteLinksBySource(ctx context.Context, sourceNoteID int64) ([]ListNoteLinksBySourceRow, error)
	// GORMのPreload("SourceNote")に相当。リンク元ノートをsqlc.embedで一緒に取得する。
	ListNoteLinksByTarget(ctx context.Context, targetNoteID int64) ([]ListNoteLinksByTargetRow, error)
	ListNoteTemplatesByUser(ctx context.Context, userID int64) ([]NoteTemplate, error)
	ListNoteVersionsByNote(ctx context.Context, arg ListNoteVersionsByNoteParams) ([]NoteVersion, error)
	ListNotesByFolder(ctx context.Context, arg ListNotesByFolderParams) ([]Note, error)
	// GORMのPreload("Folder")に相当。folder_idはNULL許容のためLEFT JOIN（理由は GetNoteByID と同じ）。
	ListNotesByUser(ctx context.Context, arg ListNotesByUserParams) ([]ListNotesByUserRow, error)
	ListPopularTags(ctx context.Context, limit int32) ([]ListPopularTagsRow, error)
	// ページングはpost_tags.id順で決め、実データ（Post本体）は別クエリでcreated_at順に取得する
	// （移行前のGORM実装と同じ2段構え）。
	ListPostIDsByTag(ctx context.Context, arg ListPostIDsByTagParams) ([]int64, error)
	// GORMのPreload("Post").Preload("Post.User")に相当。user_id/post_idともにNOT NULLのためINNER JOINでよい。
	ListPostPinsByUser(ctx context.Context, userID int64) ([]ListPostPinsByUserRow, error)
	ListPostTagsByPostID(ctx context.Context, postID int64) ([]string, error)
	ListPostTemplatesByUserID(ctx context.Context, arg ListPostTemplatesByUserIDParams) ([]PostTemplate, error)
	// GORMのPreload("User")に相当。user_idはNOT NULLのためINNER JOINでよい。
	ListPostsByIDs(ctx context.Context, dollar_1 []int64) ([]ListPostsByIDsRow, error)
	ListProjectMilestonesByProject(ctx context.Context, projectID int64) ([]ProjectMilestone, error)
	ListReactionCountsByPost(ctx context.Context, postID int64) ([]ListReactionCountsByPostRow, error)
	ListReactionCountsByPosts(ctx context.Context, dollar_1 []int64) ([]ListReactionCountsByPostsRow, error)
	// GORMのPreload("Resource")に相当。resourceは論理削除（deleted_at）付きモデルのため、
	// ソフトデリート済みリソースはJOIN条件で除外しResourceがnilになるようLEFT JOINにする
	// （resource_idの列自体はNOT NULLだが、論理削除の有無でJOINの成否が変わるため）。
	// id を第2ソートキーにして、updated_at 同値の行でもページングが安定するようにする
	// （移行前のGORM実装と同じ）。
	ListResourceProgressByUser(ctx context.Context, arg ListResourceProgressByUserParams) ([]ListResourceProgressByUserRow, error)
	ListRootNoteFoldersByUser(ctx context.Context, userID int64) ([]NoteFolder, error)
	ListStreakFreezesByUserAndMonth(ctx context.Context, arg ListStreakFreezesByUserAndMonthParams) ([]StreakFreeze, error)
	// GORMのPreload("User")に相当。user_idはNOT NULLのためINNER JOINでよい。
	ListTopLevelCommentsByPost(ctx context.Context, postID int64) ([]ListTopLevelCommentsByPostRow, error)
	ListUnreadAIAdvicesByUser(ctx context.Context, userID int64) ([]AiAdvice, error)
	ListUserActivitiesByUser(ctx context.Context, arg ListUserActivitiesByUserParams) ([]UserActivity, error)
	ListUserActivitiesByUserAndType(ctx context.Context, arg ListUserActivitiesByUserAndTypeParams) ([]UserActivity, error)
	ListUserReactionEmojisByPost(ctx context.Context, arg ListUserReactionEmojisByPostParams) ([]string, error)
	ListUserReactionsByPosts(ctx context.Context, arg ListUserReactionsByPostsParams) ([]ListUserReactionsByPostsRow, error)
	ListWeeklyGoalsByUser(ctx context.Context, userID int64) ([]WeeklyGoal, error)
	// 同一ユーザーの CreateWithinLimits 同時実行を直列化するための行ロック（GORMの clause.Locking{Strength: "UPDATE"} に相当）。
	LockUserForStreakFreeze(ctx context.Context, id int64) error
	MarkAIAdviceAsRead(ctx context.Context, arg MarkAIAdviceAsReadParams) (int64, error)
	MarkMessagesAsRead(ctx context.Context, arg MarkMessagesAsReadParams) error
	MarkPasswordResetTokenAsUsed(ctx context.Context, id int64) error
	SearchNotes(ctx context.Context, arg SearchNotesParams) ([]SearchNotesRow, error)
	// GORMのPreload("User")に相当（CodeSnippetsは別クエリで取得しGo側で結合する）。
	// ソート順はGoの動的Order()呼び出しの代わりに、sort_byごとのCASE式で切り替える
	// （sort_byはクエリ全体で単一の値のため、行ごとにNULLになったり値になったりはしない）。
	SearchPostsWithFilter(ctx context.Context, arg SearchPostsWithFilterParams) ([]SearchPostsWithFilterRow, error)
	SumAnswerVotesByUser(ctx context.Context, userID int64) (int64, error)
	SumCodeSnippetCommentCountByUser(ctx context.Context, userID int64) (int64, error)
	SumGitHubContributionsByUser(ctx context.Context, userID int64) (int64, error)
	SumLearningLogDurationByUser(ctx context.Context, userID int64) (int64, error)
	SumLearningLogDurationByUserCategorySince(ctx context.Context, arg SumLearningLogDurationByUserCategorySinceParams) (int64, error)
	SumLearningResourceLikeCountByUser(ctx context.Context, userID int64) (int64, error)
	SumLearningResourceSaveCountByUser(ctx context.Context, userID int64) (int64, error)
	SumPostCommentsReceivedByUser(ctx context.Context, userID int64) (int64, error)
	SumPostLikesReceivedByUser(ctx context.Context, userID int64) (int64, error)
	SumQuestionVotesByUser(ctx context.Context, userID int64) (int64, error)
	SumRoadmapCompletedStepCountByUser(ctx context.Context, userID int64) (int64, error)
	SumRoadmapStepCountByUser(ctx context.Context, userID int64) (int64, error)
	ToggleNoteFavorite(ctx context.Context, id int64) error
	UnarchiveNote(ctx context.Context, id int64) error
	// GORMのSave（全カラム上書き）に相当。
	UpdateNote(ctx context.Context, arg UpdateNoteParams) (Note, error)
	UpdateNoteFolder(ctx context.Context, arg UpdateNoteFolderParams) (NoteFolder, error)
	UpdateNoteTemplate(ctx context.Context, arg UpdateNoteTemplateParams) (NoteTemplate, error)
	UpdateNotificationSettings(ctx context.Context, arg UpdateNotificationSettingsParams) (NotificationSetting, error)
	// GORMのSave（全カラム上書き）に相当。呼び出し側は必ずDBから読み込んだcommentの
	// content/is_hiddenだけを変更してから呼ぶため、この2カラムの書き戻しで等価になる。
	UpdatePostComment(ctx context.Context, arg UpdatePostCommentParams) (Comment, error)
	UpdatePostPinOrder(ctx context.Context, arg UpdatePostPinOrderParams) error
	UpdatePostTemplate(ctx context.Context, arg UpdatePostTemplateParams) (PostTemplate, error)
	UpdateProjectMilestone(ctx context.Context, arg UpdateProjectMilestoneParams) (ProjectMilestone, error)
	UpdateReminderSettings(ctx context.Context, arg UpdateReminderSettingsParams) (ReminderSetting, error)
	UpdateWeeklyChallenge(ctx context.Context, arg UpdateWeeklyChallengeParams) (WeeklyChallenge, error)
	UpsertResourceProgress(ctx context.Context, arg UpsertResourceProgressParams) (ResourceProgress, error)
	UpsertWeeklyGoal(ctx context.Context, arg UpsertWeeklyGoalParams) (WeeklyGoal, error)
	UpsertWidgetSettings(ctx context.Context, arg UpsertWidgetSettingsParams) error
}

var _ Querier = (*Queries)(nil)
