// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlcgen

import (
	"context"
)

type Querier interface {
	CountAnswersByUser(ctx context.Context, userID int64) (int64, error)
	CountArchivedNotesByUser(ctx context.Context, userID int64) (int64, error)
	CountBestAnswersByUser(ctx context.Context, userID int64) (int64, error)
	CountBookmarksMadeByUser(ctx context.Context, userID int64) (int64, error)
	CountBookmarksMadeByUserSince(ctx context.Context, arg CountBookmarksMadeByUserSinceParams) (int64, error)
	CountBookmarksReceivedByUser(ctx context.Context, userID int64) (int64, error)
	CountCodeSnippetLanguagesByUser(ctx context.Context, userID int64) (int64, error)
	CountCodeSnippetsByUser(ctx context.Context, userID int64) (int64, error)
	CountCommentsByUserSince(ctx context.Context, arg CountCommentsByUserSinceParams) (int64, error)
	CountCommentsReceivedByUser(ctx context.Context, userID int64) (int64, error)
	CountConversationsByUser(ctx context.Context, senderID int64) (int64, error)
	CountFavoriteNotesByUser(ctx context.Context, userID int64) (int64, error)
	CountFollowersByUser(ctx context.Context, followeeID int64) (int64, error)
	CountFollowingByUser(ctx context.Context, followerID int64) (int64, error)
	CountLearningLogCategoriesByUser(ctx context.Context, userID int64) (int64, error)
	CountLearningLogsByUser(ctx context.Context, userID int64) (int64, error)
	CountLearningLogsByUserSince(ctx context.Context, arg CountLearningLogsByUserSinceParams) (int64, error)
	CountLearningResourceCategoriesByUser(ctx context.Context, userID int64) (int64, error)
	// learning_resources は GORM の論理削除（deleted_at）付きモデルのため、GORMの既定スコープに
	// 合わせて deleted_at IS NULL を明示する（Unscoped() されていない全クエリと同じ挙動）。
	CountLearningResourcesByUser(ctx context.Context, userID int64) (int64, error)
	CountMentionsMadeByUser(ctx context.Context, actorID int64) (int64, error)
	CountMentionsReceivedByUser(ctx context.Context, userID int64) (int64, error)
	CountMentionsReceivedByUserSince(ctx context.Context, arg CountMentionsReceivedByUserSinceParams) (int64, error)
	CountMessagesReceivedByUser(ctx context.Context, receiverID int64) (int64, error)
	CountMessagesSentByUser(ctx context.Context, senderID int64) (int64, error)
	CountMessagesSentByUserSince(ctx context.Context, arg CountMessagesSentByUserSinceParams) (int64, error)
	CountNoteFoldersByUser(ctx context.Context, userID int64) (int64, error)
	CountNotesByUser(ctx context.Context, userID int64) (int64, error)
	CountNotesByUserSince(ctx context.Context, arg CountNotesByUserSinceParams) (int64, error)
	CountNotificationsByUser(ctx context.Context, userID int64) (int64, error)
	CountNotificationsByUserSince(ctx context.Context, arg CountNotificationsByUserSinceParams) (int64, error)
	CountPostTemplatesByUserID(ctx context.Context, userID int64) (int64, error)
	// questions/answers は GORM の論理削除（deleted_at）付きモデルのため、GORMの既定スコープに
	// 合わせて deleted_at IS NULL を明示する（Unscoped() されていない全クエリと同じ挙動）。
	CountQuestionsByUser(ctx context.Context, userID int64) (int64, error)
	CountReactionsReceivedByUser(ctx context.Context, userID int64) (int64, error)
	CountReactionsReceivedByUserSince(ctx context.Context, arg CountReactionsReceivedByUserSinceParams) (int64, error)
	CountRepliesByUser(ctx context.Context, userID int64) (int64, error)
	CountRoadmapsByUser(ctx context.Context, userID int64) (int64, error)
	CountRoadmapsByUserAndStatus(ctx context.Context, arg CountRoadmapsByUserAndStatusParams) (int64, error)
	CountStudyCircleCheckinsByCircle(ctx context.Context, circleID int64) (int64, error)
	CountStudyCircleCompletedStepsByCircle(ctx context.Context, circleID int64) (int64, error)
	CountStudyCircleMembersByCircle(ctx context.Context, circleID int64) (int64, error)
	CountStudyCircleStepsByCircle(ctx context.Context, circleID int64) (int64, error)
	CountTopLevelCommentsByUser(ctx context.Context, userID int64) (int64, error)
	CountUniqueReactorsByUser(ctx context.Context, userID int64) (int64, error)
	CountUnreadNotificationsByUser(ctx context.Context, userID int64) (int64, error)
	CreatePasswordResetToken(ctx context.Context, arg CreatePasswordResetTokenParams) (PasswordResetToken, error)
	CreatePostTemplate(ctx context.Context, arg CreatePostTemplateParams) (PostTemplate, error)
	CreateWeeklyChallenge(ctx context.Context, arg CreateWeeklyChallengeParams) (WeeklyChallenge, error)
	DeletePostTemplate(ctx context.Context, id int64) error
	// book_reviews は GORM の論理削除（deleted_at）付きモデルのため、GORMの既定スコープに合わせて
	// deleted_at IS NULL を明示する。レビュー0件でもCOALESCEにより全項目0を返す
	// （GORM実装のtotal_reviews==0での早期returnと同じ結果になる）。
	GetBookReviewStats(ctx context.Context, userID int64) (GetBookReviewStatsRow, error)
	GetEmojiBreakdownByUser(ctx context.Context, userID int64) ([]GetEmojiBreakdownByUserRow, error)
	GetPasswordResetTokenByToken(ctx context.Context, token string) (PasswordResetToken, error)
	GetPostTemplateByID(ctx context.Context, id int64) (PostTemplate, error)
	// projects は GORM の論理削除（deleted_at）付きモデルのため、GORMの既定スコープに合わせて
	// deleted_at IS NULL を明示する（Unscoped() されていない全クエリと同じ挙動）。
	GetProjectStats(ctx context.Context, userID int64) (GetProjectStatsRow, error)
	GetTopReactedPostsByUser(ctx context.Context, arg GetTopReactedPostsByUserParams) ([]GetTopReactedPostsByUserRow, error)
	GetWeeklyChallengeByUserAndWeek(ctx context.Context, arg GetWeeklyChallengeByUserAndWeekParams) (WeeklyChallenge, error)
	InvalidateUserPasswordResetTokens(ctx context.Context, userID int64) error
	ListPostTemplatesByUserID(ctx context.Context, arg ListPostTemplatesByUserIDParams) ([]PostTemplate, error)
	MarkPasswordResetTokenAsUsed(ctx context.Context, id int64) error
	SumAnswerVotesByUser(ctx context.Context, userID int64) (int64, error)
	SumCodeSnippetCommentCountByUser(ctx context.Context, userID int64) (int64, error)
	SumLearningLogDurationByUser(ctx context.Context, userID int64) (int64, error)
	SumLearningResourceLikeCountByUser(ctx context.Context, userID int64) (int64, error)
	SumLearningResourceSaveCountByUser(ctx context.Context, userID int64) (int64, error)
	SumQuestionVotesByUser(ctx context.Context, userID int64) (int64, error)
	SumRoadmapCompletedStepCountByUser(ctx context.Context, userID int64) (int64, error)
	SumRoadmapStepCountByUser(ctx context.Context, userID int64) (int64, error)
	UpdatePostTemplate(ctx context.Context, arg UpdatePostTemplateParams) (PostTemplate, error)
	UpdateWeeklyChallenge(ctx context.Context, arg UpdateWeeklyChallengeParams) (WeeklyChallenge, error)
}

var _ Querier = (*Queries)(nil)
