// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: question.sql

package sqlcgen

import (
	"context"
)

const adjustQuestionVoteCount = `-- name: AdjustQuestionVoteCount :exec
UPDATE questions SET vote_count = vote_count + $1::bigint
WHERE questions.id = $2
`

type AdjustQuestionVoteCountParams struct {
	Diff int64
	ID   int64
}

func (q *Queries) AdjustQuestionVoteCount(ctx context.Context, arg AdjustQuestionVoteCountParams) error {
	_, err := q.db.Exec(ctx, adjustQuestionVoteCount, arg.Diff, arg.ID)
	return err
}

const countBookmarkedQuestions = `-- name: CountBookmarkedQuestions :one
SELECT COUNT(*) FROM questions
WHERE questions.id IN (
    SELECT qb.question_id FROM question_bookmarks qb WHERE qb.user_id = $1
)
`

func (q *Queries) CountBookmarkedQuestions(ctx context.Context, userID int64) (int64, error) {
	row := q.db.QueryRow(ctx, countBookmarkedQuestions, userID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countQuestionBookmark = `-- name: CountQuestionBookmark :one
SELECT COUNT(*) FROM question_bookmarks
WHERE question_bookmarks.user_id = $1 AND question_bookmarks.question_id = $2
`

type CountQuestionBookmarkParams struct {
	UserID     int64
	QuestionID int64
}

func (q *Queries) CountQuestionBookmark(ctx context.Context, arg CountQuestionBookmarkParams) (int64, error) {
	row := q.db.QueryRow(ctx, countQuestionBookmark, arg.UserID, arg.QuestionID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countQuestions = `-- name: CountQuestions :one
SELECT COUNT(*) FROM questions
WHERE ($1::text IS NULL OR questions.tags ILIKE $1)
    AND ($2::text != 'unanswered' OR questions.answer_count = 0)
`

type CountQuestionsParams struct {
	TagPattern *string
	Sort       string
}

func (q *Queries) CountQuestions(ctx context.Context, arg CountQuestionsParams) (int64, error) {
	row := q.db.QueryRow(ctx, countQuestions, arg.TagPattern, arg.Sort)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countSearchQuestions = `-- name: CountSearchQuestions :one
SELECT COUNT(*) FROM questions
WHERE (questions.title ILIKE $1 OR questions.body ILIKE $1 OR questions.tags ILIKE $1)
`

func (q *Queries) CountSearchQuestions(ctx context.Context, title string) (int64, error) {
	row := q.db.QueryRow(ctx, countSearchQuestions, title)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countSolvedQuestions = `-- name: CountSolvedQuestions :one
SELECT COUNT(*) FROM questions WHERE questions.is_solved = true
`

func (q *Queries) CountSolvedQuestions(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countSolvedQuestions)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countUnansweredQuestions = `-- name: CountUnansweredQuestions :one
SELECT COUNT(*) FROM questions WHERE questions.answer_count = 0
`

func (q *Queries) CountUnansweredQuestions(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countUnansweredQuestions)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createQuestion = `-- name: CreateQuestion :one
INSERT INTO questions (
    user_id, title, body, tags, vote_count, answer_count, is_solved, created_at, updated_at
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, now(), now()
) RETURNING id, user_id, title, body, tags, vote_count, answer_count, is_solved, created_at, updated_at
`

type CreateQuestionParams struct {
	UserID      int64
	Title       string
	Body        string
	Tags        *string
	VoteCount   *int64
	AnswerCount *int64
	IsSolved    bool
}

func (q *Queries) CreateQuestion(ctx context.Context, arg CreateQuestionParams) (Question, error) {
	row := q.db.QueryRow(ctx, createQuestion,
		arg.UserID,
		arg.Title,
		arg.Body,
		arg.Tags,
		arg.VoteCount,
		arg.AnswerCount,
		arg.IsSolved,
	)
	var i Question
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Title,
		&i.Body,
		&i.Tags,
		&i.VoteCount,
		&i.AnswerCount,
		&i.IsSolved,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createQuestionBookmark = `-- name: CreateQuestionBookmark :exec
INSERT INTO question_bookmarks (user_id, question_id, created_at) VALUES ($1, $2, now())
`

type CreateQuestionBookmarkParams struct {
	UserID     int64
	QuestionID int64
}

func (q *Queries) CreateQuestionBookmark(ctx context.Context, arg CreateQuestionBookmarkParams) error {
	_, err := q.db.Exec(ctx, createQuestionBookmark, arg.UserID, arg.QuestionID)
	return err
}

const createQuestionVote = `-- name: CreateQuestionVote :one
INSERT INTO question_votes (user_id, question_id, value, created_at)
VALUES ($1, $2, $3, now())
RETURNING id, user_id, question_id, value, created_at
`

type CreateQuestionVoteParams struct {
	UserID     int64
	QuestionID int64
	Value      int64
}

func (q *Queries) CreateQuestionVote(ctx context.Context, arg CreateQuestionVoteParams) (QuestionVote, error) {
	row := q.db.QueryRow(ctx, createQuestionVote, arg.UserID, arg.QuestionID, arg.Value)
	var i QuestionVote
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.QuestionID,
		&i.Value,
		&i.CreatedAt,
	)
	return i, err
}

const deleteQuestion = `-- name: DeleteQuestion :exec
DELETE FROM questions WHERE questions.id = $1
`

// 依存する回答・投票・ブックマーク等はFKのON DELETE CASCADEでDBが自動的に削除する。
func (q *Queries) DeleteQuestion(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, deleteQuestion, id)
	return err
}

const deleteQuestionBookmark = `-- name: DeleteQuestionBookmark :exec
DELETE FROM question_bookmarks
WHERE question_bookmarks.user_id = $1 AND question_bookmarks.question_id = $2
`

type DeleteQuestionBookmarkParams struct {
	UserID     int64
	QuestionID int64
}

func (q *Queries) DeleteQuestionBookmark(ctx context.Context, arg DeleteQuestionBookmarkParams) error {
	_, err := q.db.Exec(ctx, deleteQuestionBookmark, arg.UserID, arg.QuestionID)
	return err
}

const deleteQuestionVote = `-- name: DeleteQuestionVote :exec
DELETE FROM question_votes
WHERE question_votes.user_id = $1 AND question_votes.question_id = $2
`

type DeleteQuestionVoteParams struct {
	UserID     int64
	QuestionID int64
}

func (q *Queries) DeleteQuestionVote(ctx context.Context, arg DeleteQuestionVoteParams) error {
	_, err := q.db.Exec(ctx, deleteQuestionVote, arg.UserID, arg.QuestionID)
	return err
}

const getQuestionVoteByUserAndQuestion = `-- name: GetQuestionVoteByUserAndQuestion :one
SELECT id, user_id, question_id, value, created_at FROM question_votes
WHERE question_votes.user_id = $1 AND question_votes.question_id = $2
`

type GetQuestionVoteByUserAndQuestionParams struct {
	UserID     int64
	QuestionID int64
}

func (q *Queries) GetQuestionVoteByUserAndQuestion(ctx context.Context, arg GetQuestionVoteByUserAndQuestionParams) (QuestionVote, error) {
	row := q.db.QueryRow(ctx, getQuestionVoteByUserAndQuestion, arg.UserID, arg.QuestionID)
	var i QuestionVote
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.QuestionID,
		&i.Value,
		&i.CreatedAt,
	)
	return i, err
}

const getQuestionWithUserByID = `-- name: GetQuestionWithUserByID :one
SELECT questions.id, questions.user_id, questions.title, questions.body, questions.tags, questions.vote_count, questions.answer_count, questions.is_solved, questions.created_at, questions.updated_at, users.id, users.username, users.name, users.email, users.avatar_url, users.bio, users.git_hub_id, users.git_hub_username, users.git_hub_token, users.git_hub_connected, users.spotify_connected, users.spotify_token, users.spotify_refresh_token, users.spotify_token_expiry, users.zenn_username, users.qiita_username, users.at_coder_username, users.paiza_rank, users.skills_languages, users.skills_frameworks, users.onboarding_completed, users.email_weekly_report, users.email_language, users.created_at, users.updated_at
FROM questions
JOIN users ON users.id = questions.user_id
WHERE questions.id = $1
`

type GetQuestionWithUserByIDRow struct {
	Question Question
	User     User
}

// GORMのPreload("User")に相当。user_idはNOT NULLのためINNER JOINでよい。
func (q *Queries) GetQuestionWithUserByID(ctx context.Context, id int64) (GetQuestionWithUserByIDRow, error) {
	row := q.db.QueryRow(ctx, getQuestionWithUserByID, id)
	var i GetQuestionWithUserByIDRow
	err := row.Scan(
		&i.Question.ID,
		&i.Question.UserID,
		&i.Question.Title,
		&i.Question.Body,
		&i.Question.Tags,
		&i.Question.VoteCount,
		&i.Question.AnswerCount,
		&i.Question.IsSolved,
		&i.Question.CreatedAt,
		&i.Question.UpdatedAt,
		&i.User.ID,
		&i.User.Username,
		&i.User.Name,
		&i.User.Email,
		&i.User.AvatarUrl,
		&i.User.Bio,
		&i.User.GitHubID,
		&i.User.GitHubUsername,
		&i.User.GitHubToken,
		&i.User.GitHubConnected,
		&i.User.SpotifyConnected,
		&i.User.SpotifyToken,
		&i.User.SpotifyRefreshToken,
		&i.User.SpotifyTokenExpiry,
		&i.User.ZennUsername,
		&i.User.QiitaUsername,
		&i.User.AtCoderUsername,
		&i.User.PaizaRank,
		&i.User.SkillsLanguages,
		&i.User.SkillsFrameworks,
		&i.User.OnboardingCompleted,
		&i.User.EmailWeeklyReport,
		&i.User.EmailLanguage,
		&i.User.CreatedAt,
		&i.User.UpdatedAt,
	)
	return i, err
}

const listBookmarkedQuestionsWithUser = `-- name: ListBookmarkedQuestionsWithUser :many
SELECT questions.id, questions.user_id, questions.title, questions.body, questions.tags, questions.vote_count, questions.answer_count, questions.is_solved, questions.created_at, questions.updated_at, users.id, users.username, users.name, users.email, users.avatar_url, users.bio, users.git_hub_id, users.git_hub_username, users.git_hub_token, users.git_hub_connected, users.spotify_connected, users.spotify_token, users.spotify_refresh_token, users.spotify_token_expiry, users.zenn_username, users.qiita_username, users.at_coder_username, users.paiza_rank, users.skills_languages, users.skills_frameworks, users.onboarding_completed, users.email_weekly_report, users.email_language, users.created_at, users.updated_at
FROM questions
JOIN users ON users.id = questions.user_id
WHERE questions.id IN (
    SELECT qb.question_id FROM question_bookmarks qb WHERE qb.user_id = $1
)
ORDER BY questions.created_at DESC
LIMIT $2 OFFSET $3
`

type ListBookmarkedQuestionsWithUserParams struct {
	UserID int64
	Limit  int32
	Offset int32
}

type ListBookmarkedQuestionsWithUserRow struct {
	Question Question
	User     User
}

func (q *Queries) ListBookmarkedQuestionsWithUser(ctx context.Context, arg ListBookmarkedQuestionsWithUserParams) ([]ListBookmarkedQuestionsWithUserRow, error) {
	rows, err := q.db.Query(ctx, listBookmarkedQuestionsWithUser, arg.UserID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListBookmarkedQuestionsWithUserRow
	for rows.Next() {
		var i ListBookmarkedQuestionsWithUserRow
		if err := rows.Scan(
			&i.Question.ID,
			&i.Question.UserID,
			&i.Question.Title,
			&i.Question.Body,
			&i.Question.Tags,
			&i.Question.VoteCount,
			&i.Question.AnswerCount,
			&i.Question.IsSolved,
			&i.Question.CreatedAt,
			&i.Question.UpdatedAt,
			&i.User.ID,
			&i.User.Username,
			&i.User.Name,
			&i.User.Email,
			&i.User.AvatarUrl,
			&i.User.Bio,
			&i.User.GitHubID,
			&i.User.GitHubUsername,
			&i.User.GitHubToken,
			&i.User.GitHubConnected,
			&i.User.SpotifyConnected,
			&i.User.SpotifyToken,
			&i.User.SpotifyRefreshToken,
			&i.User.SpotifyTokenExpiry,
			&i.User.ZennUsername,
			&i.User.QiitaUsername,
			&i.User.AtCoderUsername,
			&i.User.PaizaRank,
			&i.User.SkillsLanguages,
			&i.User.SkillsFrameworks,
			&i.User.OnboardingCompleted,
			&i.User.EmailWeeklyReport,
			&i.User.EmailLanguage,
			&i.User.CreatedAt,
			&i.User.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listQuestionsByUser = `-- name: ListQuestionsByUser :many
SELECT id, user_id, title, body, tags, vote_count, answer_count, is_solved, created_at, updated_at FROM questions
WHERE questions.user_id = $1
ORDER BY questions.created_at DESC
LIMIT $2 OFFSET $3
`

type ListQuestionsByUserParams struct {
	UserID int64
	Limit  int32
	Offset int32
}

// Userは含めない（移行前からの挙動。一覧系の中でこれだけPreloadしない）。
func (q *Queries) ListQuestionsByUser(ctx context.Context, arg ListQuestionsByUserParams) ([]Question, error) {
	rows, err := q.db.Query(ctx, listQuestionsByUser, arg.UserID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Question
	for rows.Next() {
		var i Question
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Title,
			&i.Body,
			&i.Tags,
			&i.VoteCount,
			&i.AnswerCount,
			&i.IsSolved,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listQuestionsWithUser = `-- name: ListQuestionsWithUser :many
SELECT questions.id, questions.user_id, questions.title, questions.body, questions.tags, questions.vote_count, questions.answer_count, questions.is_solved, questions.created_at, questions.updated_at, users.id, users.username, users.name, users.email, users.avatar_url, users.bio, users.git_hub_id, users.git_hub_username, users.git_hub_token, users.git_hub_connected, users.spotify_connected, users.spotify_token, users.spotify_refresh_token, users.spotify_token_expiry, users.zenn_username, users.qiita_username, users.at_coder_username, users.paiza_rank, users.skills_languages, users.skills_frameworks, users.onboarding_completed, users.email_weekly_report, users.email_language, users.created_at, users.updated_at
FROM questions
JOIN users ON users.id = questions.user_id
WHERE ($3::text IS NULL OR questions.tags ILIKE $3)
    AND ($4::text != 'unanswered' OR questions.answer_count = 0)
ORDER BY
    CASE WHEN $4::text = 'votes' THEN questions.vote_count END DESC,
    questions.created_at DESC
LIMIT $1 OFFSET $2
`

type ListQuestionsWithUserParams struct {
	Limit      int32
	Offset     int32
	TagPattern *string
	Sort       string
}

type ListQuestionsWithUserRow struct {
	Question Question
	User     User
}

// GORMのPreload("User")に相当。tag_patternは呼び出し側で "%\"" + escapeLikeChars(tag) + "\"%"
// として組み立て済みのものを渡す（元のGo実装のエスケープ・引用符付与をそのまま踏襲するため）。
// sortが"unanswered"のときだけanswer_count=0で絞り込み、"votes"のときだけ投票数降順にする。
func (q *Queries) ListQuestionsWithUser(ctx context.Context, arg ListQuestionsWithUserParams) ([]ListQuestionsWithUserRow, error) {
	rows, err := q.db.Query(ctx, listQuestionsWithUser,
		arg.Limit,
		arg.Offset,
		arg.TagPattern,
		arg.Sort,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListQuestionsWithUserRow
	for rows.Next() {
		var i ListQuestionsWithUserRow
		if err := rows.Scan(
			&i.Question.ID,
			&i.Question.UserID,
			&i.Question.Title,
			&i.Question.Body,
			&i.Question.Tags,
			&i.Question.VoteCount,
			&i.Question.AnswerCount,
			&i.Question.IsSolved,
			&i.Question.CreatedAt,
			&i.Question.UpdatedAt,
			&i.User.ID,
			&i.User.Username,
			&i.User.Name,
			&i.User.Email,
			&i.User.AvatarUrl,
			&i.User.Bio,
			&i.User.GitHubID,
			&i.User.GitHubUsername,
			&i.User.GitHubToken,
			&i.User.GitHubConnected,
			&i.User.SpotifyConnected,
			&i.User.SpotifyToken,
			&i.User.SpotifyRefreshToken,
			&i.User.SpotifyTokenExpiry,
			&i.User.ZennUsername,
			&i.User.QiitaUsername,
			&i.User.AtCoderUsername,
			&i.User.PaizaRank,
			&i.User.SkillsLanguages,
			&i.User.SkillsFrameworks,
			&i.User.OnboardingCompleted,
			&i.User.EmailWeeklyReport,
			&i.User.EmailLanguage,
			&i.User.CreatedAt,
			&i.User.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSolvedQuestionsWithUser = `-- name: ListSolvedQuestionsWithUser :many
SELECT questions.id, questions.user_id, questions.title, questions.body, questions.tags, questions.vote_count, questions.answer_count, questions.is_solved, questions.created_at, questions.updated_at, users.id, users.username, users.name, users.email, users.avatar_url, users.bio, users.git_hub_id, users.git_hub_username, users.git_hub_token, users.git_hub_connected, users.spotify_connected, users.spotify_token, users.spotify_refresh_token, users.spotify_token_expiry, users.zenn_username, users.qiita_username, users.at_coder_username, users.paiza_rank, users.skills_languages, users.skills_frameworks, users.onboarding_completed, users.email_weekly_report, users.email_language, users.created_at, users.updated_at
FROM questions
JOIN users ON users.id = questions.user_id
WHERE questions.is_solved = true
ORDER BY questions.created_at DESC
LIMIT $1 OFFSET $2
`

type ListSolvedQuestionsWithUserParams struct {
	Limit  int32
	Offset int32
}

type ListSolvedQuestionsWithUserRow struct {
	Question Question
	User     User
}

func (q *Queries) ListSolvedQuestionsWithUser(ctx context.Context, arg ListSolvedQuestionsWithUserParams) ([]ListSolvedQuestionsWithUserRow, error) {
	rows, err := q.db.Query(ctx, listSolvedQuestionsWithUser, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListSolvedQuestionsWithUserRow
	for rows.Next() {
		var i ListSolvedQuestionsWithUserRow
		if err := rows.Scan(
			&i.Question.ID,
			&i.Question.UserID,
			&i.Question.Title,
			&i.Question.Body,
			&i.Question.Tags,
			&i.Question.VoteCount,
			&i.Question.AnswerCount,
			&i.Question.IsSolved,
			&i.Question.CreatedAt,
			&i.Question.UpdatedAt,
			&i.User.ID,
			&i.User.Username,
			&i.User.Name,
			&i.User.Email,
			&i.User.AvatarUrl,
			&i.User.Bio,
			&i.User.GitHubID,
			&i.User.GitHubUsername,
			&i.User.GitHubToken,
			&i.User.GitHubConnected,
			&i.User.SpotifyConnected,
			&i.User.SpotifyToken,
			&i.User.SpotifyRefreshToken,
			&i.User.SpotifyTokenExpiry,
			&i.User.ZennUsername,
			&i.User.QiitaUsername,
			&i.User.AtCoderUsername,
			&i.User.PaizaRank,
			&i.User.SkillsLanguages,
			&i.User.SkillsFrameworks,
			&i.User.OnboardingCompleted,
			&i.User.EmailWeeklyReport,
			&i.User.EmailLanguage,
			&i.User.CreatedAt,
			&i.User.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUnansweredQuestionsWithUser = `-- name: ListUnansweredQuestionsWithUser :many
SELECT questions.id, questions.user_id, questions.title, questions.body, questions.tags, questions.vote_count, questions.answer_count, questions.is_solved, questions.created_at, questions.updated_at, users.id, users.username, users.name, users.email, users.avatar_url, users.bio, users.git_hub_id, users.git_hub_username, users.git_hub_token, users.git_hub_connected, users.spotify_connected, users.spotify_token, users.spotify_refresh_token, users.spotify_token_expiry, users.zenn_username, users.qiita_username, users.at_coder_username, users.paiza_rank, users.skills_languages, users.skills_frameworks, users.onboarding_completed, users.email_weekly_report, users.email_language, users.created_at, users.updated_at
FROM questions
JOIN users ON users.id = questions.user_id
WHERE questions.answer_count = 0
ORDER BY questions.created_at DESC
LIMIT $1 OFFSET $2
`

type ListUnansweredQuestionsWithUserParams struct {
	Limit  int32
	Offset int32
}

type ListUnansweredQuestionsWithUserRow struct {
	Question Question
	User     User
}

func (q *Queries) ListUnansweredQuestionsWithUser(ctx context.Context, arg ListUnansweredQuestionsWithUserParams) ([]ListUnansweredQuestionsWithUserRow, error) {
	rows, err := q.db.Query(ctx, listUnansweredQuestionsWithUser, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListUnansweredQuestionsWithUserRow
	for rows.Next() {
		var i ListUnansweredQuestionsWithUserRow
		if err := rows.Scan(
			&i.Question.ID,
			&i.Question.UserID,
			&i.Question.Title,
			&i.Question.Body,
			&i.Question.Tags,
			&i.Question.VoteCount,
			&i.Question.AnswerCount,
			&i.Question.IsSolved,
			&i.Question.CreatedAt,
			&i.Question.UpdatedAt,
			&i.User.ID,
			&i.User.Username,
			&i.User.Name,
			&i.User.Email,
			&i.User.AvatarUrl,
			&i.User.Bio,
			&i.User.GitHubID,
			&i.User.GitHubUsername,
			&i.User.GitHubToken,
			&i.User.GitHubConnected,
			&i.User.SpotifyConnected,
			&i.User.SpotifyToken,
			&i.User.SpotifyRefreshToken,
			&i.User.SpotifyTokenExpiry,
			&i.User.ZennUsername,
			&i.User.QiitaUsername,
			&i.User.AtCoderUsername,
			&i.User.PaizaRank,
			&i.User.SkillsLanguages,
			&i.User.SkillsFrameworks,
			&i.User.OnboardingCompleted,
			&i.User.EmailWeeklyReport,
			&i.User.EmailLanguage,
			&i.User.CreatedAt,
			&i.User.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchQuestionsWithUser = `-- name: SearchQuestionsWithUser :many
SELECT questions.id, questions.user_id, questions.title, questions.body, questions.tags, questions.vote_count, questions.answer_count, questions.is_solved, questions.created_at, questions.updated_at, users.id, users.username, users.name, users.email, users.avatar_url, users.bio, users.git_hub_id, users.git_hub_username, users.git_hub_token, users.git_hub_connected, users.spotify_connected, users.spotify_token, users.spotify_refresh_token, users.spotify_token_expiry, users.zenn_username, users.qiita_username, users.at_coder_username, users.paiza_rank, users.skills_languages, users.skills_frameworks, users.onboarding_completed, users.email_weekly_report, users.email_language, users.created_at, users.updated_at
FROM questions
JOIN users ON users.id = questions.user_id
WHERE (questions.title ILIKE $1 OR questions.body ILIKE $1 OR questions.tags ILIKE $1)
ORDER BY questions.vote_count DESC, questions.created_at DESC
LIMIT $2 OFFSET $3
`

type SearchQuestionsWithUserParams struct {
	Title  string
	Limit  int32
	Offset int32
}

type SearchQuestionsWithUserRow struct {
	Question Question
	User     User
}

func (q *Queries) SearchQuestionsWithUser(ctx context.Context, arg SearchQuestionsWithUserParams) ([]SearchQuestionsWithUserRow, error) {
	rows, err := q.db.Query(ctx, searchQuestionsWithUser, arg.Title, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SearchQuestionsWithUserRow
	for rows.Next() {
		var i SearchQuestionsWithUserRow
		if err := rows.Scan(
			&i.Question.ID,
			&i.Question.UserID,
			&i.Question.Title,
			&i.Question.Body,
			&i.Question.Tags,
			&i.Question.VoteCount,
			&i.Question.AnswerCount,
			&i.Question.IsSolved,
			&i.Question.CreatedAt,
			&i.Question.UpdatedAt,
			&i.User.ID,
			&i.User.Username,
			&i.User.Name,
			&i.User.Email,
			&i.User.AvatarUrl,
			&i.User.Bio,
			&i.User.GitHubID,
			&i.User.GitHubUsername,
			&i.User.GitHubToken,
			&i.User.GitHubConnected,
			&i.User.SpotifyConnected,
			&i.User.SpotifyToken,
			&i.User.SpotifyRefreshToken,
			&i.User.SpotifyTokenExpiry,
			&i.User.ZennUsername,
			&i.User.QiitaUsername,
			&i.User.AtCoderUsername,
			&i.User.PaizaRank,
			&i.User.SkillsLanguages,
			&i.User.SkillsFrameworks,
			&i.User.OnboardingCompleted,
			&i.User.EmailWeeklyReport,
			&i.User.EmailLanguage,
			&i.User.CreatedAt,
			&i.User.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateQuestion = `-- name: UpdateQuestion :one
UPDATE questions SET
    title = $2, body = $3, tags = $4, vote_count = $5, answer_count = $6, is_solved = $7,
    updated_at = now()
WHERE questions.id = $1
RETURNING id, user_id, title, body, tags, vote_count, answer_count, is_solved, created_at, updated_at
`

type UpdateQuestionParams struct {
	ID          int64
	Title       string
	Body        string
	Tags        *string
	VoteCount   *int64
	AnswerCount *int64
	IsSolved    bool
}

// GORMのSave（全カラム上書き）に相当。
func (q *Queries) UpdateQuestion(ctx context.Context, arg UpdateQuestionParams) (Question, error) {
	row := q.db.QueryRow(ctx, updateQuestion,
		arg.ID,
		arg.Title,
		arg.Body,
		arg.Tags,
		arg.VoteCount,
		arg.AnswerCount,
		arg.IsSolved,
	)
	var i Question
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Title,
		&i.Body,
		&i.Tags,
		&i.VoteCount,
		&i.AnswerCount,
		&i.IsSolved,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateQuestionVoteValue = `-- name: UpdateQuestionVoteValue :exec
UPDATE question_votes SET value = $3
WHERE question_votes.user_id = $1 AND question_votes.question_id = $2
`

type UpdateQuestionVoteValueParams struct {
	UserID     int64
	QuestionID int64
	Value      int64
}

func (q *Queries) UpdateQuestionVoteValue(ctx context.Context, arg UpdateQuestionVoteValueParams) error {
	_, err := q.db.Exec(ctx, updateQuestionVoteValue, arg.UserID, arg.QuestionID, arg.Value)
	return err
}
