// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: reaction_stats.sql

package sqlcgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countReactionsReceivedByUser = `-- name: CountReactionsReceivedByUser :one
SELECT count(*) FROM reactions
JOIN posts ON posts.id = reactions.post_id
WHERE posts.user_id = $1
`

func (q *Queries) CountReactionsReceivedByUser(ctx context.Context, userID int64) (int64, error) {
	row := q.db.QueryRow(ctx, countReactionsReceivedByUser, userID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countReactionsReceivedByUserSince = `-- name: CountReactionsReceivedByUserSince :one
SELECT count(*) FROM reactions
JOIN posts ON posts.id = reactions.post_id
WHERE posts.user_id = $1 AND reactions.created_at >= $2
`

type CountReactionsReceivedByUserSinceParams struct {
	UserID    int64
	CreatedAt pgtype.Timestamptz
}

func (q *Queries) CountReactionsReceivedByUserSince(ctx context.Context, arg CountReactionsReceivedByUserSinceParams) (int64, error) {
	row := q.db.QueryRow(ctx, countReactionsReceivedByUserSince, arg.UserID, arg.CreatedAt)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countUniqueReactorsByUser = `-- name: CountUniqueReactorsByUser :one
SELECT count(DISTINCT reactions.user_id) FROM reactions
JOIN posts ON posts.id = reactions.post_id
WHERE posts.user_id = $1
`

func (q *Queries) CountUniqueReactorsByUser(ctx context.Context, userID int64) (int64, error) {
	row := q.db.QueryRow(ctx, countUniqueReactorsByUser, userID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getEmojiBreakdownByUser = `-- name: GetEmojiBreakdownByUser :many
SELECT reactions.emoji AS emoji, count(*) AS count
FROM reactions
JOIN posts ON posts.id = reactions.post_id
WHERE posts.user_id = $1
GROUP BY reactions.emoji
ORDER BY count DESC, reactions.emoji ASC
`

type GetEmojiBreakdownByUserRow struct {
	Emoji string
	Count int64
}

func (q *Queries) GetEmojiBreakdownByUser(ctx context.Context, userID int64) ([]GetEmojiBreakdownByUserRow, error) {
	rows, err := q.db.Query(ctx, getEmojiBreakdownByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetEmojiBreakdownByUserRow
	for rows.Next() {
		var i GetEmojiBreakdownByUserRow
		if err := rows.Scan(&i.Emoji, &i.Count); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getTopReactedPostsByUser = `-- name: GetTopReactedPostsByUser :many
SELECT posts.id AS id, posts.title AS title, count(*) AS reaction_count
FROM reactions
JOIN posts ON posts.id = reactions.post_id
WHERE posts.user_id = $1
GROUP BY posts.id, posts.title
ORDER BY reaction_count DESC, posts.id DESC
LIMIT $2
`

type GetTopReactedPostsByUserParams struct {
	UserID int64
	Limit  int32
}

type GetTopReactedPostsByUserRow struct {
	ID            int64
	Title         string
	ReactionCount int64
}

func (q *Queries) GetTopReactedPostsByUser(ctx context.Context, arg GetTopReactedPostsByUserParams) ([]GetTopReactedPostsByUserRow, error) {
	rows, err := q.db.Query(ctx, getTopReactedPostsByUser, arg.UserID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetTopReactedPostsByUserRow
	for rows.Next() {
		var i GetTopReactedPostsByUserRow
		if err := rows.Scan(&i.ID, &i.Title, &i.ReactionCount); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
