// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: recommendation.sql

package sqlcgen

import (
	"context"
)

const getRecommendedUserCandidates = `-- name: GetRecommendedUserCandidates :many
SELECT id, username, name, email, password, avatar_url, bio, git_hub_id, git_hub_username, git_hub_token, git_hub_connected, spotify_connected, spotify_token, spotify_refresh_token, spotify_token_expiry, zenn_username, qiita_username, at_coder_username, paiza_rank, skills_languages, skills_frameworks, onboarding_completed, email_weekly_report, email_language, created_at, updated_at FROM users
WHERE NOT (id = ANY($1::bigint[]))
    AND EXISTS (
        SELECT 1 FROM unnest($2::text[]) AS pattern
        WHERE skills_languages LIKE pattern OR skills_frameworks LIKE pattern
    )
`

type GetRecommendedUserCandidatesParams struct {
	ExcludeIds    []int64
	SkillPatterns []string
}

// スキルの部分一致で候補を絞り込む。パターンは呼び出し側で "%" + escapeLikeChars(skill) + "%" として
// 組み立て済みのものを配列で渡す（元のGo実装のエスケープ・ワイルドカード付与をそのまま踏襲するため）。
// 自分自身とフォロー済みのユーザーは候補から除く。
func (q *Queries) GetRecommendedUserCandidates(ctx context.Context, arg GetRecommendedUserCandidatesParams) ([]User, error) {
	rows, err := q.db.Query(ctx, getRecommendedUserCandidates, arg.ExcludeIds, arg.SkillPatterns)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []User
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.Username,
			&i.Name,
			&i.Email,
			&i.Password,
			&i.AvatarUrl,
			&i.Bio,
			&i.GitHubID,
			&i.GitHubUsername,
			&i.GitHubToken,
			&i.GitHubConnected,
			&i.SpotifyConnected,
			&i.SpotifyToken,
			&i.SpotifyRefreshToken,
			&i.SpotifyTokenExpiry,
			&i.ZennUsername,
			&i.QiitaUsername,
			&i.AtCoderUsername,
			&i.PaizaRank,
			&i.SkillsLanguages,
			&i.SkillsFrameworks,
			&i.OnboardingCompleted,
			&i.EmailWeeklyReport,
			&i.EmailLanguage,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listFolloweeIDs = `-- name: ListFolloweeIDs :many
SELECT followee_id FROM follows WHERE follower_id = $1
`

// 指定ユーザーがフォローしているユーザーのIDを返す。
func (q *Queries) ListFolloweeIDs(ctx context.Context, followerID int64) ([]int64, error) {
	rows, err := q.db.Query(ctx, listFolloweeIDs, followerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []int64
	for rows.Next() {
		var followee_id int64
		if err := rows.Scan(&followee_id); err != nil {
			return nil, err
		}
		items = append(items, followee_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTrendingPosts = `-- name: ListTrendingPosts :many
SELECT posts.id, posts.user_id, posts.title, posts.content, posts.image_urls, posts.is_draft, posts.estimated_read_time, posts.scheduled_at, posts.created_at, posts.updated_at, users.id, users.username, users.name, users.email, users.password, users.avatar_url, users.bio, users.git_hub_id, users.git_hub_username, users.git_hub_token, users.git_hub_connected, users.spotify_connected, users.spotify_token, users.spotify_refresh_token, users.spotify_token_expiry, users.zenn_username, users.qiita_username, users.at_coder_username, users.paiza_rank, users.skills_languages, users.skills_frameworks, users.onboarding_completed, users.email_weekly_report, users.email_language, users.created_at, users.updated_at
FROM posts
JOIN users ON users.id = posts.user_id
LEFT JOIN post_metrics pm ON pm.post_id = posts.id
WHERE posts.created_at > NOW() - INTERVAL '1 day' * $1::int
ORDER BY (COALESCE(pm.like_count, 0) + COALESCE(pm.comment_count, 0)) DESC
LIMIT $2
`

type ListTrendingPostsParams struct {
	Days  int32
	Limit int32
}

type ListTrendingPostsRow struct {
	Post Post
	User User
}

// GORMのPreload("User")に相当。user_idはNOT NULLのためINNER JOINでよい。
// CodeSnippetsは別途 ListCodeSnippetsByPostIDs（post_bookmark.sql）で取得しGo側で付与する。
// like_count/comment_countはpost_metrics側（DEVSYNC-159）。まだ1件もいいね/コメントが
// 無い投稿はpost_metrics行が遅延生成前のため、LEFT JOIN + COALESCEで0扱いにする。
func (q *Queries) ListTrendingPosts(ctx context.Context, arg ListTrendingPostsParams) ([]ListTrendingPostsRow, error) {
	rows, err := q.db.Query(ctx, listTrendingPosts, arg.Days, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListTrendingPostsRow
	for rows.Next() {
		var i ListTrendingPostsRow
		if err := rows.Scan(
			&i.Post.ID,
			&i.Post.UserID,
			&i.Post.Title,
			&i.Post.Content,
			&i.Post.ImageUrls,
			&i.Post.IsDraft,
			&i.Post.EstimatedReadTime,
			&i.Post.ScheduledAt,
			&i.Post.CreatedAt,
			&i.Post.UpdatedAt,
			&i.User.ID,
			&i.User.Username,
			&i.User.Name,
			&i.User.Email,
			&i.User.Password,
			&i.User.AvatarUrl,
			&i.User.Bio,
			&i.User.GitHubID,
			&i.User.GitHubUsername,
			&i.User.GitHubToken,
			&i.User.GitHubConnected,
			&i.User.SpotifyConnected,
			&i.User.SpotifyToken,
			&i.User.SpotifyRefreshToken,
			&i.User.SpotifyTokenExpiry,
			&i.User.ZennUsername,
			&i.User.QiitaUsername,
			&i.User.AtCoderUsername,
			&i.User.PaizaRank,
			&i.User.SkillsLanguages,
			&i.User.SkillsFrameworks,
			&i.User.OnboardingCompleted,
			&i.User.EmailWeeklyReport,
			&i.User.EmailLanguage,
			&i.User.CreatedAt,
			&i.User.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTrendingResources = `-- name: ListTrendingResources :many
SELECT learning_resources.id, learning_resources.user_id, learning_resources.title, learning_resources.description, learning_resources.url, learning_resources.category, learning_resources.difficulty, learning_resources.tags, learning_resources.image_url, learning_resources.is_public, learning_resources.created_at, learning_resources.updated_at, users.id, users.username, users.name, users.email, users.password, users.avatar_url, users.bio, users.git_hub_id, users.git_hub_username, users.git_hub_token, users.git_hub_connected, users.spotify_connected, users.spotify_token, users.spotify_refresh_token, users.spotify_token_expiry, users.zenn_username, users.qiita_username, users.at_coder_username, users.paiza_rank, users.skills_languages, users.skills_frameworks, users.onboarding_completed, users.email_weekly_report, users.email_language, users.created_at, users.updated_at
FROM learning_resources
JOIN users ON users.id = learning_resources.user_id
LEFT JOIN learning_resource_metrics lrm ON lrm.resource_id = learning_resources.id
WHERE learning_resources.is_public = true
    AND learning_resources.created_at > NOW() - INTERVAL '1 day' * $1::int
ORDER BY (COALESCE(lrm.like_count, 0) + COALESCE(lrm.save_count, 0)) DESC
LIMIT $2
`

type ListTrendingResourcesParams struct {
	Days  int32
	Limit int32
}

type ListTrendingResourcesRow struct {
	LearningResource LearningResource
	User             User
}

// GORMのPreload("User")に相当。user_idはNOT NULLのためINNER JOINでよい。
// like_count/save_countはlearning_resource_metrics側（DEVSYNC-159）。
// LEFT JOIN + COALESCEで0扱いにする。
func (q *Queries) ListTrendingResources(ctx context.Context, arg ListTrendingResourcesParams) ([]ListTrendingResourcesRow, error) {
	rows, err := q.db.Query(ctx, listTrendingResources, arg.Days, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListTrendingResourcesRow
	for rows.Next() {
		var i ListTrendingResourcesRow
		if err := rows.Scan(
			&i.LearningResource.ID,
			&i.LearningResource.UserID,
			&i.LearningResource.Title,
			&i.LearningResource.Description,
			&i.LearningResource.Url,
			&i.LearningResource.Category,
			&i.LearningResource.Difficulty,
			&i.LearningResource.Tags,
			&i.LearningResource.ImageUrl,
			&i.LearningResource.IsPublic,
			&i.LearningResource.CreatedAt,
			&i.LearningResource.UpdatedAt,
			&i.User.ID,
			&i.User.Username,
			&i.User.Name,
			&i.User.Email,
			&i.User.Password,
			&i.User.AvatarUrl,
			&i.User.Bio,
			&i.User.GitHubID,
			&i.User.GitHubUsername,
			&i.User.GitHubToken,
			&i.User.GitHubConnected,
			&i.User.SpotifyConnected,
			&i.User.SpotifyToken,
			&i.User.SpotifyRefreshToken,
			&i.User.SpotifyTokenExpiry,
			&i.User.ZennUsername,
			&i.User.QiitaUsername,
			&i.User.AtCoderUsername,
			&i.User.PaizaRank,
			&i.User.SkillsLanguages,
			&i.User.SkillsFrameworks,
			&i.User.OnboardingCompleted,
			&i.User.EmailWeeklyReport,
			&i.User.EmailLanguage,
			&i.User.CreatedAt,
			&i.User.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
