// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: reminder_settings.sql

package sqlcgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createDefaultReminderSettings = `-- name: CreateDefaultReminderSettings :many
INSERT INTO reminder_settings (
  user_id, enabled, frequency, notification_time, inactive_days,
  enable_web, enable_email, created_at, updated_at
)
VALUES ($1, $2, $3, $4, $5, $6, $7, now(), now())
ON CONFLICT (user_id) DO NOTHING
RETURNING id, user_id, enabled, frequency, notification_time, inactive_days, enable_web, enable_email, last_reminded_at, created_at, updated_at
`

type CreateDefaultReminderSettingsParams struct {
	UserID           int64
	Enabled          bool
	Frequency        *string
	NotificationTime *string
	InactiveDays     *int64
	EnableWeb        bool
	EnableEmail      bool
}

// 同時に複数リクエストが「不在」と判定してもuser_idの一意制約とDO NOTHINGで
// 競合を無害化する。競合で挿入されなかった場合は0行が返る（エラーにはしない）。
func (q *Queries) CreateDefaultReminderSettings(ctx context.Context, arg CreateDefaultReminderSettingsParams) ([]ReminderSetting, error) {
	rows, err := q.db.Query(ctx, createDefaultReminderSettings,
		arg.UserID,
		arg.Enabled,
		arg.Frequency,
		arg.NotificationTime,
		arg.InactiveDays,
		arg.EnableWeb,
		arg.EnableEmail,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ReminderSetting
	for rows.Next() {
		var i ReminderSetting
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Enabled,
			&i.Frequency,
			&i.NotificationTime,
			&i.InactiveDays,
			&i.EnableWeb,
			&i.EnableEmail,
			&i.LastRemindedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getReminderSettingsByUserID = `-- name: GetReminderSettingsByUserID :one
SELECT id, user_id, enabled, frequency, notification_time, inactive_days, enable_web, enable_email, last_reminded_at, created_at, updated_at FROM reminder_settings
WHERE user_id = $1
`

func (q *Queries) GetReminderSettingsByUserID(ctx context.Context, userID int64) (ReminderSetting, error) {
	row := q.db.QueryRow(ctx, getReminderSettingsByUserID, userID)
	var i ReminderSetting
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Enabled,
		&i.Frequency,
		&i.NotificationTime,
		&i.InactiveDays,
		&i.EnableWeb,
		&i.EnableEmail,
		&i.LastRemindedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateReminderSettings = `-- name: UpdateReminderSettings :one
UPDATE reminder_settings
SET enabled = $2,
    frequency = $3,
    notification_time = $4,
    inactive_days = $5,
    enable_web = $6,
    enable_email = $7,
    last_reminded_at = $8,
    updated_at = now()
WHERE id = $1
RETURNING id, user_id, enabled, frequency, notification_time, inactive_days, enable_web, enable_email, last_reminded_at, created_at, updated_at
`

type UpdateReminderSettingsParams struct {
	ID               int64
	Enabled          bool
	Frequency        *string
	NotificationTime *string
	InactiveDays     *int64
	EnableWeb        bool
	EnableEmail      bool
	LastRemindedAt   pgtype.Timestamptz
}

func (q *Queries) UpdateReminderSettings(ctx context.Context, arg UpdateReminderSettingsParams) (ReminderSetting, error) {
	row := q.db.QueryRow(ctx, updateReminderSettings,
		arg.ID,
		arg.Enabled,
		arg.Frequency,
		arg.NotificationTime,
		arg.InactiveDays,
		arg.EnableWeb,
		arg.EnableEmail,
		arg.LastRemindedAt,
	)
	var i ReminderSetting
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Enabled,
		&i.Frequency,
		&i.NotificationTime,
		&i.InactiveDays,
		&i.EnableWeb,
		&i.EnableEmail,
		&i.LastRemindedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
