// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: resource_progress.sql

package sqlcgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countResourceProgressByUser = `-- name: CountResourceProgressByUser :one
SELECT COUNT(*) FROM resource_progresses
WHERE user_id = $1
    AND ($2::text IS NULL OR status = $2)
`

type CountResourceProgressByUserParams struct {
	UserID int64
	Status *string
}

func (q *Queries) CountResourceProgressByUser(ctx context.Context, arg CountResourceProgressByUserParams) (int64, error) {
	row := q.db.QueryRow(ctx, countResourceProgressByUser, arg.UserID, arg.Status)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getResourceProgressByUserAndResource = `-- name: GetResourceProgressByUserAndResource :one
SELECT id, user_id, resource_id, status, completion_percent, note, started_at, completed_at, created_at, updated_at FROM resource_progresses WHERE user_id = $1 AND resource_id = $2
`

type GetResourceProgressByUserAndResourceParams struct {
	UserID     int64
	ResourceID int64
}

func (q *Queries) GetResourceProgressByUserAndResource(ctx context.Context, arg GetResourceProgressByUserAndResourceParams) (ResourceProgress, error) {
	row := q.db.QueryRow(ctx, getResourceProgressByUserAndResource, arg.UserID, arg.ResourceID)
	var i ResourceProgress
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ResourceID,
		&i.Status,
		&i.CompletionPercent,
		&i.Note,
		&i.StartedAt,
		&i.CompletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listResourceProgressByUser = `-- name: ListResourceProgressByUser :many
SELECT resource_progresses.id, resource_progresses.user_id, resource_progresses.resource_id, resource_progresses.status, resource_progresses.completion_percent, resource_progresses.note, resource_progresses.started_at, resource_progresses.completed_at, resource_progresses.created_at, resource_progresses.updated_at,
    lr.id AS resource_id_2,
    lr.user_id AS resource_user_id,
    lr.title AS resource_title,
    lr.description AS resource_description,
    lr.url AS resource_url,
    lr.category AS resource_category,
    lr.difficulty AS resource_difficulty,
    lr.tags AS resource_tags,
    lr.image_url AS resource_image_url,
    lr.is_public AS resource_is_public,
    lr.like_count AS resource_like_count,
    lr.save_count AS resource_save_count,
    lr.created_at AS resource_created_at,
    lr.updated_at AS resource_updated_at
FROM resource_progresses
LEFT JOIN learning_resources lr ON lr.id = resource_progresses.resource_id AND lr.deleted_at IS NULL
WHERE resource_progresses.user_id = $1
    AND ($4::text IS NULL OR resource_progresses.status = $4)
ORDER BY resource_progresses.updated_at DESC, resource_progresses.id DESC
LIMIT $2 OFFSET $3
`

type ListResourceProgressByUserParams struct {
	UserID int64
	Limit  int32
	Offset int32
	Status *string
}

type ListResourceProgressByUserRow struct {
	ResourceProgress    ResourceProgress
	ResourceID2         *int64
	ResourceUserID      *int64
	ResourceTitle       *string
	ResourceDescription *string
	ResourceUrl         *string
	ResourceCategory    *string
	ResourceDifficulty  *string
	ResourceTags        *string
	ResourceImageUrl    *string
	ResourceIsPublic    *bool
	ResourceLikeCount   *int64
	ResourceSaveCount   *int64
	ResourceCreatedAt   pgtype.Timestamptz
	ResourceUpdatedAt   pgtype.Timestamptz
}

// GORMのPreload("Resource")に相当。resourceは論理削除（deleted_at）付きモデルのため、
// ソフトデリート済みリソースはJOIN条件で除外しResourceがnilになるようLEFT JOINにする
// （resource_idの列自体はNOT NULLだが、論理削除の有無でJOINの成否が変わるため）。
// id を第2ソートキーにして、updated_at 同値の行でもページングが安定するようにする
// （移行前のGORM実装と同じ）。
func (q *Queries) ListResourceProgressByUser(ctx context.Context, arg ListResourceProgressByUserParams) ([]ListResourceProgressByUserRow, error) {
	rows, err := q.db.Query(ctx, listResourceProgressByUser,
		arg.UserID,
		arg.Limit,
		arg.Offset,
		arg.Status,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListResourceProgressByUserRow
	for rows.Next() {
		var i ListResourceProgressByUserRow
		if err := rows.Scan(
			&i.ResourceProgress.ID,
			&i.ResourceProgress.UserID,
			&i.ResourceProgress.ResourceID,
			&i.ResourceProgress.Status,
			&i.ResourceProgress.CompletionPercent,
			&i.ResourceProgress.Note,
			&i.ResourceProgress.StartedAt,
			&i.ResourceProgress.CompletedAt,
			&i.ResourceProgress.CreatedAt,
			&i.ResourceProgress.UpdatedAt,
			&i.ResourceID2,
			&i.ResourceUserID,
			&i.ResourceTitle,
			&i.ResourceDescription,
			&i.ResourceUrl,
			&i.ResourceCategory,
			&i.ResourceDifficulty,
			&i.ResourceTags,
			&i.ResourceImageUrl,
			&i.ResourceIsPublic,
			&i.ResourceLikeCount,
			&i.ResourceSaveCount,
			&i.ResourceCreatedAt,
			&i.ResourceUpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertResourceProgress = `-- name: UpsertResourceProgress :one
INSERT INTO resource_progresses (user_id, resource_id, status, completion_percent, note, started_at, completed_at, created_at, updated_at)
VALUES ($1, $2, $3, $4, $5, $6, $7, now(), now())
ON CONFLICT (user_id, resource_id) DO UPDATE SET
    status = EXCLUDED.status,
    completion_percent = EXCLUDED.completion_percent,
    note = EXCLUDED.note,
    started_at = EXCLUDED.started_at,
    completed_at = EXCLUDED.completed_at,
    updated_at = EXCLUDED.updated_at
RETURNING id, user_id, resource_id, status, completion_percent, note, started_at, completed_at, created_at, updated_at
`

type UpsertResourceProgressParams struct {
	UserID            int64
	ResourceID        int64
	Status            *string
	CompletionPercent *int64
	Note              *string
	StartedAt         pgtype.Timestamptz
	CompletedAt       pgtype.Timestamptz
}

func (q *Queries) UpsertResourceProgress(ctx context.Context, arg UpsertResourceProgressParams) (ResourceProgress, error) {
	row := q.db.QueryRow(ctx, upsertResourceProgress,
		arg.UserID,
		arg.ResourceID,
		arg.Status,
		arg.CompletionPercent,
		arg.Note,
		arg.StartedAt,
		arg.CompletedAt,
	)
	var i ResourceProgress
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ResourceID,
		&i.Status,
		&i.CompletionPercent,
		&i.Note,
		&i.StartedAt,
		&i.CompletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
