// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: resource_review.sql

package sqlcgen

import (
	"context"
)

const countResourceReviewsByResource = `-- name: CountResourceReviewsByResource :one
SELECT COUNT(*) FROM resource_reviews WHERE resource_id = $1
`

func (q *Queries) CountResourceReviewsByResource(ctx context.Context, resourceID int64) (int64, error) {
	row := q.db.QueryRow(ctx, countResourceReviewsByResource, resourceID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createResourceReview = `-- name: CreateResourceReview :one
INSERT INTO resource_reviews (user_id, resource_id, rating, comment, created_at, updated_at)
VALUES ($1, $2, $3, $4, now(), now())
RETURNING id, user_id, resource_id, rating, comment, created_at, updated_at
`

type CreateResourceReviewParams struct {
	UserID     int64
	ResourceID int64
	Rating     int64
	Comment    *string
}

func (q *Queries) CreateResourceReview(ctx context.Context, arg CreateResourceReviewParams) (ResourceReview, error) {
	row := q.db.QueryRow(ctx, createResourceReview,
		arg.UserID,
		arg.ResourceID,
		arg.Rating,
		arg.Comment,
	)
	var i ResourceReview
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ResourceID,
		&i.Rating,
		&i.Comment,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteResourceReview = `-- name: DeleteResourceReview :exec
DELETE FROM resource_reviews WHERE id = $1
`

func (q *Queries) DeleteResourceReview(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, deleteResourceReview, id)
	return err
}

const getResourceReviewByUserAndResource = `-- name: GetResourceReviewByUserAndResource :one
SELECT id, user_id, resource_id, rating, comment, created_at, updated_at FROM resource_reviews WHERE user_id = $1 AND resource_id = $2
`

type GetResourceReviewByUserAndResourceParams struct {
	UserID     int64
	ResourceID int64
}

func (q *Queries) GetResourceReviewByUserAndResource(ctx context.Context, arg GetResourceReviewByUserAndResourceParams) (ResourceReview, error) {
	row := q.db.QueryRow(ctx, getResourceReviewByUserAndResource, arg.UserID, arg.ResourceID)
	var i ResourceReview
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ResourceID,
		&i.Rating,
		&i.Comment,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getResourceReviewWithUserByID = `-- name: GetResourceReviewWithUserByID :one
SELECT resource_reviews.id, resource_reviews.user_id, resource_reviews.resource_id, resource_reviews.rating, resource_reviews.comment, resource_reviews.created_at, resource_reviews.updated_at, users.id, users.username, users.name, users.email, users.password, users.avatar_url, users.bio, users.git_hub_id, users.git_hub_username, users.git_hub_token, users.git_hub_connected, users.spotify_connected, users.spotify_token, users.spotify_refresh_token, users.spotify_token_expiry, users.zenn_username, users.qiita_username, users.at_coder_username, users.paiza_rank, users.skills_languages, users.skills_frameworks, users.onboarding_completed, users.email_weekly_report, users.email_language, users.created_at, users.updated_at
FROM resource_reviews
JOIN users ON users.id = resource_reviews.user_id
WHERE resource_reviews.id = $1
`

type GetResourceReviewWithUserByIDRow struct {
	ResourceReview ResourceReview
	User           User
}

// GORMのPreload("User")に相当。user_idはNOT NULLのためINNER JOINでよい。
func (q *Queries) GetResourceReviewWithUserByID(ctx context.Context, id int64) (GetResourceReviewWithUserByIDRow, error) {
	row := q.db.QueryRow(ctx, getResourceReviewWithUserByID, id)
	var i GetResourceReviewWithUserByIDRow
	err := row.Scan(
		&i.ResourceReview.ID,
		&i.ResourceReview.UserID,
		&i.ResourceReview.ResourceID,
		&i.ResourceReview.Rating,
		&i.ResourceReview.Comment,
		&i.ResourceReview.CreatedAt,
		&i.ResourceReview.UpdatedAt,
		&i.User.ID,
		&i.User.Username,
		&i.User.Name,
		&i.User.Email,
		&i.User.Password,
		&i.User.AvatarUrl,
		&i.User.Bio,
		&i.User.GitHubID,
		&i.User.GitHubUsername,
		&i.User.GitHubToken,
		&i.User.GitHubConnected,
		&i.User.SpotifyConnected,
		&i.User.SpotifyToken,
		&i.User.SpotifyRefreshToken,
		&i.User.SpotifyTokenExpiry,
		&i.User.ZennUsername,
		&i.User.QiitaUsername,
		&i.User.AtCoderUsername,
		&i.User.PaizaRank,
		&i.User.SkillsLanguages,
		&i.User.SkillsFrameworks,
		&i.User.OnboardingCompleted,
		&i.User.EmailWeeklyReport,
		&i.User.EmailLanguage,
		&i.User.CreatedAt,
		&i.User.UpdatedAt,
	)
	return i, err
}

const listResourceReviewsByResource = `-- name: ListResourceReviewsByResource :many
SELECT resource_reviews.id, resource_reviews.user_id, resource_reviews.resource_id, resource_reviews.rating, resource_reviews.comment, resource_reviews.created_at, resource_reviews.updated_at, users.id, users.username, users.name, users.email, users.password, users.avatar_url, users.bio, users.git_hub_id, users.git_hub_username, users.git_hub_token, users.git_hub_connected, users.spotify_connected, users.spotify_token, users.spotify_refresh_token, users.spotify_token_expiry, users.zenn_username, users.qiita_username, users.at_coder_username, users.paiza_rank, users.skills_languages, users.skills_frameworks, users.onboarding_completed, users.email_weekly_report, users.email_language, users.created_at, users.updated_at
FROM resource_reviews
JOIN users ON users.id = resource_reviews.user_id
WHERE resource_reviews.resource_id = $1
ORDER BY resource_reviews.created_at DESC
LIMIT $2 OFFSET $3
`

type ListResourceReviewsByResourceParams struct {
	ResourceID int64
	Limit      int32
	Offset     int32
}

type ListResourceReviewsByResourceRow struct {
	ResourceReview ResourceReview
	User           User
}

// GORMのPreload("User")に相当。user_idはNOT NULLのためINNER JOINでよい。
func (q *Queries) ListResourceReviewsByResource(ctx context.Context, arg ListResourceReviewsByResourceParams) ([]ListResourceReviewsByResourceRow, error) {
	rows, err := q.db.Query(ctx, listResourceReviewsByResource, arg.ResourceID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListResourceReviewsByResourceRow
	for rows.Next() {
		var i ListResourceReviewsByResourceRow
		if err := rows.Scan(
			&i.ResourceReview.ID,
			&i.ResourceReview.UserID,
			&i.ResourceReview.ResourceID,
			&i.ResourceReview.Rating,
			&i.ResourceReview.Comment,
			&i.ResourceReview.CreatedAt,
			&i.ResourceReview.UpdatedAt,
			&i.User.ID,
			&i.User.Username,
			&i.User.Name,
			&i.User.Email,
			&i.User.Password,
			&i.User.AvatarUrl,
			&i.User.Bio,
			&i.User.GitHubID,
			&i.User.GitHubUsername,
			&i.User.GitHubToken,
			&i.User.GitHubConnected,
			&i.User.SpotifyConnected,
			&i.User.SpotifyToken,
			&i.User.SpotifyRefreshToken,
			&i.User.SpotifyTokenExpiry,
			&i.User.ZennUsername,
			&i.User.QiitaUsername,
			&i.User.AtCoderUsername,
			&i.User.PaizaRank,
			&i.User.SkillsLanguages,
			&i.User.SkillsFrameworks,
			&i.User.OnboardingCompleted,
			&i.User.EmailWeeklyReport,
			&i.User.EmailLanguage,
			&i.User.CreatedAt,
			&i.User.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateResourceReview = `-- name: UpdateResourceReview :one
UPDATE resource_reviews SET rating = $2, comment = $3, updated_at = now()
WHERE id = $1
RETURNING id, user_id, resource_id, rating, comment, created_at, updated_at
`

type UpdateResourceReviewParams struct {
	ID      int64
	Rating  int64
	Comment *string
}

// GORMのSave（全カラム上書き）に相当。
func (q *Queries) UpdateResourceReview(ctx context.Context, arg UpdateResourceReviewParams) (ResourceReview, error) {
	row := q.db.QueryRow(ctx, updateResourceReview, arg.ID, arg.Rating, arg.Comment)
	var i ResourceReview
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ResourceID,
		&i.Rating,
		&i.Comment,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
