// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: roadmap_stats.sql

package sqlcgen

import (
	"context"
)

const countRoadmapsByUser = `-- name: CountRoadmapsByUser :one
SELECT count(*) FROM roadmaps
WHERE user_id = $1
`

func (q *Queries) CountRoadmapsByUser(ctx context.Context, userID int64) (int64, error) {
	row := q.db.QueryRow(ctx, countRoadmapsByUser, userID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countRoadmapsByUserAndStatus = `-- name: CountRoadmapsByUserAndStatus :one
SELECT count(*) FROM roadmaps
WHERE user_id = $1 AND status = $2
`

type CountRoadmapsByUserAndStatusParams struct {
	UserID int64
	Status *string
}

func (q *Queries) CountRoadmapsByUserAndStatus(ctx context.Context, arg CountRoadmapsByUserAndStatusParams) (int64, error) {
	row := q.db.QueryRow(ctx, countRoadmapsByUserAndStatus, arg.UserID, arg.Status)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const sumRoadmapCompletedStepCountByUser = `-- name: SumRoadmapCompletedStepCountByUser :one
SELECT COALESCE(SUM(rm.completed_step_count), 0)::bigint
FROM roadmaps r
LEFT JOIN roadmap_metrics rm ON rm.roadmap_id = r.id
WHERE r.user_id = $1
`

func (q *Queries) SumRoadmapCompletedStepCountByUser(ctx context.Context, userID int64) (int64, error) {
	row := q.db.QueryRow(ctx, sumRoadmapCompletedStepCountByUser, userID)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const sumRoadmapStepCountByUser = `-- name: SumRoadmapStepCountByUser :one
SELECT COALESCE(SUM(rm.step_count), 0)::bigint
FROM roadmaps r
LEFT JOIN roadmap_metrics rm ON rm.roadmap_id = r.id
WHERE r.user_id = $1
`

// step_countはroadmap_metrics側（DEVSYNC-159）。LEFT JOIN + COALESCEで0扱いにする。
func (q *Queries) SumRoadmapStepCountByUser(ctx context.Context, userID int64) (int64, error) {
	row := q.db.QueryRow(ctx, sumRoadmapStepCountByUser, userID)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}
