// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: roadmap_metrics.sql

package sqlcgen

import (
	"context"
)

const getRoadmapMetricsByRoadmapIDs = `-- name: GetRoadmapMetricsByRoadmapIDs :many
SELECT
    roadmap_id,
    step_count,
    completed_step_count,
    CASE WHEN step_count > 0 THEN (completed_step_count * 100 / step_count) ELSE 0 END::bigint AS progress
FROM roadmap_metrics
WHERE roadmap_id = ANY($1::bigint[])
`

type GetRoadmapMetricsByRoadmapIDsRow struct {
	RoadmapID          int64
	StepCount          int64
	CompletedStepCount int64
	Progress           int64
}

// ロードマップ一覧へstep_count/completed_step_count/progressを付与するためのまとめ取り。
// progressは列として持たず、ここでSELECT側の算出式として都度計算する（生成列にすると
// 既存のUPDATE系クエリを壊すため不採用。DEVSYNC-159）。1件もステップが無い
// ロードマップはroadmap_metrics行が存在しない（遅延生成）ため、この結果に
// 現れないロードマップはGo側で0扱いにする（attachRoadmapMetrics参照）。
func (q *Queries) GetRoadmapMetricsByRoadmapIDs(ctx context.Context, dollar_1 []int64) ([]GetRoadmapMetricsByRoadmapIDsRow, error) {
	rows, err := q.db.Query(ctx, getRoadmapMetricsByRoadmapIDs, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetRoadmapMetricsByRoadmapIDsRow
	for rows.Next() {
		var i GetRoadmapMetricsByRoadmapIDsRow
		if err := rows.Scan(
			&i.RoadmapID,
			&i.StepCount,
			&i.CompletedStepCount,
			&i.Progress,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const reconcileAllRoadmapMetrics = `-- name: ReconcileAllRoadmapMetrics :exec
INSERT INTO roadmap_metrics (roadmap_id, step_count, completed_step_count)
SELECT
    r.id,
    COALESCE(s.cnt, 0),
    COALESCE(sc.cnt, 0)
FROM roadmaps r
LEFT JOIN (SELECT roadmap_id, COUNT(*) AS cnt FROM roadmap_steps GROUP BY roadmap_id) s ON s.roadmap_id = r.id
LEFT JOIN (SELECT roadmap_id, COUNT(*) AS cnt FROM roadmap_steps WHERE is_completed = true GROUP BY roadmap_id) sc ON sc.roadmap_id = r.id
ON CONFLICT (roadmap_id) DO UPDATE SET
    step_count = EXCLUDED.step_count,
    completed_step_count = EXCLUDED.completed_step_count
`

// 夜次reconcileジョブ本体。roadmap_stepsの実件数からroadmap_metrics全件を補正する。
func (q *Queries) ReconcileAllRoadmapMetrics(ctx context.Context) error {
	_, err := q.db.Exec(ctx, reconcileAllRoadmapMetrics)
	return err
}
