// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: room_member_lookup.sql

package sqlcgen

import (
	"context"
)

const listChatRoomMemberUserIDs = `-- name: ListChatRoomMemberUserIDs :many
SELECT user_id FROM chat_room_members WHERE chat_room_id = $1
`

func (q *Queries) ListChatRoomMemberUserIDs(ctx context.Context, chatRoomID int64) ([]int64, error) {
	rows, err := q.db.Query(ctx, listChatRoomMemberUserIDs, chatRoomID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []int64
	for rows.Next() {
		var user_id int64
		if err := rows.Scan(&user_id); err != nil {
			return nil, err
		}
		items = append(items, user_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
