// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: streak_freeze.sql

package sqlcgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countStreakFreezesInMonth = `-- name: CountStreakFreezesInMonth :one
SELECT COUNT(*) FROM streak_freezes WHERE user_id = $1 AND year = $2 AND month = $3
`

type CountStreakFreezesInMonthParams struct {
	UserID int64
	Year   int64
	Month  int64
}

func (q *Queries) CountStreakFreezesInMonth(ctx context.Context, arg CountStreakFreezesInMonthParams) (int64, error) {
	row := q.db.QueryRow(ctx, countStreakFreezesInMonth, arg.UserID, arg.Year, arg.Month)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countStreakFreezesOnDate = `-- name: CountStreakFreezesOnDate :one
SELECT COUNT(*) FROM streak_freezes WHERE user_id = $1 AND used_on = $2
`

type CountStreakFreezesOnDateParams struct {
	UserID int64
	UsedOn pgtype.Date
}

func (q *Queries) CountStreakFreezesOnDate(ctx context.Context, arg CountStreakFreezesOnDateParams) (int64, error) {
	row := q.db.QueryRow(ctx, countStreakFreezesOnDate, arg.UserID, arg.UsedOn)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createStreakFreeze = `-- name: CreateStreakFreeze :one
INSERT INTO streak_freezes (user_id, used_on, month, year, created_at)
VALUES ($1, $2, $3, $4, now())
RETURNING id, user_id, used_on, month, year, created_at
`

type CreateStreakFreezeParams struct {
	UserID int64
	UsedOn pgtype.Date
	Month  int64
	Year   int64
}

func (q *Queries) CreateStreakFreeze(ctx context.Context, arg CreateStreakFreezeParams) (StreakFreeze, error) {
	row := q.db.QueryRow(ctx, createStreakFreeze,
		arg.UserID,
		arg.UsedOn,
		arg.Month,
		arg.Year,
	)
	var i StreakFreeze
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.UsedOn,
		&i.Month,
		&i.Year,
		&i.CreatedAt,
	)
	return i, err
}

const hasStreakFreezeOnDate = `-- name: HasStreakFreezeOnDate :one
SELECT COUNT(*) > 0 FROM streak_freezes WHERE user_id = $1 AND used_on = $2
`

type HasStreakFreezeOnDateParams struct {
	UserID int64
	UsedOn pgtype.Date
}

func (q *Queries) HasStreakFreezeOnDate(ctx context.Context, arg HasStreakFreezeOnDateParams) (bool, error) {
	row := q.db.QueryRow(ctx, hasStreakFreezeOnDate, arg.UserID, arg.UsedOn)
	var column_1 bool
	err := row.Scan(&column_1)
	return column_1, err
}

const listStreakFreezesByUserAndMonth = `-- name: ListStreakFreezesByUserAndMonth :many
SELECT id, user_id, used_on, month, year, created_at FROM streak_freezes
WHERE user_id = $1 AND year = $2 AND month = $3
ORDER BY used_on ASC
`

type ListStreakFreezesByUserAndMonthParams struct {
	UserID int64
	Year   int64
	Month  int64
}

func (q *Queries) ListStreakFreezesByUserAndMonth(ctx context.Context, arg ListStreakFreezesByUserAndMonthParams) ([]StreakFreeze, error) {
	rows, err := q.db.Query(ctx, listStreakFreezesByUserAndMonth, arg.UserID, arg.Year, arg.Month)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []StreakFreeze
	for rows.Next() {
		var i StreakFreeze
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.UsedOn,
			&i.Month,
			&i.Year,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockUserForStreakFreeze = `-- name: LockUserForStreakFreeze :exec
SELECT id FROM users WHERE id = $1 FOR UPDATE
`

// 同一ユーザーの CreateWithinLimits 同時実行を直列化するための行ロック（GORMの clause.Locking{Strength: "UPDATE"} に相当）。
func (q *Queries) LockUserForStreakFreeze(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, lockUserForStreakFreeze, id)
	return err
}
