// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: study_circle_stats.sql

package sqlcgen

import (
	"context"
)

const countStudyCircleCheckinsByCircle = `-- name: CountStudyCircleCheckinsByCircle :one
SELECT count(*) FROM study_circle_checkins
WHERE circle_id = $1
`

func (q *Queries) CountStudyCircleCheckinsByCircle(ctx context.Context, circleID int64) (int64, error) {
	row := q.db.QueryRow(ctx, countStudyCircleCheckinsByCircle, circleID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countStudyCircleCompletedStepsByCircle = `-- name: CountStudyCircleCompletedStepsByCircle :one
SELECT count(*) FROM study_circle_member_progresses
WHERE circle_id = $1 AND is_completed = true
`

func (q *Queries) CountStudyCircleCompletedStepsByCircle(ctx context.Context, circleID int64) (int64, error) {
	row := q.db.QueryRow(ctx, countStudyCircleCompletedStepsByCircle, circleID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countStudyCircleMembersByCircle = `-- name: CountStudyCircleMembersByCircle :one
SELECT count(*) FROM study_circle_members
WHERE circle_id = $1
`

func (q *Queries) CountStudyCircleMembersByCircle(ctx context.Context, circleID int64) (int64, error) {
	row := q.db.QueryRow(ctx, countStudyCircleMembersByCircle, circleID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countStudyCircleStepsByCircle = `-- name: CountStudyCircleStepsByCircle :one
SELECT count(*) FROM study_circle_steps
WHERE circle_id = $1
`

func (q *Queries) CountStudyCircleStepsByCircle(ctx context.Context, circleID int64) (int64, error) {
	row := q.db.QueryRow(ctx, countStudyCircleStepsByCircle, circleID)
	var count int64
	err := row.Scan(&count)
	return count, err
}
