// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: user.sql

package sqlcgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createUser = `-- name: CreateUser :one
INSERT INTO users (
    username, name, email, password, avatar_url, bio, git_hub_id, git_hub_username,
    git_hub_token, git_hub_connected, spotify_connected, spotify_token, spotify_refresh_token,
    spotify_token_expiry, zenn_username, qiita_username, at_coder_username, paiza_rank,
    skills_languages, skills_frameworks, onboarding_completed, email_weekly_report,
    email_language, created_at, updated_at
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15, $16, $17, $18,
    $19, $20, $21, $22, $23, now(), now()
) RETURNING id, username, name, email, password, avatar_url, bio, git_hub_id, git_hub_username, git_hub_token, git_hub_connected, spotify_connected, spotify_token, spotify_refresh_token, spotify_token_expiry, zenn_username, qiita_username, at_coder_username, paiza_rank, skills_languages, skills_frameworks, onboarding_completed, email_weekly_report, email_language, created_at, updated_at
`

type CreateUserParams struct {
	Username            string
	Name                string
	Email               string
	Password            *string
	AvatarUrl           *string
	Bio                 *string
	GitHubID            *int64
	GitHubUsername      *string
	GitHubToken         *string
	GitHubConnected     *bool
	SpotifyConnected    *bool
	SpotifyToken        *string
	SpotifyRefreshToken *string
	SpotifyTokenExpiry  pgtype.Timestamptz
	ZennUsername        *string
	QiitaUsername       *string
	AtCoderUsername     *string
	PaizaRank           *string
	SkillsLanguages     *string
	SkillsFrameworks    *string
	OnboardingCompleted *bool
	EmailWeeklyReport   *bool
	EmailLanguage       *string
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, createUser,
		arg.Username,
		arg.Name,
		arg.Email,
		arg.Password,
		arg.AvatarUrl,
		arg.Bio,
		arg.GitHubID,
		arg.GitHubUsername,
		arg.GitHubToken,
		arg.GitHubConnected,
		arg.SpotifyConnected,
		arg.SpotifyToken,
		arg.SpotifyRefreshToken,
		arg.SpotifyTokenExpiry,
		arg.ZennUsername,
		arg.QiitaUsername,
		arg.AtCoderUsername,
		arg.PaizaRank,
		arg.SkillsLanguages,
		arg.SkillsFrameworks,
		arg.OnboardingCompleted,
		arg.EmailWeeklyReport,
		arg.EmailLanguage,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Name,
		&i.Email,
		&i.Password,
		&i.AvatarUrl,
		&i.Bio,
		&i.GitHubID,
		&i.GitHubUsername,
		&i.GitHubToken,
		&i.GitHubConnected,
		&i.SpotifyConnected,
		&i.SpotifyToken,
		&i.SpotifyRefreshToken,
		&i.SpotifyTokenExpiry,
		&i.ZennUsername,
		&i.QiitaUsername,
		&i.AtCoderUsername,
		&i.PaizaRank,
		&i.SkillsLanguages,
		&i.SkillsFrameworks,
		&i.OnboardingCompleted,
		&i.EmailWeeklyReport,
		&i.EmailLanguage,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteBookmarkCollectionItemsByUserPosts = `-- name: DeleteBookmarkCollectionItemsByUserPosts :exec
DELETE FROM bookmark_collection_items
WHERE bookmark_collection_items.post_id IN (SELECT p.id FROM posts p WHERE p.user_id = $1)
`

func (q *Queries) DeleteBookmarkCollectionItemsByUserPosts(ctx context.Context, userID int64) error {
	_, err := q.db.Exec(ctx, deleteBookmarkCollectionItemsByUserPosts, userID)
	return err
}

const deleteBookmarksByUserPosts = `-- name: DeleteBookmarksByUserPosts :exec
DELETE FROM bookmarks WHERE bookmarks.post_id IN (SELECT p.id FROM posts p WHERE p.user_id = $1)
`

func (q *Queries) DeleteBookmarksByUserPosts(ctx context.Context, userID int64) error {
	_, err := q.db.Exec(ctx, deleteBookmarksByUserPosts, userID)
	return err
}

const deleteCodeSnippetsByUserPosts = `-- name: DeleteCodeSnippetsByUserPosts :exec
DELETE FROM code_snippets
WHERE code_snippets.post_id IN (SELECT p.id FROM posts p WHERE p.user_id = $1)
`

func (q *Queries) DeleteCodeSnippetsByUserPosts(ctx context.Context, userID int64) error {
	_, err := q.db.Exec(ctx, deleteCodeSnippetsByUserPosts, userID)
	return err
}

const deleteCommentLikesByUserCommentsSet = `-- name: DeleteCommentLikesByUserCommentsSet :exec
DELETE FROM comment_likes WHERE comment_likes.comment_id IN (
    SELECT c.id FROM comments c
    WHERE c.post_id IN (SELECT p.id FROM posts p WHERE p.user_id = $1) OR c.user_id = $1
)
`

// 退会者の投稿配下のコメント、および退会者自身が他の投稿へ書いたコメントの
// 従属行（コメントいいね）をまとめて消す。
func (q *Queries) DeleteCommentLikesByUserCommentsSet(ctx context.Context, userID int64) error {
	_, err := q.db.Exec(ctx, deleteCommentLikesByUserCommentsSet, userID)
	return err
}

const deleteCommentsByUserPostsAndSelf = `-- name: DeleteCommentsByUserPostsAndSelf :exec
DELETE FROM comments
WHERE comments.post_id IN (SELECT p.id FROM posts p WHERE p.user_id = $1) OR comments.user_id = $1
`

func (q *Queries) DeleteCommentsByUserPostsAndSelf(ctx context.Context, userID int64) error {
	_, err := q.db.Exec(ctx, deleteCommentsByUserPostsAndSelf, userID)
	return err
}

const deleteFollowsByUser = `-- name: DeleteFollowsByUser :exec
DELETE FROM follows WHERE follows.follower_id = $1 OR follows.followee_id = $1
`

func (q *Queries) DeleteFollowsByUser(ctx context.Context, followerID int64) error {
	_, err := q.db.Exec(ctx, deleteFollowsByUser, followerID)
	return err
}

const deleteLikesByUser = `-- name: DeleteLikesByUser :exec
DELETE FROM likes WHERE likes.user_id = $1
`

func (q *Queries) DeleteLikesByUser(ctx context.Context, userID int64) error {
	_, err := q.db.Exec(ctx, deleteLikesByUser, userID)
	return err
}

const deleteLikesByUserPosts = `-- name: DeleteLikesByUserPosts :exec
DELETE FROM likes WHERE likes.post_id IN (SELECT p.id FROM posts p WHERE p.user_id = $1)
`

func (q *Queries) DeleteLikesByUserPosts(ctx context.Context, userID int64) error {
	_, err := q.db.Exec(ctx, deleteLikesByUserPosts, userID)
	return err
}

const deleteMentionsByUserCommentsSet = `-- name: DeleteMentionsByUserCommentsSet :exec
DELETE FROM mentions WHERE mentions.comment_id IN (
    SELECT c.id FROM comments c
    WHERE c.post_id IN (SELECT p.id FROM posts p WHERE p.user_id = $1) OR c.user_id = $1
)
`

// mentions自身もpost_id列を持つため、サブクエリのcommentsを明示的にエイリアス修飾しないと
// post_idの参照先が曖昧になる（PostgreSQLの相関サブクエリの解決規則による）。
func (q *Queries) DeleteMentionsByUserCommentsSet(ctx context.Context, userID int64) error {
	_, err := q.db.Exec(ctx, deleteMentionsByUserCommentsSet, userID)
	return err
}

const deleteMentionsByUserPosts = `-- name: DeleteMentionsByUserPosts :exec
DELETE FROM mentions WHERE mentions.post_id IN (SELECT p.id FROM posts p WHERE p.user_id = $1)
`

func (q *Queries) DeleteMentionsByUserPosts(ctx context.Context, userID int64) error {
	_, err := q.db.Exec(ctx, deleteMentionsByUserPosts, userID)
	return err
}

const deleteMessagesByUser = `-- name: DeleteMessagesByUser :exec
DELETE FROM messages WHERE messages.sender_id = $1 OR messages.receiver_id = $1
`

func (q *Queries) DeleteMessagesByUser(ctx context.Context, senderID int64) error {
	_, err := q.db.Exec(ctx, deleteMessagesByUser, senderID)
	return err
}

const deleteNotificationsForUserDeletion = `-- name: DeleteNotificationsForUserDeletion :exec
DELETE FROM notifications
WHERE notifications.user_id = $1 OR notifications.actor_id = $1
    OR notifications.post_id IN (SELECT p.id FROM posts p WHERE p.user_id = $1)
`

func (q *Queries) DeleteNotificationsForUserDeletion(ctx context.Context, userID int64) error {
	_, err := q.db.Exec(ctx, deleteNotificationsForUserDeletion, userID)
	return err
}

const deletePasswordResetTokensByUser = `-- name: DeletePasswordResetTokensByUser :exec
DELETE FROM password_reset_tokens WHERE password_reset_tokens.user_id = $1
`

func (q *Queries) DeletePasswordResetTokensByUser(ctx context.Context, userID int64) error {
	_, err := q.db.Exec(ctx, deletePasswordResetTokensByUser, userID)
	return err
}

const deletePostCollectionItemsByUserPosts = `-- name: DeletePostCollectionItemsByUserPosts :exec
DELETE FROM post_collection_items
WHERE post_collection_items.post_id IN (SELECT p.id FROM posts p WHERE p.user_id = $1)
`

func (q *Queries) DeletePostCollectionItemsByUserPosts(ctx context.Context, userID int64) error {
	_, err := q.db.Exec(ctx, deletePostCollectionItemsByUserPosts, userID)
	return err
}

const deletePostPinsByUserPosts = `-- name: DeletePostPinsByUserPosts :exec
DELETE FROM post_pins WHERE post_pins.post_id IN (SELECT p.id FROM posts p WHERE p.user_id = $1)
`

func (q *Queries) DeletePostPinsByUserPosts(ctx context.Context, userID int64) error {
	_, err := q.db.Exec(ctx, deletePostPinsByUserPosts, userID)
	return err
}

const deletePostSeriesItemsByUserPosts = `-- name: DeletePostSeriesItemsByUserPosts :exec
DELETE FROM post_series_items
WHERE post_series_items.post_id IN (SELECT p.id FROM posts p WHERE p.user_id = $1)
`

func (q *Queries) DeletePostSeriesItemsByUserPosts(ctx context.Context, userID int64) error {
	_, err := q.db.Exec(ctx, deletePostSeriesItemsByUserPosts, userID)
	return err
}

const deletePostTagsByUserPosts = `-- name: DeletePostTagsByUserPosts :exec
DELETE FROM post_tags WHERE post_tags.post_id IN (SELECT p.id FROM posts p WHERE p.user_id = $1)
`

func (q *Queries) DeletePostTagsByUserPosts(ctx context.Context, userID int64) error {
	_, err := q.db.Exec(ctx, deletePostTagsByUserPosts, userID)
	return err
}

const deletePostViewsByUserPosts = `-- name: DeletePostViewsByUserPosts :exec
DELETE FROM post_views WHERE post_views.post_id IN (SELECT p.id FROM posts p WHERE p.user_id = $1)
`

func (q *Queries) DeletePostViewsByUserPosts(ctx context.Context, userID int64) error {
	_, err := q.db.Exec(ctx, deletePostViewsByUserPosts, userID)
	return err
}

const deletePostsByUser = `-- name: DeletePostsByUser :exec
DELETE FROM posts WHERE posts.user_id = $1
`

func (q *Queries) DeletePostsByUser(ctx context.Context, userID int64) error {
	_, err := q.db.Exec(ctx, deletePostsByUser, userID)
	return err
}

const deleteReactionsByUserPosts = `-- name: DeleteReactionsByUserPosts :exec
DELETE FROM reactions WHERE reactions.post_id IN (SELECT p.id FROM posts p WHERE p.user_id = $1)
`

func (q *Queries) DeleteReactionsByUserPosts(ctx context.Context, userID int64) error {
	_, err := q.db.Exec(ctx, deleteReactionsByUserPosts, userID)
	return err
}

const deleteSnippetCommentsByUserPostSnippets = `-- name: DeleteSnippetCommentsByUserPostSnippets :exec
DELETE FROM snippet_comments WHERE snippet_comments.snippet_id IN (
    SELECT cs.id FROM code_snippets cs
    WHERE cs.post_id IN (SELECT p.id FROM posts p WHERE p.user_id = $1)
)
`

func (q *Queries) DeleteSnippetCommentsByUserPostSnippets(ctx context.Context, userID int64) error {
	_, err := q.db.Exec(ctx, deleteSnippetCommentsByUserPostSnippets, userID)
	return err
}

const deleteUser = `-- name: DeleteUser :exec
DELETE FROM users WHERE users.id = $1
`

func (q *Queries) DeleteUser(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, deleteUser, id)
	return err
}

const findAllUsers = `-- name: FindAllUsers :many
SELECT id, username, name, email, password, avatar_url, bio, git_hub_id, git_hub_username, git_hub_token, git_hub_connected, spotify_connected, spotify_token, spotify_refresh_token, spotify_token_expiry, zenn_username, qiita_username, at_coder_username, paiza_rank, skills_languages, skills_frameworks, onboarding_completed, email_weekly_report, email_language, created_at, updated_at FROM users
`

func (q *Queries) FindAllUsers(ctx context.Context) ([]User, error) {
	rows, err := q.db.Query(ctx, findAllUsers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []User
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.Username,
			&i.Name,
			&i.Email,
			&i.Password,
			&i.AvatarUrl,
			&i.Bio,
			&i.GitHubID,
			&i.GitHubUsername,
			&i.GitHubToken,
			&i.GitHubConnected,
			&i.SpotifyConnected,
			&i.SpotifyToken,
			&i.SpotifyRefreshToken,
			&i.SpotifyTokenExpiry,
			&i.ZennUsername,
			&i.QiitaUsername,
			&i.AtCoderUsername,
			&i.PaizaRank,
			&i.SkillsLanguages,
			&i.SkillsFrameworks,
			&i.OnboardingCompleted,
			&i.EmailWeeklyReport,
			&i.EmailLanguage,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, username, name, email, password, avatar_url, bio, git_hub_id, git_hub_username, git_hub_token, git_hub_connected, spotify_connected, spotify_token, spotify_refresh_token, spotify_token_expiry, zenn_username, qiita_username, at_coder_username, paiza_rank, skills_languages, skills_frameworks, onboarding_completed, email_weekly_report, email_language, created_at, updated_at FROM users WHERE users.email = $1
`

func (q *Queries) GetUserByEmail(ctx context.Context, email string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByEmail, email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Name,
		&i.Email,
		&i.Password,
		&i.AvatarUrl,
		&i.Bio,
		&i.GitHubID,
		&i.GitHubUsername,
		&i.GitHubToken,
		&i.GitHubConnected,
		&i.SpotifyConnected,
		&i.SpotifyToken,
		&i.SpotifyRefreshToken,
		&i.SpotifyTokenExpiry,
		&i.ZennUsername,
		&i.QiitaUsername,
		&i.AtCoderUsername,
		&i.PaizaRank,
		&i.SkillsLanguages,
		&i.SkillsFrameworks,
		&i.OnboardingCompleted,
		&i.EmailWeeklyReport,
		&i.EmailLanguage,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByGitHubID = `-- name: GetUserByGitHubID :one
SELECT id, username, name, email, password, avatar_url, bio, git_hub_id, git_hub_username, git_hub_token, git_hub_connected, spotify_connected, spotify_token, spotify_refresh_token, spotify_token_expiry, zenn_username, qiita_username, at_coder_username, paiza_rank, skills_languages, skills_frameworks, onboarding_completed, email_weekly_report, email_language, created_at, updated_at FROM users WHERE users.git_hub_id = $1
`

func (q *Queries) GetUserByGitHubID(ctx context.Context, gitHubID *int64) (User, error) {
	row := q.db.QueryRow(ctx, getUserByGitHubID, gitHubID)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Name,
		&i.Email,
		&i.Password,
		&i.AvatarUrl,
		&i.Bio,
		&i.GitHubID,
		&i.GitHubUsername,
		&i.GitHubToken,
		&i.GitHubConnected,
		&i.SpotifyConnected,
		&i.SpotifyToken,
		&i.SpotifyRefreshToken,
		&i.SpotifyTokenExpiry,
		&i.ZennUsername,
		&i.QiitaUsername,
		&i.AtCoderUsername,
		&i.PaizaRank,
		&i.SkillsLanguages,
		&i.SkillsFrameworks,
		&i.OnboardingCompleted,
		&i.EmailWeeklyReport,
		&i.EmailLanguage,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, username, name, email, password, avatar_url, bio, git_hub_id, git_hub_username, git_hub_token, git_hub_connected, spotify_connected, spotify_token, spotify_refresh_token, spotify_token_expiry, zenn_username, qiita_username, at_coder_username, paiza_rank, skills_languages, skills_frameworks, onboarding_completed, email_weekly_report, email_language, created_at, updated_at FROM users WHERE users.id = $1
`

func (q *Queries) GetUserByID(ctx context.Context, id int64) (User, error) {
	row := q.db.QueryRow(ctx, getUserByID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Name,
		&i.Email,
		&i.Password,
		&i.AvatarUrl,
		&i.Bio,
		&i.GitHubID,
		&i.GitHubUsername,
		&i.GitHubToken,
		&i.GitHubConnected,
		&i.SpotifyConnected,
		&i.SpotifyToken,
		&i.SpotifyRefreshToken,
		&i.SpotifyTokenExpiry,
		&i.ZennUsername,
		&i.QiitaUsername,
		&i.AtCoderUsername,
		&i.PaizaRank,
		&i.SkillsLanguages,
		&i.SkillsFrameworks,
		&i.OnboardingCompleted,
		&i.EmailWeeklyReport,
		&i.EmailLanguage,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByUsername = `-- name: GetUserByUsername :one
SELECT id, username, name, email, password, avatar_url, bio, git_hub_id, git_hub_username, git_hub_token, git_hub_connected, spotify_connected, spotify_token, spotify_refresh_token, spotify_token_expiry, zenn_username, qiita_username, at_coder_username, paiza_rank, skills_languages, skills_frameworks, onboarding_completed, email_weekly_report, email_language, created_at, updated_at FROM users WHERE users.username = $1
`

func (q *Queries) GetUserByUsername(ctx context.Context, username string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByUsername, username)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Name,
		&i.Email,
		&i.Password,
		&i.AvatarUrl,
		&i.Bio,
		&i.GitHubID,
		&i.GitHubUsername,
		&i.GitHubToken,
		&i.GitHubConnected,
		&i.SpotifyConnected,
		&i.SpotifyToken,
		&i.SpotifyRefreshToken,
		&i.SpotifyTokenExpiry,
		&i.ZennUsername,
		&i.QiitaUsername,
		&i.AtCoderUsername,
		&i.PaizaRank,
		&i.SkillsLanguages,
		&i.SkillsFrameworks,
		&i.OnboardingCompleted,
		&i.EmailWeeklyReport,
		&i.EmailLanguage,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const searchUsers = `-- name: SearchUsers :many
SELECT id, username, name, email, password, avatar_url, bio, git_hub_id, git_hub_username, git_hub_token, git_hub_connected, spotify_connected, spotify_token, spotify_refresh_token, spotify_token_expiry, zenn_username, qiita_username, at_coder_username, paiza_rank, skills_languages, skills_frameworks, onboarding_completed, email_weekly_report, email_language, created_at, updated_at FROM users WHERE users.name ILIKE $1 OR users.email ILIKE $1 LIMIT $2
`

type SearchUsersParams struct {
	Name  string
	Limit int32
}

func (q *Queries) SearchUsers(ctx context.Context, arg SearchUsersParams) ([]User, error) {
	rows, err := q.db.Query(ctx, searchUsers, arg.Name, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []User
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.Username,
			&i.Name,
			&i.Email,
			&i.Password,
			&i.AvatarUrl,
			&i.Bio,
			&i.GitHubID,
			&i.GitHubUsername,
			&i.GitHubToken,
			&i.GitHubConnected,
			&i.SpotifyConnected,
			&i.SpotifyToken,
			&i.SpotifyRefreshToken,
			&i.SpotifyTokenExpiry,
			&i.ZennUsername,
			&i.QiitaUsername,
			&i.AtCoderUsername,
			&i.PaizaRank,
			&i.SkillsLanguages,
			&i.SkillsFrameworks,
			&i.OnboardingCompleted,
			&i.EmailWeeklyReport,
			&i.EmailLanguage,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateUser = `-- name: UpdateUser :one
UPDATE users SET
    username = $2, name = $3, email = $4, password = $5, avatar_url = $6, bio = $7,
    git_hub_id = $8, git_hub_username = $9, git_hub_token = $10, git_hub_connected = $11,
    spotify_connected = $12, spotify_token = $13, spotify_refresh_token = $14,
    spotify_token_expiry = $15, zenn_username = $16, qiita_username = $17,
    at_coder_username = $18, paiza_rank = $19, skills_languages = $20, skills_frameworks = $21,
    onboarding_completed = $22, email_weekly_report = $23, email_language = $24, updated_at = now()
WHERE users.id = $1
RETURNING id, username, name, email, password, avatar_url, bio, git_hub_id, git_hub_username, git_hub_token, git_hub_connected, spotify_connected, spotify_token, spotify_refresh_token, spotify_token_expiry, zenn_username, qiita_username, at_coder_username, paiza_rank, skills_languages, skills_frameworks, onboarding_completed, email_weekly_report, email_language, created_at, updated_at
`

type UpdateUserParams struct {
	ID                  int64
	Username            string
	Name                string
	Email               string
	Password            *string
	AvatarUrl           *string
	Bio                 *string
	GitHubID            *int64
	GitHubUsername      *string
	GitHubToken         *string
	GitHubConnected     *bool
	SpotifyConnected    *bool
	SpotifyToken        *string
	SpotifyRefreshToken *string
	SpotifyTokenExpiry  pgtype.Timestamptz
	ZennUsername        *string
	QiitaUsername       *string
	AtCoderUsername     *string
	PaizaRank           *string
	SkillsLanguages     *string
	SkillsFrameworks    *string
	OnboardingCompleted *bool
	EmailWeeklyReport   *bool
	EmailLanguage       *string
}

// GORMのSave（全カラム上書き）に相当。
func (q *Queries) UpdateUser(ctx context.Context, arg UpdateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, updateUser,
		arg.ID,
		arg.Username,
		arg.Name,
		arg.Email,
		arg.Password,
		arg.AvatarUrl,
		arg.Bio,
		arg.GitHubID,
		arg.GitHubUsername,
		arg.GitHubToken,
		arg.GitHubConnected,
		arg.SpotifyConnected,
		arg.SpotifyToken,
		arg.SpotifyRefreshToken,
		arg.SpotifyTokenExpiry,
		arg.ZennUsername,
		arg.QiitaUsername,
		arg.AtCoderUsername,
		arg.PaizaRank,
		arg.SkillsLanguages,
		arg.SkillsFrameworks,
		arg.OnboardingCompleted,
		arg.EmailWeeklyReport,
		arg.EmailLanguage,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Name,
		&i.Email,
		&i.Password,
		&i.AvatarUrl,
		&i.Bio,
		&i.GitHubID,
		&i.GitHubUsername,
		&i.GitHubToken,
		&i.GitHubConnected,
		&i.SpotifyConnected,
		&i.SpotifyToken,
		&i.SpotifyRefreshToken,
		&i.SpotifyTokenExpiry,
		&i.ZennUsername,
		&i.QiitaUsername,
		&i.AtCoderUsername,
		&i.PaizaRank,
		&i.SkillsLanguages,
		&i.SkillsFrameworks,
		&i.OnboardingCompleted,
		&i.EmailWeeklyReport,
		&i.EmailLanguage,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateUserPassword = `-- name: UpdateUserPassword :exec
UPDATE users SET password = $2 WHERE users.id = $1
`

type UpdateUserPasswordParams struct {
	ID       int64
	Password *string
}

func (q *Queries) UpdateUserPassword(ctx context.Context, arg UpdateUserPasswordParams) error {
	_, err := q.db.Exec(ctx, updateUserPassword, arg.ID, arg.Password)
	return err
}
