// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: user_activity.sql

package sqlcgen

import (
	"context"
)

const countUserActivitiesByUser = `-- name: CountUserActivitiesByUser :one
SELECT count(*) FROM user_activities
WHERE user_id = $1
`

func (q *Queries) CountUserActivitiesByUser(ctx context.Context, userID int64) (int64, error) {
	row := q.db.QueryRow(ctx, countUserActivitiesByUser, userID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countUserActivitiesByUserAndType = `-- name: CountUserActivitiesByUserAndType :one
SELECT count(*) FROM user_activities
WHERE user_id = $1 AND activity_type = $2
`

type CountUserActivitiesByUserAndTypeParams struct {
	UserID       int64
	ActivityType string
}

func (q *Queries) CountUserActivitiesByUserAndType(ctx context.Context, arg CountUserActivitiesByUserAndTypeParams) (int64, error) {
	row := q.db.QueryRow(ctx, countUserActivitiesByUserAndType, arg.UserID, arg.ActivityType)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const listUserActivitiesByUser = `-- name: ListUserActivitiesByUser :many
SELECT id, user_id, activity_type, target_type, target_id, metadata, created_at FROM user_activities
WHERE user_id = $1
ORDER BY created_at DESC, id DESC
LIMIT $2 OFFSET $3
`

type ListUserActivitiesByUserParams struct {
	UserID int64
	Limit  int32
	Offset int32
}

func (q *Queries) ListUserActivitiesByUser(ctx context.Context, arg ListUserActivitiesByUserParams) ([]UserActivity, error) {
	rows, err := q.db.Query(ctx, listUserActivitiesByUser, arg.UserID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []UserActivity
	for rows.Next() {
		var i UserActivity
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.ActivityType,
			&i.TargetType,
			&i.TargetID,
			&i.Metadata,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUserActivitiesByUserAndType = `-- name: ListUserActivitiesByUserAndType :many
SELECT id, user_id, activity_type, target_type, target_id, metadata, created_at FROM user_activities
WHERE user_id = $1 AND activity_type = $2
ORDER BY created_at DESC, id DESC
LIMIT $3 OFFSET $4
`

type ListUserActivitiesByUserAndTypeParams struct {
	UserID       int64
	ActivityType string
	Limit        int32
	Offset       int32
}

func (q *Queries) ListUserActivitiesByUserAndType(ctx context.Context, arg ListUserActivitiesByUserAndTypeParams) ([]UserActivity, error) {
	rows, err := q.db.Query(ctx, listUserActivitiesByUserAndType,
		arg.UserID,
		arg.ActivityType,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []UserActivity
	for rows.Next() {
		var i UserActivity
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.ActivityType,
			&i.TargetType,
			&i.TargetID,
			&i.Metadata,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
