// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: weekly_challenge.sql

package sqlcgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createWeeklyChallenge = `-- name: CreateWeeklyChallenge :one
INSERT INTO weekly_challenges (
  user_id, year, week, challenge_type, description, target_value,
  current_value, is_completed, completed_at, created_at, updated_at
)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, now(), now())
RETURNING id, user_id, year, week, challenge_type, description, target_value, current_value, is_completed, completed_at, created_at, updated_at
`

type CreateWeeklyChallengeParams struct {
	UserID        int64
	Year          int64
	Week          int64
	ChallengeType string
	Description   string
	TargetValue   int64
	CurrentValue  *int64
	IsCompleted   bool
	CompletedAt   pgtype.Timestamptz
}

func (q *Queries) CreateWeeklyChallenge(ctx context.Context, arg CreateWeeklyChallengeParams) (WeeklyChallenge, error) {
	row := q.db.QueryRow(ctx, createWeeklyChallenge,
		arg.UserID,
		arg.Year,
		arg.Week,
		arg.ChallengeType,
		arg.Description,
		arg.TargetValue,
		arg.CurrentValue,
		arg.IsCompleted,
		arg.CompletedAt,
	)
	var i WeeklyChallenge
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Year,
		&i.Week,
		&i.ChallengeType,
		&i.Description,
		&i.TargetValue,
		&i.CurrentValue,
		&i.IsCompleted,
		&i.CompletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getWeeklyChallengeByUserAndWeek = `-- name: GetWeeklyChallengeByUserAndWeek :one
SELECT id, user_id, year, week, challenge_type, description, target_value, current_value, is_completed, completed_at, created_at, updated_at FROM weekly_challenges
WHERE user_id = $1 AND year = $2 AND week = $3
ORDER BY id ASC
LIMIT 1
`

type GetWeeklyChallengeByUserAndWeekParams struct {
	UserID int64
	Year   int64
	Week   int64
}

func (q *Queries) GetWeeklyChallengeByUserAndWeek(ctx context.Context, arg GetWeeklyChallengeByUserAndWeekParams) (WeeklyChallenge, error) {
	row := q.db.QueryRow(ctx, getWeeklyChallengeByUserAndWeek, arg.UserID, arg.Year, arg.Week)
	var i WeeklyChallenge
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Year,
		&i.Week,
		&i.ChallengeType,
		&i.Description,
		&i.TargetValue,
		&i.CurrentValue,
		&i.IsCompleted,
		&i.CompletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateWeeklyChallenge = `-- name: UpdateWeeklyChallenge :one
UPDATE weekly_challenges
SET user_id = $2,
    year = $3,
    week = $4,
    challenge_type = $5,
    description = $6,
    target_value = $7,
    current_value = $8,
    is_completed = $9,
    completed_at = $10,
    updated_at = now()
WHERE id = $1
RETURNING id, user_id, year, week, challenge_type, description, target_value, current_value, is_completed, completed_at, created_at, updated_at
`

type UpdateWeeklyChallengeParams struct {
	ID            int64
	UserID        int64
	Year          int64
	Week          int64
	ChallengeType string
	Description   string
	TargetValue   int64
	CurrentValue  *int64
	IsCompleted   bool
	CompletedAt   pgtype.Timestamptz
}

func (q *Queries) UpdateWeeklyChallenge(ctx context.Context, arg UpdateWeeklyChallengeParams) (WeeklyChallenge, error) {
	row := q.db.QueryRow(ctx, updateWeeklyChallenge,
		arg.ID,
		arg.UserID,
		arg.Year,
		arg.Week,
		arg.ChallengeType,
		arg.Description,
		arg.TargetValue,
		arg.CurrentValue,
		arg.IsCompleted,
		arg.CompletedAt,
	)
	var i WeeklyChallenge
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Year,
		&i.Week,
		&i.ChallengeType,
		&i.Description,
		&i.TargetValue,
		&i.CurrentValue,
		&i.IsCompleted,
		&i.CompletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
