// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: zenn.sql

package sqlcgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const deleteZennArticlesByUser = `-- name: DeleteZennArticlesByUser :exec
DELETE FROM zenn_articles WHERE user_id = $1
`

func (q *Queries) DeleteZennArticlesByUser(ctx context.Context, userID int64) error {
	_, err := q.db.Exec(ctx, deleteZennArticlesByUser, userID)
	return err
}

const getZennStatsByUser = `-- name: GetZennStatsByUser :one
SELECT
    COUNT(*) AS total_articles,
    COALESCE(SUM(liked_count), 0)::bigint AS total_likes,
    COALESCE(SUM(comments_count), 0)::bigint AS total_comments
FROM zenn_articles WHERE user_id = $1
`

type GetZennStatsByUserRow struct {
	TotalArticles int64
	TotalLikes    int64
	TotalComments int64
}

func (q *Queries) GetZennStatsByUser(ctx context.Context, userID int64) (GetZennStatsByUserRow, error) {
	row := q.db.QueryRow(ctx, getZennStatsByUser, userID)
	var i GetZennStatsByUserRow
	err := row.Scan(&i.TotalArticles, &i.TotalLikes, &i.TotalComments)
	return i, err
}

const listZennArticlesByUser = `-- name: ListZennArticlesByUser :many
SELECT id, user_id, zenn_id, title, slug, emoji, article_type, liked_count, comments_count, published_at, updated_at FROM zenn_articles WHERE user_id = $1 ORDER BY published_at DESC
`

func (q *Queries) ListZennArticlesByUser(ctx context.Context, userID int64) ([]ZennArticle, error) {
	rows, err := q.db.Query(ctx, listZennArticlesByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ZennArticle
	for rows.Next() {
		var i ZennArticle
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.ZennID,
			&i.Title,
			&i.Slug,
			&i.Emoji,
			&i.ArticleType,
			&i.LikedCount,
			&i.CommentsCount,
			&i.PublishedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertZennArticle = `-- name: UpsertZennArticle :one
INSERT INTO zenn_articles (user_id, zenn_id, title, slug, emoji, article_type, liked_count, comments_count, published_at, updated_at)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, now())
ON CONFLICT (zenn_id) DO UPDATE SET
    title = EXCLUDED.title,
    slug = EXCLUDED.slug,
    emoji = EXCLUDED.emoji,
    article_type = EXCLUDED.article_type,
    liked_count = EXCLUDED.liked_count,
    comments_count = EXCLUDED.comments_count,
    published_at = EXCLUDED.published_at,
    updated_at = EXCLUDED.updated_at
RETURNING id, user_id, zenn_id, title, slug, emoji, article_type, liked_count, comments_count, published_at, updated_at
`

type UpsertZennArticleParams struct {
	UserID        int64
	ZennID        int64
	Title         string
	Slug          string
	Emoji         *string
	ArticleType   *string
	LikedCount    *int64
	CommentsCount *int64
	PublishedAt   pgtype.Timestamptz
}

func (q *Queries) UpsertZennArticle(ctx context.Context, arg UpsertZennArticleParams) (ZennArticle, error) {
	row := q.db.QueryRow(ctx, upsertZennArticle,
		arg.UserID,
		arg.ZennID,
		arg.Title,
		arg.Slug,
		arg.Emoji,
		arg.ArticleType,
		arg.LikedCount,
		arg.CommentsCount,
		arg.PublishedAt,
	)
	var i ZennArticle
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ZennID,
		&i.Title,
		&i.Slug,
		&i.Emoji,
		&i.ArticleType,
		&i.LikedCount,
		&i.CommentsCount,
		&i.PublishedAt,
		&i.UpdatedAt,
	)
	return i, err
}
